(library
 (name flow_gpu)
 (public_name rays.flow_gpu)
 (modules emit pipelines run host image_sink)
 (libraries flow flow_ir ogpu rays_execution rays_math lru))

(test
 (name test_emit)
 (modules test_emit test_program)
 (deps (glob_files goldens/*.metal))
 (libraries flow_gpu flow flow_ir rays_math))

(executable
 (name test_run)
 (modules test_run test_program)
 (libraries flow_gpu flow flow_ir rays_execution ogpu unix))

(rule
 (alias runtest-native)
 (action (run %{exe:test_run.exe})))

(executable
 (name test_image_sink_native)
 (modules test_image_sink_native test_program)
 (libraries flow_gpu flow flow_ir flow_sop procedural rays rays_execution ogpu unix))

(rule
 (alias runtest-native)
 (action (run %{exe:test_image_sink_native.exe})))

(test
 (name test_pipelines)
 (modules test_pipelines test_program)
 (libraries flow_gpu flow flow_ir ogpu_mock unix))

(test
 (name test_run_lifetime)
 (modules test_run_lifetime test_program)
 (libraries flow_gpu flow flow_ir ogpu_mock unix))

(test
 (name test_image_sink)
 (modules test_image_sink test_program)
 (libraries flow_gpu flow flow_ir ogpu_mock unix))
