(library
 (name prismel_next_resources)
 (public_name prismel.prismel_next_resources)
 (modules prismel_next_resources)
 (libraries sdl3 sdl3_image sdl3_ttf sdl3_mixer unix))

(test
 (name test_prismel_next_resources)
 (modules test_prismel_next_resources)
 (libraries prismel_next_resources unix))

(test
 (name test_prismel_next_font)
 (modules test_prismel_next_font)
 (libraries prismel_next_resources))

(test
 (name test_prismel_next_audio)
 (modules test_prismel_next_audio)
 (libraries prismel_next_resources)
 (action (setenv SDL_AUDIODRIVER dummy (run %{test}))))
