(library
 (name prismel_next_resources)
 (public_name prismel.prismel_next_resources)
 (modules prismel_next_resources)
 (libraries sdl3 sdl3_image sdl3_ttf sdl3_mixer ogpu unix))

(executable
 (name test_main)
 (modules test_main test_prismel_next_resources test_prismel_next_font test_prismel_next_audio test_png_rows)
 (libraries prismel_next_resources unix))

(rule
 (aliases runtest test_prismel_next_resources)
 (action (run %{exe:test_main.exe} test_prismel_next_resources)))

(rule
 (aliases runtest test_prismel_next_font)
 (action (run %{exe:test_main.exe} test_prismel_next_font)))

(rule
 (aliases runtest test_prismel_next_audio)
 (action
  (setenv SDL_AUDIODRIVER dummy
   (run %{exe:test_main.exe} test_prismel_next_audio))))

(rule
 (aliases runtest test_png_rows)
 (action (run %{exe:test_main.exe} test_png_rows)))
