A temp project with one valid sketch and one with a typo. Only the generated
main.ml is built here (the executables need the repository's libraries): a
valid sketch yields it, a typo fails the build at the .plisp line.

  $ echo '(lang dune 3.17)' > dune-project
  $ mkdir ok bad
  $ echo '(workspace ok (graph g :context sop (sop/box)))' > ok/sketch.plisp
  $ printf '(workspace bad\n  (graph g :context sop\n    (sop/bx)))\n' > bad/sketch.plisp
  $ prismel-plisp dune . > dune.plisp.inc
  $ echo '(include dune.plisp.inc)' > dune
  $ dune build ./ok/main.ml 2>&1
  $ head -3 _build/default/ok/main.ml
  (* generated by prismel-plisp from ok/sketch.plisp; do not edit *)
  let () =
    Prismel_editor.Workspace.main
  $ dune build ./bad/main.ml 2>&1
  File "bad/sketch.plisp", line 3, characters 4-12:
  Error [E_UNKNOWN_KIND]: Unknown operator “sop/bx”. Did you mean box?
  [1]
