type lane=Mechanical|Ownership|Metadata
type package=Dispatch|Sample_indices|Pass_graph|Sample_buffer|Attachment_array|Type_metadata
type item={id:string;lane:lane;package:package;operation:string;tests:string list}
let dispatch_ids=["method:-[MTLComputePassDescriptor dispatchType]";"method:-[MTLComputePassDescriptor setDispatchType:]";"property:MTLComputePassDescriptor:dispatchType"]
let index_ids=["method:-[MTLComputePassSampleBufferAttachmentDescriptor endOfEncoderSampleIndex]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor setEndOfEncoderSampleIndex:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor setStartOfEncoderSampleIndex:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor startOfEncoderSampleIndex]";"property:MTLComputePassSampleBufferAttachmentDescriptor:endOfEncoderSampleIndex";"property:MTLComputePassSampleBufferAttachmentDescriptor:startOfEncoderSampleIndex"]
let mechanical_ids=dispatch_ids@index_ids
let callable_ids=["method:+[MTLComputePassDescriptor computePassDescriptor]";"method:-[MTLComputePassDescriptor dispatchType]";"method:-[MTLComputePassDescriptor sampleBufferAttachments]";"method:-[MTLComputePassDescriptor setDispatchType:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor endOfEncoderSampleIndex]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor sampleBuffer]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor setEndOfEncoderSampleIndex:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor setSampleBuffer:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor setStartOfEncoderSampleIndex:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptor startOfEncoderSampleIndex]";"method:-[MTLComputePassSampleBufferAttachmentDescriptorArray objectAtIndexedSubscript:]";"method:-[MTLComputePassSampleBufferAttachmentDescriptorArray setObject:atIndexedSubscript:]";"property:MTLComputePassDescriptor:dispatchType";"property:MTLComputePassDescriptor:sampleBufferAttachments";"property:MTLComputePassSampleBufferAttachmentDescriptor:endOfEncoderSampleIndex";"property:MTLComputePassSampleBufferAttachmentDescriptor:sampleBuffer";"property:MTLComputePassSampleBufferAttachmentDescriptor:startOfEncoderSampleIndex"]
let contains s n=let l=String.length n in let rec f i=i+l<=String.length s&&(String.sub s i l=n||f(i+1))in f 0
let classify~kind id=let lane=if List.mem id mechanical_ids then Mechanical else if kind="method"||kind="property"then Ownership else Metadata in let package,operation,tests=if lane=Metadata then Type_metadata,"Metal.Compute_pass opaque descriptor types",["public type provenance"]else if List.mem id dispatch_ids then Dispatch,"Metal.Compute_pass.Descriptor.dispatch_type",["typed enum round trip";"capability"]else if List.mem id index_ids then Sample_indices,"Metal.Compute_pass.Sample_attachment sample range",["start/end ordering";"counter buffer bounds"]else if contains id "DescriptorArray"then Attachment_array,"Metal.Compute_pass attachments",["index bounds";"replacement retention"]else if contains id "SampleBufferAttachment"then Sample_buffer,"Metal.Compute_pass.Sample_attachment.buffer",["same-device counter buffer";"nullable ownership";"destroy order"]else Pass_graph,"Metal.Compute_pass.Descriptor",["native defaults";"attachment graph mutation retention"]in{id;lane;package;operation;tests}
let validate items=let count f=List.length(List.filter f items)in if List.length items<>20||count(fun x->x.lane=Mechanical)<>9||count(fun x->x.lane=Ownership)<>8||count(fun x->x.lane=Metadata)<>3||List.map(fun p->count(fun x->x.package=p))[Dispatch;Sample_indices;Pass_graph;Sample_buffer;Attachment_array;Type_metadata]<>[3;6;3;3;2;3]then failwith"ComputePass20 tail drift"
