type ownership = Value | Queue | Command | Callback | Resource | Allocator
type entry = { id:string; ownership:ownership }
let e ownership id={id;ownership}
let entries=
 [e Command "method:-[MTLIOCommandBuffer addBarrier]";e Callback "method:-[MTLIOCommandBuffer addCompletedHandler:]";e Resource "method:-[MTLIOCommandBuffer copyStatusToBuffer:offset:]";e Command "method:-[MTLIOCommandBuffer enqueue]";e Value "method:-[MTLIOCommandBuffer error]";e Value "method:-[MTLIOCommandBuffer label]";e Resource "method:-[MTLIOCommandBuffer loadBytes:size:sourceHandle:sourceHandleOffset:]";e Resource "method:-[MTLIOCommandBuffer loadTexture:slice:level:size:sourceBytesPerRow:sourceBytesPerImage:destinationOrigin:sourceHandle:sourceHandleOffset:]";e Command "method:-[MTLIOCommandBuffer popDebugGroup]";e Command "method:-[MTLIOCommandBuffer pushDebugGroup:]";e Value "method:-[MTLIOCommandBuffer setLabel:]";e Resource "method:-[MTLIOCommandBuffer signalEvent:value:]";e Command "method:-[MTLIOCommandBuffer tryCancel]";e Resource "method:-[MTLIOCommandBuffer waitForEvent:value:]";e Value "property:MTLIOCommandBuffer:error";e Value "property:MTLIOCommandBuffer:label";e Value "property:MTLIOCommandBuffer:status";e Callback "typedef:MTLIOCommandBufferHandler";e Queue "method:-[MTLIOCommandQueue commandBufferWithUnretainedReferences]";e Queue "method:-[MTLIOCommandQueue enqueueBarrier]";e Value "method:-[MTLIOCommandQueue label]";e Value "method:-[MTLIOCommandQueue setLabel:]";e Allocator "method:-[MTLIOCommandQueueDescriptor scratchBufferAllocator]";e Allocator "method:-[MTLIOCommandQueueDescriptor setScratchBufferAllocator:]";e Value "method:-[MTLIOFileHandle label]";e Value "method:-[MTLIOFileHandle setLabel:]";e Resource "method:-[MTLIOScratchBuffer buffer]";e Allocator "method:-[MTLIOScratchBufferAllocator newScratchBufferWithMinimumSize:]";e Value "property:MTLIOCommandQueue:label";e Allocator "property:MTLIOCommandQueueDescriptor:scratchBufferAllocator";e Value "property:MTLIOFileHandle:label";e Resource "property:MTLIOScratchBuffer:buffer";e Resource "protocol:MTLIOScratchBuffer";e Allocator "protocol:MTLIOScratchBufferAllocator"]
let ids=List.map(fun e->e.id)entries
let validate()=
 if List.length entries<>34||List.length(List.sort_uniq String.compare ids)<>34 then invalid_arg"IO command queue34 safe closure drift";
 if not(List.exists(fun e->e.ownership=Callback)entries&&List.exists(fun e->e.ownership=Allocator)entries&&List.exists(fun e->e.ownership=Resource)entries)then invalid_arg"IO command queue34 ownership partition drift"
