let methods =
  [ "MTLMeshRenderPipelineDescriptor", "binaryArchives"; "MTLMeshRenderPipelineDescriptor", "colorAttachments"; "MTLMeshRenderPipelineDescriptor", "fragmentBuffers"; "MTLMeshRenderPipelineDescriptor", "fragmentFunction"; "MTLMeshRenderPipelineDescriptor", "fragmentLinkedFunctions"; "MTLMeshRenderPipelineDescriptor", "meshBuffers"; "MTLMeshRenderPipelineDescriptor", "meshFunction"; "MTLMeshRenderPipelineDescriptor", "meshLinkedFunctions"; "MTLMeshRenderPipelineDescriptor", "objectBuffers"; "MTLMeshRenderPipelineDescriptor", "objectFunction"; "MTLMeshRenderPipelineDescriptor", "objectLinkedFunctions"; "MTLMeshRenderPipelineDescriptor", "reset"; "MTLMeshRenderPipelineDescriptor", "setBinaryArchives:"; "MTLMeshRenderPipelineDescriptor", "setFragmentFunction:"; "MTLMeshRenderPipelineDescriptor", "setFragmentLinkedFunctions:"; "MTLMeshRenderPipelineDescriptor", "setMeshFunction:"; "MTLMeshRenderPipelineDescriptor", "setMeshLinkedFunctions:"; "MTLMeshRenderPipelineDescriptor", "setObjectFunction:"; "MTLMeshRenderPipelineDescriptor", "setObjectLinkedFunctions:";
    "MTLRenderPipelineColorAttachmentDescriptorArray", "objectAtIndexedSubscript:"; "MTLRenderPipelineColorAttachmentDescriptorArray", "setObject:atIndexedSubscript:";
    "MTLRenderPipelineDescriptor", "colorAttachments"; "MTLRenderPipelineDescriptor", "fragmentBuffers"; "MTLRenderPipelineDescriptor", "label"; "MTLRenderPipelineDescriptor", "setLabel:"; "MTLRenderPipelineDescriptor", "setVertexDescriptor:"; "MTLRenderPipelineDescriptor", "vertexBuffers"; "MTLRenderPipelineDescriptor", "vertexDescriptor";
    "MTLRenderPipelineFunctionsDescriptor", "fragmentAdditionalBinaryFunctions"; "MTLRenderPipelineFunctionsDescriptor", "setFragmentAdditionalBinaryFunctions:"; "MTLRenderPipelineFunctionsDescriptor", "setTileAdditionalBinaryFunctions:"; "MTLRenderPipelineFunctionsDescriptor", "setVertexAdditionalBinaryFunctions:"; "MTLRenderPipelineFunctionsDescriptor", "tileAdditionalBinaryFunctions"; "MTLRenderPipelineFunctionsDescriptor", "vertexAdditionalBinaryFunctions";
    "MTLRenderPipelineReflection", "fragmentArguments"; "MTLRenderPipelineReflection", "tileArguments"; "MTLRenderPipelineReflection", "vertexArguments";
    "MTLRenderPipelineState", "functionHandleWithBinaryFunction:stage:"; "MTLRenderPipelineState", "functionHandleWithFunction:stage:"; "MTLRenderPipelineState", "functionHandleWithName:stage:"; "MTLRenderPipelineState", "newIntersectionFunctionTableWithDescriptor:stage:"; "MTLRenderPipelineState", "newRenderPipelineDescriptorForSpecialization"; "MTLRenderPipelineState", "newRenderPipelineStateWithAdditionalBinaryFunctions:error:"; "MTLRenderPipelineState", "newRenderPipelineStateWithBinaryFunctions:error:"; "MTLRenderPipelineState", "newVisibleFunctionTableWithDescriptor:stage:"; "MTLRenderPipelineState", "requiredThreadsPerMeshThreadgroup"; "MTLRenderPipelineState", "requiredThreadsPerObjectThreadgroup";
    "MTLTileRenderPipelineDescriptor", "binaryArchives"; "MTLTileRenderPipelineDescriptor", "colorAttachments"; "MTLTileRenderPipelineDescriptor", "linkedFunctions"; "MTLTileRenderPipelineDescriptor", "preloadedLibraries"; "MTLTileRenderPipelineDescriptor", "reset"; "MTLTileRenderPipelineDescriptor", "setBinaryArchives:"; "MTLTileRenderPipelineDescriptor", "setLinkedFunctions:"; "MTLTileRenderPipelineDescriptor", "setPreloadedLibraries:"; "MTLTileRenderPipelineDescriptor", "setTileFunction:"; "MTLTileRenderPipelineDescriptor", "tileBuffers"; "MTLTileRenderPipelineDescriptor", "tileFunction" ]
let callable_ids = List.map (fun (owner, selector) -> "method:-[" ^ owner ^ " " ^ selector ^ "]") methods
let properties =
  [ "MTLMeshRenderPipelineDescriptor", ["binaryArchives";"colorAttachments";"fragmentBuffers";"fragmentFunction";"fragmentLinkedFunctions";"meshBuffers";"meshFunction";"meshLinkedFunctions";"objectBuffers";"objectFunction";"objectLinkedFunctions"];
    "MTLRenderPipelineDescriptor", ["colorAttachments";"fragmentBuffers";"label";"vertexBuffers";"vertexDescriptor"];
    "MTLRenderPipelineFunctionsDescriptor", ["fragmentAdditionalBinaryFunctions";"tileAdditionalBinaryFunctions";"vertexAdditionalBinaryFunctions"];
    "MTLRenderPipelineReflection", ["fragmentArguments";"tileArguments";"vertexArguments"];
    "MTLRenderPipelineState", ["requiredThreadsPerMeshThreadgroup";"requiredThreadsPerObjectThreadgroup"];
    "MTLTileRenderPipelineDescriptor", ["binaryArchives";"colorAttachments";"linkedFunctions";"preloadedLibraries";"tileBuffers";"tileFunction"] ]
let property_ids = List.concat_map (fun (owner, names) -> List.map (fun name -> "property:" ^ owner ^ ":" ^ name) names) properties
let class_ids = List.map (fun name -> "class:" ^ name) ["MTLMeshRenderPipelineDescriptor";"MTLRenderPipelineColorAttachmentDescriptor";"MTLRenderPipelineColorAttachmentDescriptorArray";"MTLRenderPipelineFunctionsDescriptor";"MTLTileRenderPipelineDescriptor"]
let ids = callable_ids @ property_ids @ class_ids
let validate () =
  if List.length callable_ids <> 58 || List.length property_ids <> 30 || List.length class_ids <> 5 || List.length ids <> 93 || List.length (List.sort_uniq String.compare ids) <> 93 then invalid_arg "RenderPipeline93 native closure drift"
