let ids=
  [ "class:MTLBlitPassDescriptor"
  ; "class:MTLBlitPassSampleBufferAttachmentDescriptor"
  ; "class:MTLBlitPassSampleBufferAttachmentDescriptorArray"
  ; "class:MTLCounterSampleBufferDescriptor"
  ; "class:MTLIOCommandQueueDescriptor"
  ; "function:MTLIOCompressionContextAppendData"
  ; "function:MTLIOCompressionContextDefaultChunkSize"
  ; "function:MTLIOCreateCompressionContext"
  ; "function:MTLIOFlushAndDestroyCompressionContext"
  ; "method:-[MTLBlitPassDescriptor sampleBufferAttachments]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptor endOfEncoderSampleIndex]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptor sampleBuffer]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptor setEndOfEncoderSampleIndex:]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptor setSampleBuffer:]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptor setStartOfEncoderSampleIndex:]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptor startOfEncoderSampleIndex]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptorArray objectAtIndexedSubscript:]"
  ; "method:-[MTLBlitPassSampleBufferAttachmentDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLCounter name]"
  ; "method:-[MTLCounterSampleBuffer device]"
  ; "method:-[MTLCounterSampleBuffer label]"
  ; "method:-[MTLCounterSampleBuffer resolveCounterRange:]"
  ; "method:-[MTLCounterSampleBuffer sampleCount]"
  ; "method:-[MTLCounterSampleBufferDescriptor counterSet]"
  ; "method:-[MTLCounterSampleBufferDescriptor label]"
  ; "method:-[MTLCounterSampleBufferDescriptor sampleCount]"
  ; "method:-[MTLCounterSampleBufferDescriptor setCounterSet:]"
  ; "method:-[MTLCounterSampleBufferDescriptor setLabel:]"
  ; "method:-[MTLCounterSampleBufferDescriptor setSampleCount:]"
  ; "method:-[MTLCounterSampleBufferDescriptor setStorageMode:]"
  ; "method:-[MTLCounterSampleBufferDescriptor storageMode]"
  ; "method:-[MTLCounterSet counters]"
  ; "method:-[MTLCounterSet name]"
  ; "method:-[MTLIOCommandBuffer addBarrier]"
  ; "method:-[MTLIOCommandBuffer addCompletedHandler:]"
  ; "method:-[MTLIOCommandBuffer commit]"
  ; "method:-[MTLIOCommandBuffer copyStatusToBuffer:offset:]"
  ; "method:-[MTLIOCommandBuffer enqueue]"
  ; "method:-[MTLIOCommandBuffer error]"
  ; "method:-[MTLIOCommandBuffer label]"
  ; "method:-[MTLIOCommandBuffer loadBuffer:offset:size:sourceHandle:sourceHandleOffset:]"
  ; "method:-[MTLIOCommandBuffer loadBytes:size:sourceHandle:sourceHandleOffset:]"
  ; "method:-[MTLIOCommandBuffer loadTexture:slice:level:size:sourceBytesPerRow:sourceBytesPerImage:destinationOrigin:sourceHandle:sourceHandleOffset:]"
  ; "method:-[MTLIOCommandBuffer popDebugGroup]"
  ; "method:-[MTLIOCommandBuffer pushDebugGroup:]"
  ; "method:-[MTLIOCommandBuffer setLabel:]"
  ; "method:-[MTLIOCommandBuffer signalEvent:value:]"
  ; "method:-[MTLIOCommandBuffer status]"
  ; "method:-[MTLIOCommandBuffer tryCancel]"
  ; "method:-[MTLIOCommandBuffer waitForEvent:value:]"
  ; "method:-[MTLIOCommandBuffer waitUntilCompleted]"
  ; "method:-[MTLIOCommandQueue commandBuffer]"
  ; "method:-[MTLIOCommandQueue commandBufferWithUnretainedReferences]"
  ; "method:-[MTLIOCommandQueue enqueueBarrier]"
  ; "method:-[MTLIOCommandQueue label]"
  ; "method:-[MTLIOCommandQueue setLabel:]"
  ; "method:-[MTLIOCommandQueueDescriptor maxCommandBufferCount]"
  ; "method:-[MTLIOCommandQueueDescriptor maxCommandsInFlight]"
  ; "method:-[MTLIOCommandQueueDescriptor priority]"
  ; "method:-[MTLIOCommandQueueDescriptor scratchBufferAllocator]"
  ; "method:-[MTLIOCommandQueueDescriptor setMaxCommandBufferCount:]"
  ; "method:-[MTLIOCommandQueueDescriptor setMaxCommandsInFlight:]"
  ; "method:-[MTLIOCommandQueueDescriptor setPriority:]"
  ; "method:-[MTLIOCommandQueueDescriptor setScratchBufferAllocator:]"
  ; "method:-[MTLIOCommandQueueDescriptor setType:]"
  ; "method:-[MTLIOCommandQueueDescriptor type]"
  ; "method:-[MTLIOFileHandle label]"
  ; "method:-[MTLIOFileHandle setLabel:]"
  ; "method:-[MTLIOScratchBuffer buffer]"
  ; "method:-[MTLIOScratchBufferAllocator newScratchBufferWithMinimumSize:]"
  ; "method:+[MTLBlitPassDescriptor blitPassDescriptor]"
  ; "property:MTLBlitPassDescriptor:sampleBufferAttachments"
  ; "property:MTLBlitPassSampleBufferAttachmentDescriptor:endOfEncoderSampleIndex"
  ; "property:MTLBlitPassSampleBufferAttachmentDescriptor:sampleBuffer"
  ; "property:MTLBlitPassSampleBufferAttachmentDescriptor:startOfEncoderSampleIndex"
  ; "property:MTLCounter:name"
  ; "property:MTLCounterSampleBuffer:device"
  ; "property:MTLCounterSampleBuffer:label"
  ; "property:MTLCounterSampleBuffer:sampleCount"
  ; "property:MTLCounterSampleBufferDescriptor:counterSet"
  ; "property:MTLCounterSampleBufferDescriptor:label"
  ; "property:MTLCounterSampleBufferDescriptor:sampleCount"
  ; "property:MTLCounterSampleBufferDescriptor:storageMode"
  ; "property:MTLCounterSet:counters"
  ; "property:MTLCounterSet:name"
  ; "property:MTLIOCommandBuffer:error"
  ; "property:MTLIOCommandBuffer:label"
  ; "property:MTLIOCommandBuffer:status"
  ; "property:MTLIOCommandQueue:label"
  ; "property:MTLIOCommandQueueDescriptor:maxCommandBufferCount"
  ; "property:MTLIOCommandQueueDescriptor:maxCommandsInFlight"
  ; "property:MTLIOCommandQueueDescriptor:priority"
  ; "property:MTLIOCommandQueueDescriptor:scratchBufferAllocator"
  ; "property:MTLIOCommandQueueDescriptor:type"
  ; "property:MTLIOFileHandle:label"
  ; "property:MTLIOScratchBuffer:buffer"
  ; "protocol:MTLCounter"
  ; "protocol:MTLCounterSampleBuffer"
  ; "protocol:MTLCounterSet"
  ; "protocol:MTLIOCommandBuffer"
  ; "protocol:MTLIOCommandQueue"
  ; "protocol:MTLIOFileHandle"
  ; "protocol:MTLIOScratchBuffer"
  ; "protocol:MTLIOScratchBufferAllocator"
  ; "typedef:MTLCommonCounter"
  ; "typedef:MTLCommonCounterSet"
  ; "typedef:MTLCounterResultStageUtilization"
  ; "typedef:MTLCounterResultStatistic"
  ; "typedef:MTLCounterResultTimestamp"
  ; "typedef:MTLIOCommandBufferHandler"
  ; "typedef:MTLIOCompressionContext"
  ]
let count=List.length ids
let digest="0b1707e1f3b8d2fd2470725f95a7ec0122e8b38cc32e0fcb534747b6b5bfcd6d"
