let ids =
  [ "class:MTLBufferLayoutDescriptor"
  ; "class:MTLBufferLayoutDescriptorArray"
  ; "class:MTLResourceStatePassDescriptor"
  ; "class:MTLResourceStatePassSampleBufferAttachmentDescriptor"
  ; "class:MTLResourceStatePassSampleBufferAttachmentDescriptorArray"
  ; "class:MTLResourceViewPoolDescriptor"
  ; "class:MTLTextureReferenceType"
  ; "enum-case:MTLResourceOptions:MTLResourceOptionCPUCacheModeDefault"
  ; "enum-case:MTLResourceOptions:MTLResourceOptionCPUCacheModeWriteCombined"
  ; "enum-case:MTLResourceOptions:MTLResourceStorageModeMemoryless"
  ; "method:-[MTLBuffer addDebugMarker:range:]"
  ; "method:-[MTLBuffer newRemoteBufferViewForDevice:]"
  ; "method:-[MTLBuffer newTensorWithDescriptor:offset:error:]"
  ; "method:-[MTLBuffer remoteStorageBuffer]"
  ; "method:-[MTLBuffer removeAllDebugMarkers]"
  ; "method:-[MTLBufferLayoutDescriptor setStepFunction:]"
  ; "method:-[MTLBufferLayoutDescriptor setStepRate:]"
  ; "method:-[MTLBufferLayoutDescriptor setStride:]"
  ; "method:-[MTLBufferLayoutDescriptor stepFunction]"
  ; "method:-[MTLBufferLayoutDescriptor stepRate]"
  ; "method:-[MTLBufferLayoutDescriptor stride]"
  ; "method:-[MTLBufferLayoutDescriptorArray objectAtIndexedSubscript:]"
  ; "method:-[MTLBufferLayoutDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLCommandBuffer resourceStateCommandEncoderWithDescriptor:]"
  ; "method:-[MTLDevice newTextureViewPoolWithDescriptor:error:]"
  ; "method:-[MTLDevice sparseTileSizeWithTextureType:pixelFormat:sampleCount:]"
  ; "method:-[MTLHeap device]"
  ; "method:-[MTLHeap newAccelerationStructureWithDescriptor:]"
  ; "method:-[MTLHeap newAccelerationStructureWithDescriptor:offset:]"
  ; "method:-[MTLHeap newAccelerationStructureWithSize:]"
  ; "method:-[MTLHeap newAccelerationStructureWithSize:offset:]"
  ; "method:-[MTLHeap resourceOptions]"
  ; "method:-[MTLResource allocatedSize]"
  ; "method:-[MTLResource device]"
  ; "method:-[MTLResource heap]"
  ; "method:-[MTLResource resourceOptions]"
  ; "method:-[MTLResource setOwnerWithIdentity:]"
  ; "method:-[MTLResourceStateCommandEncoder moveTextureMappingsFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:]"
  ; "method:-[MTLResourceStateCommandEncoder updateFence:]"
  ; "method:-[MTLResourceStateCommandEncoder updateTextureMapping:mode:indirectBuffer:indirectBufferOffset:]"
  ; "method:-[MTLResourceStateCommandEncoder updateTextureMappings:mode:regions:mipLevels:slices:numRegions:]"
  ; "method:-[MTLResourceStateCommandEncoder waitForFence:]"
  ; "method:-[MTLResourceStatePassDescriptor sampleBufferAttachments]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptor endOfEncoderSampleIndex]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptor sampleBuffer]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptor setEndOfEncoderSampleIndex:]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptor setSampleBuffer:]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptor setStartOfEncoderSampleIndex:]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptor startOfEncoderSampleIndex]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptorArray objectAtIndexedSubscript:]"
  ; "method:-[MTLResourceStatePassSampleBufferAttachmentDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLResourceViewPool baseResourceID]"
  ; "method:-[MTLResourceViewPool copyResourceViewsFromPool:sourceRange:destinationIndex:]"
  ; "method:-[MTLResourceViewPool device]"
  ; "method:-[MTLResourceViewPool label]"
  ; "method:-[MTLResourceViewPool resourceViewCount]"
  ; "method:-[MTLResourceViewPoolDescriptor label]"
  ; "method:-[MTLResourceViewPoolDescriptor resourceViewCount]"
  ; "method:-[MTLResourceViewPoolDescriptor setLabel:]"
  ; "method:-[MTLResourceViewPoolDescriptor setResourceViewCount:]"
  ; "method:-[MTLTexture getBytes:bytesPerRow:fromRegion:mipmapLevel:]"
  ; "method:-[MTLTexture isFramebufferOnly]"
  ; "method:-[MTLTexture newRemoteTextureViewForDevice:]"
  ; "method:-[MTLTexture newTextureViewWithPixelFormat:]"
  ; "method:-[MTLTexture remoteStorageTexture]"
  ; "method:-[MTLTexture replaceRegion:mipmapLevel:withBytes:bytesPerRow:]"
  ; "method:-[MTLTexture rootResource]"
  ; "method:-[MTLTextureViewPool setTextureView:atIndex:]"
  ; "method:-[MTLTextureViewPool setTextureView:descriptor:atIndex:]"
  ; "method:-[MTLTextureViewPool setTextureViewFromBuffer:descriptor:offset:bytesPerRow:atIndex:]"
  ; "method:+[MTLResourceStatePassDescriptor resourceStatePassDescriptor]"
  ; "method:+[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:width:height:mipmapped:]"
  ; "method:+[MTLTextureDescriptor textureBufferDescriptorWithPixelFormat:width:resourceOptions:usage:]"
  ; "method:+[MTLTextureDescriptor textureCubeDescriptorWithPixelFormat:size:mipmapped:]"
  ; "property:MTLBuffer:remoteStorageBuffer"
  ; "property:MTLBufferLayoutDescriptor:stepFunction"
  ; "property:MTLBufferLayoutDescriptor:stepRate"
  ; "property:MTLBufferLayoutDescriptor:stride"
  ; "property:MTLHeap:device"
  ; "property:MTLHeap:resourceOptions"
  ; "property:MTLResource:allocatedSize"
  ; "property:MTLResource:device"
  ; "property:MTLResource:heap"
  ; "property:MTLResource:resourceOptions"
  ; "property:MTLResourceStatePassDescriptor:sampleBufferAttachments"
  ; "property:MTLResourceStatePassSampleBufferAttachmentDescriptor:endOfEncoderSampleIndex"
  ; "property:MTLResourceStatePassSampleBufferAttachmentDescriptor:sampleBuffer"
  ; "property:MTLResourceStatePassSampleBufferAttachmentDescriptor:startOfEncoderSampleIndex"
  ; "property:MTLResourceViewPool:baseResourceID"
  ; "property:MTLResourceViewPool:device"
  ; "property:MTLResourceViewPool:label"
  ; "property:MTLResourceViewPool:resourceViewCount"
  ; "property:MTLResourceViewPoolDescriptor:label"
  ; "property:MTLResourceViewPoolDescriptor:resourceViewCount"
  ; "property:MTLTexture:buffer"
  ; "property:MTLTexture:bufferBytesPerRow"
  ; "property:MTLTexture:bufferOffset"
  ; "property:MTLTexture:framebufferOnly"
  ; "property:MTLTexture:remoteStorageTexture"
  ; "property:MTLTexture:rootResource"
  ]
let count = List.length ids
let digest = "68a50b3d551df185e1ac15abb0b5592ac2254516db8b0907d9c04be0835609c8"
