type lane=Mechanical|Ownership|Metadata
type package=Layout_scalar|Identity_label|Argument_storage|Single_binding|Array_binding|Type_metadata
type item={id:string;lane:lane;package:package;operation:string;tests:string list}
let mechanical_ids=["method:-[MTLArgumentEncoder alignment]";"method:-[MTLArgumentEncoder encodedLength]";"property:MTLArgumentEncoder:alignment";"property:MTLArgumentEncoder:encodedLength"]
let callable_ids=
  ["method:-[MTLArgumentEncoder alignment]";"method:-[MTLArgumentEncoder constantDataAtIndex:]";"method:-[MTLArgumentEncoder device]";"method:-[MTLArgumentEncoder encodedLength]";"method:-[MTLArgumentEncoder label]";"method:-[MTLArgumentEncoder newArgumentEncoderForBufferAtIndex:]";"method:-[MTLArgumentEncoder setAccelerationStructure:atIndex:]";"method:-[MTLArgumentEncoder setArgumentBuffer:offset:]";"method:-[MTLArgumentEncoder setArgumentBuffer:startOffset:arrayElement:]";"method:-[MTLArgumentEncoder setBuffer:offset:atIndex:]";"method:-[MTLArgumentEncoder setBuffers:offsets:withRange:]";"method:-[MTLArgumentEncoder setComputePipelineState:atIndex:]";"method:-[MTLArgumentEncoder setComputePipelineStates:withRange:]";"method:-[MTLArgumentEncoder setDepthStencilState:atIndex:]";"method:-[MTLArgumentEncoder setDepthStencilStates:withRange:]";"method:-[MTLArgumentEncoder setIndirectCommandBuffer:atIndex:]";"method:-[MTLArgumentEncoder setIndirectCommandBuffers:withRange:]";"method:-[MTLArgumentEncoder setIntersectionFunctionTable:atIndex:]";"method:-[MTLArgumentEncoder setIntersectionFunctionTables:withRange:]";"method:-[MTLArgumentEncoder setLabel:]";"method:-[MTLArgumentEncoder setRenderPipelineState:atIndex:]";"method:-[MTLArgumentEncoder setRenderPipelineStates:withRange:]";"method:-[MTLArgumentEncoder setSamplerState:atIndex:]";"method:-[MTLArgumentEncoder setSamplerStates:withRange:]";"method:-[MTLArgumentEncoder setTexture:atIndex:]";"method:-[MTLArgumentEncoder setTextures:withRange:]";"method:-[MTLArgumentEncoder setVisibleFunctionTable:atIndex:]";"method:-[MTLArgumentEncoder setVisibleFunctionTables:withRange:]";"property:MTLArgumentEncoder:alignment";"property:MTLArgumentEncoder:device";"property:MTLArgumentEncoder:encodedLength";"property:MTLArgumentEncoder:label"]
let contains s n=let l=String.length n in let rec f i=i+l<=String.length s&&(String.sub s i l=n||f(i+1))in f 0
let classify~kind id=let lane=if List.mem id mechanical_ids then Mechanical else if kind="method"||kind="property"then Ownership else Metadata in let package,operation,tests=if lane=Metadata then Type_metadata,"Metal.Argument_encoder opaque capability/constants",["public provenance"]else if lane=Mechanical then Layout_scalar,"Metal.Argument_encoder alignment/encoded_length",["exact NSUInteger mapping";"destroyed rejection"]else if contains id " device]"||contains id ":device"||contains id "label"||contains id "Label"then Identity_label,"Metal.Argument_encoder device/label",["device identity";"nullable label round trip"]else if contains id "constantData"||contains id "newArgumentEncoder"||contains id "setArgumentBuffer"then Argument_storage,"Metal.Argument_encoder storage/nesting",["buffer range/alignment";"nested ownership";"pointer lifetime"]else if contains id "withRange"then Array_binding,"Metal.Argument_encoder set_* array",["array/range cardinality";"same-device all elements";"atomic rejection"]else Single_binding,"Metal.Argument_encoder set_*",["index bounds";"same-device and exact handle kind";"retention until buffer replacement"]in{id;lane;package;operation;tests}
let validate items=let count f=List.length(List.filter f items)in if List.length items<>34||count(fun x->x.lane=Mechanical)<>4||count(fun x->x.lane=Ownership)<>28||count(fun x->x.lane=Metadata)<>2||List.map(fun p->count(fun x->x.package=p))[Layout_scalar;Identity_label;Argument_storage;Single_binding;Array_binding;Type_metadata]<>[4;5;4;10;9;2]then failwith"ArgumentEncoder34 handoff drift"
