let ids=
  [ "class:MTLArgument"
  ; "class:MTLArrayType"
  ; "class:MTLCommandBufferDescriptor"
  ; "class:MTLCommandQueueDescriptor"
  ; "class:MTLLogStateDescriptor"
  ; "class:MTLPointerType"
  ; "class:MTLStructMember"
  ; "class:MTLStructType"
  ; "class:MTLTensorReferenceType"
  ; "class:MTLType"
  ; "method:-[MTLArgumentEncoder alignment]"
  ; "method:-[MTLArgumentEncoder constantDataAtIndex:]"
  ; "method:-[MTLArgumentEncoder device]"
  ; "method:-[MTLArgumentEncoder encodedLength]"
  ; "method:-[MTLArgumentEncoder label]"
  ; "method:-[MTLArgumentEncoder newArgumentEncoderForBufferAtIndex:]"
  ; "method:-[MTLArgumentEncoder setAccelerationStructure:atIndex:]"
  ; "method:-[MTLArgumentEncoder setArgumentBuffer:offset:]"
  ; "method:-[MTLArgumentEncoder setArgumentBuffer:startOffset:arrayElement:]"
  ; "method:-[MTLArgumentEncoder setBuffer:offset:atIndex:]"
  ; "method:-[MTLArgumentEncoder setBuffers:offsets:withRange:]"
  ; "method:-[MTLArgumentEncoder setComputePipelineState:atIndex:]"
  ; "method:-[MTLArgumentEncoder setComputePipelineStates:withRange:]"
  ; "method:-[MTLArgumentEncoder setDepthStencilState:atIndex:]"
  ; "method:-[MTLArgumentEncoder setDepthStencilStates:withRange:]"
  ; "method:-[MTLArgumentEncoder setIndirectCommandBuffer:atIndex:]"
  ; "method:-[MTLArgumentEncoder setIndirectCommandBuffers:withRange:]"
  ; "method:-[MTLArgumentEncoder setIntersectionFunctionTable:atIndex:]"
  ; "method:-[MTLArgumentEncoder setIntersectionFunctionTables:withRange:]"
  ; "method:-[MTLArgumentEncoder setLabel:]"
  ; "method:-[MTLArgumentEncoder setRenderPipelineState:atIndex:]"
  ; "method:-[MTLArgumentEncoder setRenderPipelineStates:withRange:]"
  ; "method:-[MTLArgumentEncoder setSamplerState:atIndex:]"
  ; "method:-[MTLArgumentEncoder setSamplerStates:withRange:]"
  ; "method:-[MTLArgumentEncoder setTexture:atIndex:]"
  ; "method:-[MTLArgumentEncoder setTextures:withRange:]"
  ; "method:-[MTLArgumentEncoder setVisibleFunctionTable:atIndex:]"
  ; "method:-[MTLArgumentEncoder setVisibleFunctionTables:withRange:]"
  ; "method:-[MTLCaptureScope beginScope]"
  ; "method:-[MTLCaptureScope commandQueue]"
  ; "method:-[MTLCaptureScope device]"
  ; "method:-[MTLCaptureScope endScope]"
  ; "method:-[MTLCaptureScope label]"
  ; "method:-[MTLCaptureScope mtl4CommandQueue]"
  ; "method:-[MTLCaptureScope setLabel:]"
  ; "method:-[MTLCommandBufferDescriptor errorOptions]"
  ; "method:-[MTLCommandBufferDescriptor logState]"
  ; "method:-[MTLCommandBufferDescriptor retainedReferences]"
  ; "method:-[MTLCommandBufferDescriptor setErrorOptions:]"
  ; "method:-[MTLCommandBufferDescriptor setLogState:]"
  ; "method:-[MTLCommandBufferDescriptor setRetainedReferences:]"
  ; "method:-[MTLCommandBufferEncoderInfo debugSignposts]"
  ; "method:-[MTLCommandBufferEncoderInfo errorState]"
  ; "method:-[MTLCommandBufferEncoderInfo label]"
  ; "method:-[MTLCommandQueue commandBufferWithDescriptor:]"
  ; "method:-[MTLCommandQueue commandBufferWithUnretainedReferences]"
  ; "method:-[MTLCommandQueue device]"
  ; "method:-[MTLCommandQueue insertDebugCaptureBoundary]"
  ; "method:-[MTLCommandQueue label]"
  ; "method:-[MTLCommandQueue setLabel:]"
  ; "method:-[MTLCommandQueueDescriptor logState]"
  ; "method:-[MTLCommandQueueDescriptor maxCommandBufferCount]"
  ; "method:-[MTLCommandQueueDescriptor setLogState:]"
  ; "method:-[MTLCommandQueueDescriptor setMaxCommandBufferCount:]"
  ; "method:-[MTLDrawable addPresentedHandler:]"
  ; "method:-[MTLDrawable drawableID]"
  ; "method:-[MTLDrawable present]"
  ; "method:-[MTLDrawable presentAfterMinimumDuration:]"
  ; "method:-[MTLDrawable presentAtTime:]"
  ; "method:-[MTLDrawable presentedTime]"
  ; "method:-[MTLLinkedFunctions binaryFunctions]"
  ; "method:-[MTLLinkedFunctions groups]"
  ; "method:-[MTLLinkedFunctions privateFunctions]"
  ; "method:-[MTLLinkedFunctions setBinaryFunctions:]"
  ; "method:-[MTLLinkedFunctions setGroups:]"
  ; "method:-[MTLLinkedFunctions setPrivateFunctions:]"
  ; "method:-[MTLLogState addLogHandler:]"
  ; "method:-[MTLLogStateDescriptor bufferSize]"
  ; "method:-[MTLLogStateDescriptor level]"
  ; "method:-[MTLLogStateDescriptor setBufferSize:]"
  ; "method:-[MTLLogStateDescriptor setLevel:]"
  ; "property:MTLArgumentEncoder:alignment"
  ; "property:MTLArgumentEncoder:device"
  ; "property:MTLArgumentEncoder:encodedLength"
  ; "property:MTLArgumentEncoder:label"
  ; "property:MTLCaptureScope:commandQueue"
  ; "property:MTLCaptureScope:device"
  ; "property:MTLCaptureScope:label"
  ; "property:MTLCaptureScope:mtl4CommandQueue"
  ; "property:MTLCommandBufferDescriptor:errorOptions"
  ; "property:MTLCommandBufferDescriptor:logState"
  ; "property:MTLCommandBufferDescriptor:retainedReferences"
  ; "property:MTLCommandBufferEncoderInfo:debugSignposts"
  ; "property:MTLCommandBufferEncoderInfo:errorState"
  ; "property:MTLCommandBufferEncoderInfo:label"
  ; "property:MTLCommandQueue:device"
  ; "property:MTLCommandQueue:label"
  ; "property:MTLCommandQueueDescriptor:logState"
  ; "property:MTLCommandQueueDescriptor:maxCommandBufferCount"
  ; "property:MTLDrawable:drawableID"
  ; "property:MTLDrawable:presentedTime"
  ; "property:MTLLinkedFunctions:binaryFunctions"
  ; "property:MTLLinkedFunctions:groups"
  ; "property:MTLLinkedFunctions:privateFunctions"
  ; "property:MTLLogStateDescriptor:bufferSize"
  ; "property:MTLLogStateDescriptor:level"
  ; "protocol:MTLArgumentEncoder"
  ; "protocol:MTLCaptureScope"
  ; "protocol:MTLCommandBufferEncoderInfo"
  ; "protocol:MTLDrawable"
  ; "protocol:MTLLogContainer"
  ; "protocol:MTLLogState"
  ; "protocol:MTLTensorBinding"
  ; "typedef:MTLArgumentAccess"
  ; "typedef:MTLCommandBufferHandler"
  ; "typedef:MTLDrawablePresentedHandler"
  ; "typedef:MTLIndexType"
  ; "variable:MTLAttributeStrideStatic"
  ]
let count=List.length ids
let digest="f6d4e9f6e3d0d3b76615554006414b91ca513894d6f895363735aba43f03537f"
