let ids =
  [ "method:-[CAMetalDrawable layer]"
  ; "method:-[CAMetalDrawable texture]"
  ; "method:-[CAMetalLayer allowsNextDrawableTimeout]"
  ; "method:-[CAMetalLayer colorspace]"
  ; "method:-[CAMetalLayer device]"
  ; "method:-[CAMetalLayer displaySyncEnabled]"
  ; "method:-[CAMetalLayer drawableSize]"
  ; "method:-[CAMetalLayer EDRMetadata]"
  ; "method:-[CAMetalLayer framebufferOnly]"
  ; "method:-[CAMetalLayer maximumDrawableCount]"
  ; "method:-[CAMetalLayer nextDrawable]"
  ; "method:-[CAMetalLayer pixelFormat]"
  ; "method:-[CAMetalLayer presentsWithTransaction]"
  ; "method:-[CAMetalLayer setAllowsNextDrawableTimeout:]"
  ; "method:-[CAMetalLayer setColorspace:]"
  ; "method:-[CAMetalLayer setDevice:]"
  ; "method:-[CAMetalLayer setDisplaySyncEnabled:]"
  ; "method:-[CAMetalLayer setDrawableSize:]"
  ; "method:-[CAMetalLayer setEDRMetadata:]"
  ; "method:-[CAMetalLayer setFramebufferOnly:]"
  ; "method:-[CAMetalLayer setMaximumDrawableCount:]"
  ; "method:-[CAMetalLayer setPixelFormat:]"
  ; "method:-[CAMetalLayer setPresentsWithTransaction:]"
  ; "method:-[CAMetalLayer setWantsExtendedDynamicRangeContent:]"
  ; "method:-[CAMetalLayer wantsExtendedDynamicRangeContent]"
  ; "method:-[MTLCommandBuffer accelerationStructureCommandEncoder]"
  ; "method:-[MTLCommandBuffer accelerationStructureCommandEncoderWithDescriptor:]"
  ; "method:-[MTLCommandBuffer addCompletedHandler:]"
  ; "method:-[MTLCommandBuffer addScheduledHandler:]"
  ; "method:-[MTLCommandBuffer blitCommandEncoderWithDescriptor:]"
  ; "method:-[MTLCommandBuffer commandQueue]"
  ; "method:-[MTLCommandBuffer computeCommandEncoderWithDescriptor:]"
  ; "method:-[MTLCommandBuffer computeCommandEncoderWithDispatchType:]"
  ; "method:-[MTLCommandBuffer device]"
  ; "method:-[MTLCommandBuffer encodeSignalEvent:value:]"
  ; "method:-[MTLCommandBuffer encodeWaitForEvent:value:]"
  ; "method:-[MTLCommandBuffer enqueue]"
  ; "method:-[MTLCommandBuffer errorOptions]"
  ; "method:-[MTLCommandBuffer GPUEndTime]"
  ; "method:-[MTLCommandBuffer GPUStartTime]"
  ; "method:-[MTLCommandBuffer kernelEndTime]"
  ; "method:-[MTLCommandBuffer kernelStartTime]"
  ; "method:-[MTLCommandBuffer logs]"
  ; "method:-[MTLCommandBuffer parallelRenderCommandEncoderWithDescriptor:]"
  ; "method:-[MTLCommandBuffer popDebugGroup]"
  ; "method:-[MTLCommandBuffer presentDrawable:]"
  ; "method:-[MTLCommandBuffer presentDrawable:afterMinimumDuration:]"
  ; "method:-[MTLCommandBuffer presentDrawable:atTime:]"
  ; "method:-[MTLCommandBuffer pushDebugGroup:]"
  ; "method:-[MTLCommandBuffer renderCommandEncoderWithDescriptor:]"
  ; "method:-[MTLCommandBuffer resourceStateCommandEncoderWithDescriptor:]"
  ; "method:-[MTLCommandBuffer retainedReferences]"
  ; "method:-[MTLCommandBuffer waitUntilScheduled]"
  ; "method:-[MTLRenderPassDescriptor colorAttachments]"
  ; "method:-[MTLRenderPassDescriptor defaultRasterSampleCount]"
  ; "method:-[MTLRenderPassDescriptor depthAttachment]"
  ; "method:-[MTLRenderPassDescriptor getSamplePositions:count:]"
  ; "method:-[MTLRenderPassDescriptor imageblockSampleLength]"
  ; "method:-[MTLRenderPassDescriptor rasterizationRateMap]"
  ; "method:-[MTLRenderPassDescriptor renderTargetArrayLength]"
  ; "method:-[MTLRenderPassDescriptor renderTargetHeight]"
  ; "method:-[MTLRenderPassDescriptor renderTargetWidth]"
  ; "method:-[MTLRenderPassDescriptor sampleBufferAttachments]"
  ; "method:-[MTLRenderPassDescriptor setDefaultRasterSampleCount:]"
  ; "method:-[MTLRenderPassDescriptor setDepthAttachment:]"
  ; "method:-[MTLRenderPassDescriptor setImageblockSampleLength:]"
  ; "method:-[MTLRenderPassDescriptor setRasterizationRateMap:]"
  ; "method:-[MTLRenderPassDescriptor setRenderTargetArrayLength:]"
  ; "method:-[MTLRenderPassDescriptor setRenderTargetHeight:]"
  ; "method:-[MTLRenderPassDescriptor setRenderTargetWidth:]"
  ; "method:-[MTLRenderPassDescriptor setSamplePositions:count:]"
  ; "method:-[MTLRenderPassDescriptor setStencilAttachment:]"
  ; "method:-[MTLRenderPassDescriptor setSupportColorAttachmentMapping:]"
  ; "method:-[MTLRenderPassDescriptor setThreadgroupMemoryLength:]"
  ; "method:-[MTLRenderPassDescriptor setTileHeight:]"
  ; "method:-[MTLRenderPassDescriptor setTileWidth:]"
  ; "method:-[MTLRenderPassDescriptor setVisibilityResultBuffer:]"
  ; "method:-[MTLRenderPassDescriptor setVisibilityResultType:]"
  ; "method:-[MTLRenderPassDescriptor stencilAttachment]"
  ; "method:-[MTLRenderPassDescriptor supportColorAttachmentMapping]"
  ; "method:-[MTLRenderPassDescriptor threadgroupMemoryLength]"
  ; "method:-[MTLRenderPassDescriptor tileHeight]"
  ; "method:-[MTLRenderPassDescriptor tileWidth]"
  ; "method:-[MTLRenderPassDescriptor visibilityResultBuffer]"
  ; "method:-[MTLRenderPassDescriptor visibilityResultType]"
  ; "method:+[MTLRenderPassDescriptor renderPassDescriptor]"
  ; "property:CAMetalDrawable:layer"
  ; "property:CAMetalDrawable:texture"
  ; "property:CAMetalLayer:allowsNextDrawableTimeout"
  ; "property:CAMetalLayer:colorspace"
  ; "property:CAMetalLayer:device"
  ; "property:CAMetalLayer:displaySyncEnabled"
  ; "property:CAMetalLayer:drawableSize"
  ; "property:CAMetalLayer:EDRMetadata"
  ; "property:CAMetalLayer:framebufferOnly"
  ; "property:CAMetalLayer:maximumDrawableCount"
  ; "property:CAMetalLayer:pixelFormat"
  ; "property:CAMetalLayer:presentsWithTransaction"
  ; "property:CAMetalLayer:wantsExtendedDynamicRangeContent"
  ; "property:MTLCommandBuffer:commandQueue"
  ; "property:MTLCommandBuffer:device"
  ; "property:MTLCommandBuffer:errorOptions"
  ; "property:MTLCommandBuffer:GPUEndTime"
  ; "property:MTLCommandBuffer:GPUStartTime"
  ; "property:MTLCommandBuffer:kernelEndTime"
  ; "property:MTLCommandBuffer:kernelStartTime"
  ; "property:MTLCommandBuffer:logs"
  ; "property:MTLCommandBuffer:retainedReferences"
  ; "property:MTLRenderPassDescriptor:colorAttachments"
  ; "property:MTLRenderPassDescriptor:defaultRasterSampleCount"
  ; "property:MTLRenderPassDescriptor:depthAttachment"
  ; "property:MTLRenderPassDescriptor:imageblockSampleLength"
  ; "property:MTLRenderPassDescriptor:rasterizationRateMap"
  ; "property:MTLRenderPassDescriptor:renderTargetArrayLength"
  ; "property:MTLRenderPassDescriptor:renderTargetHeight"
  ; "property:MTLRenderPassDescriptor:renderTargetWidth"
  ; "property:MTLRenderPassDescriptor:sampleBufferAttachments"
  ; "property:MTLRenderPassDescriptor:stencilAttachment"
  ; "property:MTLRenderPassDescriptor:supportColorAttachmentMapping"
  ; "property:MTLRenderPassDescriptor:threadgroupMemoryLength"
  ; "property:MTLRenderPassDescriptor:tileHeight"
  ; "property:MTLRenderPassDescriptor:tileWidth"
  ; "property:MTLRenderPassDescriptor:visibilityResultBuffer"
  ; "property:MTLRenderPassDescriptor:visibilityResultType"
  ; "record:_CAMetalLayerPrivate"
  ]

let count = List.length ids
let digest = "82710196daca14152ffc09bf9079d55ce1cd0e8dbdcfe9fbd4fb93055e680d92"
