type handoff = Existing_safe | Constructor_graph | Parent_metadata | Completion_retention | Buffer_backed_texture_graph
type item={id:string;raw_symbol:string;native_symbol:string;safe_operation:string;handoff:handoff}
let contains s n=let l=String.length n in let rec f i=i+l<=String.length s&&(String.sub s i l=n||f(i+1))in f 0
let raw id =
 if contains id "resourceStatePassDescriptor" then "resource_pass_create"
 else if contains id "texture2DDescriptor" then "resource_texture_descriptor_2d"
 else if contains id "textureBufferDescriptor" then "resource_texture_descriptor_buffer"
 else if contains id "textureCubeDescriptor" then "resource_texture_descriptor_cube"
 else if contains id "addDebugMarker" then "resource_buffer_add_debug_marker"
 else if contains id "newRemoteBufferView" then "resource_buffer_remote_view"
 else if contains id "newTensor" then "resource_buffer_new_tensor"
 else if contains id "remoteStorageBuffer" then "resource_buffer_remote_storage"
 else if contains id "MTLBufferLayoutDescriptorArray object" then "resource_layout_array_get"
 else if contains id "MTLBufferLayoutDescriptorArray setObject" then "resource_layout_array_set"
 else if contains id "resourceStateCommandEncoderWithDescriptor" then "resource_command_buffer_state_encoder"
 else if contains id "newTextureViewPool" then "resource_device_new_view_pool"
 else if contains id "MTLHeap device"||contains id "MTLHeap:device" then "resource_heap_device"
 else if contains id "newAccelerationStructureWithDescriptor:offset" then "resource_heap_acceleration_descriptor_offset"
 else if contains id "newAccelerationStructureWithDescriptor" then "resource_heap_acceleration_descriptor"
 else if contains id "newAccelerationStructureWithSize:offset" then "resource_heap_acceleration_size_offset"
 else if contains id "newAccelerationStructureWithSize" then "resource_heap_acceleration_size"
 else if contains id "MTLResource device"||contains id "MTLResource:device" then "resource_resource_device"
 else if contains id "MTLResource heap"||contains id "MTLResource:heap" then "resource_resource_heap"
 else if contains id "setOwnerWithIdentity" then "resource_set_owner"
 else if contains id "moveTextureMappings" then "resource_encoder_move_texture"
 else if contains id "updateFence" then "resource_encoder_update_fence"
 else if contains id "indirectBuffer" then "resource_encoder_indirect_mapping"
 else if contains id "updateTextureMappings" then "resource_encoder_mappings"
 else if contains id "waitForFence" then "resource_encoder_wait_fence"
 else if contains id "sampleBufferAttachments" then "resource_pass_sample_attachments"
 else if contains id "SampleBufferAttachmentDescriptor sampleBuffer"||contains id "SampleBufferAttachmentDescriptor:sampleBuffer" then "resource_sample_attachment_buffer"
 else if contains id "setSampleBuffer" then "resource_sample_attachment_set_buffer"
 else if contains id "AttachmentDescriptorArray object" then "resource_sample_array_get"
 else if contains id "AttachmentDescriptorArray setObject" then "resource_sample_array_set"
 else if contains id "baseResourceID" then "resource_pool_base_id"
 else if contains id "copyResourceViews" then "resource_pool_copy"
 else if contains id "MTLResourceViewPool device"||contains id "MTLResourceViewPool:device" then "resource_pool_device"
 else if contains id "MTLResourceViewPool label"||contains id "MTLResourceViewPool:label" then "resource_pool_label"
 else if contains id "resourceViewCount" then "resource_pool_count"
 else if contains id "getBytes" then "resource_texture_get_bytes"
 else if contains id "newRemoteTextureView" then "resource_texture_remote_view"
 else if contains id "newTextureViewWithPixelFormat" then "resource_texture_view"
 else if contains id "remoteStorageTexture" then "resource_texture_remote_storage"
 else if contains id "replaceRegion" then "resource_texture_replace"
 else if contains id "rootResource" then "resource_texture_root"
 else if contains id "setTextureViewFromBuffer" then "resource_texture_pool_set_buffer"
 else if contains id "setTextureView:descriptor" then "resource_texture_pool_set_descriptor"
 else if contains id "setTextureView:atIndex" then "resource_texture_pool_set"
 else if contains id "MTLTexture:buffer" then "resource_texture_buffer_graph"
 else failwith("missing Resource100 raw mapping: "^id)
let handoff id=if contains id "MTLTexture:buffer" then Buffer_backed_texture_graph else if contains id "resourceStateCommandEncoder"||contains id "ResourceStateCommandEncoder" then Completion_retention else if contains id "Descriptor"||contains id " new"||String.starts_with~prefix:"method:+"id then Constructor_graph else if (Binding_resource_safe_reachability.find id).status=Binding_resource_safe_reachability.Promotable then Existing_safe else Parent_metadata
let items=List.map(fun id->let raw_symbol=raw id in{id;raw_symbol;native_symbol="caml_prismel_metal_"^raw_symbol;safe_operation=(Binding_resource_safe_reachability.find id).public_operation;handoff=handoff id})Binding_resource_native_closure.callable_ids
let buffer_backed_texture_ids=List.filter_map(fun x->if x.handoff=Buffer_backed_texture_graph then Some x.id else None)items
let validate()=if List.length items<>59||List.length buffer_backed_texture_ids<>3||List.exists(fun x->x.raw_symbol=""||x.native_symbol=""||x.safe_operation="")items then failwith"Resource100 native59 reachability drift"
let ()=validate()
