let ids=
  [ "class:MTLCaptureDescriptor"
  ; "class:MTLCaptureManager"
  ; "class:MTLSharedEventHandle"
  ; "class:MTLSharedEventListener"
  ; "method:-[MTLBlitCommandEncoder copyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]"
  ; "method:-[MTLBlitCommandEncoder copyFromBuffer:sourceOffset:toBuffer:destinationOffset:size:]"
  ; "method:-[MTLBlitCommandEncoder copyFromTensor:sourceOrigin:sourceDimensions:toTensor:destinationOrigin:destinationDimensions:]"
  ; "method:-[MTLBlitCommandEncoder copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toBuffer:destinationOffset:destinationBytesPerRow:destinationBytesPerImage:]"
  ; "method:-[MTLBlitCommandEncoder copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toBuffer:destinationOffset:destinationBytesPerRow:destinationBytesPerImage:options:]"
  ; "method:-[MTLBlitCommandEncoder copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:]"
  ; "method:-[MTLBlitCommandEncoder copyFromTexture:sourceSlice:sourceLevel:toTexture:destinationSlice:destinationLevel:sliceCount:levelCount:]"
  ; "method:-[MTLBlitCommandEncoder copyFromTexture:toTexture:]"
  ; "method:-[MTLBlitCommandEncoder copyIndirectCommandBuffer:sourceRange:destination:destinationIndex:]"
  ; "method:-[MTLBlitCommandEncoder fillBuffer:range:value:]"
  ; "method:-[MTLBlitCommandEncoder generateMipmapsForTexture:]"
  ; "method:-[MTLBlitCommandEncoder getTextureAccessCounters:region:mipLevel:slice:resetCounters:countersBuffer:countersBufferOffset:]"
  ; "method:-[MTLBlitCommandEncoder optimizeContentsForCPUAccess:]"
  ; "method:-[MTLBlitCommandEncoder optimizeContentsForCPUAccess:slice:level:]"
  ; "method:-[MTLBlitCommandEncoder optimizeContentsForGPUAccess:]"
  ; "method:-[MTLBlitCommandEncoder optimizeContentsForGPUAccess:slice:level:]"
  ; "method:-[MTLBlitCommandEncoder optimizeIndirectCommandBuffer:withRange:]"
  ; "method:-[MTLBlitCommandEncoder resetCommandsInBuffer:withRange:]"
  ; "method:-[MTLBlitCommandEncoder resetTextureAccessCounters:region:mipLevel:slice:]"
  ; "method:-[MTLBlitCommandEncoder resolveCounters:inRange:destinationBuffer:destinationOffset:]"
  ; "method:-[MTLBlitCommandEncoder sampleCountersInBuffer:atSampleIndex:withBarrier:]"
  ; "method:-[MTLBlitCommandEncoder synchronizeResource:]"
  ; "method:-[MTLBlitCommandEncoder synchronizeTexture:slice:level:]"
  ; "method:-[MTLBlitCommandEncoder updateFence:]"
  ; "method:-[MTLBlitCommandEncoder waitForFence:]"
  ; "method:-[MTLCaptureDescriptor captureObject]"
  ; "method:-[MTLCaptureDescriptor destination]"
  ; "method:-[MTLCaptureDescriptor outputURL]"
  ; "method:-[MTLCaptureDescriptor setCaptureObject:]"
  ; "method:-[MTLCaptureDescriptor setDestination:]"
  ; "method:-[MTLCaptureDescriptor setOutputURL:]"
  ; "method:-[MTLCaptureManager defaultCaptureScope]"
  ; "method:-[MTLCaptureManager isCapturing]"
  ; "method:-[MTLCaptureManager newCaptureScopeWithCommandQueue:]"
  ; "method:-[MTLCaptureManager newCaptureScopeWithDevice:]"
  ; "method:-[MTLCaptureManager newCaptureScopeWithMTL4CommandQueue:]"
  ; "method:-[MTLCaptureManager setDefaultCaptureScope:]"
  ; "method:-[MTLCaptureManager startCaptureWithCommandQueue:]"
  ; "method:-[MTLCaptureManager startCaptureWithDescriptor:error:]"
  ; "method:-[MTLCaptureManager startCaptureWithDevice:]"
  ; "method:-[MTLCaptureManager startCaptureWithScope:]"
  ; "method:-[MTLCaptureManager stopCapture]"
  ; "method:-[MTLCaptureManager supportsDestination:]"
  ; "method:-[MTLEvent device]"
  ; "method:-[MTLEvent label]"
  ; "method:-[MTLEvent setLabel:]"
  ; "method:-[MTLFunctionLog debugLocation]"
  ; "method:-[MTLFunctionLog encoderLabel]"
  ; "method:-[MTLFunctionLog function]"
  ; "method:-[MTLFunctionLog type]"
  ; "method:-[MTLFunctionLogDebugLocation column]"
  ; "method:-[MTLFunctionLogDebugLocation functionName]"
  ; "method:-[MTLFunctionLogDebugLocation line]"
  ; "method:-[MTLFunctionLogDebugLocation URL]"
  ; "method:-[MTLIndirectComputeCommand clearBarrier]"
  ; "method:-[MTLIndirectComputeCommand concurrentDispatchThreadgroups:threadsPerThreadgroup:]"
  ; "method:-[MTLIndirectComputeCommand setBarrier]"
  ; "method:-[MTLIndirectComputeCommand setImageblockWidth:height:]"
  ; "method:-[MTLIndirectComputeCommand setKernelBuffer:offset:attributeStride:atIndex:]"
  ; "method:-[MTLIndirectComputeCommand setStageInRegion:]"
  ; "method:-[MTLIndirectComputeCommand setThreadgroupMemoryLength:atIndex:]"
  ; "method:-[MTLIndirectRenderCommand clearBarrier]"
  ; "method:-[MTLIndirectRenderCommand drawIndexedPatches:patchStart:patchCount:patchIndexBuffer:patchIndexBufferOffset:controlPointIndexBuffer:controlPointIndexBufferOffset:instanceCount:baseInstance:tessellationFactorBuffer:tessellationFactorBufferOffset:tessellationFactorBufferInstanceStride:]"
  ; "method:-[MTLIndirectRenderCommand drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:instanceCount:baseVertex:baseInstance:]"
  ; "method:-[MTLIndirectRenderCommand drawMeshThreadgroups:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:]"
  ; "method:-[MTLIndirectRenderCommand drawMeshThreads:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:]"
  ; "method:-[MTLIndirectRenderCommand drawPatches:patchStart:patchCount:patchIndexBuffer:patchIndexBufferOffset:instanceCount:baseInstance:tessellationFactorBuffer:tessellationFactorBufferOffset:tessellationFactorBufferInstanceStride:]"
  ; "method:-[MTLIndirectRenderCommand drawPrimitives:vertexStart:vertexCount:instanceCount:baseInstance:]"
  ; "method:-[MTLIndirectRenderCommand reset]"
  ; "method:-[MTLIndirectRenderCommand setBarrier]"
  ; "method:-[MTLIndirectRenderCommand setCullMode:]"
  ; "method:-[MTLIndirectRenderCommand setDepthBias:slopeScale:clamp:]"
  ; "method:-[MTLIndirectRenderCommand setDepthClipMode:]"
  ; "method:-[MTLIndirectRenderCommand setDepthStencilState:]"
  ; "method:-[MTLIndirectRenderCommand setFragmentBuffer:offset:atIndex:]"
  ; "method:-[MTLIndirectRenderCommand setFrontFacingWinding:]"
  ; "method:-[MTLIndirectRenderCommand setMeshBuffer:offset:atIndex:]"
  ; "method:-[MTLIndirectRenderCommand setObjectBuffer:offset:atIndex:]"
  ; "method:-[MTLIndirectRenderCommand setObjectThreadgroupMemoryLength:atIndex:]"
  ; "method:-[MTLIndirectRenderCommand setRenderPipelineState:]"
  ; "method:-[MTLIndirectRenderCommand setTriangleFillMode:]"
  ; "method:-[MTLIndirectRenderCommand setVertexBuffer:offset:atIndex:]"
  ; "method:-[MTLIndirectRenderCommand setVertexBuffer:offset:attributeStride:atIndex:]"
  ; "method:-[MTLSharedEvent newSharedEventHandle]"
  ; "method:-[MTLSharedEvent notifyListener:atValue:block:]"
  ; "method:-[MTLSharedEvent setSignaledValue:]"
  ; "method:-[MTLSharedEvent signaledValue]"
  ; "method:-[MTLSharedEventHandle label]"
  ; "method:-[MTLSharedEventListener dispatchQueue]"
  ; "method:-[MTLSharedEventListener init]"
  ; "method:-[MTLSharedEventListener initWithDispatchQueue:]"
  ; "method:+[MTLCaptureManager sharedCaptureManager]"
  ; "method:+[MTLSharedEventListener sharedListener]"
  ; "property:MTLCaptureDescriptor:captureObject"
  ; "property:MTLCaptureDescriptor:destination"
  ; "property:MTLCaptureDescriptor:outputURL"
  ; "property:MTLCaptureManager:defaultCaptureScope"
  ; "property:MTLCaptureManager:isCapturing"
  ; "property:MTLEvent:device"
  ; "property:MTLEvent:label"
  ; "property:MTLFunctionLog:debugLocation"
  ; "property:MTLFunctionLog:encoderLabel"
  ; "property:MTLFunctionLog:function"
  ; "property:MTLFunctionLog:type"
  ; "property:MTLFunctionLogDebugLocation:column"
  ; "property:MTLFunctionLogDebugLocation:functionName"
  ; "property:MTLFunctionLogDebugLocation:line"
  ; "property:MTLFunctionLogDebugLocation:URL"
  ; "property:MTLSharedEvent:signaledValue"
  ; "property:MTLSharedEventHandle:label"
  ; "property:MTLSharedEventListener:dispatchQueue"
  ; "protocol:MTLFunctionLog"
  ; "protocol:MTLFunctionLogDebugLocation"
  ; "protocol:MTLIndirectComputeCommand"
  ; "protocol:MTLIndirectRenderCommand"
  ; "record:MTLSharedEventHandlePrivate"
  ; "typedef:MTLSharedEventNotificationBlock"
  ]
let count=List.length ids
let digest="4ce3c9d04f22236b42c0ba183fd079144cbe64a047461f4f023069eba6a260af"
