let ids=
  [ "class:MTL4BinaryFunction"
  ; "class:MTL4CommandBufferOptions"
  ; "class:MTL4CounterHeapDescriptor"
  ; "class:MTL4MachineLearningPipelineDescriptor"
  ; "class:MTL4MachineLearningPipelineReflection"
  ; "class:MTL4RenderPipelineBinaryFunctionsDescriptor"
  ; "class:MTL4SpecializedFunctionDescriptor"
  ; "class:MTL4StitchedFunctionDescriptor"
  ; "class:MTLDynamicLibrary"
  ; "enum-case:MTL4BlendState:MTL4BlendStateUnspecialized"
  ; "enum-case:MTL4ShaderReflection:MTL4ShaderReflectionNone"
  ; "enum-case:MTL4VisibilityOptions:MTL4VisibilityOptionDevice"
  ; "enum-case:MTL4VisibilityOptions:MTL4VisibilityOptionNone"
  ; "function:MTL4BufferRangeMake"
  ; "method:-[MTL4Archive newComputePipelineStateWithDescriptor:dynamicLinkingDescriptor:error:]"
  ; "method:-[MTL4Archive newComputePipelineStateWithDescriptor:error:]"
  ; "method:-[MTL4Archive newRenderPipelineStateWithDescriptor:dynamicLinkingDescriptor:error:]"
  ; "method:-[MTL4Archive newRenderPipelineStateWithDescriptor:error:]"
  ; "method:-[MTL4ArgumentTable setResource:atBufferIndex:]"
  ; "method:-[MTL4BinaryFunction functionType]"
  ; "method:-[MTL4BinaryFunction name]"
  ; "method:-[MTL4CommandBuffer beginCommandBufferWithAllocator:options:]"
  ; "method:-[MTL4CommandBuffer machineLearningCommandEncoder]"
  ; "method:-[MTL4CommandBuffer popDebugGroup]"
  ; "method:-[MTL4CommandBuffer pushDebugGroup:]"
  ; "method:-[MTL4CommandBuffer renderCommandEncoderWithDescriptor:options:]"
  ; "method:-[MTL4CommandBuffer resolveCounterHeap:withRange:intoBuffer:waitFence:updateFence:]"
  ; "method:-[MTL4CommandBuffer useResidencySet:]"
  ; "method:-[MTL4CommandBuffer useResidencySets:count:]"
  ; "method:-[MTL4CommandBuffer writeTimestampIntoHeap:atIndex:]"
  ; "method:-[MTL4CommandBufferOptions logState]"
  ; "method:-[MTL4CommandBufferOptions setLogState:]"
  ; "method:-[MTL4CommandEncoder barrierAfterEncoderStages:beforeEncoderStages:visibilityOptions:]"
  ; "method:-[MTL4CommandEncoder barrierAfterStages:beforeQueueStages:visibilityOptions:]"
  ; "method:-[MTL4CommandEncoder insertDebugSignpost:]"
  ; "method:-[MTL4CommandEncoder popDebugGroup]"
  ; "method:-[MTL4CommandEncoder pushDebugGroup:]"
  ; "method:-[MTL4CommandEncoder updateFence:afterEncoderStages:]"
  ; "method:-[MTL4CommandEncoder waitForFence:beforeEncoderStages:]"
  ; "method:-[MTL4CommandQueue addResidencySet:]"
  ; "method:-[MTL4CommandQueue addResidencySets:count:]"
  ; "method:-[MTL4CommandQueue copyBufferMappingsFromBuffer:toBuffer:operations:count:]"
  ; "method:-[MTL4CommandQueue copyTextureMappingsFromTexture:toTexture:operations:count:]"
  ; "method:-[MTL4CommandQueue removeResidencySet:]"
  ; "method:-[MTL4CommandQueue removeResidencySets:count:]"
  ; "method:-[MTL4CommandQueue signalDrawable:]"
  ; "method:-[MTL4CommandQueue waitForDrawable:]"
  ; "method:-[MTL4CommandQueue waitForEvent:value:]"
  ; "method:-[MTL4CommandQueueDescriptor feedbackQueue]"
  ; "method:-[MTL4CommandQueueDescriptor setFeedbackQueue:]"
  ; "method:-[MTL4CommitFeedback GPUEndTime]"
  ; "method:-[MTL4CommitFeedback GPUStartTime]"
  ; "method:-[MTL4Compiler newMachineLearningPipelineStateWithDescriptor:completionHandler:]"
  ; "method:-[MTL4Compiler newMachineLearningPipelineStateWithDescriptor:error:]"
  ; "method:-[MTL4Compiler newRenderPipelineStateBySpecializationWithDescriptor:pipeline:completionHandler:]"
  ; "method:-[MTL4Compiler newRenderPipelineStateBySpecializationWithDescriptor:pipeline:error:]"
  ; "method:-[MTL4ComputeCommandEncoder buildAccelerationStructure:descriptor:scratchBuffer:]"
  ; "method:-[MTL4ComputeCommandEncoder copyAccelerationStructure:toAccelerationStructure:]"
  ; "method:-[MTL4ComputeCommandEncoder copyAndCompactAccelerationStructure:toAccelerationStructure:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromBuffer:sourceOffset:toBuffer:destinationOffset:size:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromTensor:sourceOrigin:sourceDimensions:toTensor:destinationOrigin:destinationDimensions:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toBuffer:destinationOffset:destinationBytesPerRow:destinationBytesPerImage:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toBuffer:destinationOffset:destinationBytesPerRow:destinationBytesPerImage:options:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromTexture:sourceSlice:sourceLevel:toTexture:destinationSlice:destinationLevel:sliceCount:levelCount:]"
  ; "method:-[MTL4ComputeCommandEncoder copyFromTexture:toTexture:]"
  ; "method:-[MTL4ComputeCommandEncoder copyIndirectCommandBuffer:sourceRange:destination:destinationIndex:]"
  ; "method:-[MTL4ComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]"
  ; "method:-[MTL4ComputeCommandEncoder dispatchThreadgroupsWithIndirectBuffer:threadsPerThreadgroup:]"
  ; "method:-[MTL4ComputeCommandEncoder dispatchThreadsWithIndirectBuffer:]"
  ; "method:-[MTL4ComputeCommandEncoder executeCommandsInBuffer:indirectBuffer:]"
  ; "method:-[MTL4ComputeCommandEncoder executeCommandsInBuffer:withRange:]"
  ; "method:-[MTL4ComputeCommandEncoder fillBuffer:range:value:]"
  ; "method:-[MTL4ComputeCommandEncoder generateMipmapsForTexture:]"
  ; "method:-[MTL4ComputeCommandEncoder optimizeContentsForCPUAccess:]"
  ; "method:-[MTL4ComputeCommandEncoder optimizeContentsForCPUAccess:slice:level:]"
  ; "method:-[MTL4ComputeCommandEncoder optimizeContentsForGPUAccess:]"
  ; "method:-[MTL4ComputeCommandEncoder optimizeContentsForGPUAccess:slice:level:]"
  ; "method:-[MTL4ComputeCommandEncoder optimizeIndirectCommandBuffer:withRange:]"
  ; "method:-[MTL4ComputeCommandEncoder refitAccelerationStructure:descriptor:destination:scratchBuffer:]"
  ; "method:-[MTL4ComputeCommandEncoder refitAccelerationStructure:descriptor:destination:scratchBuffer:options:]"
  ; "method:-[MTL4ComputeCommandEncoder resetCommandsInBuffer:withRange:]"
  ; "method:-[MTL4ComputeCommandEncoder setImageblockWidth:height:]"
  ; "method:-[MTL4ComputeCommandEncoder stages]"
  ; "method:-[MTL4ComputeCommandEncoder writeCompactedAccelerationStructureSize:toBuffer:]"
  ; "method:-[MTL4ComputeCommandEncoder writeTimestampWithGranularity:intoHeap:atIndex:]"
  ; "method:-[MTL4ComputePipelineDescriptor reset]"
  ; "method:-[MTL4CounterHeap count]"
  ; "method:-[MTL4CounterHeap invalidateCounterRange:]"
  ; "method:-[MTL4CounterHeap label]"
  ; "method:-[MTL4CounterHeap resolveCounterRange:]"
  ; "method:-[MTL4CounterHeap setLabel:]"
  ; "method:-[MTL4CounterHeap type]"
  ; "method:-[MTL4CounterHeapDescriptor count]"
  ; "method:-[MTL4CounterHeapDescriptor setCount:]"
  ; "method:-[MTL4CounterHeapDescriptor setType:]"
  ; "method:-[MTL4CounterHeapDescriptor type]"
  ; "method:-[MTL4MachineLearningCommandEncoder dispatchNetworkWithIntermediatesHeap:]"
  ; "method:-[MTL4MachineLearningCommandEncoder setArgumentTable:]"
  ; "method:-[MTL4MachineLearningCommandEncoder setPipelineState:]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor inputDimensionsAtBufferIndex:]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor label]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor machineLearningFunctionDescriptor]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor reset]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor setInputDimensions:atBufferIndex:]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor setInputDimensions:withRange:]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor setLabel:]"
  ; "method:-[MTL4MachineLearningPipelineDescriptor setMachineLearningFunctionDescriptor:]"
  ; "method:-[MTL4MachineLearningPipelineReflection bindings]"
  ; "method:-[MTL4MachineLearningPipelineState device]"
  ; "method:-[MTL4MachineLearningPipelineState intermediatesHeapSize]"
  ; "method:-[MTL4MachineLearningPipelineState label]"
  ; "method:-[MTL4MachineLearningPipelineState reflection]"
  ; "method:-[MTL4RenderCommandEncoder drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferLength:instanceCount:]"
  ; "method:-[MTL4RenderCommandEncoder drawMeshThreadgroupsWithIndirectBuffer:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:]"
  ; "method:-[MTL4RenderCommandEncoder drawMeshThreads:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:]"
  ; "method:-[MTL4RenderCommandEncoder drawPrimitives:vertexStart:vertexCount:instanceCount:]"
  ; "method:-[MTL4RenderCommandEncoder executeCommandsInBuffer:indirectBuffer:]"
  ; "method:-[MTL4RenderCommandEncoder executeCommandsInBuffer:withRange:]"
  ; "method:-[MTL4RenderCommandEncoder setObjectThreadgroupMemoryLength:atIndex:]"
  ; "method:-[MTL4RenderCommandEncoder setThreadgroupMemoryLength:offset:atIndex:]"
  ; "method:-[MTL4RenderCommandEncoder writeTimestampWithGranularity:afterStage:intoHeap:atIndex:]"
  ; "method:-[MTL4RenderPassDescriptor getSamplePositions:count:]"
  ; "method:-[MTL4RenderPassDescriptor rasterizationRateMap]"
  ; "method:-[MTL4RenderPassDescriptor setDepthAttachment:]"
  ; "method:-[MTL4RenderPassDescriptor setRasterizationRateMap:]"
  ; "method:-[MTL4RenderPassDescriptor setSamplePositions:count:]"
  ; "method:-[MTL4RenderPassDescriptor setStencilAttachment:]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor fragmentAdditionalBinaryFunctions]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor meshAdditionalBinaryFunctions]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor objectAdditionalBinaryFunctions]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor reset]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor setFragmentAdditionalBinaryFunctions:]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor setMeshAdditionalBinaryFunctions:]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor setObjectAdditionalBinaryFunctions:]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor setTileAdditionalBinaryFunctions:]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor setVertexAdditionalBinaryFunctions:]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor tileAdditionalBinaryFunctions]"
  ; "method:-[MTL4RenderPipelineBinaryFunctionsDescriptor vertexAdditionalBinaryFunctions]"
  ; "method:-[MTL4RenderPipelineColorAttachmentDescriptor reset]"
  ; "method:-[MTL4RenderPipelineColorAttachmentDescriptorArray reset]"
  ; "method:-[MTL4SpecializedFunctionDescriptor constantValues]"
  ; "method:-[MTL4SpecializedFunctionDescriptor functionDescriptor]"
  ; "method:-[MTL4SpecializedFunctionDescriptor setConstantValues:]"
  ; "method:-[MTL4SpecializedFunctionDescriptor setFunctionDescriptor:]"
  ; "method:-[MTL4SpecializedFunctionDescriptor setSpecializedName:]"
  ; "method:-[MTL4SpecializedFunctionDescriptor specializedName]"
  ; "method:-[MTL4StitchedFunctionDescriptor functionDescriptors]"
  ; "method:-[MTL4StitchedFunctionDescriptor functionGraph]"
  ; "method:-[MTL4StitchedFunctionDescriptor setFunctionDescriptors:]"
  ; "method:-[MTL4StitchedFunctionDescriptor setFunctionGraph:]"
  ; "property:MTL4BinaryFunction:functionType"
  ; "property:MTL4BinaryFunction:name"
  ; "property:MTL4CommandBufferOptions:logState"
  ; "property:MTL4CommandQueueDescriptor:feedbackQueue"
  ; "property:MTL4CommitFeedback:GPUEndTime"
  ; "property:MTL4CommitFeedback:GPUStartTime"
  ; "property:MTL4CounterHeap:count"
  ; "property:MTL4CounterHeap:label"
  ; "property:MTL4CounterHeap:type"
  ; "property:MTL4CounterHeapDescriptor:count"
  ; "property:MTL4CounterHeapDescriptor:type"
  ; "property:MTL4MachineLearningPipelineDescriptor:label"
  ; "property:MTL4MachineLearningPipelineDescriptor:machineLearningFunctionDescriptor"
  ; "property:MTL4MachineLearningPipelineReflection:bindings"
  ; "property:MTL4MachineLearningPipelineState:device"
  ; "property:MTL4MachineLearningPipelineState:intermediatesHeapSize"
  ; "property:MTL4MachineLearningPipelineState:label"
  ; "property:MTL4MachineLearningPipelineState:reflection"
  ; "property:MTL4RenderPassDescriptor:rasterizationRateMap"
  ; "property:MTL4RenderPipelineBinaryFunctionsDescriptor:fragmentAdditionalBinaryFunctions"
  ; "property:MTL4RenderPipelineBinaryFunctionsDescriptor:meshAdditionalBinaryFunctions"
  ; "property:MTL4RenderPipelineBinaryFunctionsDescriptor:objectAdditionalBinaryFunctions"
  ; "property:MTL4RenderPipelineBinaryFunctionsDescriptor:tileAdditionalBinaryFunctions"
  ; "property:MTL4RenderPipelineBinaryFunctionsDescriptor:vertexAdditionalBinaryFunctions"
  ; "property:MTL4SpecializedFunctionDescriptor:constantValues"
  ; "property:MTL4SpecializedFunctionDescriptor:functionDescriptor"
  ; "property:MTL4SpecializedFunctionDescriptor:specializedName"
  ; "property:MTL4StitchedFunctionDescriptor:functionDescriptors"
  ; "property:MTL4StitchedFunctionDescriptor:functionGraph"
  ; "protocol:MTL4CounterHeap"
  ; "protocol:MTL4MachineLearningCommandEncoder"
  ; "protocol:MTL4MachineLearningPipelineState"
  ; "typedef:MTL4BufferRange"
  ; "typedef:MTL4CopySparseBufferMappingOperation"
  ; "typedef:MTL4CopySparseTextureMappingOperation"
  ; "typedef:MTL4NewMachineLearningPipelineStateCompletionHandler"
  ; "typedef:MTL4TimestampHeapEntry"
  ]
let count=List.length ids
let digest="3c2848f1c1dc8b31de399cb502a444f30a672b1da00c07246989f0561dd0c2a4"
