let ids=
  [ "class:MTLComputePassDescriptor"
  ; "class:MTLComputePassSampleBufferAttachmentDescriptor"
  ; "class:MTLComputePassSampleBufferAttachmentDescriptorArray"
  ; "enum-case:MTLStages:MTLStageAccelerationStructure"
  ; "enum-case:MTLStages:MTLStageBlit"
  ; "enum-case:MTLStages:MTLStageDispatch"
  ; "enum-case:MTLStages:MTLStageFragment"
  ; "enum-case:MTLStages:MTLStageMachineLearning"
  ; "enum-case:MTLStages:MTLStageMesh"
  ; "enum-case:MTLStages:MTLStageObject"
  ; "enum-case:MTLStages:MTLStageTile"
  ; "enum-case:MTLStages:MTLStageVertex"
  ; "method:-[MTLCommandEncoder barrierAfterQueueStages:beforeStages:]"
  ; "method:-[MTLCommandEncoder device]"
  ; "method:-[MTLCommandEncoder insertDebugSignpost:]"
  ; "method:-[MTLCommandEncoder label]"
  ; "method:-[MTLCommandEncoder popDebugGroup]"
  ; "method:-[MTLCommandEncoder pushDebugGroup:]"
  ; "method:-[MTLCommandEncoder setLabel:]"
  ; "method:-[MTLComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]"
  ; "method:-[MTLComputeCommandEncoder dispatchThreadgroupsWithIndirectBuffer:indirectBufferOffset:threadsPerThreadgroup:]"
  ; "method:-[MTLComputeCommandEncoder dispatchType]"
  ; "method:-[MTLComputeCommandEncoder executeCommandsInBuffer:indirectBuffer:indirectBufferOffset:]"
  ; "method:-[MTLComputeCommandEncoder memoryBarrierWithResources:count:]"
  ; "method:-[MTLComputeCommandEncoder memoryBarrierWithScope:]"
  ; "method:-[MTLComputeCommandEncoder sampleCountersInBuffer:atSampleIndex:withBarrier:]"
  ; "method:-[MTLComputeCommandEncoder setAccelerationStructure:atBufferIndex:]"
  ; "method:-[MTLComputeCommandEncoder setBuffer:offset:attributeStride:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setBufferOffset:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setBufferOffset:attributeStride:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setBuffers:offsets:attributeStrides:withRange:]"
  ; "method:-[MTLComputeCommandEncoder setBuffers:offsets:withRange:]"
  ; "method:-[MTLComputeCommandEncoder setBytes:length:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setBytes:length:attributeStride:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setImageblockWidth:height:]"
  ; "method:-[MTLComputeCommandEncoder setIntersectionFunctionTable:atBufferIndex:]"
  ; "method:-[MTLComputeCommandEncoder setIntersectionFunctionTables:withBufferRange:]"
  ; "method:-[MTLComputeCommandEncoder setSamplerState:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setSamplerState:lodMinClamp:lodMaxClamp:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setSamplerStates:lodMinClamps:lodMaxClamps:withRange:]"
  ; "method:-[MTLComputeCommandEncoder setSamplerStates:withRange:]"
  ; "method:-[MTLComputeCommandEncoder setStageInRegion:]"
  ; "method:-[MTLComputeCommandEncoder setStageInRegionWithIndirectBuffer:indirectBufferOffset:]"
  ; "method:-[MTLComputeCommandEncoder setTextures:withRange:]"
  ; "method:-[MTLComputeCommandEncoder setThreadgroupMemoryLength:atIndex:]"
  ; "method:-[MTLComputeCommandEncoder setVisibleFunctionTable:atBufferIndex:]"
  ; "method:-[MTLComputeCommandEncoder setVisibleFunctionTables:withBufferRange:]"
  ; "method:-[MTLComputeCommandEncoder updateFence:]"
  ; "method:-[MTLComputeCommandEncoder useHeap:]"
  ; "method:-[MTLComputeCommandEncoder useHeaps:count:]"
  ; "method:-[MTLComputeCommandEncoder useResource:usage:]"
  ; "method:-[MTLComputeCommandEncoder useResources:count:usage:]"
  ; "method:-[MTLComputeCommandEncoder waitForFence:]"
  ; "method:-[MTLComputePassDescriptor dispatchType]"
  ; "method:-[MTLComputePassDescriptor sampleBufferAttachments]"
  ; "method:-[MTLComputePassDescriptor setDispatchType:]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptor endOfEncoderSampleIndex]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptor sampleBuffer]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptor setEndOfEncoderSampleIndex:]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptor setSampleBuffer:]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptor setStartOfEncoderSampleIndex:]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptor startOfEncoderSampleIndex]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptorArray objectAtIndexedSubscript:]"
  ; "method:-[MTLComputePassSampleBufferAttachmentDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLComputePipelineDescriptor buffers]"
  ; "method:-[MTLComputePipelineDescriptor insertLibraries]"
  ; "method:-[MTLComputePipelineDescriptor requiredThreadsPerThreadgroup]"
  ; "method:-[MTLComputePipelineDescriptor reset]"
  ; "method:-[MTLComputePipelineDescriptor setInsertLibraries:]"
  ; "method:-[MTLComputePipelineDescriptor setRequiredThreadsPerThreadgroup:]"
  ; "method:-[MTLComputePipelineDescriptor setStageInputDescriptor:]"
  ; "method:-[MTLComputePipelineDescriptor stageInputDescriptor]"
  ; "method:-[MTLComputePipelineReflection arguments]"
  ; "method:-[MTLComputePipelineState functionHandleWithBinaryFunction:]"
  ; "method:-[MTLComputePipelineState functionHandleWithName:]"
  ; "method:-[MTLComputePipelineState gpuResourceID]"
  ; "method:-[MTLComputePipelineState imageblockMemoryLengthForDimensions:]"
  ; "method:-[MTLComputePipelineState newComputePipelineStateWithAdditionalBinaryFunctions:error:]"
  ; "method:-[MTLComputePipelineState newComputePipelineStateWithBinaryFunctions:error:]"
  ; "method:-[MTLComputePipelineState requiredThreadsPerThreadgroup]"
  ; "method:-[MTLComputePipelineState shaderValidation]"
  ; "method:-[MTLComputePipelineState supportIndirectCommandBuffers]"
  ; "method:+[MTLComputePassDescriptor computePassDescriptor]"
  ; "property:MTLCommandEncoder:device"
  ; "property:MTLCommandEncoder:label"
  ; "property:MTLComputeCommandEncoder:dispatchType"
  ; "property:MTLComputePassDescriptor:dispatchType"
  ; "property:MTLComputePassDescriptor:sampleBufferAttachments"
  ; "property:MTLComputePassSampleBufferAttachmentDescriptor:endOfEncoderSampleIndex"
  ; "property:MTLComputePassSampleBufferAttachmentDescriptor:sampleBuffer"
  ; "property:MTLComputePassSampleBufferAttachmentDescriptor:startOfEncoderSampleIndex"
  ; "property:MTLComputePipelineDescriptor:buffers"
  ; "property:MTLComputePipelineDescriptor:insertLibraries"
  ; "property:MTLComputePipelineDescriptor:requiredThreadsPerThreadgroup"
  ; "property:MTLComputePipelineDescriptor:stageInputDescriptor"
  ; "property:MTLComputePipelineReflection:arguments"
  ; "property:MTLComputePipelineState:gpuResourceID"
  ; "property:MTLComputePipelineState:requiredThreadsPerThreadgroup"
  ; "property:MTLComputePipelineState:shaderValidation"
  ; "property:MTLComputePipelineState:supportIndirectCommandBuffers"
  ; "typedef:MTLDispatchThreadgroupsIndirectArguments"
  ; "typedef:MTLDispatchThreadsIndirectArguments"
  ; "typedef:MTLStageInRegionIndirectArguments"
  ]
let count=List.length ids
let digest="b619dfe53124faadff6aab9b8d971a4b36dec9e130a69e95f59e1765feeda20f"
