let ids=
  [ "class:MTLIntersectionFunctionDescriptor"
  ; "class:MTLPipelineBufferDescriptor"
  ; "class:MTLPipelineBufferDescriptorArray"
  ; "class:MTLRenderPassDescriptor"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatInvalid"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGB_2BPP"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGB_2BPP_sRGB"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGB_4BPP"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGB_4BPP_sRGB"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGBA_2BPP"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGBA_2BPP_sRGB"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGBA_4BPP"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
  ; "enum-case:MTLPixelFormat:MTLPixelFormatUnspecialized"
  ; "enum-case:MTLStorageMode:MTLStorageModeMemoryless"
  ; "enum-case:MTLStoreAction:MTLStoreActionCustomSampleDepthStore"
  ; "enum-case:MTLStoreAction:MTLStoreActionMultisampleResolve"
  ; "enum-case:MTLStoreAction:MTLStoreActionStoreAndMultisampleResolve"
  ; "enum-case:MTLVertexFormat:MTLVertexFormatInvalid"
  ; "function:MTLCoordinate2DMake"
  ; "function:MTLIndirectCommandBufferExecutionRangeMake"
  ; "function:MTLRegionMake1D"
  ; "function:MTLRegionMake2D"
  ; "function:MTLSamplePositionMake"
  ; "method:-[MTLBinaryArchive addFunctionWithDescriptor:library:error:]"
  ; "method:-[MTLBinaryArchive addLibraryWithDescriptor:error:]"
  ; "method:-[MTLBinaryArchive addMeshRenderPipelineFunctionsWithDescriptor:error:]"
  ; "method:-[MTLBinaryArchive addRenderPipelineFunctionsWithDescriptor:error:]"
  ; "method:-[MTLBinaryArchive addTileRenderPipelineFunctionsWithDescriptor:error:]"
  ; "method:-[MTLDepthStencilState gpuResourceID]"
  ; "method:-[MTLFence device]"
  ; "method:-[MTLFence label]"
  ; "method:-[MTLFence setLabel:]"
  ; "method:-[MTLFunctionConstantValues reset]"
  ; "method:-[MTLFunctionConstantValues setConstantValue:type:atIndex:]"
  ; "method:-[MTLFunctionConstantValues setConstantValues:type:withRange:]"
  ; "method:-[MTLFunctionDescriptor binaryArchives]"
  ; "method:-[MTLFunctionDescriptor setBinaryArchives:]"
  ; "method:-[MTLFunctionHandle device]"
  ; "method:-[MTLFunctionHandle functionType]"
  ; "method:-[MTLFunctionHandle gpuResourceID]"
  ; "method:-[MTLFunctionHandle name]"
  ; "method:-[MTLIndirectCommandBuffer gpuResourceID]"
  ; "method:-[MTLIndirectCommandBuffer indirectRenderCommandAtIndex:]"
  ; "method:-[MTLIntersectionFunctionTable setBuffers:offsets:withRange:]"
  ; "method:-[MTLIntersectionFunctionTable setFunctions:withRange:]"
  ; "method:-[MTLIntersectionFunctionTable setOpaqueCurveIntersectionFunctionWithSignature:atIndex:]"
  ; "method:-[MTLIntersectionFunctionTable setOpaqueCurveIntersectionFunctionWithSignature:withRange:]"
  ; "method:-[MTLIntersectionFunctionTable setOpaqueTriangleIntersectionFunctionWithSignature:atIndex:]"
  ; "method:-[MTLIntersectionFunctionTable setOpaqueTriangleIntersectionFunctionWithSignature:withRange:]"
  ; "method:-[MTLIntersectionFunctionTable setVisibleFunctionTables:withBufferRange:]"
  ; "method:-[MTLParallelRenderCommandEncoder renderCommandEncoder]"
  ; "method:-[MTLParallelRenderCommandEncoder setColorStoreAction:atIndex:]"
  ; "method:-[MTLParallelRenderCommandEncoder setColorStoreActionOptions:atIndex:]"
  ; "method:-[MTLParallelRenderCommandEncoder setDepthStoreAction:]"
  ; "method:-[MTLParallelRenderCommandEncoder setDepthStoreActionOptions:]"
  ; "method:-[MTLParallelRenderCommandEncoder setStencilStoreAction:]"
  ; "method:-[MTLParallelRenderCommandEncoder setStencilStoreActionOptions:]"
  ; "method:-[MTLPipelineBufferDescriptor mutability]"
  ; "method:-[MTLPipelineBufferDescriptor setMutability:]"
  ; "method:-[MTLPipelineBufferDescriptorArray objectAtIndexedSubscript:]"
  ; "method:-[MTLPipelineBufferDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLRenderPassAttachmentDescriptor resolveTexture]"
  ; "method:-[MTLRenderPassAttachmentDescriptor setResolveTexture:]"
  ; "method:-[MTLRenderPassColorAttachmentDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLVisibleFunctionTable setFunctions:withRange:]"
  ; "property:MTLDepthStencilState:gpuResourceID"
  ; "property:MTLFence:device"
  ; "property:MTLFence:label"
  ; "property:MTLFunctionDescriptor:binaryArchives"
  ; "property:MTLFunctionHandle:device"
  ; "property:MTLFunctionHandle:functionType"
  ; "property:MTLFunctionHandle:gpuResourceID"
  ; "property:MTLFunctionHandle:name"
  ; "property:MTLIndirectCommandBuffer:gpuResourceID"
  ; "property:MTLPipelineBufferDescriptor:mutability"
  ; "property:MTLRenderPassAttachmentDescriptor:resolveTexture"
  ; "protocol:MTLFence"
  ; "protocol:MTLIndirectCommandBuffer"
  ; "protocol:MTLParallelRenderCommandEncoder"
  ; "protocol:MTLResourceViewPool"
  ; "record:MTLSharedTextureHandlePrivate"
  ; "typedef:MTLCoordinate2D"
  ; "typedef:MTLIndirectCommandBufferExecutionRange"
  ; "typedef:MTLIntersectionFunctionBufferArguments"
  ; "typedef:MTLMapIndirectArguments"
  ; "typedef:MTLSamplePosition"
  ]
let count=List.length ids
let digest="6e9785aff8c239b62814d5f3ee7e2847465c558054b057f0b2c5a002b3b79267"
