let ids=
  [ "class:MTLAttribute"
  ; "class:MTLAttributeDescriptor"
  ; "class:MTLAttributeDescriptorArray"
  ; "class:MTLFunctionReflection"
  ; "class:MTLFunctionStitchingAttributeAlwaysInline"
  ; "class:MTLFunctionStitchingFunctionNode"
  ; "class:MTLFunctionStitchingGraph"
  ; "class:MTLFunctionStitchingInputNode"
  ; "class:MTLStageInputOutputDescriptor"
  ; "class:MTLStitchedLibraryDescriptor"
  ; "class:MTLVertexAttribute"
  ; "enum-case:MTLDataType:MTLDataTypeComputePipeline"
  ; "enum-case:MTLDataType:MTLDataTypeDepthStencilState"
  ; "enum-case:MTLDataType:MTLDataTypeIndirectCommandBuffer"
  ; "enum-case:MTLDataType:MTLDataTypeInstanceAccelerationStructure"
  ; "enum-case:MTLDataType:MTLDataTypeIntersectionFunctionTable"
  ; "enum-case:MTLDataType:MTLDataTypePrimitiveAccelerationStructure"
  ; "enum-case:MTLDataType:MTLDataTypeR16Snorm"
  ; "enum-case:MTLDataType:MTLDataTypeR16Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeR8Snorm"
  ; "enum-case:MTLDataType:MTLDataTypeR8Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeRenderPipeline"
  ; "enum-case:MTLDataType:MTLDataTypeRG11B10Float"
  ; "enum-case:MTLDataType:MTLDataTypeRG16Snorm"
  ; "enum-case:MTLDataType:MTLDataTypeRG16Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeRG8Snorm"
  ; "enum-case:MTLDataType:MTLDataTypeRG8Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeRGB10A2Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeRGB9E5Float"
  ; "enum-case:MTLDataType:MTLDataTypeRGBA16Snorm"
  ; "enum-case:MTLDataType:MTLDataTypeRGBA16Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeRGBA8Snorm"
  ; "enum-case:MTLDataType:MTLDataTypeRGBA8Unorm"
  ; "enum-case:MTLDataType:MTLDataTypeRGBA8Unorm_sRGB"
  ; "enum-case:MTLDataType:MTLDataTypeTensor"
  ; "enum-case:MTLDataType:MTLDataTypeVisibleFunctionTable"
  ; "method:-[MTLAttribute attributeIndex]"
  ; "method:-[MTLAttribute attributeType]"
  ; "method:-[MTLAttribute isActive]"
  ; "method:-[MTLAttribute isPatchControlPointData]"
  ; "method:-[MTLAttribute isPatchData]"
  ; "method:-[MTLAttribute name]"
  ; "method:-[MTLAttributeDescriptor bufferIndex]"
  ; "method:-[MTLAttributeDescriptor format]"
  ; "method:-[MTLAttributeDescriptor offset]"
  ; "method:-[MTLAttributeDescriptor setBufferIndex:]"
  ; "method:-[MTLAttributeDescriptor setFormat:]"
  ; "method:-[MTLAttributeDescriptor setOffset:]"
  ; "method:-[MTLAttributeDescriptorArray objectAtIndexedSubscript:]"
  ; "method:-[MTLAttributeDescriptorArray setObject:atIndexedSubscript:]"
  ; "method:-[MTLCompileOptions preprocessorMacros]"
  ; "method:-[MTLCompileOptions requiredThreadsPerThreadgroup]"
  ; "method:-[MTLCompileOptions setPreprocessorMacros:]"
  ; "method:-[MTLCompileOptions setRequiredThreadsPerThreadgroup:]"
  ; "method:-[MTLFunction newArgumentEncoderWithBufferIndex:]"
  ; "method:-[MTLFunction newArgumentEncoderWithBufferIndex:reflection:]"
  ; "method:-[MTLFunction options]"
  ; "method:-[MTLFunction patchControlPointCount]"
  ; "method:-[MTLFunction patchType]"
  ; "method:-[MTLFunction stageInputAttributes]"
  ; "method:-[MTLFunction vertexAttributes]"
  ; "method:-[MTLFunctionReflection bindings]"
  ; "method:-[MTLFunctionReflection userAnnotation]"
  ; "method:-[MTLFunctionStitchingFunctionNode arguments]"
  ; "method:-[MTLFunctionStitchingFunctionNode controlDependencies]"
  ; "method:-[MTLFunctionStitchingFunctionNode initWithName:arguments:controlDependencies:]"
  ; "method:-[MTLFunctionStitchingFunctionNode name]"
  ; "method:-[MTLFunctionStitchingFunctionNode setArguments:]"
  ; "method:-[MTLFunctionStitchingFunctionNode setControlDependencies:]"
  ; "method:-[MTLFunctionStitchingFunctionNode setName:]"
  ; "method:-[MTLFunctionStitchingGraph attributes]"
  ; "method:-[MTLFunctionStitchingGraph functionName]"
  ; "method:-[MTLFunctionStitchingGraph initWithFunctionName:nodes:outputNode:attributes:]"
  ; "method:-[MTLFunctionStitchingGraph nodes]"
  ; "method:-[MTLFunctionStitchingGraph outputNode]"
  ; "method:-[MTLFunctionStitchingGraph setAttributes:]"
  ; "method:-[MTLFunctionStitchingGraph setFunctionName:]"
  ; "method:-[MTLFunctionStitchingGraph setNodes:]"
  ; "method:-[MTLFunctionStitchingGraph setOutputNode:]"
  ; "method:-[MTLFunctionStitchingInputNode argumentIndex]"
  ; "method:-[MTLFunctionStitchingInputNode initWithArgumentIndex:]"
  ; "method:-[MTLFunctionStitchingInputNode setArgumentIndex:]"
  ; "method:-[MTLLibrary newFunctionWithDescriptor:completionHandler:]"
  ; "method:-[MTLLibrary newFunctionWithDescriptor:error:]"
  ; "method:-[MTLLibrary newFunctionWithName:constantValues:completionHandler:]"
  ; "method:-[MTLLibrary newIntersectionFunctionWithDescriptor:completionHandler:]"
  ; "method:-[MTLLibrary newIntersectionFunctionWithDescriptor:error:]"
  ; "method:-[MTLLibrary reflectionForFunctionWithName:]"
  ; "method:-[MTLStageInputOutputDescriptor attributes]"
  ; "method:-[MTLStageInputOutputDescriptor indexBufferIndex]"
  ; "method:-[MTLStageInputOutputDescriptor indexType]"
  ; "method:-[MTLStageInputOutputDescriptor layouts]"
  ; "method:-[MTLStageInputOutputDescriptor reset]"
  ; "method:-[MTLStageInputOutputDescriptor setIndexBufferIndex:]"
  ; "method:-[MTLStageInputOutputDescriptor setIndexType:]"
  ; "method:-[MTLStitchedLibraryDescriptor binaryArchives]"
  ; "method:-[MTLStitchedLibraryDescriptor functionGraphs]"
  ; "method:-[MTLStitchedLibraryDescriptor functions]"
  ; "method:-[MTLStitchedLibraryDescriptor options]"
  ; "method:-[MTLStitchedLibraryDescriptor setBinaryArchives:]"
  ; "method:-[MTLStitchedLibraryDescriptor setFunctionGraphs:]"
  ; "method:-[MTLStitchedLibraryDescriptor setFunctions:]"
  ; "method:-[MTLStitchedLibraryDescriptor setOptions:]"
  ; "method:-[MTLVertexAttribute attributeIndex]"
  ; "method:-[MTLVertexAttribute attributeType]"
  ; "method:-[MTLVertexAttribute isActive]"
  ; "method:-[MTLVertexAttribute isPatchControlPointData]"
  ; "method:-[MTLVertexAttribute isPatchData]"
  ; "method:-[MTLVertexAttribute name]"
  ; "method:+[MTLStageInputOutputDescriptor stageInputOutputDescriptor]"
  ; "property:MTLAttribute:active"
  ; "property:MTLAttribute:attributeIndex"
  ; "property:MTLAttribute:attributeType"
  ; "property:MTLAttribute:name"
  ; "property:MTLAttribute:patchControlPointData"
  ; "property:MTLAttribute:patchData"
  ; "property:MTLAttributeDescriptor:bufferIndex"
  ; "property:MTLAttributeDescriptor:format"
  ; "property:MTLAttributeDescriptor:offset"
  ; "property:MTLCompileOptions:preprocessorMacros"
  ; "property:MTLCompileOptions:requiredThreadsPerThreadgroup"
  ; "property:MTLFunction:options"
  ; "property:MTLFunction:patchControlPointCount"
  ; "property:MTLFunction:patchType"
  ; "property:MTLFunction:stageInputAttributes"
  ; "property:MTLFunction:vertexAttributes"
  ; "property:MTLFunctionReflection:bindings"
  ; "property:MTLFunctionReflection:userAnnotation"
  ; "property:MTLFunctionStitchingFunctionNode:arguments"
  ; "property:MTLFunctionStitchingFunctionNode:controlDependencies"
  ; "property:MTLFunctionStitchingFunctionNode:name"
  ; "property:MTLFunctionStitchingGraph:attributes"
  ; "property:MTLFunctionStitchingGraph:functionName"
  ; "property:MTLFunctionStitchingGraph:nodes"
  ; "property:MTLFunctionStitchingGraph:outputNode"
  ; "property:MTLFunctionStitchingInputNode:argumentIndex"
  ; "property:MTLStageInputOutputDescriptor:attributes"
  ; "property:MTLStageInputOutputDescriptor:indexBufferIndex"
  ; "property:MTLStageInputOutputDescriptor:indexType"
  ; "property:MTLStageInputOutputDescriptor:layouts"
  ; "property:MTLStitchedLibraryDescriptor:binaryArchives"
  ; "property:MTLStitchedLibraryDescriptor:functionGraphs"
  ; "property:MTLStitchedLibraryDescriptor:functions"
  ; "property:MTLStitchedLibraryDescriptor:options"
  ; "property:MTLVertexAttribute:active"
  ; "property:MTLVertexAttribute:attributeIndex"
  ; "property:MTLVertexAttribute:attributeType"
  ; "property:MTLVertexAttribute:name"
  ; "property:MTLVertexAttribute:patchControlPointData"
  ; "property:MTLVertexAttribute:patchData"
  ; "protocol:MTLFunctionStitchingAttribute"
  ; "protocol:MTLFunctionStitchingNode"
  ; "typedef:MTLAutoreleasedArgument"
  ; "typedef:MTLAutoreleasedComputePipelineReflection"
  ; "typedef:MTLAutoreleasedRenderPipelineReflection"
  ; "typedef:MTLNewComputePipelineStateWithReflectionCompletionHandler"
  ; "typedef:MTLNewRenderPipelineStateWithReflectionCompletionHandler"
  ]
let count=List.length ids
let digest="a37ec14cd83ad3bb96b9ffc111d1feba837621ee69134445404395d3f55456bb"
