type t =
  | Bound
  | Availability_gated
  | Scope_excluded
  | Unreviewed

module String_set = Set.Make (String)

let methods owners =
  List.concat_map
    (fun (owner, selectors) ->
      List.map (fun selector -> "method:-[" ^ owner ^ " " ^ selector ^ "]")
        selectors)
    owners

let properties owners =
  List.concat_map
    (fun (owner, names) ->
      List.map (fun property -> "property:" ^ owner ^ ":" ^ property) names)
    owners

let enum_cases owner names =
  List.map (fun name -> "enum-case:" ^ owner ^ ":" ^ name) names

let bound_identifiers =
  [ "class:MTLFunctionDescriptor"
  ; "method:+[MTLFunctionDescriptor functionDescriptor]"
  ; "method:-[MTLFunctionDescriptor constantValues]"
  ; "method:-[MTLFunctionDescriptor name]"
  ; "method:-[MTLFunctionDescriptor options]"
  ; "method:-[MTLFunctionDescriptor setConstantValues:]"
  ; "method:-[MTLFunctionDescriptor setName:]"
  ; "method:-[MTLFunctionDescriptor setOptions:]"
  ; "method:-[MTLFunctionDescriptor setSpecializedName:]"
  ; "method:-[MTLFunctionDescriptor specializedName]"
  ; "property:MTLFunctionDescriptor:constantValues"
  ; "property:MTLFunctionDescriptor:name"
  ; "property:MTLFunctionDescriptor:options"
  ; "property:MTLFunctionDescriptor:specializedName"
  ; "class:MTL4ArgumentTableDescriptor"
  ; "class:MTL4BinaryFunctionDescriptor"
  ; "class:MTL4CommandAllocatorDescriptor"
  ; "class:MTL4CommandQueueDescriptor"
  ; "class:MTL4CommitOptions"
  ; "class:MTL4CompilerDescriptor"
  ; "class:MTL4CompilerTaskOptions"
  ; "class:MTL4ComputePipelineDescriptor"
  ; "class:MTL4FunctionDescriptor"
  ; "class:MTL4LibraryDescriptor"
  ; "class:MTL4LibraryFunctionDescriptor"
  ; "class:MTL4MeshRenderPipelineDescriptor"
  ; "class:MTL4PipelineDataSetSerializerDescriptor"
  ; "class:MTL4PipelineDescriptor"
  ; "class:MTL4PipelineOptions"
  ; "class:MTL4PipelineStageDynamicLinkingDescriptor"
  ; "class:MTL4RenderPipelineColorAttachmentDescriptor"
  ; "class:MTL4RenderPipelineColorAttachmentDescriptorArray"
  ; "class:MTL4RenderPipelineDescriptor"
  ; "class:MTL4RenderPipelineDynamicLinkingDescriptor"
  ; "class:MTL4RenderPassDescriptor"
  ; "class:MTL4StaticLinkingDescriptor"
  ; "class:MTL4TileRenderPipelineDescriptor"
  ; "class:MTLBinaryArchiveDescriptor"
  ; "class:MTLCompileOptions"
  ; "class:MTLComputePipelineDescriptor"
  ; "class:MTLComputePipelineReflection"
  ; "class:MTLDepthStencilDescriptor"
  ; "class:MTLFunctionConstant"
  ; "class:MTLFunctionConstantValues"
  ; "class:MTLHeapDescriptor"
  ; "class:MTLLinkedFunctions"
  ; "class:MTLLogicalToPhysicalColorAttachmentMap"
  ; "class:MTLResidencySetDescriptor"
  ; "class:MTLRenderPipelineReflection"
  ; "class:MTLRenderPassAttachmentDescriptor"
  ; "class:MTLRenderPassColorAttachmentDescriptor"
  ; "class:MTLRenderPassColorAttachmentDescriptorArray"
  ; "class:MTLRenderPassDepthAttachmentDescriptor"
  ; "class:MTLRenderPassStencilAttachmentDescriptor"
  ; "class:MTLSamplerDescriptor"
  ; "class:MTLSharedTextureHandle"
  ; "class:MTLStencilDescriptor"
  ; "class:MTLTextureDescriptor"
  ; "class:MTLTextureViewDescriptor"
  ; "class:MTLTileRenderPipelineColorAttachmentDescriptor"
  ; "class:MTLTileRenderPipelineColorAttachmentDescriptorArray"
  ; "class:MTLVertexAttributeDescriptor"
  ; "class:MTLVertexAttributeDescriptorArray"
  ; "class:MTLVertexBufferLayoutDescriptor"
  ; "class:MTLVertexBufferLayoutDescriptorArray"
  ; "class:MTLVertexDescriptor"
  ; "enum:MTL4AlphaToCoverageState"
  ; "enum:MTL4AlphaToOneState"
  ; "enum:MTL4BinaryFunctionOptions"
  ; "enum:MTL4BlendState"
  ; "enum:MTL4CompilerTaskStatus"
  ; "enum:MTLCommandBufferStatus"
  ; "enum:MTLIndexType"
  ; "enum:MTLLoadAction"
  ; "enum:MTLPrimitiveType"
  ; "enum:MTLRenderStages"
  ; "enum:MTLStoreAction"
  ; "enum:MTL4VisibilityOptions"
  ; "enum:MTL4IndirectCommandBufferSupportState"
  ; "enum:MTL4LogicalToPhysicalColorAttachmentMappingState"
  ; "enum:MTL4PipelineDataSetSerializerConfiguration"
  ; "enum:MTL4ShaderReflection"
  ; "enum:MTLBindingAccess"
  ; "enum:MTLBindingType"
  ; "enum:MTLBlendFactor"
  ; "enum:MTLBlendOperation"
  ; "enum:MTLDataType"
  ; "enum:MTLCompareFunction"
  ; "enum:MTLColorWriteMask"
  ; "enum:MTLBufferSparseTier"
  ; "enum:MTLCPUCacheMode"
  ; "enum:MTLCullMode"
  ; "enum:MTLDepthClipMode"
  ; "enum:MTLGPUFamily"
  ; "enum:MTLHazardTrackingMode"
  ; "enum:MTLHeapType"
  ; "enum:MTLFunctionType"
  ; "enum:MTLLibraryType"
  ; "enum:MTLPixelFormat"
  ; "enum:MTLPipelineOption"
  ; "enum:MTLPrimitiveTopologyClass"
  ; "enum:MTLPurgeableState"
  ; "enum:MTLResourceOptions"
  ; "enum:MTLSamplerAddressMode"
  ; "enum:MTLSamplerBorderColor"
  ; "enum:MTLSamplerMinMagFilter"
  ; "enum:MTLSamplerMipFilter"
  ; "enum:MTLSamplerReductionMode"
  ; "enum:MTLSparsePageSize"
  ; "enum:MTLSparseTextureMappingMode"
  ; "enum:MTLStorageMode"
  ; "enum:MTLStages"
  ; "enum:MTLStencilOperation"
  ; "enum:MTLTextureType"
  ; "enum:MTLTextureCompressionType"
  ; "enum:MTLTextureSparseTier"
  ; "enum:MTLTextureSwizzle"
  ; "enum:MTLTextureUsage"
  ; "enum:MTLTriangleFillMode"
  ; "enum:MTLVertexFormat"
  ; "enum:MTLVertexStepFunction"
  ; "enum:MTLVisibilityResultMode"
  ; "enum:MTLVisibilityResultType"
  ; "enum:MTLWinding"
  ; "function:MTLCopyAllDevices"
  ; "function:MTLClearColorMake"
  ; "function:MTLCreateSystemDefaultDevice"
  ; "function:MTLOriginMake"
  ; "function:MTLRegionMake3D"
  ; "function:MTLSizeMake"
  ; "function:MTLTextureSwizzleChannelsMake"
  ; "method:+[MTLLinkedFunctions linkedFunctions]"
  ; "method:+[MTLVertexDescriptor vertexDescriptor]"
  ; "record:MTLOrigin"
  ; "record:MTLClearColor"
  ; "record:MTL4UpdateSparseBufferMappingOperation"
  ; "record:MTL4UpdateSparseTextureMappingOperation"
  ; "record:MTLDrawIndexedPrimitivesIndirectArguments"
  ; "record:MTLDrawPrimitivesIndirectArguments"
  ; "record:MTLRegion"
  ; "record:MTLResourceID"
  ; "record:MTLScissorRect"
  ; "record:MTLSize"
  ; "record:MTLSizeAndAlign"
  ; "record:MTLTextureSwizzleChannels"
  ; "record:MTLVertexAmplificationViewMapping"
  ; "record:MTLViewport"
  ; "field:MTLClearColor:alpha"
  ; "field:MTLClearColor:blue"
  ; "field:MTLClearColor:green"
  ; "field:MTLClearColor:red"
  ; "field:MTLOrigin:x"
  ; "field:MTLOrigin:y"
  ; "field:MTLOrigin:z"
  ; "field:MTLRegion:origin"
  ; "field:MTLRegion:size"
  ; "field:MTLResourceID:_impl"
  ; "field:MTLScissorRect:height"
  ; "field:MTLScissorRect:width"
  ; "field:MTLScissorRect:x"
  ; "field:MTLScissorRect:y"
  ; "field:MTLSize:width"
  ; "field:MTLSize:height"
  ; "field:MTLSize:depth"
  ; "field:MTLSizeAndAlign:align"
  ; "field:MTLSizeAndAlign:size"
  ; "field:MTLTextureSwizzleChannels:alpha"
  ; "field:MTLTextureSwizzleChannels:blue"
  ; "field:MTLTextureSwizzleChannels:green"
  ; "field:MTLTextureSwizzleChannels:red"
  ; "field:MTLVertexAmplificationViewMapping:renderTargetArrayIndexOffset"
  ; "field:MTLVertexAmplificationViewMapping:viewportArrayIndexOffset"
  ; "field:MTLViewport:height"
  ; "field:MTLViewport:originX"
  ; "field:MTLViewport:originY"
  ; "field:MTLViewport:width"
  ; "field:MTLViewport:zfar"
  ; "field:MTLViewport:znear"
  ; "field:MTL4UpdateSparseBufferMappingOperation:bufferRange"
  ; "field:MTL4UpdateSparseBufferMappingOperation:heapOffset"
  ; "field:MTL4UpdateSparseBufferMappingOperation:mode"
  ; "field:MTL4UpdateSparseTextureMappingOperation:heapOffset"
  ; "field:MTL4UpdateSparseTextureMappingOperation:mode"
  ; "field:MTL4UpdateSparseTextureMappingOperation:textureLevel"
  ; "field:MTL4UpdateSparseTextureMappingOperation:textureRegion"
  ; "field:MTL4UpdateSparseTextureMappingOperation:textureSlice"
  ; "field:MTLDrawIndexedPrimitivesIndirectArguments:baseInstance"
  ; "field:MTLDrawIndexedPrimitivesIndirectArguments:baseVertex"
  ; "field:MTLDrawIndexedPrimitivesIndirectArguments:indexCount"
  ; "field:MTLDrawIndexedPrimitivesIndirectArguments:indexStart"
  ; "field:MTLDrawIndexedPrimitivesIndirectArguments:instanceCount"
  ; "field:MTLDrawPrimitivesIndirectArguments:baseInstance"
  ; "field:MTLDrawPrimitivesIndirectArguments:instanceCount"
  ; "field:MTLDrawPrimitivesIndirectArguments:vertexCount"
  ; "field:MTLDrawPrimitivesIndirectArguments:vertexStart"
  ; "protocol:MTL4ArgumentTable"
  ; "protocol:MTL4BinaryFunction"
  ; "protocol:MTL4CommandAllocator"
  ; "protocol:MTL4CommandBuffer"
  ; "protocol:MTL4CommandEncoder"
  ; "protocol:MTL4CommandQueue"
  ; "protocol:MTL4CommitFeedback"
  ; "protocol:MTL4ComputeCommandEncoder"
  ; "protocol:MTL4RenderCommandEncoder"
  ; "protocol:MTL4Archive"
  ; "protocol:MTL4Compiler"
  ; "protocol:MTL4CompilerTask"
  ; "protocol:MTL4PipelineDataSetSerializer"
  ; "protocol:MTLBinaryArchive"
  ; "protocol:MTLBuffer"
  ; "protocol:MTLAllocation"
  ; "protocol:MTLBlitCommandEncoder"
  ; "protocol:MTLBinding"
  ; "protocol:MTLBufferBinding"
  ; "protocol:MTLCommandBuffer"
  ; "protocol:MTLCommandEncoder"
  ; "protocol:MTLCommandQueue"
  ; "protocol:MTLComputeCommandEncoder"
  ; "protocol:MTLComputePipelineState"
  ; "protocol:MTLDepthStencilState"
  ; "protocol:MTLDevice"
  ; "protocol:MTLDynamicLibrary"
  ; "protocol:MTLEvent"
  ; "protocol:MTLFunction"
  ; "protocol:MTLHeap"
  ; "protocol:MTLLibrary"
  ; "protocol:MTLObjectPayloadBinding"
  ; "protocol:MTLResource"
  ; "protocol:MTLResidencySet"
  ; "protocol:MTLRenderPipelineState"
  ; "protocol:MTLResourceStateCommandEncoder"
  ; "protocol:MTLSamplerState"
  ; "protocol:MTLSharedEvent"
  ; "protocol:MTLTexture"
  ; "protocol:MTLTextureBinding"
  ; "protocol:MTLThreadgroupBinding"
  ; "typedef:MTL4AlphaToCoverageState"
  ; "typedef:MTL4AlphaToOneState"
  ; "typedef:MTL4BinaryFunctionOptions"
  ; "typedef:MTL4BlendState"
  ; "typedef:MTL4CompilerTaskStatus"
  ; "typedef:MTL4CommitFeedbackHandler"
  ; "typedef:MTL4NewBinaryFunctionCompletionHandler"
  ; "typedef:MTLCommandBufferStatus"
  ; "typedef:MTLClearColor"
  ; "typedef:MTLLoadAction"
  ; "typedef:MTLPrimitiveType"
  ; "typedef:MTLRenderStages"
  ; "typedef:MTLResourceID"
  ; "typedef:MTLStoreAction"
  ; "typedef:MTL4IndirectCommandBufferSupportState"
  ; "typedef:MTL4LogicalToPhysicalColorAttachmentMappingState"
  ; "typedef:MTL4PipelineDataSetSerializerConfiguration"
  ; "typedef:MTL4ShaderReflection"
  ; "typedef:MTL4UpdateSparseBufferMappingOperation"
  ; "typedef:MTL4UpdateSparseTextureMappingOperation"
  ; "typedef:MTL4VisibilityOptions"
  ; "typedef:MTLBindingAccess"
  ; "typedef:MTLBindingType"
  ; "typedef:MTLBlendFactor"
  ; "typedef:MTLBlendOperation"
  ; "typedef:MTLDataType"
  ; "typedef:MTLCompareFunction"
  ; "typedef:MTLColorWriteMask"
  ; "typedef:MTLBufferSparseTier"
  ; "typedef:MTLCPUCacheMode"
  ; "typedef:MTLCullMode"
  ; "typedef:MTLDepthClipMode"
  ; "typedef:MTLGPUFamily"
  ; "typedef:MTLHazardTrackingMode"
  ; "typedef:MTLHeapType"
  ; "typedef:MTLFunctionType"
  ; "typedef:MTLGPUAddress"
  ; "typedef:MTLLibraryType"
  ; "typedef:MTLOrigin"
  ; "typedef:MTLPixelFormat"
  ; "typedef:MTLPipelineOption"
  ; "typedef:MTLPrimitiveTopologyClass"
  ; "typedef:MTLPurgeableState"
  ; "typedef:MTLRegion"
  ; "typedef:MTLResourceOptions"
  ; "typedef:MTLScissorRect"
  ; "typedef:MTLSamplerAddressMode"
  ; "typedef:MTLSamplerBorderColor"
  ; "typedef:MTLSamplerMinMagFilter"
  ; "typedef:MTLSamplerMipFilter"
  ; "typedef:MTLSamplerReductionMode"
  ; "typedef:MTLSparsePageSize"
  ; "typedef:MTLSparseTextureMappingMode"
  ; "typedef:MTLSize"
  ; "typedef:MTLSizeAndAlign"
  ; "typedef:MTLStorageMode"
  ; "typedef:MTLStages"
  ; "typedef:MTLStencilOperation"
  ; "typedef:MTLTextureType"
  ; "typedef:MTLTextureCompressionType"
  ; "typedef:MTLTextureSparseTier"
  ; "typedef:MTLTextureSwizzle"
  ; "typedef:MTLTextureSwizzleChannels"
  ; "typedef:MTLTextureUsage"
  ; "typedef:MTLTriangleFillMode"
  ; "typedef:MTLVertexAmplificationViewMapping"
  ; "typedef:MTLVertexFormat"
  ; "typedef:MTLVertexStepFunction"
  ; "typedef:MTLVisibilityResultMode"
  ; "typedef:MTLVisibilityResultType"
  ; "typedef:MTLWinding"
  ; "typedef:MTLViewport"
  ; "typedef:MTLNewLibraryCompletionHandler"
  ; "typedef:MTLNewComputePipelineStateCompletionHandler"
  ; "typedef:MTLNewDynamicLibraryCompletionHandler"
  ; "typedef:MTLNewRenderPipelineStateCompletionHandler"
  ; "variable:MTLBufferLayoutStrideDynamic"
  ; "variable:swizzle"
  ]
  @ methods
      [ ( "MTL4Archive"
        , [ "label"; "newBinaryFunctionWithDescriptor:error:"
          ; "setLabel:"
          ] )
      ; ( "MTL4ArgumentTable"
        , [ "device"; "label"; "setAddress:atIndex:"
          ; "setAddress:attributeStride:atIndex:"
          ; "setSamplerState:atIndex:"; "setTexture:atIndex:"
          ] )
      ; ( "MTL4ArgumentTableDescriptor"
        , [ "initializeBindings"; "label"; "maxBufferBindCount"
          ; "maxSamplerStateBindCount"; "maxTextureBindCount"
          ; "setInitializeBindings:"; "setLabel:"
          ; "setMaxBufferBindCount:"; "setMaxSamplerStateBindCount:"
          ; "setMaxTextureBindCount:"; "setSupportAttributeStrides:"
          ; "supportAttributeStrides"
          ] )
      ; ( "MTL4BinaryFunctionDescriptor"
        , [ "functionDescriptor"; "name"; "options"
          ; "setFunctionDescriptor:"; "setName:"; "setOptions:"
          ] )
      ; ( "MTL4CommandAllocator"
        , [ "allocatedSize"; "device"; "label"; "reset" ] )
      ; ( "MTL4CommandAllocatorDescriptor", [ "label"; "setLabel:" ] )
      ; ( "MTL4CommandBuffer"
        , [ "beginCommandBufferWithAllocator:"; "computeCommandEncoder"
          ; "device"; "endCommandBuffer"; "label"
          ; "renderCommandEncoderWithDescriptor:"; "setLabel:"
          ] )
      ; ( "MTL4CommandEncoder"
        , [ "barrierAfterQueueStages:beforeStages:visibilityOptions:"
          ; "commandBuffer"; "endEncoding"; "label"; "setLabel:"
          ] )
      ; ( "MTL4CommandQueue"
        , [ "commit:count:"; "commit:count:options:"; "device"; "label"
          ; "signalEvent:value:"
          ; "updateBufferMappings:heap:operations:count:"
          ; "updateTextureMappings:heap:operations:count:"
          ] )
      ; ( "MTL4CommandQueueDescriptor"
        , [ "label"; "setLabel:" ] )
      ; "MTL4CommitFeedback", [ "error" ]
      ; "MTL4CommitOptions", [ "addFeedbackHandler:" ]
      ; ( "MTL4ComputeCommandEncoder"
        , [ "dispatchThreads:threadsPerThreadgroup:"
          ; "setArgumentTable:"; "setComputePipelineState:"
          ] )
      ; ( "MTL4RenderCommandEncoder"
        , [ "dispatchThreadsPerTile:"
          ; "drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferLength:"
          ; "drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferLength:instanceCount:baseVertex:baseInstance:"
          ; "drawIndexedPrimitives:indexType:indexBuffer:indexBufferLength:indirectBuffer:"
          ; "drawMeshThreadgroups:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:"
          ; "drawPrimitives:indirectBuffer:"
          ; "drawPrimitives:vertexStart:vertexCount:"
          ; "drawPrimitives:vertexStart:vertexCount:instanceCount:baseInstance:"
          ; "setArgumentTable:atStages:"
          ; "setBlendColorRed:green:blue:alpha:"
          ; "setColorAttachmentMap:"
          ; "setColorStoreAction:atIndex:"
          ; "setDepthBias:slopeScale:clamp:"
          ; "setDepthTestMinBound:maxBound:"
          ; "setDepthStencilState:"; "setDepthStoreAction:"
          ; "setRenderPipelineState:"
          ; "setScissorRect:"; "setScissorRects:count:"
          ; "setStencilStoreAction:"
          ; "setStencilFrontReferenceValue:backReferenceValue:"
          ; "setStencilReferenceValue:"
          ; "setVertexAmplificationCount:viewMappings:"
          ; "setVisibilityResultMode:offset:"
          ; "setViewport:"; "setViewports:count:"; "tileHeight"; "tileWidth"
          ] )
      ; ( "MTL4RenderPassDescriptor"
        , [ "colorAttachments"; "defaultRasterSampleCount"; "depthAttachment"
          ; "renderTargetHeight"; "renderTargetWidth"
          ; "setDefaultRasterSampleCount:"; "setRenderTargetHeight:"
          ; "setRenderTargetWidth:"; "setSupportColorAttachmentMapping:"
          ; "setVisibilityResultBuffer:"; "setVisibilityResultType:"
          ; "stencilAttachment"; "supportColorAttachmentMapping"
          ; "visibilityResultBuffer"; "visibilityResultType"
          ] )
      ; ( "MTL4Compiler"
        , [ "device"; "label"
          ; "newBinaryFunctionWithDescriptor:compilerTaskOptions:error:"
          ; "newBinaryFunctionWithDescriptor:compilerTaskOptions:completionHandler:"
          ; "newComputePipelineStateWithDescriptor:compilerTaskOptions:error:"
          ; "newComputePipelineStateWithDescriptor:compilerTaskOptions:completionHandler:"
          ; "newComputePipelineStateWithDescriptor:dynamicLinkingDescriptor:compilerTaskOptions:error:"
          ; "newRenderPipelineStateWithDescriptor:compilerTaskOptions:error:"
          ; "newRenderPipelineStateWithDescriptor:compilerTaskOptions:completionHandler:"
          ; "newRenderPipelineStateWithDescriptor:dynamicLinkingDescriptor:compilerTaskOptions:error:"
          ; "newRenderPipelineStateWithDescriptor:dynamicLinkingDescriptor:compilerTaskOptions:completionHandler:"
          ; "newDynamicLibrary:completionHandler:"
          ; "newDynamicLibrary:error:"
          ; "newDynamicLibraryWithURL:completionHandler:"
          ; "newDynamicLibraryWithURL:error:"
          ; "newLibraryWithDescriptor:completionHandler:"
          ; "newLibraryWithDescriptor:error:"; "pipelineDataSetSerializer"
          ] )
      ; ( "MTL4CompilerTask"
        , [ "compiler"; "status"; "waitUntilCompleted" ] )
      ; ( "MTL4CompilerDescriptor"
        , [ "label"; "pipelineDataSetSerializer"; "setLabel:"
          ; "setPipelineDataSetSerializer:"
          ] )
      ; ( "MTL4CompilerTaskOptions"
        , [ "lookupArchives"; "setLookupArchives:" ] )
      ; ( "MTL4ComputePipelineDescriptor"
        , [ "computeFunctionDescriptor"; "maxTotalThreadsPerThreadgroup"
          ; "requiredThreadsPerThreadgroup"; "setComputeFunctionDescriptor:"
          ; "setMaxTotalThreadsPerThreadgroup:"
          ; "setRequiredThreadsPerThreadgroup:"; "setStaticLinkingDescriptor:"
          ; "setSupportBinaryLinking:"
          ; "setSupportIndirectCommandBuffers:"
          ; "setThreadGroupSizeIsMultipleOfThreadExecutionWidth:"
          ; "staticLinkingDescriptor"; "supportBinaryLinking"
          ; "supportIndirectCommandBuffers"
          ; "threadGroupSizeIsMultipleOfThreadExecutionWidth"
          ] )
      ; ( "MTL4RenderPipelineColorAttachmentDescriptor"
        , [ "alphaBlendOperation"; "blendingState"
          ; "destinationAlphaBlendFactor"; "destinationRGBBlendFactor"
          ; "pixelFormat"; "rgbBlendOperation"; "setAlphaBlendOperation:"
          ; "setBlendingState:"; "setDestinationAlphaBlendFactor:"
          ; "setDestinationRGBBlendFactor:"; "setPixelFormat:"
          ; "setRgbBlendOperation:"; "setSourceAlphaBlendFactor:"
          ; "setSourceRGBBlendFactor:"; "setWriteMask:"
          ; "sourceAlphaBlendFactor"; "sourceRGBBlendFactor"; "writeMask"
          ] )
      ; ( "MTL4RenderPipelineColorAttachmentDescriptorArray"
        , [ "objectAtIndexedSubscript:"
          ; "setObject:atIndexedSubscript:"
          ] )
      ; ( "MTL4RenderPipelineDescriptor"
        , [ "alphaToCoverageState"; "alphaToOneState"; "colorAttachments"
          ; "colorAttachmentMappingState"; "fragmentFunctionDescriptor"
          ; "fragmentStaticLinkingDescriptor"
          ; "inputPrimitiveTopology"; "isRasterizationEnabled"
          ; "maxVertexAmplificationCount"; "rasterSampleCount"; "reset"
          ; "setAlphaToCoverageState:"; "setAlphaToOneState:"
          ; "setColorAttachmentMappingState:"
          ; "setFragmentFunctionDescriptor:"
          ; "setFragmentStaticLinkingDescriptor:"
          ; "setInputPrimitiveTopology:"; "setRasterSampleCount:"
          ; "setRasterizationEnabled:"
          ; "setMaxVertexAmplificationCount:"
          ; "setSupportFragmentBinaryLinking:"
          ; "setSupportIndirectCommandBuffers:"
          ; "setSupportVertexBinaryLinking:"
          ; "setVertexStaticLinkingDescriptor:"
          ; "setVertexDescriptor:"; "setVertexFunctionDescriptor:"
          ; "supportFragmentBinaryLinking"; "supportIndirectCommandBuffers"
          ; "supportVertexBinaryLinking"; "vertexDescriptor"
          ; "vertexFunctionDescriptor"; "vertexStaticLinkingDescriptor"
          ] )
      ; ( "MTL4RenderPipelineDynamicLinkingDescriptor"
        , [ "fragmentLinkingDescriptor"; "meshLinkingDescriptor"
          ; "objectLinkingDescriptor"; "tileLinkingDescriptor"
          ; "vertexLinkingDescriptor"
          ] )
      ; ( "MTL4MeshRenderPipelineDescriptor"
        , [ "alphaToCoverageState"; "alphaToOneState"; "colorAttachments"
          ; "colorAttachmentMappingState"; "fragmentFunctionDescriptor"
          ; "fragmentStaticLinkingDescriptor"
          ; "isRasterizationEnabled"; "maxTotalThreadgroupsPerMeshGrid"
          ; "maxTotalThreadsPerMeshThreadgroup"
          ; "maxTotalThreadsPerObjectThreadgroup"
          ; "maxVertexAmplificationCount"
          ; "meshFunctionDescriptor"; "meshStaticLinkingDescriptor"
          ; "meshThreadgroupSizeIsMultipleOfThreadExecutionWidth"
          ; "objectFunctionDescriptor"; "objectStaticLinkingDescriptor"
          ; "objectThreadgroupSizeIsMultipleOfThreadExecutionWidth"
          ; "payloadMemoryLength"; "rasterSampleCount"; "reset"
          ; "requiredThreadsPerMeshThreadgroup"
          ; "requiredThreadsPerObjectThreadgroup"
          ; "setAlphaToCoverageState:"; "setAlphaToOneState:"
          ; "setColorAttachmentMappingState:"
          ; "setFragmentFunctionDescriptor:"
          ; "setFragmentStaticLinkingDescriptor:"
          ; "setMaxTotalThreadgroupsPerMeshGrid:"
          ; "setMaxTotalThreadsPerMeshThreadgroup:"
          ; "setMaxTotalThreadsPerObjectThreadgroup:"
          ; "setMaxVertexAmplificationCount:"
          ; "setMeshFunctionDescriptor:"
          ; "setMeshStaticLinkingDescriptor:"
          ; "setMeshThreadgroupSizeIsMultipleOfThreadExecutionWidth:"
          ; "setObjectFunctionDescriptor:"
          ; "setObjectStaticLinkingDescriptor:"
          ; "setObjectThreadgroupSizeIsMultipleOfThreadExecutionWidth:"
          ; "setPayloadMemoryLength:"; "setRasterSampleCount:"
          ; "setRasterizationEnabled:"
          ; "setSupportFragmentBinaryLinking:"
          ; "setRequiredThreadsPerMeshThreadgroup:"
          ; "setRequiredThreadsPerObjectThreadgroup:"
          ; "setSupportIndirectCommandBuffers:"
          ; "setSupportMeshBinaryLinking:"
          ; "setSupportObjectBinaryLinking:"
          ; "supportFragmentBinaryLinking"; "supportIndirectCommandBuffers"
          ; "supportMeshBinaryLinking"; "supportObjectBinaryLinking"
          ] )
      ; ( "MTL4TileRenderPipelineDescriptor"
        , [ "colorAttachments"; "maxTotalThreadsPerThreadgroup"
          ; "rasterSampleCount"; "requiredThreadsPerThreadgroup"; "reset"
          ; "setMaxTotalThreadsPerThreadgroup:"; "setRasterSampleCount:"
          ; "setRequiredThreadsPerThreadgroup:"
          ; "setStaticLinkingDescriptor:"; "setSupportBinaryLinking:"
          ; "setThreadgroupSizeMatchesTileSize:"
          ; "setTileFunctionDescriptor:"; "staticLinkingDescriptor"
          ; "supportBinaryLinking"; "threadgroupSizeMatchesTileSize"
          ; "tileFunctionDescriptor"
          ] )
      ; ( "MTL4LibraryDescriptor"
        , [ "name"; "options"; "setName:"; "setOptions:"; "setSource:"
          ; "source"
          ] )
      ; ( "MTL4LibraryFunctionDescriptor"
        , [ "library"; "name"; "setLibrary:"; "setName:" ] )
      ; ( "MTL4PipelineDataSetSerializer"
        , [ "serializeAsArchiveAndFlushToURL:error:"
          ; "serializeAsPipelinesScriptWithError:"
          ] )
      ; ( "MTL4PipelineDataSetSerializerDescriptor"
        , [ "configuration"; "setConfiguration:" ] )
      ; ( "MTL4PipelineDescriptor"
        , [ "label"; "options"; "setLabel:"; "setOptions:" ] )
      ; ( "MTL4PipelineOptions"
        , [ "setShaderReflection:"; "shaderReflection" ] )
      ; ( "MTL4PipelineStageDynamicLinkingDescriptor"
        , [ "binaryLinkedFunctions"; "maxCallStackDepth"
          ; "preloadedLibraries"; "setBinaryLinkedFunctions:"
          ; "setMaxCallStackDepth:"; "setPreloadedLibraries:"
          ] )
      ; ( "MTL4StaticLinkingDescriptor"
        , [ "functionDescriptors"; "groups"; "privateFunctionDescriptors"
          ; "setFunctionDescriptors:"; "setGroups:"
          ; "setPrivateFunctionDescriptors:"
          ] )
      ; ( "MTLBuffer"
        , [ "contents"; "didModifyRange:"; "gpuAddress"; "length"
          ; "sparseBufferTier"
          ; "newTextureWithDescriptor:offset:bytesPerRow:"
          ] )
      ; "MTLAllocation", [ "allocatedSize" ]
      ; ( "MTLBinaryArchive"
        , [ "addComputePipelineFunctionsWithDescriptor:error:"; "device"
          ; "label"; "serializeToURL:error:"; "setLabel:"
          ] )
      ; "MTLBinaryArchiveDescriptor", [ "setUrl:"; "url" ]
      ; ( "MTLBlitCommandEncoder"
        , [ "copyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:"
          ] )
      ; ( "MTLCommandBuffer"
        , [ "blitCommandEncoder"; "commit"; "computeCommandEncoder"; "error"
          ; "label"; "resourceStateCommandEncoder"; "setLabel:"; "status"
          ; "useResidencySet:"; "useResidencySets:count:"
          ; "waitUntilCompleted"
          ] )
      ; "MTLCommandEncoder", [ "endEncoding" ]
      ; ( "MTLCompileOptions"
        , [ "fastMathEnabled"; "installName"; "libraries"; "libraryType"
          ; "setFastMathEnabled:"; "setInstallName:"; "setLibraries:"
          ; "setLibraryType:"
          ] )
      ; ( "MTLComputeCommandEncoder"
        , [ "dispatchThreads:threadsPerThreadgroup:"
          ; "setBuffer:offset:atIndex:"
          ; "setComputePipelineState:"; "setTexture:atIndex:"
          ] )
      ; ( "MTLComputePipelineDescriptor"
        , [ "binaryArchives"; "computeFunction"; "label"; "linkedFunctions"
          ; "preloadedLibraries"; "setBinaryArchives:"
          ; "setComputeFunction:"; "setLabel:"; "setLinkedFunctions:"
          ; "setPreloadedLibraries:"
          ] )
      ; "MTLComputePipelineReflection", [ "bindings" ]
      ; ( "MTLComputePipelineState"
        , [ "device"; "label"; "maxTotalThreadsPerThreadgroup"; "reflection"
          ; "threadExecutionWidth"
          ] )
      ; ( "MTLRenderPipelineReflection"
        , [ "fragmentBindings"; "meshBindings"; "objectBindings"
          ; "tileBindings"; "vertexBindings"
          ] )
      ; ( "MTLRenderPipelineState"
        , [ "device"; "label"; "maxTotalThreadgroupsPerMeshGrid"
          ; "maxTotalThreadsPerMeshThreadgroup"
          ; "maxTotalThreadsPerObjectThreadgroup"
          ; "maxTotalThreadsPerThreadgroup"; "meshThreadExecutionWidth"
          ; "objectThreadExecutionWidth"; "reflection"
          ; "threadgroupSizeMatchesTileSize"
          ] )
      ; ( "MTLRenderPassAttachmentDescriptor"
        , [ "loadAction"; "setLoadAction:"; "setStoreAction:"
          ; "setTexture:"; "storeAction"; "texture"
          ] )
      ; ( "MTLRenderPassColorAttachmentDescriptor"
        , [ "clearColor"; "setClearColor:" ] )
      ; ( "MTLRenderPassColorAttachmentDescriptorArray"
        , [ "objectAtIndexedSubscript:" ] )
      ; ( "MTLRenderPassDepthAttachmentDescriptor"
        , [ "clearDepth"; "setClearDepth:" ] )
      ; ( "MTLRenderPassStencilAttachmentDescriptor"
        , [ "clearStencil"; "setClearStencil:" ] )
      ; ( "MTLDepthStencilDescriptor"
        , [ "backFaceStencil"; "depthCompareFunction"; "frontFaceStencil"
          ; "isDepthWriteEnabled"; "label"; "setBackFaceStencil:"
          ; "setDepthCompareFunction:"; "setDepthWriteEnabled:"
          ; "setFrontFaceStencil:"; "setLabel:"
          ] )
      ; "MTLDepthStencilState", [ "device"; "label" ]
      ; ( "MTLStencilDescriptor"
        , [ "depthFailureOperation"; "depthStencilPassOperation"; "readMask"
          ; "setDepthFailureOperation:"; "setDepthStencilPassOperation:"
          ; "setReadMask:"; "setStencilCompareFunction:"
          ; "setStencilFailureOperation:"; "setWriteMask:"
          ; "stencilCompareFunction"; "stencilFailureOperation"; "writeMask"
          ] )
      ; ( "MTLDevice"
        , [ "currentAllocatedSize"; "hasUnifiedMemory"; "isHeadless"
          ; "heapBufferSizeAndAlignWithLength:options:"
          ; "heapTextureSizeAndAlignWithDescriptor:"
          ; "isLowPower"; "isRemovable"; "maxBufferLength"; "name"
          ; "minimumLinearTextureAlignmentForPixelFormat:"
          ; "minimumTextureBufferAlignmentForPixelFormat:"
          ; "newBufferWithBytes:length:options:"
          ; "newBufferWithBytesNoCopy:length:options:deallocator:"
          ; "newBufferWithLength:options:"
          ; "newBufferWithLength:options:placementSparsePageSize:"
          ; "newArgumentTableWithDescriptor:error:"
          ; "newCommandAllocator"; "newCommandAllocatorWithDescriptor:error:"
          ; "newCommandBuffer"
          ; "newCommandQueue"
          ; "newBinaryArchiveWithDescriptor:error:"
          ; "newArchiveWithURL:error:"
          ; "newCompilerWithDescriptor:error:"
          ; "newComputePipelineStateWithDescriptor:options:reflection:error:"
          ; "newComputePipelineStateWithFunction:error:"
          ; "newDepthStencilStateWithDescriptor:"
          ; "newDynamicLibrary:error:"; "newDynamicLibraryWithURL:error:"
          ; "newLibraryWithURL:error:"
          ; "newLibraryWithSource:options:error:"
          ; "newHeapWithDescriptor:"
          ; "newResidencySetWithDescriptor:error:"
          ; "newMTL4CommandQueueWithDescriptor:error:"
          ; "newPipelineDataSetSerializerWithDescriptor:"
          ; "newSamplerStateWithDescriptor:"
          ; "newSharedTextureWithDescriptor:"
          ; "newSharedTextureWithHandle:"
          ; "newSharedEvent"
          ; "newTextureWithDescriptor:iosurface:plane:"
          ; "newTextureWithDescriptor:"
          ; "isDepth24Stencil8PixelFormatSupported"
          ; "supportsBCTextureCompression"
          ; "recommendedMaxWorkingSetSize"; "registryID"
          ; "sparseTileSizeInBytes"
          ; "sparseTileSizeInBytesForSparsePageSize:"
          ; "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
          ; "supportsDynamicLibraries"; "supportsFamily:"
          ; "supportsFunctionPointers"; "supportsFunctionPointersFromRender"
          ; "supportsRaytracing"
          ; "supportsRaytracingFromRender"; "supportsTextureSampleCount:"
          ; "supportsVertexAmplificationCount:"
          ; "supportsPlacementSparse"
          ] )
      ; ( "MTLFunction"
        , [ "device"; "functionConstantsDictionary"; "functionType"; "label"
          ; "name"; "setLabel:"
          ] )
      ; ( "MTLFunctionConstant"
        , [ "index"; "name"; "required"; "type" ] )
      ; ( "MTLFunctionConstantValues"
        , [ "setConstantValue:type:withName:" ] )
      ; ( "MTLDynamicLibrary"
        , [ "device"; "installName"; "label"; "serializeToURL:error:"
          ; "setLabel:"
          ] )
      ; ( "MTLHeap"
        , [ "cpuCacheMode"; "currentAllocatedSize"; "hazardTrackingMode"
          ; "label"; "maxAvailableSizeWithAlignment:"
          ; "newBufferWithLength:options:"
          ; "newBufferWithLength:options:offset:"
          ; "newTextureWithDescriptor:"
          ; "newTextureWithDescriptor:offset:"; "setLabel:"
          ; "setPurgeableState:"; "size"; "storageMode"; "type"
          ; "usedSize"
          ] )
      ; ( "MTLHeapDescriptor"
        , [ "cpuCacheMode"; "hazardTrackingMode"; "setCpuCacheMode:"
          ; "maxCompatiblePlacementSparsePageSize"
          ; "setHazardTrackingMode:"; "setSize:"; "setStorageMode:"
          ; "setMaxCompatiblePlacementSparsePageSize:"
          ; "setSparsePageSize:"; "setType:"; "size"; "sparsePageSize"
          ; "storageMode"; "type"
          ] )
      ; ( "MTLLibrary"
        , [ "device"; "functionNames"; "installName"; "label"
          ; "newFunctionWithName:"
          ; "newFunctionWithName:constantValues:error:"; "setLabel:"
          ; "type"
          ] )
      ; ( "MTLLinkedFunctions"
        , [ "functions"; "setFunctions:" ] )
      ; ( "MTLLogicalToPhysicalColorAttachmentMap"
        , [ "getPhysicalIndexForLogicalIndex:"; "reset"
          ; "setPhysicalIndex:forLogicalIndex:"
          ] )
      ; ( "MTLBinding"
        , [ "access"; "index"; "isArgument"; "isUsed"; "name"; "type" ] )
      ; ( "MTLBufferBinding"
        , [ "bufferAlignment"; "bufferDataSize"; "bufferDataType" ] )
      ; ( "MTLThreadgroupBinding"
        , [ "threadgroupMemoryAlignment"; "threadgroupMemoryDataSize" ] )
      ; ( "MTLTextureBinding"
        , [ "arrayLength"; "isDepthTexture"; "textureDataType"
          ; "textureType"
          ] )
      ; ( "MTLObjectPayloadBinding"
        , [ "objectPayloadAlignment"; "objectPayloadDataSize" ] )
      ; ( "MTLResidencySet"
        , [ "addAllocation:"; "addAllocations:count:"; "allAllocations"
          ; "allocatedSize"; "allocationCount"; "commit"
          ; "containsAllocation:"; "device"; "endResidency"; "label"
          ; "removeAllAllocations"; "removeAllocation:"
          ; "removeAllocations:count:"; "requestResidency"
          ] )
      ; ( "MTLResidencySetDescriptor"
        , [ "initialCapacity"; "label"; "setInitialCapacity:"; "setLabel:" ] )
      ; ( "MTLResourceStateCommandEncoder"
        , [ "updateTextureMapping:mode:region:mipLevel:slice:" ] )
      ; ( "MTLResource"
        , [ "cpuCacheMode"; "hazardTrackingMode"; "heapOffset"; "isAliasable"
          ; "label"; "makeAliasable"; "setLabel:"; "setPurgeableState:"
          ; "storageMode"
          ] )
      ; ( "MTLSamplerDescriptor"
        , [ "borderColor"; "compareFunction"; "label"; "lodAverage"
          ; "lodBias"; "lodMaxClamp"; "lodMinClamp"; "magFilter"
          ; "maxAnisotropy"
          ; "minFilter"; "mipFilter"; "normalizedCoordinates"
          ; "rAddressMode"; "reductionMode"; "sAddressMode"; "setBorderColor:"
          ; "setCompareFunction:"; "setLabel:"; "setLodAverage:"
          ; "setLodBias:"; "setLodMaxClamp:"; "setLodMinClamp:"
          ; "setMagFilter:"
          ; "setMaxAnisotropy:"; "setMinFilter:"; "setMipFilter:"
          ; "setNormalizedCoordinates:"; "setRAddressMode:"
          ; "setReductionMode:"
          ; "setSAddressMode:"; "setSupportArgumentBuffers:"
          ; "setTAddressMode:"; "supportArgumentBuffers"; "tAddressMode"
          ] )
      ; "MTLSamplerState", [ "device"; "gpuResourceID"; "label" ]
      ; "MTLSharedTextureHandle", [ "device"; "label" ]
      ; "MTLSharedEvent", [ "waitUntilSignaledValue:timeoutMS:" ]
      ; ( "MTLTexture"
        , [ "allowGPUOptimizedContents"; "arrayLength"; "buffer"
          ; "bufferBytesPerRow"; "bufferOffset"; "compressionType"; "depth"
          ; "getBytes:bytesPerRow:bytesPerImage:fromRegion:mipmapLevel:slice:"
          ; "firstMipmapInTail"; "height"; "iosurface"; "iosurfacePlane"
          ; "isShareable"; "isSparse"; "mipmapLevelCount"
          ; "newSharedTextureHandle"
          ; "newTextureViewWithDescriptor:"
          ; "newTextureViewWithPixelFormat:textureType:levels:slices:"
          ; "newTextureViewWithPixelFormat:textureType:levels:slices:swizzle:"
          ; "parentRelativeLevel"; "parentRelativeSlice"; "parentTexture"
          ; "gpuResourceID"; "pixelFormat"
          ; "replaceRegion:mipmapLevel:slice:withBytes:bytesPerRow:bytesPerImage:"
          ; "sampleCount"; "sparseTextureTier"; "tailSizeInBytes"
          ; "swizzle"; "textureType"; "usage"; "width"
          ] )
      ; ( "MTLTextureDescriptor"
        , [ "allowGPUOptimizedContents"; "arrayLength"; "cpuCacheMode"
          ; "compressionType"; "depth"; "hazardTrackingMode"; "height"
          ; "mipmapLevelCount"
          ; "pixelFormat"; "sampleCount"; "setAllowGPUOptimizedContents:"
          ; "setArrayLength:"; "setCpuCacheMode:"; "setDepth:"
          ; "setHazardTrackingMode:"; "setHeight:"
          ; "setCompressionType:"; "setMipmapLevelCount:"; "setPixelFormat:"
          ; "setSampleCount:"
          ; "placementSparsePageSize"; "setPlacementSparsePageSize:"
          ; "setStorageMode:"; "setSwizzle:"; "setTextureType:"
          ; "setUsage:"; "setWidth:"; "storageMode"; "swizzle"
          ; "textureType"; "usage"; "width"
          ] )
      ; ( "MTLTextureViewDescriptor"
        , [ "levelRange"; "pixelFormat"; "setLevelRange:"
          ; "setPixelFormat:"; "setSliceRange:"; "setSwizzle:"
          ; "setTextureType:"; "sliceRange"; "swizzle"; "textureType"
          ] )
      ; ( "MTLTileRenderPipelineColorAttachmentDescriptor"
        , [ "pixelFormat"; "setPixelFormat:" ] )
      ; ( "MTLTileRenderPipelineColorAttachmentDescriptorArray"
        , [ "objectAtIndexedSubscript:"
          ; "setObject:atIndexedSubscript:"
          ] )
      ; ( "MTLVertexAttributeDescriptor"
        , [ "bufferIndex"; "format"; "offset"; "setBufferIndex:"
          ; "setFormat:"; "setOffset:"
          ] )
      ; ( "MTLVertexAttributeDescriptorArray"
        , [ "objectAtIndexedSubscript:"
          ; "setObject:atIndexedSubscript:"
          ] )
      ; ( "MTLVertexBufferLayoutDescriptor"
        , [ "setStepFunction:"; "setStepRate:"; "setStride:"
          ; "stepFunction"; "stepRate"; "stride"
          ] )
      ; ( "MTLVertexBufferLayoutDescriptorArray"
        , [ "objectAtIndexedSubscript:"
          ; "setObject:atIndexedSubscript:"
          ] )
      ; "MTLVertexDescriptor", [ "attributes"; "layouts"; "reset" ]
      ; ( "MTLCommandQueue"
        , [ "addResidencySet:"; "addResidencySets:count:"; "commandBuffer"
          ; "removeResidencySet:"; "removeResidencySets:count:"
          ] )
      ]
  @ properties
      [ "MTL4Archive", [ "label" ]
      ; ( "MTL4BinaryFunctionDescriptor"
        , [ "functionDescriptor"; "name"; "options" ] )
      ; ( "MTL4Compiler"
        , [ "device"; "label"; "pipelineDataSetSerializer" ] )
      ; "MTL4CompilerTask", [ "compiler"; "status" ]
      ; ( "MTL4CompilerDescriptor"
        , [ "label"; "pipelineDataSetSerializer" ] )
      ; "MTL4CompilerTaskOptions", [ "lookupArchives" ]
      ; ( "MTL4ComputePipelineDescriptor"
        , [ "computeFunctionDescriptor"; "maxTotalThreadsPerThreadgroup"
          ; "requiredThreadsPerThreadgroup"; "staticLinkingDescriptor"
          ; "supportBinaryLinking"
          ; "supportIndirectCommandBuffers"
          ; "threadGroupSizeIsMultipleOfThreadExecutionWidth"
          ] )
      ; ( "MTL4RenderPipelineColorAttachmentDescriptor"
        , [ "alphaBlendOperation"; "blendingState"
          ; "destinationAlphaBlendFactor"; "destinationRGBBlendFactor"
          ; "pixelFormat"; "rgbBlendOperation"; "sourceAlphaBlendFactor"
          ; "sourceRGBBlendFactor"; "writeMask"
          ] )
      ; ( "MTL4RenderPipelineDescriptor"
        , [ "alphaToCoverageState"; "alphaToOneState"; "colorAttachments"
          ; "colorAttachmentMappingState"; "fragmentFunctionDescriptor"
          ; "fragmentStaticLinkingDescriptor"; "inputPrimitiveTopology"
          ; "maxVertexAmplificationCount"; "rasterSampleCount"
          ; "rasterizationEnabled"; "supportFragmentBinaryLinking"
          ; "supportIndirectCommandBuffers"; "supportVertexBinaryLinking"
          ; "vertexDescriptor"; "vertexFunctionDescriptor"
          ; "vertexStaticLinkingDescriptor"
          ] )
      ; ( "MTL4RenderPipelineDynamicLinkingDescriptor"
        , [ "fragmentLinkingDescriptor"; "meshLinkingDescriptor"
          ; "objectLinkingDescriptor"; "tileLinkingDescriptor"
          ; "vertexLinkingDescriptor"
          ] )
      ; ( "MTL4MeshRenderPipelineDescriptor"
        , [ "alphaToCoverageState"; "alphaToOneState"; "colorAttachments"
          ; "colorAttachmentMappingState"; "fragmentFunctionDescriptor"
          ; "fragmentStaticLinkingDescriptor"
          ; "maxTotalThreadgroupsPerMeshGrid"
          ; "maxTotalThreadsPerMeshThreadgroup"
          ; "maxTotalThreadsPerObjectThreadgroup"
          ; "maxVertexAmplificationCount"
          ; "meshFunctionDescriptor"; "meshStaticLinkingDescriptor"
          ; "meshThreadgroupSizeIsMultipleOfThreadExecutionWidth"
          ; "objectFunctionDescriptor"; "objectStaticLinkingDescriptor"
          ; "objectThreadgroupSizeIsMultipleOfThreadExecutionWidth"
          ; "payloadMemoryLength"; "rasterSampleCount"
          ; "rasterizationEnabled"; "requiredThreadsPerMeshThreadgroup"
          ; "requiredThreadsPerObjectThreadgroup"
          ; "supportFragmentBinaryLinking"; "supportIndirectCommandBuffers"
          ; "supportMeshBinaryLinking"; "supportObjectBinaryLinking"
          ] )
      ; ( "MTL4TileRenderPipelineDescriptor"
        , [ "colorAttachments"; "maxTotalThreadsPerThreadgroup"
          ; "rasterSampleCount"; "requiredThreadsPerThreadgroup"
          ; "staticLinkingDescriptor"; "supportBinaryLinking"
          ; "threadgroupSizeMatchesTileSize"; "tileFunctionDescriptor"
          ] )
      ; "MTL4LibraryDescriptor", [ "name"; "options"; "source" ]
      ; "MTL4LibraryFunctionDescriptor", [ "library"; "name" ]
      ; "MTL4PipelineDataSetSerializerDescriptor", [ "configuration" ]
      ; "MTL4PipelineDescriptor", [ "label"; "options" ]
      ; "MTL4PipelineOptions", [ "shaderReflection" ]
      ; ( "MTL4PipelineStageDynamicLinkingDescriptor"
        , [ "binaryLinkedFunctions"; "maxCallStackDepth"
          ; "preloadedLibraries"
          ] )
      ; ( "MTL4StaticLinkingDescriptor"
        , [ "functionDescriptors"; "groups"; "privateFunctionDescriptors" ] )
      ; "MTL4ArgumentTable", [ "device"; "label" ]
      ; ( "MTL4ArgumentTableDescriptor"
        , [ "initializeBindings"; "label"; "maxBufferBindCount"
          ; "maxSamplerStateBindCount"; "maxTextureBindCount"
          ; "supportAttributeStrides"
          ] )
      ; "MTL4CommandAllocator", [ "device"; "label" ]
      ; "MTL4CommandAllocatorDescriptor", [ "label" ]
      ; "MTL4CommandBuffer", [ "device"; "label" ]
      ; "MTL4CommandEncoder", [ "commandBuffer"; "label" ]
      ; "MTL4CommandQueue", [ "device"; "label" ]
      ; "MTL4CommandQueueDescriptor", [ "label" ]
      ; "MTL4CommitFeedback", [ "error" ]
      ; "MTL4RenderCommandEncoder", [ "tileHeight"; "tileWidth" ]
      ; ( "MTL4RenderPassDescriptor"
        , [ "colorAttachments"; "defaultRasterSampleCount"; "depthAttachment"
          ; "renderTargetHeight"; "renderTargetWidth"; "stencilAttachment"
          ; "supportColorAttachmentMapping"
          ; "visibilityResultBuffer"; "visibilityResultType"
          ] )
      ; "MTLAllocation", [ "allocatedSize" ]
      ; "MTLBinaryArchive", [ "device"; "label" ]
      ; "MTLBinaryArchiveDescriptor", [ "url" ]
      ; ( "MTLCommandBuffer", [ "error"; "label"; "status" ] )
      ; ( "MTLCompileOptions"
        , [ "fastMathEnabled"; "installName"; "libraries"; "libraryType" ] )
      ; ( "MTLComputePipelineDescriptor"
        , [ "binaryArchives"; "computeFunction"; "label"; "linkedFunctions"
          ; "preloadedLibraries"
          ] )
      ; "MTLComputePipelineReflection", [ "bindings" ]
      ; ( "MTLComputePipelineState"
        , [ "device"; "label"; "maxTotalThreadsPerThreadgroup"; "reflection"
          ; "threadExecutionWidth"
          ] )
      ; ( "MTLRenderPipelineReflection"
        , [ "fragmentBindings"; "meshBindings"; "objectBindings"
          ; "tileBindings"; "vertexBindings"
          ] )
      ; ( "MTLRenderPipelineState"
        , [ "device"; "label"; "maxTotalThreadgroupsPerMeshGrid"
          ; "maxTotalThreadsPerMeshThreadgroup"
          ; "maxTotalThreadsPerObjectThreadgroup"
          ; "maxTotalThreadsPerThreadgroup"; "meshThreadExecutionWidth"
          ; "objectThreadExecutionWidth"; "reflection"
          ; "threadgroupSizeMatchesTileSize"
          ] )
      ; ( "MTLRenderPassAttachmentDescriptor"
        , [ "loadAction"; "storeAction"; "texture" ] )
      ; "MTLRenderPassColorAttachmentDescriptor", [ "clearColor" ]
      ; "MTLRenderPassDepthAttachmentDescriptor", [ "clearDepth" ]
      ; "MTLRenderPassStencilAttachmentDescriptor", [ "clearStencil" ]
      ; ( "MTLDepthStencilDescriptor"
        , [ "backFaceStencil"; "depthCompareFunction"; "depthWriteEnabled"
          ; "frontFaceStencil"; "label"
          ] )
      ; "MTLDepthStencilState", [ "device"; "label" ]
      ; ( "MTLStencilDescriptor"
        , [ "depthFailureOperation"; "depthStencilPassOperation"; "readMask"
          ; "stencilCompareFunction"; "stencilFailureOperation"; "writeMask"
          ] )
      ; ( "MTLDevice"
        , [ "currentAllocatedSize"; "depth24Stencil8PixelFormatSupported"
          ; "hasUnifiedMemory"; "headless"; "lowPower"; "maxBufferLength"
          ; "name"; "recommendedMaxWorkingSetSize"
          ; "registryID"; "removable"; "supportsDynamicLibraries"
          ; "supportsFunctionPointers"; "supportsFunctionPointersFromRender"
          ; "supportsRaytracing"
          ; "supportsPlacementSparse"; "supportsRaytracingFromRender"
          ; "sparseTileSizeInBytes"
          ] )
      ; ( "MTLFunction"
        , [ "device"; "functionConstantsDictionary"; "functionType"; "label"
          ; "name"
          ] )
      ; ( "MTLFunctionConstant"
        , [ "index"; "name"; "required"; "type" ] )
      ; ( "MTLDynamicLibrary"
        , [ "device"; "installName"; "label" ] )
      ; ( "MTLHeap"
        , [ "cpuCacheMode"; "currentAllocatedSize"; "hazardTrackingMode"
          ; "label"; "size"; "storageMode"; "type"; "usedSize"
          ] )
      ; ( "MTLHeapDescriptor"
        , [ "cpuCacheMode"; "hazardTrackingMode"
          ; "maxCompatiblePlacementSparsePageSize"; "size"
          ; "sparsePageSize"; "storageMode"; "type"
          ] )
      ; ( "MTLLibrary"
        , [ "device"; "functionNames"; "installName"; "label"; "type" ] )
      ; "MTLLinkedFunctions", [ "functions" ]
      ; ( "MTLBinding"
        , [ "access"; "argument"; "index"; "name"; "type"; "used" ] )
      ; ( "MTLBufferBinding"
        , [ "bufferAlignment"; "bufferDataSize"; "bufferDataType" ] )
      ; ( "MTLThreadgroupBinding"
        , [ "threadgroupMemoryAlignment"; "threadgroupMemoryDataSize" ] )
      ; ( "MTLTextureBinding"
        , [ "arrayLength"; "depthTexture"; "textureDataType"; "textureType" ] )
      ; ( "MTLObjectPayloadBinding"
        , [ "objectPayloadAlignment"; "objectPayloadDataSize" ] )
      ; ( "MTLResource"
        , [ "cpuCacheMode"; "hazardTrackingMode"; "heapOffset"; "label"
          ; "storageMode"
          ] )
      ; ( "MTLResidencySet"
        , [ "allAllocations"; "allocatedSize"; "allocationCount"; "device"
          ; "label"
          ] )
      ; ( "MTLResidencySetDescriptor", [ "initialCapacity"; "label" ] )
      ; ( "MTLSamplerDescriptor"
        , [ "borderColor"; "compareFunction"; "label"; "lodAverage"
          ; "lodBias"; "lodMaxClamp"; "lodMinClamp"; "magFilter"
          ; "maxAnisotropy"
          ; "minFilter"; "mipFilter"; "normalizedCoordinates"
          ; "rAddressMode"; "reductionMode"; "sAddressMode"
          ; "supportArgumentBuffers"; "tAddressMode"
          ] )
      ; "MTLSamplerState", [ "device"; "gpuResourceID"; "label" ]
      ; "MTLSharedTextureHandle", [ "device"; "label" ]
      ; ( "MTLTexture"
        , [ "allowGPUOptimizedContents"; "arrayLength"; "compressionType"
          ; "depth"; "firstMipmapInTail"; "height"
          ; "iosurface"; "iosurfacePlane"; "isSparse"; "mipmapLevelCount"
          ; "parentRelativeLevel"; "parentRelativeSlice"; "parentTexture"
          ; "gpuResourceID"; "pixelFormat"; "sampleCount"; "shareable"
          ; "sparseTextureTier"
          ; "swizzle"; "tailSizeInBytes"; "textureType"; "usage"; "width"
          ] )
      ; ( "MTLTextureDescriptor"
        , [ "allowGPUOptimizedContents"; "arrayLength"; "cpuCacheMode"
          ; "compressionType"; "depth"; "hazardTrackingMode"; "height"
          ; "mipmapLevelCount"
          ; "pixelFormat"; "placementSparsePageSize"; "sampleCount"
          ; "storageMode"; "swizzle"; "textureType"; "usage"; "width"
          ] )
      ; ( "MTLTextureViewDescriptor"
        , [ "levelRange"; "pixelFormat"; "sliceRange"; "swizzle"
          ; "textureType"
          ] )
      ; "MTLTileRenderPipelineColorAttachmentDescriptor", [ "pixelFormat" ]
      ; ( "MTLVertexAttributeDescriptor"
        , [ "bufferIndex"; "format"; "offset" ] )
      ; ( "MTLVertexBufferLayoutDescriptor"
        , [ "stepFunction"; "stepRate"; "stride" ] )
      ; "MTLVertexDescriptor", [ "attributes"; "layouts" ]
      ; "MTLBuffer", [ "gpuAddress"; "length"; "sparseBufferTier" ]
      ]
  @ enum_cases "MTL4AlphaToCoverageState"
      [ "MTL4AlphaToCoverageStateDisabled"
      ; "MTL4AlphaToCoverageStateEnabled"
      ]
  @ enum_cases "MTL4AlphaToOneState"
      [ "MTL4AlphaToOneStateDisabled"; "MTL4AlphaToOneStateEnabled" ]
  @ enum_cases "MTL4VisibilityOptions"
      [ "MTL4VisibilityOptionResourceAlias" ]
  @ enum_cases "MTL4BinaryFunctionOptions"
      [ "MTL4BinaryFunctionOptionNone"
      ; "MTL4BinaryFunctionOptionPipelineIndependent"
      ]
  @ enum_cases "MTL4BlendState"
      [ "MTL4BlendStateDisabled"; "MTL4BlendStateEnabled" ]
  @ enum_cases "MTL4CompilerTaskStatus"
      [ "MTL4CompilerTaskStatusNone"; "MTL4CompilerTaskStatusScheduled"
      ; "MTL4CompilerTaskStatusCompiling"; "MTL4CompilerTaskStatusFinished"
      ]
  @ enum_cases "MTL4IndirectCommandBufferSupportState"
      [ "MTL4IndirectCommandBufferSupportStateDisabled"
      ; "MTL4IndirectCommandBufferSupportStateEnabled"
      ]
  @ enum_cases "MTL4LogicalToPhysicalColorAttachmentMappingState"
      [ "MTL4LogicalToPhysicalColorAttachmentMappingStateIdentity"
      ; "MTL4LogicalToPhysicalColorAttachmentMappingStateInherited"
      ]
  @ enum_cases "MTL4PipelineDataSetSerializerConfiguration"
      [ "MTL4PipelineDataSetSerializerConfigurationCaptureBinaries"
      ; "MTL4PipelineDataSetSerializerConfigurationCaptureDescriptors"
      ]
  @ enum_cases "MTL4ShaderReflection"
      [ "MTL4ShaderReflectionBindingInfo"
      ; "MTL4ShaderReflectionBufferTypeInfo"
      ]
  @ enum_cases "MTLLoadAction"
      [ "MTLLoadActionClear"; "MTLLoadActionDontCare"; "MTLLoadActionLoad" ]
  @ enum_cases "MTLIndexType"
      [ "MTLIndexTypeUInt16"; "MTLIndexTypeUInt32" ]
  @ enum_cases "MTLCullMode"
      [ "MTLCullModeNone"; "MTLCullModeFront"; "MTLCullModeBack" ]
  @ enum_cases "MTLDepthClipMode"
      [ "MTLDepthClipModeClip"; "MTLDepthClipModeClamp" ]
  @ enum_cases "MTLPrimitiveType"
      [ "MTLPrimitiveTypeLine"; "MTLPrimitiveTypeLineStrip"
      ; "MTLPrimitiveTypePoint"; "MTLPrimitiveTypeTriangle"
      ; "MTLPrimitiveTypeTriangleStrip"
      ]
  @ enum_cases "MTLRenderStages"
      [ "MTLRenderStageFragment"; "MTLRenderStageMesh"
      ; "MTLRenderStageObject"; "MTLRenderStageTile"
      ; "MTLRenderStageVertex"
      ]
  @ enum_cases "MTLStoreAction"
      [ "MTLStoreActionDontCare"; "MTLStoreActionStore"
      ; "MTLStoreActionUnknown"
      ]
  @ enum_cases "MTLTriangleFillMode"
      [ "MTLTriangleFillModeFill"; "MTLTriangleFillModeLines" ]
  @ enum_cases "MTLWinding"
      [ "MTLWindingClockwise"; "MTLWindingCounterClockwise" ]
  @ enum_cases "MTLVisibilityResultMode"
      [ "MTLVisibilityResultModeDisabled"; "MTLVisibilityResultModeBoolean"
      ; "MTLVisibilityResultModeCounting"
      ]
  @ enum_cases "MTLVisibilityResultType"
      [ "MTLVisibilityResultTypeReset"; "MTLVisibilityResultTypeAccumulate" ]
  @ enum_cases "MTLBindingAccess"
      [ "MTLArgumentAccessReadOnly"; "MTLArgumentAccessReadWrite"
      ; "MTLArgumentAccessWriteOnly"; "MTLBindingAccessReadOnly"
      ; "MTLBindingAccessReadWrite"; "MTLBindingAccessWriteOnly"
      ]
  @ enum_cases "MTLBindingType"
      [ "MTLBindingTypeBuffer"; "MTLBindingTypeThreadgroupMemory"
      ; "MTLBindingTypeTexture"; "MTLBindingTypeSampler"
      ; "MTLBindingTypeImageblockData"; "MTLBindingTypeImageblock"
      ; "MTLBindingTypeVisibleFunctionTable"
      ; "MTLBindingTypePrimitiveAccelerationStructure"
      ; "MTLBindingTypeInstanceAccelerationStructure"
      ; "MTLBindingTypeIntersectionFunctionTable"
      ; "MTLBindingTypeObjectPayload"; "MTLBindingTypeTensor"
      ]
  @ enum_cases "MTLBlendFactor"
      [ "MTLBlendFactorZero"; "MTLBlendFactorOne"
      ; "MTLBlendFactorSourceColor"; "MTLBlendFactorOneMinusSourceColor"
      ; "MTLBlendFactorSourceAlpha"; "MTLBlendFactorOneMinusSourceAlpha"
      ; "MTLBlendFactorDestinationColor"
      ; "MTLBlendFactorOneMinusDestinationColor"
      ; "MTLBlendFactorDestinationAlpha"
      ; "MTLBlendFactorOneMinusDestinationAlpha"
      ; "MTLBlendFactorSourceAlphaSaturated"; "MTLBlendFactorBlendColor"
      ; "MTLBlendFactorOneMinusBlendColor"; "MTLBlendFactorBlendAlpha"
      ; "MTLBlendFactorOneMinusBlendAlpha"; "MTLBlendFactorSource1Color"
      ; "MTLBlendFactorOneMinusSource1Color"
      ; "MTLBlendFactorSource1Alpha"
      ; "MTLBlendFactorOneMinusSource1Alpha"
      ]
  @ enum_cases "MTLBlendOperation"
      [ "MTLBlendOperationAdd"; "MTLBlendOperationSubtract"
      ; "MTLBlendOperationReverseSubtract"; "MTLBlendOperationMin"
      ; "MTLBlendOperationMax"
      ]
  @ enum_cases "MTLFunctionType"
      [ "MTLFunctionTypeVertex"; "MTLFunctionTypeFragment"
      ; "MTLFunctionTypeKernel"; "MTLFunctionTypeVisible"
      ; "MTLFunctionTypeIntersection"; "MTLFunctionTypeMesh"
      ; "MTLFunctionTypeObject"
      ]
  @ enum_cases "MTLPrimitiveTopologyClass"
      [ "MTLPrimitiveTopologyClassPoint"; "MTLPrimitiveTopologyClassLine"
      ; "MTLPrimitiveTopologyClassTriangle"
      ]
  @ enum_cases "MTLPipelineOption"
      [ "MTLPipelineOptionNone"; "MTLPipelineOptionArgumentInfo"
      ; "MTLPipelineOptionBindingInfo"; "MTLPipelineOptionBufferTypeInfo"
      ; "MTLPipelineOptionFailOnBinaryArchiveMiss"
      ]
  @ enum_cases "MTLLibraryType"
      [ "MTLLibraryTypeExecutable"; "MTLLibraryTypeDynamic" ]
  @ enum_cases "MTLDataType"
      [ "MTLDataTypeNone"; "MTLDataTypeStruct"; "MTLDataTypeArray"
      ; "MTLDataTypeFloat"; "MTLDataTypeFloat2"; "MTLDataTypeFloat3"
      ; "MTLDataTypeFloat4"; "MTLDataTypeFloat2x2"
      ; "MTLDataTypeFloat2x3"; "MTLDataTypeFloat2x4"
      ; "MTLDataTypeFloat3x2"; "MTLDataTypeFloat3x3"
      ; "MTLDataTypeFloat3x4"; "MTLDataTypeFloat4x2"
      ; "MTLDataTypeFloat4x3"; "MTLDataTypeFloat4x4"
      ; "MTLDataTypeHalf"; "MTLDataTypeHalf2"; "MTLDataTypeHalf3"
      ; "MTLDataTypeHalf4"; "MTLDataTypeHalf2x2"; "MTLDataTypeHalf2x3"
      ; "MTLDataTypeHalf2x4"; "MTLDataTypeHalf3x2"
      ; "MTLDataTypeHalf3x3"; "MTLDataTypeHalf3x4"
      ; "MTLDataTypeHalf4x2"; "MTLDataTypeHalf4x3"
      ; "MTLDataTypeHalf4x4"; "MTLDataTypeInt"; "MTLDataTypeInt2"
      ; "MTLDataTypeInt3"; "MTLDataTypeInt4"; "MTLDataTypeUInt"
      ; "MTLDataTypeUInt2"; "MTLDataTypeUInt3"; "MTLDataTypeUInt4"
      ; "MTLDataTypeShort"; "MTLDataTypeShort2"; "MTLDataTypeShort3"
      ; "MTLDataTypeShort4"; "MTLDataTypeUShort"; "MTLDataTypeUShort2"
      ; "MTLDataTypeUShort3"; "MTLDataTypeUShort4"; "MTLDataTypeChar"
      ; "MTLDataTypeChar2"; "MTLDataTypeChar3"; "MTLDataTypeChar4"
      ; "MTLDataTypeUChar"; "MTLDataTypeUChar2"; "MTLDataTypeUChar3"
      ; "MTLDataTypeUChar4"; "MTLDataTypeBool"; "MTLDataTypeBool2"
      ; "MTLDataTypeBool3"; "MTLDataTypeBool4"; "MTLDataTypeTexture"
      ; "MTLDataTypeSampler"; "MTLDataTypePointer"; "MTLDataTypeLong"
      ; "MTLDataTypeLong2"; "MTLDataTypeLong3"; "MTLDataTypeLong4"
      ; "MTLDataTypeULong"; "MTLDataTypeULong2"; "MTLDataTypeULong3"
      ; "MTLDataTypeULong4"; "MTLDataTypeBFloat"; "MTLDataTypeBFloat2"
      ; "MTLDataTypeBFloat3"; "MTLDataTypeBFloat4"
      ]
  @ enum_cases "MTLStages"
      [ "MTLStageAll"; "MTLStageResourceState" ]
  @ enum_cases "MTLGPUFamily"
      [ "MTLGPUFamilyApple1"; "MTLGPUFamilyApple2"; "MTLGPUFamilyApple3"
      ; "MTLGPUFamilyApple4"; "MTLGPUFamilyApple5"; "MTLGPUFamilyApple6"
      ; "MTLGPUFamilyApple7"; "MTLGPUFamilyApple8"; "MTLGPUFamilyApple9"
      ; "MTLGPUFamilyApple10"; "MTLGPUFamilyMac2"; "MTLGPUFamilyCommon1"
      ; "MTLGPUFamilyCommon2"; "MTLGPUFamilyCommon3"; "MTLGPUFamilyMetal3"
      ; "MTLGPUFamilyMetal4"
      ]
  @ enum_cases "MTLStorageMode"
      [ "MTLStorageModeShared"; "MTLStorageModeManaged"; "MTLStorageModePrivate" ]
  @ enum_cases "MTLResourceOptions"
      [ "MTLResourceStorageModeShared"; "MTLResourceStorageModeManaged"
      ; "MTLResourceStorageModePrivate"
      ]
  @ enum_cases "MTLCommandBufferStatus"
      [ "MTLCommandBufferStatusNotEnqueued"; "MTLCommandBufferStatusEnqueued"
      ; "MTLCommandBufferStatusCommitted"; "MTLCommandBufferStatusScheduled"
      ; "MTLCommandBufferStatusCompleted"; "MTLCommandBufferStatusError"
      ]
  @ enum_cases "MTLCompareFunction"
      [ "MTLCompareFunctionNever"; "MTLCompareFunctionLess"
      ; "MTLCompareFunctionEqual"; "MTLCompareFunctionLessEqual"
      ; "MTLCompareFunctionGreater"; "MTLCompareFunctionNotEqual"
      ; "MTLCompareFunctionGreaterEqual"; "MTLCompareFunctionAlways"
      ]
  @ enum_cases "MTLColorWriteMask"
      [ "MTLColorWriteMaskNone"; "MTLColorWriteMaskRed"
      ; "MTLColorWriteMaskGreen"; "MTLColorWriteMaskBlue"
      ; "MTLColorWriteMaskAlpha"; "MTLColorWriteMaskAll"
      ]
  @ enum_cases "MTLVertexFormat"
      [ "MTLVertexFormatUChar2"; "MTLVertexFormatUChar3"
      ; "MTLVertexFormatUChar4"; "MTLVertexFormatChar2"
      ; "MTLVertexFormatChar3"; "MTLVertexFormatChar4"
      ; "MTLVertexFormatUChar2Normalized"
      ; "MTLVertexFormatUChar3Normalized"
      ; "MTLVertexFormatUChar4Normalized"
      ; "MTLVertexFormatChar2Normalized"
      ; "MTLVertexFormatChar3Normalized"
      ; "MTLVertexFormatChar4Normalized"; "MTLVertexFormatUShort2"
      ; "MTLVertexFormatUShort3"; "MTLVertexFormatUShort4"
      ; "MTLVertexFormatShort2"; "MTLVertexFormatShort3"
      ; "MTLVertexFormatShort4"; "MTLVertexFormatUShort2Normalized"
      ; "MTLVertexFormatUShort3Normalized"
      ; "MTLVertexFormatUShort4Normalized"
      ; "MTLVertexFormatShort2Normalized"
      ; "MTLVertexFormatShort3Normalized"
      ; "MTLVertexFormatShort4Normalized"; "MTLVertexFormatHalf2"
      ; "MTLVertexFormatHalf3"; "MTLVertexFormatHalf4"
      ; "MTLVertexFormatFloat"; "MTLVertexFormatFloat2"
      ; "MTLVertexFormatFloat3"; "MTLVertexFormatFloat4"
      ; "MTLVertexFormatInt"; "MTLVertexFormatInt2"
      ; "MTLVertexFormatInt3"; "MTLVertexFormatInt4"
      ; "MTLVertexFormatUInt"; "MTLVertexFormatUInt2"
      ; "MTLVertexFormatUInt3"; "MTLVertexFormatUInt4"
      ; "MTLVertexFormatInt1010102Normalized"
      ; "MTLVertexFormatUInt1010102Normalized"
      ; "MTLVertexFormatUChar4Normalized_BGRA"; "MTLVertexFormatUChar"
      ; "MTLVertexFormatChar"; "MTLVertexFormatUCharNormalized"
      ; "MTLVertexFormatCharNormalized"; "MTLVertexFormatUShort"
      ; "MTLVertexFormatShort"; "MTLVertexFormatUShortNormalized"
      ; "MTLVertexFormatShortNormalized"; "MTLVertexFormatHalf"
      ; "MTLVertexFormatFloatRG11B10"; "MTLVertexFormatFloatRGB9E5"
      ]
  @ enum_cases "MTLVertexStepFunction"
      [ "MTLVertexStepFunctionConstant"; "MTLVertexStepFunctionPerVertex"
      ; "MTLVertexStepFunctionPerInstance"; "MTLVertexStepFunctionPerPatch"
      ; "MTLVertexStepFunctionPerPatchControlPoint"
      ]
  @ enum_cases "MTLStencilOperation"
      [ "MTLStencilOperationKeep"; "MTLStencilOperationZero"
      ; "MTLStencilOperationReplace"; "MTLStencilOperationIncrementClamp"
      ; "MTLStencilOperationDecrementClamp"; "MTLStencilOperationInvert"
      ; "MTLStencilOperationIncrementWrap"
      ; "MTLStencilOperationDecrementWrap"
      ]
  @ enum_cases "MTLCPUCacheMode"
      [ "MTLCPUCacheModeDefaultCache"; "MTLCPUCacheModeWriteCombined" ]
  @ enum_cases "MTLHazardTrackingMode"
      [ "MTLHazardTrackingModeDefault"; "MTLHazardTrackingModeUntracked"
      ; "MTLHazardTrackingModeTracked"
      ]
  @ enum_cases "MTLHeapType"
      [ "MTLHeapTypeAutomatic"; "MTLHeapTypePlacement"; "MTLHeapTypeSparse" ]
  @ enum_cases "MTLSparsePageSize"
      [ "MTLSparsePageSize16"; "MTLSparsePageSize64"
      ; "MTLSparsePageSize256"
      ]
  @ enum_cases "MTLSparseTextureMappingMode"
      [ "MTLSparseTextureMappingModeMap"; "MTLSparseTextureMappingModeUnmap" ]
  @ enum_cases "MTLSamplerReductionMode"
      [ "MTLSamplerReductionModeWeightedAverage"
      ; "MTLSamplerReductionModeMinimum"; "MTLSamplerReductionModeMaximum"
      ]
  @ enum_cases "MTLBufferSparseTier"
      [ "MTLBufferSparseTierNone"; "MTLBufferSparseTier1" ]
  @ enum_cases "MTLTextureSparseTier"
      [ "MTLTextureSparseTierNone"; "MTLTextureSparseTier1"
      ; "MTLTextureSparseTier2"
      ]
  @ enum_cases "MTLTextureCompressionType"
      [ "MTLTextureCompressionTypeLossless"; "MTLTextureCompressionTypeLossy" ]
  @ enum_cases "MTLTextureSwizzle"
      [ "MTLTextureSwizzleZero"; "MTLTextureSwizzleOne"
      ; "MTLTextureSwizzleRed"; "MTLTextureSwizzleGreen"
      ; "MTLTextureSwizzleBlue"; "MTLTextureSwizzleAlpha"
      ]
  @ enum_cases "MTLPixelFormat"
      [ "MTLPixelFormatA8Unorm"; "MTLPixelFormatR8Unorm"
      ; "MTLPixelFormatR8Unorm_sRGB"; "MTLPixelFormatR8Snorm"
      ; "MTLPixelFormatR8Uint"; "MTLPixelFormatR8Sint"
      ; "MTLPixelFormatR16Unorm"; "MTLPixelFormatR16Snorm"
      ; "MTLPixelFormatR16Uint"; "MTLPixelFormatR16Sint"
      ; "MTLPixelFormatR16Float"; "MTLPixelFormatRG8Unorm"
      ; "MTLPixelFormatRG8Unorm_sRGB"; "MTLPixelFormatRG8Snorm"
      ; "MTLPixelFormatRG8Uint"; "MTLPixelFormatRG8Sint"
      ; "MTLPixelFormatB5G6R5Unorm"; "MTLPixelFormatA1BGR5Unorm"
      ; "MTLPixelFormatABGR4Unorm"; "MTLPixelFormatBGR5A1Unorm"
      ; "MTLPixelFormatR32Uint"; "MTLPixelFormatR32Sint"
      ; "MTLPixelFormatR32Float"; "MTLPixelFormatRG16Unorm"
      ; "MTLPixelFormatRG16Snorm"; "MTLPixelFormatRG16Uint"
      ; "MTLPixelFormatRG16Sint"; "MTLPixelFormatRG16Float"
      ; "MTLPixelFormatRGBA8Unorm"; "MTLPixelFormatRGBA8Unorm_sRGB"
      ; "MTLPixelFormatRGBA8Snorm"; "MTLPixelFormatRGBA8Uint"
      ; "MTLPixelFormatRGBA8Sint"; "MTLPixelFormatBGRA8Unorm"
      ; "MTLPixelFormatBGRA8Unorm_sRGB"; "MTLPixelFormatRGB10A2Unorm"
      ; "MTLPixelFormatRGB10A2Uint"; "MTLPixelFormatRG11B10Float"
      ; "MTLPixelFormatRGB9E5Float"; "MTLPixelFormatBGR10A2Unorm"
      ; "MTLPixelFormatBGR10_XR"; "MTLPixelFormatBGR10_XR_sRGB"
      ; "MTLPixelFormatRG32Uint"; "MTLPixelFormatRG32Sint"
      ; "MTLPixelFormatRG32Float"; "MTLPixelFormatRGBA16Unorm"
      ; "MTLPixelFormatRGBA16Snorm"; "MTLPixelFormatRGBA16Uint"
      ; "MTLPixelFormatRGBA16Sint"; "MTLPixelFormatRGBA16Float"
      ; "MTLPixelFormatBGRA10_XR"; "MTLPixelFormatBGRA10_XR_sRGB"
      ; "MTLPixelFormatRGBA32Uint"; "MTLPixelFormatRGBA32Sint"
      ; "MTLPixelFormatRGBA32Float"
      ; "MTLPixelFormatBC1_RGBA"; "MTLPixelFormatBC1_RGBA_sRGB"
      ; "MTLPixelFormatBC2_RGBA"; "MTLPixelFormatBC2_RGBA_sRGB"
      ; "MTLPixelFormatBC3_RGBA"; "MTLPixelFormatBC3_RGBA_sRGB"
      ; "MTLPixelFormatBC4_RUnorm"; "MTLPixelFormatBC4_RSnorm"
      ; "MTLPixelFormatBC5_RGUnorm"; "MTLPixelFormatBC5_RGSnorm"
      ; "MTLPixelFormatBC6H_RGBFloat"; "MTLPixelFormatBC6H_RGBUfloat"
      ; "MTLPixelFormatBC7_RGBAUnorm"; "MTLPixelFormatBC7_RGBAUnorm_sRGB"
      ; "MTLPixelFormatEAC_R11Unorm"; "MTLPixelFormatEAC_R11Snorm"
      ; "MTLPixelFormatEAC_RG11Unorm"; "MTLPixelFormatEAC_RG11Snorm"
      ; "MTLPixelFormatEAC_RGBA8"; "MTLPixelFormatEAC_RGBA8_sRGB"
      ; "MTLPixelFormatETC2_RGB8"; "MTLPixelFormatETC2_RGB8_sRGB"
      ; "MTLPixelFormatETC2_RGB8A1"; "MTLPixelFormatETC2_RGB8A1_sRGB"
      ; "MTLPixelFormatASTC_4x4_sRGB"; "MTLPixelFormatASTC_5x4_sRGB"
      ; "MTLPixelFormatASTC_5x5_sRGB"; "MTLPixelFormatASTC_6x5_sRGB"
      ; "MTLPixelFormatASTC_6x6_sRGB"; "MTLPixelFormatASTC_8x5_sRGB"
      ; "MTLPixelFormatASTC_8x6_sRGB"; "MTLPixelFormatASTC_8x8_sRGB"
      ; "MTLPixelFormatASTC_10x5_sRGB"; "MTLPixelFormatASTC_10x6_sRGB"
      ; "MTLPixelFormatASTC_10x8_sRGB"; "MTLPixelFormatASTC_10x10_sRGB"
      ; "MTLPixelFormatASTC_12x10_sRGB"; "MTLPixelFormatASTC_12x12_sRGB"
      ; "MTLPixelFormatASTC_4x4_LDR"; "MTLPixelFormatASTC_5x4_LDR"
      ; "MTLPixelFormatASTC_5x5_LDR"; "MTLPixelFormatASTC_6x5_LDR"
      ; "MTLPixelFormatASTC_6x6_LDR"; "MTLPixelFormatASTC_8x5_LDR"
      ; "MTLPixelFormatASTC_8x6_LDR"; "MTLPixelFormatASTC_8x8_LDR"
      ; "MTLPixelFormatASTC_10x5_LDR"; "MTLPixelFormatASTC_10x6_LDR"
      ; "MTLPixelFormatASTC_10x8_LDR"; "MTLPixelFormatASTC_10x10_LDR"
      ; "MTLPixelFormatASTC_12x10_LDR"; "MTLPixelFormatASTC_12x12_LDR"
      ; "MTLPixelFormatASTC_4x4_HDR"; "MTLPixelFormatASTC_5x4_HDR"
      ; "MTLPixelFormatASTC_5x5_HDR"; "MTLPixelFormatASTC_6x5_HDR"
      ; "MTLPixelFormatASTC_6x6_HDR"; "MTLPixelFormatASTC_8x5_HDR"
      ; "MTLPixelFormatASTC_8x6_HDR"; "MTLPixelFormatASTC_8x8_HDR"
      ; "MTLPixelFormatASTC_10x5_HDR"; "MTLPixelFormatASTC_10x6_HDR"
      ; "MTLPixelFormatASTC_10x8_HDR"; "MTLPixelFormatASTC_10x10_HDR"
      ; "MTLPixelFormatASTC_12x10_HDR"; "MTLPixelFormatASTC_12x12_HDR"
      ; "MTLPixelFormatGBGR422"
      ; "MTLPixelFormatBGRG422"
      ; "MTLPixelFormatDepth16Unorm"; "MTLPixelFormatDepth32Float"
      ; "MTLPixelFormatStencil8"; "MTLPixelFormatDepth24Unorm_Stencil8"
      ; "MTLPixelFormatDepth32Float_Stencil8"; "MTLPixelFormatX32_Stencil8"
      ; "MTLPixelFormatX24_Stencil8"
      ]
  @ enum_cases "MTLPurgeableState"
      [ "MTLPurgeableStateKeepCurrent"; "MTLPurgeableStateNonVolatile"
      ; "MTLPurgeableStateVolatile"; "MTLPurgeableStateEmpty"
      ]
  @ enum_cases "MTLSamplerAddressMode"
      [ "MTLSamplerAddressModeClampToEdge"
      ; "MTLSamplerAddressModeMirrorClampToEdge"
      ; "MTLSamplerAddressModeRepeat"; "MTLSamplerAddressModeMirrorRepeat"
      ; "MTLSamplerAddressModeClampToZero"
      ; "MTLSamplerAddressModeClampToBorderColor"
      ]
  @ enum_cases "MTLSamplerBorderColor"
      [ "MTLSamplerBorderColorTransparentBlack"
      ; "MTLSamplerBorderColorOpaqueBlack"; "MTLSamplerBorderColorOpaqueWhite"
      ]
  @ enum_cases "MTLSamplerMinMagFilter"
      [ "MTLSamplerMinMagFilterNearest"; "MTLSamplerMinMagFilterLinear" ]
  @ enum_cases "MTLSamplerMipFilter"
      [ "MTLSamplerMipFilterNotMipmapped"; "MTLSamplerMipFilterNearest"
      ; "MTLSamplerMipFilterLinear"
      ]
  @ enum_cases "MTLTextureType"
      [ "MTLTextureType1D"; "MTLTextureType1DArray"; "MTLTextureType2D"
      ; "MTLTextureType2DArray"; "MTLTextureType2DMultisample"
      ; "MTLTextureTypeCube"; "MTLTextureTypeCubeArray"; "MTLTextureType3D"
      ; "MTLTextureType2DMultisampleArray"; "MTLTextureTypeTextureBuffer"
      ]
  @ enum_cases "MTLTextureUsage"
      [ "MTLTextureUsageUnknown"; "MTLTextureUsageShaderRead"
      ; "MTLTextureUsageShaderWrite"; "MTLTextureUsageRenderTarget"
      ; "MTLTextureUsagePixelFormatView"; "MTLTextureUsageShaderAtomic"
      ]
  @ enum_cases "MTLResourceOptions"
      [ "MTLResourceCPUCacheModeDefaultCache"
      ; "MTLResourceCPUCacheModeWriteCombined"
      ; "MTLResourceHazardTrackingModeDefault"
      ; "MTLResourceHazardTrackingModeUntracked"
      ; "MTLResourceHazardTrackingModeTracked"
      ]
  @ Binding_plan.bound_identifiers
  @ Binding_direct_plan.safe_device_identifiers

let bound_identifier_set = String_set.of_list bound_identifiers

let generated_public_enum_family_set =
  String_set.of_list
    (Binding_enum_plan.family_names
     @ List.map
         (fun (family : Binding_enum_implicit_plan.family) -> family.sdk_name)
         Binding_enum_implicit_plan.families)

let generated_public_enum_identifier identifier =
  let family_after prefix =
    if String.starts_with ~prefix identifier then
      let suffix =
        String.sub identifier (String.length prefix)
          (String.length identifier - String.length prefix)
      in
      let family =
        match String.index_opt suffix ':' with
        | None -> suffix
        | Some separator -> String.sub suffix 0 separator
      in
      String_set.mem family generated_public_enum_family_set
    else false
  in
  family_after "enum:" || family_after "typedef:"
  || family_after "enum-case:"

let availability_gated_identifier_set =
  String_set.of_list
    [ "method:-[MTL4Compiler newComputePipelineStateWithDescriptor:dynamicLinkingDescriptor:compilerTaskOptions:completionHandler:]"
    ]

let name = function
  | Bound -> "bound"
  | Availability_gated -> "availability-gated"
  | Scope_excluded -> "scope-excluded"
  | Unreviewed -> "unreviewed"

let classify ~unavailable ~identifier =
  if unavailable then
    Scope_excluded, "Clang marks this declaration unavailable for macOS."
  else if String_set.mem identifier availability_gated_identifier_set then
    ( Availability_gated
    , "Implemented with an Apple9/M3+ capability gate; the Apple7/M1 Metal 4 driver crashes while serializing this asynchronous dynamic-link request." )
  else if String_set.mem identifier bound_identifier_set then
    Bound, "Implemented by the ownership-aware prismel.metal safe layer."
  else if generated_public_enum_identifier identifier then
    Bound, "Implemented by the generated, typed prismel.metal pure-value enum surface."
  else Unreviewed, "Binding classification pending during Phase 2."
