#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
/* exact conventional render/compute pipeline mechanical shard */
static MTLSize prismel_pipeline_mtlcomputepipelinedescriptor_requiredthreadsperthreadgroup(MTLComputePipelineDescriptor * receiver){return [receiver requiredThreadsPerThreadgroup];}/*method:-[MTLComputePipelineDescriptor requiredThreadsPerThreadgroup]*/
static void prismel_pipeline_mtlcomputepipelinedescriptor_reset(MTLComputePipelineDescriptor * receiver){[receiver reset];}/*method:-[MTLComputePipelineDescriptor reset]*/
static void prismel_pipeline_mtlcomputepipelinedescriptor_setrequiredthreadsperthreadgroup_(MTLComputePipelineDescriptor * receiver, MTLSize a0){[receiver setRequiredThreadsPerThreadgroup:a0];}/*method:-[MTLComputePipelineDescriptor setRequiredThreadsPerThreadgroup:]*/
static MTLResourceID prismel_pipeline_mtlcomputepipelinestate_gpuresourceid(id<MTLComputePipelineState> receiver){return [receiver gpuResourceID];}/*method:-[MTLComputePipelineState gpuResourceID]*/
static NSUInteger prismel_pipeline_mtlcomputepipelinestate_imageblockmemorylengthfordimensions_(id<MTLComputePipelineState> receiver, MTLSize a0){return [receiver imageblockMemoryLengthForDimensions:a0];}/*method:-[MTLComputePipelineState imageblockMemoryLengthForDimensions:]*/
static MTLSize prismel_pipeline_mtlcomputepipelinestate_requiredthreadsperthreadgroup(id<MTLComputePipelineState> receiver){return [receiver requiredThreadsPerThreadgroup];}/*method:-[MTLComputePipelineState requiredThreadsPerThreadgroup]*/
static MTLShaderValidation prismel_pipeline_mtlcomputepipelinestate_shadervalidation(id<MTLComputePipelineState> receiver){return [receiver shaderValidation];}/*method:-[MTLComputePipelineState shaderValidation]*/
static BOOL prismel_pipeline_mtlcomputepipelinestate_supportindirectcommandbuffers(id<MTLComputePipelineState> receiver){return [receiver supportIndirectCommandBuffers];}/*method:-[MTLComputePipelineState supportIndirectCommandBuffers]*/
static MTLPixelFormat prismel_pipeline_mtlrenderpipelinedescriptor_depthattachmentpixelformat(MTLRenderPipelineDescriptor * receiver){return [receiver depthAttachmentPixelFormat];}/*method:-[MTLRenderPipelineDescriptor depthAttachmentPixelFormat]*/
static MTLPrimitiveTopologyClass prismel_pipeline_mtlrenderpipelinedescriptor_inputprimitivetopology(MTLRenderPipelineDescriptor * receiver){return [receiver inputPrimitiveTopology];}/*method:-[MTLRenderPipelineDescriptor inputPrimitiveTopology]*/
static void prismel_pipeline_mtlrenderpipelinedescriptor_reset(MTLRenderPipelineDescriptor * receiver){[receiver reset];}/*method:-[MTLRenderPipelineDescriptor reset]*/
static NSUInteger prismel_pipeline_mtlrenderpipelinedescriptor_samplecount(MTLRenderPipelineDescriptor * receiver){return [receiver sampleCount];}/*method:-[MTLRenderPipelineDescriptor sampleCount]*/
static void prismel_pipeline_mtlrenderpipelinedescriptor_setdepthattachmentpixelformat_(MTLRenderPipelineDescriptor * receiver, MTLPixelFormat a0){[receiver setDepthAttachmentPixelFormat:a0];}/*method:-[MTLRenderPipelineDescriptor setDepthAttachmentPixelFormat:]*/
static void prismel_pipeline_mtlrenderpipelinedescriptor_setinputprimitivetopology_(MTLRenderPipelineDescriptor * receiver, MTLPrimitiveTopologyClass a0){[receiver setInputPrimitiveTopology:a0];}/*method:-[MTLRenderPipelineDescriptor setInputPrimitiveTopology:]*/
static void prismel_pipeline_mtlrenderpipelinedescriptor_setsamplecount_(MTLRenderPipelineDescriptor * receiver, NSUInteger a0){[receiver setSampleCount:a0];}/*method:-[MTLRenderPipelineDescriptor setSampleCount:]*/
static void prismel_pipeline_mtlrenderpipelinedescriptor_setstencilattachmentpixelformat_(MTLRenderPipelineDescriptor * receiver, MTLPixelFormat a0){[receiver setStencilAttachmentPixelFormat:a0];}/*method:-[MTLRenderPipelineDescriptor setStencilAttachmentPixelFormat:]*/
static void prismel_pipeline_mtlrenderpipelinedescriptor_settessellationoutputwindingorder_(MTLRenderPipelineDescriptor * receiver, MTLWinding a0){[receiver setTessellationOutputWindingOrder:a0];}/*method:-[MTLRenderPipelineDescriptor setTessellationOutputWindingOrder:]*/
static MTLPixelFormat prismel_pipeline_mtlrenderpipelinedescriptor_stencilattachmentpixelformat(MTLRenderPipelineDescriptor * receiver){return [receiver stencilAttachmentPixelFormat];}/*method:-[MTLRenderPipelineDescriptor stencilAttachmentPixelFormat]*/
static MTLWinding prismel_pipeline_mtlrenderpipelinedescriptor_tessellationoutputwindingorder(MTLRenderPipelineDescriptor * receiver){return [receiver tessellationOutputWindingOrder];}/*method:-[MTLRenderPipelineDescriptor tessellationOutputWindingOrder]*/
static MTLResourceID prismel_pipeline_mtlrenderpipelinestate_gpuresourceid(id<MTLRenderPipelineState> receiver){return [receiver gpuResourceID];}/*method:-[MTLRenderPipelineState gpuResourceID]*/
static NSUInteger prismel_pipeline_mtlrenderpipelinestate_imageblockmemorylengthfordimensions_(id<MTLRenderPipelineState> receiver, MTLSize a0){return [receiver imageblockMemoryLengthForDimensions:a0];}/*method:-[MTLRenderPipelineState imageblockMemoryLengthForDimensions:]*/
static NSUInteger prismel_pipeline_mtlrenderpipelinestate_imageblocksamplelength(id<MTLRenderPipelineState> receiver){return [receiver imageblockSampleLength];}/*method:-[MTLRenderPipelineState imageblockSampleLength]*/
static MTLSize prismel_pipeline_mtlrenderpipelinestate_requiredthreadspermeshthreadgroup(id<MTLRenderPipelineState> receiver){return [receiver requiredThreadsPerMeshThreadgroup];}/*method:-[MTLRenderPipelineState requiredThreadsPerMeshThreadgroup]*/
static MTLSize prismel_pipeline_mtlrenderpipelinestate_requiredthreadsperobjectthreadgroup(id<MTLRenderPipelineState> receiver){return [receiver requiredThreadsPerObjectThreadgroup];}/*method:-[MTLRenderPipelineState requiredThreadsPerObjectThreadgroup]*/
static MTLSize prismel_pipeline_mtlrenderpipelinestate_requiredthreadspertilethreadgroup(id<MTLRenderPipelineState> receiver){return [receiver requiredThreadsPerTileThreadgroup];}/*method:-[MTLRenderPipelineState requiredThreadsPerTileThreadgroup]*/
static MTLShaderValidation prismel_pipeline_mtlrenderpipelinestate_shadervalidation(id<MTLRenderPipelineState> receiver){return [receiver shaderValidation];}/*method:-[MTLRenderPipelineState shaderValidation]*/
static BOOL prismel_pipeline_mtlrenderpipelinestate_supportindirectcommandbuffers(id<MTLRenderPipelineState> receiver){return [receiver supportIndirectCommandBuffers];}/*method:-[MTLRenderPipelineState supportIndirectCommandBuffers]*/
