#import <QuartzCore/CAMetalLayer.h>
#import <Metal/Metal.h>
#include <cstdint>
extern "C" {
#include <caml/alloc.h>
#include <caml/memory.h>
#include <caml/mlvalues.h>
}

/* Generated callable, statically typed presentation adapters and CAML entry points. */
static MTLRenderPassDescriptor * _Nonnull prismel_presentation_mtlrenderpassdescriptor_renderpassdescriptor() { return [MTLRenderPassDescriptor renderPassDescriptor]; } /* method:+[MTLRenderPassDescriptor renderPassDescriptor] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_renderpassdescriptor(value raw_unit) { CAMLparam0(); auto r=prismel_presentation_mtlrenderpassdescriptor_renderpassdescriptor(); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static CAEDRMetadata * _Nullable prismel_presentation_cametallayer_edrmetadata(CAMetalLayer * receiver) { return [receiver EDRMetadata]; } /* method:-[CAMetalLayer EDRMetadata] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_edrmetadata(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_cametallayer_edrmetadata((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static BOOL prismel_presentation_cametallayer_allowsnextdrawabletimeout(CAMetalLayer * receiver) { return [receiver allowsNextDrawableTimeout]; } /* method:-[CAMetalLayer allowsNextDrawableTimeout] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_allowsnextdrawabletimeout(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_cametallayer_allowsnextdrawabletimeout((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static CGColorSpaceRef _Nullable prismel_presentation_cametallayer_colorspace(CAMetalLayer * receiver) { return [receiver colorspace]; } /* method:-[CAMetalLayer colorspace] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_colorspace(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_cametallayer_colorspace((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(void *) r)); }
static id<MTLDevice> _Nullable prismel_presentation_cametallayer_device(CAMetalLayer * receiver) { return [receiver device]; } /* method:-[CAMetalLayer device] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_device(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_cametallayer_device((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static BOOL prismel_presentation_cametallayer_displaysyncenabled(CAMetalLayer * receiver) { return [receiver displaySyncEnabled]; } /* method:-[CAMetalLayer displaySyncEnabled] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_displaysyncenabled(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_cametallayer_displaysyncenabled((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static CGSize prismel_presentation_cametallayer_drawablesize(CAMetalLayer * receiver) { return [receiver drawableSize]; } /* method:-[CAMetalLayer drawableSize] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_drawablesize(value raw0) { CAMLparam1(raw0); CGSize r=prismel_presentation_cametallayer_drawablesize((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)); CAMLlocal1(v); v=caml_alloc_tuple(2); Store_field(v,0,caml_copy_double(r.width)); Store_field(v,1,caml_copy_double(r.height)); CAMLreturn(v); }
static BOOL prismel_presentation_cametallayer_framebufferonly(CAMetalLayer * receiver) { return [receiver framebufferOnly]; } /* method:-[CAMetalLayer framebufferOnly] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_framebufferonly(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_cametallayer_framebufferonly((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_cametallayer_maximumdrawablecount(CAMetalLayer * receiver) { return [receiver maximumDrawableCount]; } /* method:-[CAMetalLayer maximumDrawableCount] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_maximumdrawablecount(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_cametallayer_maximumdrawablecount((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static MTLPixelFormat prismel_presentation_cametallayer_pixelformat(CAMetalLayer * receiver) { return [receiver pixelFormat]; } /* method:-[CAMetalLayer pixelFormat] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_pixelformat(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_cametallayer_pixelformat((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static BOOL prismel_presentation_cametallayer_presentswithtransaction(CAMetalLayer * receiver) { return [receiver presentsWithTransaction]; } /* method:-[CAMetalLayer presentsWithTransaction] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_presentswithtransaction(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_cametallayer_presentswithtransaction((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static void prismel_presentation_cametallayer_setallowsnextdrawabletimeout_(CAMetalLayer * receiver, BOOL arg0) { [receiver setAllowsNextDrawableTimeout:arg0]; } /* method:-[CAMetalLayer setAllowsNextDrawableTimeout:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setallowsnextdrawabletimeout_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setallowsnextdrawabletimeout_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), Bool_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setcolorspace_(CAMetalLayer * receiver, CGColorSpaceRef _Nullable arg0) { [receiver setColorspace:arg0]; } /* method:-[CAMetalLayer setColorspace:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setcolorspace_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setcolorspace_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), (CGColorSpaceRef)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setdevice_(CAMetalLayer * receiver, id<MTLDevice> _Nullable arg0) { [receiver setDevice:arg0]; } /* method:-[CAMetalLayer setDevice:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setdevice_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setdevice_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), (__bridge id<MTLDevice>)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setdisplaysyncenabled_(CAMetalLayer * receiver, BOOL arg0) { [receiver setDisplaySyncEnabled:arg0]; } /* method:-[CAMetalLayer setDisplaySyncEnabled:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setdisplaysyncenabled_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setdisplaysyncenabled_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), Bool_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setdrawablesize_(CAMetalLayer * receiver, CGSize arg0) { [receiver setDrawableSize:arg0]; } /* method:-[CAMetalLayer setDrawableSize:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setdrawablesize_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setdrawablesize_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), CGSizeMake(Double_val(Field(raw1,0)),Double_val(Field(raw1,1)))); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setedrmetadata_(CAMetalLayer * receiver, CAEDRMetadata * _Nullable arg0) { [receiver setEDRMetadata:arg0]; } /* method:-[CAMetalLayer setEDRMetadata:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setedrmetadata_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setedrmetadata_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), (__bridge CAEDRMetadata *)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setframebufferonly_(CAMetalLayer * receiver, BOOL arg0) { [receiver setFramebufferOnly:arg0]; } /* method:-[CAMetalLayer setFramebufferOnly:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setframebufferonly_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setframebufferonly_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), Bool_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setmaximumdrawablecount_(CAMetalLayer * receiver, NSUInteger arg0) { [receiver setMaximumDrawableCount:arg0]; } /* method:-[CAMetalLayer setMaximumDrawableCount:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setmaximumdrawablecount_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setmaximumdrawablecount_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setpixelformat_(CAMetalLayer * receiver, MTLPixelFormat arg0) { [receiver setPixelFormat:arg0]; } /* method:-[CAMetalLayer setPixelFormat:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setpixelformat_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setpixelformat_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), static_cast<MTLPixelFormat>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setpresentswithtransaction_(CAMetalLayer * receiver, BOOL arg0) { [receiver setPresentsWithTransaction:arg0]; } /* method:-[CAMetalLayer setPresentsWithTransaction:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setpresentswithtransaction_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setpresentswithtransaction_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), Bool_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_cametallayer_setwantsextendeddynamicrangecontent_(CAMetalLayer * receiver, BOOL arg0) { [receiver setWantsExtendedDynamicRangeContent:arg0]; } /* method:-[CAMetalLayer setWantsExtendedDynamicRangeContent:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_setwantsextendeddynamicrangecontent_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_cametallayer_setwantsextendeddynamicrangecontent_((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0), Bool_val(raw1)); CAMLreturn(Val_unit); }
static BOOL prismel_presentation_cametallayer_wantsextendeddynamicrangecontent(CAMetalLayer * receiver) { return [receiver wantsExtendedDynamicRangeContent]; } /* method:-[CAMetalLayer wantsExtendedDynamicRangeContent] */
extern "C" CAMLprim value caml_prismel_metal_presentation_cametallayer_wantsextendeddynamicrangecontent(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_cametallayer_wantsextendeddynamicrangecontent((__bridge CAMetalLayer *)(void *)Nativeint_val(raw0)))); }
static CFTimeInterval prismel_presentation_mtlcommandbuffer_gpuendtime(id<MTLCommandBuffer> receiver) { return [receiver GPUEndTime]; } /* method:-[MTLCommandBuffer GPUEndTime] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_gpuendtime(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_double(prismel_presentation_mtlcommandbuffer_gpuendtime((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)))); }
static CFTimeInterval prismel_presentation_mtlcommandbuffer_gpustarttime(id<MTLCommandBuffer> receiver) { return [receiver GPUStartTime]; } /* method:-[MTLCommandBuffer GPUStartTime] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_gpustarttime(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_double(prismel_presentation_mtlcommandbuffer_gpustarttime((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)))); }
static id<MTLAccelerationStructureCommandEncoder> _Nonnull prismel_presentation_mtlcommandbuffer_accelerationstructurecommandencoderwithdescriptor_(id<MTLCommandBuffer> receiver, MTLAccelerationStructurePassDescriptor * _Nonnull __strong arg0) { return [receiver accelerationStructureCommandEncoderWithDescriptor:arg0]; } /* method:-[MTLCommandBuffer accelerationStructureCommandEncoderWithDescriptor:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_accelerationstructurecommandencoderwithdescriptor_(value raw0, value raw1) { CAMLparam2(raw0,raw1); auto r=prismel_presentation_mtlcommandbuffer_accelerationstructurecommandencoderwithdescriptor_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge MTLAccelerationStructurePassDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLAccelerationStructureCommandEncoder> _Nullable prismel_presentation_mtlcommandbuffer_accelerationstructurecommandencoder(id<MTLCommandBuffer> receiver) { return [receiver accelerationStructureCommandEncoder]; } /* method:-[MTLCommandBuffer accelerationStructureCommandEncoder] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_accelerationstructurecommandencoder(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_mtlcommandbuffer_accelerationstructurecommandencoder((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLBlitCommandEncoder> _Nullable prismel_presentation_mtlcommandbuffer_blitcommandencoderwithdescriptor_(id<MTLCommandBuffer> receiver, MTLBlitPassDescriptor * _Nonnull __strong arg0) { return [receiver blitCommandEncoderWithDescriptor:arg0]; } /* method:-[MTLCommandBuffer blitCommandEncoderWithDescriptor:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_blitcommandencoderwithdescriptor_(value raw0, value raw1) { CAMLparam2(raw0,raw1); auto r=prismel_presentation_mtlcommandbuffer_blitcommandencoderwithdescriptor_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge MTLBlitPassDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLCommandQueue> _Nonnull prismel_presentation_mtlcommandbuffer_commandqueue(id<MTLCommandBuffer> receiver) { return [receiver commandQueue]; } /* method:-[MTLCommandBuffer commandQueue] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_commandqueue(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_mtlcommandbuffer_commandqueue((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLComputeCommandEncoder> _Nullable prismel_presentation_mtlcommandbuffer_computecommandencoderwithdescriptor_(id<MTLCommandBuffer> receiver, MTLComputePassDescriptor * _Nonnull __strong arg0) { return [receiver computeCommandEncoderWithDescriptor:arg0]; } /* method:-[MTLCommandBuffer computeCommandEncoderWithDescriptor:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_computecommandencoderwithdescriptor_(value raw0, value raw1) { CAMLparam2(raw0,raw1); auto r=prismel_presentation_mtlcommandbuffer_computecommandencoderwithdescriptor_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge MTLComputePassDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLComputeCommandEncoder> _Nullable prismel_presentation_mtlcommandbuffer_computecommandencoderwithdispatchtype_(id<MTLCommandBuffer> receiver, MTLDispatchType arg0) { return [receiver computeCommandEncoderWithDispatchType:arg0]; } /* method:-[MTLCommandBuffer computeCommandEncoderWithDispatchType:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_computecommandencoderwithdispatchtype_(value raw0, value raw1) { CAMLparam2(raw0,raw1); auto r=prismel_presentation_mtlcommandbuffer_computecommandencoderwithdispatchtype_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), static_cast<MTLDispatchType>(Int64_val(raw1))); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLDevice> _Nonnull prismel_presentation_mtlcommandbuffer_device(id<MTLCommandBuffer> receiver) { return [receiver device]; } /* method:-[MTLCommandBuffer device] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_device(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_mtlcommandbuffer_device((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static void prismel_presentation_mtlcommandbuffer_encodesignalevent_value_(id<MTLCommandBuffer> receiver, id<MTLEvent>  _Nonnull __strong arg0, uint64_t arg1) { [receiver encodeSignalEvent:arg0 value:arg1]; } /* method:-[MTLCommandBuffer encodeSignalEvent:value:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_encodesignalevent_value_(value raw0, value raw1, value raw2) { CAMLparam3(raw0,raw1,raw2); prismel_presentation_mtlcommandbuffer_encodesignalevent_value_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge id<MTLEvent>)(void *)Nativeint_val(raw1), static_cast<uint64_t>(Int64_val(raw2))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlcommandbuffer_encodewaitforevent_value_(id<MTLCommandBuffer> receiver, id<MTLEvent>  _Nonnull __strong arg0, uint64_t arg1) { [receiver encodeWaitForEvent:arg0 value:arg1]; } /* method:-[MTLCommandBuffer encodeWaitForEvent:value:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_encodewaitforevent_value_(value raw0, value raw1, value raw2) { CAMLparam3(raw0,raw1,raw2); prismel_presentation_mtlcommandbuffer_encodewaitforevent_value_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge id<MTLEvent>)(void *)Nativeint_val(raw1), static_cast<uint64_t>(Int64_val(raw2))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlcommandbuffer_enqueue(id<MTLCommandBuffer> receiver) { [receiver enqueue]; } /* method:-[MTLCommandBuffer enqueue] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_enqueue(value raw0) { CAMLparam1(raw0); prismel_presentation_mtlcommandbuffer_enqueue((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(Val_unit); }
static MTLCommandBufferErrorOption prismel_presentation_mtlcommandbuffer_erroroptions(id<MTLCommandBuffer> receiver) { return [receiver errorOptions]; } /* method:-[MTLCommandBuffer errorOptions] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_erroroptions(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlcommandbuffer_erroroptions((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)))); }
static CFTimeInterval prismel_presentation_mtlcommandbuffer_kernelendtime(id<MTLCommandBuffer> receiver) { return [receiver kernelEndTime]; } /* method:-[MTLCommandBuffer kernelEndTime] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_kernelendtime(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_double(prismel_presentation_mtlcommandbuffer_kernelendtime((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)))); }
static CFTimeInterval prismel_presentation_mtlcommandbuffer_kernelstarttime(id<MTLCommandBuffer> receiver) { return [receiver kernelStartTime]; } /* method:-[MTLCommandBuffer kernelStartTime] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_kernelstarttime(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_double(prismel_presentation_mtlcommandbuffer_kernelstarttime((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)))); }
static id<MTLLogContainer> _Nonnull prismel_presentation_mtlcommandbuffer_logs(id<MTLCommandBuffer> receiver) { return [receiver logs]; } /* method:-[MTLCommandBuffer logs] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_logs(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_mtlcommandbuffer_logs((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static id<MTLParallelRenderCommandEncoder> _Nullable prismel_presentation_mtlcommandbuffer_parallelrendercommandencoderwithdescriptor_(id<MTLCommandBuffer> receiver, MTLRenderPassDescriptor * _Nonnull __strong arg0) { return [receiver parallelRenderCommandEncoderWithDescriptor:arg0]; } /* method:-[MTLCommandBuffer parallelRenderCommandEncoderWithDescriptor:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_parallelrendercommandencoderwithdescriptor_(value raw0, value raw1) { CAMLparam2(raw0,raw1); auto r=prismel_presentation_mtlcommandbuffer_parallelrendercommandencoderwithdescriptor_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static void prismel_presentation_mtlcommandbuffer_popdebuggroup(id<MTLCommandBuffer> receiver) { [receiver popDebugGroup]; } /* method:-[MTLCommandBuffer popDebugGroup] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_popdebuggroup(value raw0) { CAMLparam1(raw0); prismel_presentation_mtlcommandbuffer_popdebuggroup((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlcommandbuffer_pushdebuggroup_(id<MTLCommandBuffer> receiver, NSString * _Nonnull __strong arg0) { [receiver pushDebugGroup:arg0]; } /* method:-[MTLCommandBuffer pushDebugGroup:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_pushdebuggroup_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlcommandbuffer_pushdebuggroup_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge NSString *)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static id<MTLResourceStateCommandEncoder> _Nullable prismel_presentation_mtlcommandbuffer_resourcestatecommandencoderwithdescriptor_(id<MTLCommandBuffer> receiver, MTLResourceStatePassDescriptor * _Nonnull __strong arg0) { return [receiver resourceStateCommandEncoderWithDescriptor:arg0]; } /* method:-[MTLCommandBuffer resourceStateCommandEncoderWithDescriptor:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_resourcestatecommandencoderwithdescriptor_(value raw0, value raw1) { CAMLparam2(raw0,raw1); auto r=prismel_presentation_mtlcommandbuffer_resourcestatecommandencoderwithdescriptor_((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0), (__bridge MTLResourceStatePassDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static BOOL prismel_presentation_mtlcommandbuffer_retainedreferences(id<MTLCommandBuffer> receiver) { return [receiver retainedReferences]; } /* method:-[MTLCommandBuffer retainedReferences] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_retainedreferences(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_mtlcommandbuffer_retainedreferences((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)))); }
static void prismel_presentation_mtlcommandbuffer_waituntilscheduled(id<MTLCommandBuffer> receiver) { [receiver waitUntilScheduled]; } /* method:-[MTLCommandBuffer waitUntilScheduled] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlcommandbuffer_waituntilscheduled(value raw0) { CAMLparam1(raw0); prismel_presentation_mtlcommandbuffer_waituntilscheduled((__bridge id<MTLCommandBuffer>)(void *)Nativeint_val(raw0)); CAMLreturn(Val_unit); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_defaultrastersamplecount(MTLRenderPassDescriptor * receiver) { return [receiver defaultRasterSampleCount]; } /* method:-[MTLRenderPassDescriptor defaultRasterSampleCount] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_defaultrastersamplecount(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_defaultrastersamplecount((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_getsamplepositions_count_(MTLRenderPassDescriptor * receiver, MTLSamplePosition * _Nullable arg0, NSUInteger arg1) { return [receiver getSamplePositions:arg0 count:arg1]; } /* method:-[MTLRenderPassDescriptor getSamplePositions:count:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_getsamplepositions_count_(value raw0, value raw1, value raw2) { CAMLparam3(raw0,raw1,raw2); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_getsamplepositions_count_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), (MTLSamplePosition *)(void *)Nativeint_val(raw1), static_cast<NSUInteger>(Int64_val(raw2))))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_imageblocksamplelength(MTLRenderPassDescriptor * receiver) { return [receiver imageblockSampleLength]; } /* method:-[MTLRenderPassDescriptor imageblockSampleLength] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_imageblocksamplelength(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_imageblocksamplelength((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_rendertargetarraylength(MTLRenderPassDescriptor * receiver) { return [receiver renderTargetArrayLength]; } /* method:-[MTLRenderPassDescriptor renderTargetArrayLength] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_rendertargetarraylength(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_rendertargetarraylength((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_rendertargetheight(MTLRenderPassDescriptor * receiver) { return [receiver renderTargetHeight]; } /* method:-[MTLRenderPassDescriptor renderTargetHeight] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_rendertargetheight(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_rendertargetheight((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_rendertargetwidth(MTLRenderPassDescriptor * receiver) { return [receiver renderTargetWidth]; } /* method:-[MTLRenderPassDescriptor renderTargetWidth] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_rendertargetwidth(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_rendertargetwidth((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static MTLRenderPassSampleBufferAttachmentDescriptorArray * _Nonnull prismel_presentation_mtlrenderpassdescriptor_samplebufferattachments(MTLRenderPassDescriptor * receiver) { return [receiver sampleBufferAttachments]; } /* method:-[MTLRenderPassDescriptor sampleBufferAttachments] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_samplebufferattachments(value raw0) { CAMLparam1(raw0); auto r=prismel_presentation_mtlrenderpassdescriptor_samplebufferattachments((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)); CAMLreturn(caml_copy_nativeint((intnat)(__bridge void *) r)); }
static void prismel_presentation_mtlrenderpassdescriptor_setdefaultrastersamplecount_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setDefaultRasterSampleCount:arg0]; } /* method:-[MTLRenderPassDescriptor setDefaultRasterSampleCount:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setdefaultrastersamplecount_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setdefaultrastersamplecount_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setdepthattachment_(MTLRenderPassDescriptor * receiver, MTLRenderPassDepthAttachmentDescriptor * _Nullable arg0) { [receiver setDepthAttachment:arg0]; } /* method:-[MTLRenderPassDescriptor setDepthAttachment:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setdepthattachment_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setdepthattachment_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), (__bridge MTLRenderPassDepthAttachmentDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setimageblocksamplelength_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setImageblockSampleLength:arg0]; } /* method:-[MTLRenderPassDescriptor setImageblockSampleLength:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setimageblocksamplelength_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setimageblocksamplelength_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setrasterizationratemap_(MTLRenderPassDescriptor * receiver, id<MTLRasterizationRateMap> _Nullable arg0) { [receiver setRasterizationRateMap:arg0]; } /* method:-[MTLRenderPassDescriptor setRasterizationRateMap:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setrasterizationratemap_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setrasterizationratemap_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), (__bridge id<MTLRasterizationRateMap>)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setrendertargetarraylength_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setRenderTargetArrayLength:arg0]; } /* method:-[MTLRenderPassDescriptor setRenderTargetArrayLength:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setrendertargetarraylength_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setrendertargetarraylength_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setrendertargetheight_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setRenderTargetHeight:arg0]; } /* method:-[MTLRenderPassDescriptor setRenderTargetHeight:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setrendertargetheight_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setrendertargetheight_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setrendertargetwidth_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setRenderTargetWidth:arg0]; } /* method:-[MTLRenderPassDescriptor setRenderTargetWidth:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setrendertargetwidth_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setrendertargetwidth_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setsamplepositions_count_(MTLRenderPassDescriptor * receiver, const MTLSamplePosition * _Nullable arg0, NSUInteger arg1) { [receiver setSamplePositions:arg0 count:arg1]; } /* method:-[MTLRenderPassDescriptor setSamplePositions:count:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setsamplepositions_count_(value raw0, value raw1, value raw2) { CAMLparam3(raw0,raw1,raw2); prismel_presentation_mtlrenderpassdescriptor_setsamplepositions_count_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), (MTLSamplePosition *)(void *)Nativeint_val(raw1), static_cast<NSUInteger>(Int64_val(raw2))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setstencilattachment_(MTLRenderPassDescriptor * receiver, MTLRenderPassStencilAttachmentDescriptor * _Nullable arg0) { [receiver setStencilAttachment:arg0]; } /* method:-[MTLRenderPassDescriptor setStencilAttachment:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setstencilattachment_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setstencilattachment_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), (__bridge MTLRenderPassStencilAttachmentDescriptor *)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setsupportcolorattachmentmapping_(MTLRenderPassDescriptor * receiver, BOOL arg0) { [receiver setSupportColorAttachmentMapping:arg0]; } /* method:-[MTLRenderPassDescriptor setSupportColorAttachmentMapping:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setsupportcolorattachmentmapping_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setsupportcolorattachmentmapping_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), Bool_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setthreadgroupmemorylength_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setThreadgroupMemoryLength:arg0]; } /* method:-[MTLRenderPassDescriptor setThreadgroupMemoryLength:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setthreadgroupmemorylength_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setthreadgroupmemorylength_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_settileheight_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setTileHeight:arg0]; } /* method:-[MTLRenderPassDescriptor setTileHeight:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_settileheight_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_settileheight_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_settilewidth_(MTLRenderPassDescriptor * receiver, NSUInteger arg0) { [receiver setTileWidth:arg0]; } /* method:-[MTLRenderPassDescriptor setTileWidth:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_settilewidth_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_settilewidth_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<NSUInteger>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setvisibilityresultbuffer_(MTLRenderPassDescriptor * receiver, id<MTLBuffer> _Nullable arg0) { [receiver setVisibilityResultBuffer:arg0]; } /* method:-[MTLRenderPassDescriptor setVisibilityResultBuffer:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setvisibilityresultbuffer_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setvisibilityresultbuffer_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), (__bridge id<MTLBuffer>)(void *)Nativeint_val(raw1)); CAMLreturn(Val_unit); }
static void prismel_presentation_mtlrenderpassdescriptor_setvisibilityresulttype_(MTLRenderPassDescriptor * receiver, MTLVisibilityResultType arg0) { [receiver setVisibilityResultType:arg0]; } /* method:-[MTLRenderPassDescriptor setVisibilityResultType:] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_setvisibilityresulttype_(value raw0, value raw1) { CAMLparam2(raw0,raw1); prismel_presentation_mtlrenderpassdescriptor_setvisibilityresulttype_((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0), static_cast<MTLVisibilityResultType>(Int64_val(raw1))); CAMLreturn(Val_unit); }
static BOOL prismel_presentation_mtlrenderpassdescriptor_supportcolorattachmentmapping(MTLRenderPassDescriptor * receiver) { return [receiver supportColorAttachmentMapping]; } /* method:-[MTLRenderPassDescriptor supportColorAttachmentMapping] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_supportcolorattachmentmapping(value raw0) { CAMLparam1(raw0); CAMLreturn(Val_bool(prismel_presentation_mtlrenderpassdescriptor_supportcolorattachmentmapping((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_threadgroupmemorylength(MTLRenderPassDescriptor * receiver) { return [receiver threadgroupMemoryLength]; } /* method:-[MTLRenderPassDescriptor threadgroupMemoryLength] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_threadgroupmemorylength(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_threadgroupmemorylength((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_tileheight(MTLRenderPassDescriptor * receiver) { return [receiver tileHeight]; } /* method:-[MTLRenderPassDescriptor tileHeight] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_tileheight(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_tileheight((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static NSUInteger prismel_presentation_mtlrenderpassdescriptor_tilewidth(MTLRenderPassDescriptor * receiver) { return [receiver tileWidth]; } /* method:-[MTLRenderPassDescriptor tileWidth] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_tilewidth(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_tilewidth((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
static MTLVisibilityResultType prismel_presentation_mtlrenderpassdescriptor_visibilityresulttype(MTLRenderPassDescriptor * receiver) { return [receiver visibilityResultType]; } /* method:-[MTLRenderPassDescriptor visibilityResultType] */
extern "C" CAMLprim value caml_prismel_metal_presentation_mtlrenderpassdescriptor_visibilityresulttype(value raw0) { CAMLparam1(raw0); CAMLreturn(caml_copy_int64((int64_t)prismel_presentation_mtlrenderpassdescriptor_visibilityresulttype((__bridge MTLRenderPassDescriptor *)(void *)Nativeint_val(raw0)))); }
