#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
/* exact MTL4 residual mechanical shard */
static void prismel_mtl4_mtl4argumenttable_setresource_atbufferindex_(id<MTL4ArgumentTable> receiver, MTLResourceID a0, NSUInteger a1){[receiver setResource:a0 atBufferIndex:a1];}/*method:-[MTL4ArgumentTable setResource:atBufferIndex:]*/
static void prismel_mtl4_mtl4commandbuffer_popdebuggroup(id<MTL4CommandBuffer> receiver){[receiver popDebugGroup];}/*method:-[MTL4CommandBuffer popDebugGroup]*/
static void prismel_mtl4_mtl4commandencoder_barrierafterencoderstages_beforeencoderstages_visibilityoptions_(id<MTL4CommandEncoder> receiver, MTLStages a0, MTLStages a1, MTL4VisibilityOptions a2){[receiver barrierAfterEncoderStages:a0 beforeEncoderStages:a1 visibilityOptions:a2];}/*method:-[MTL4CommandEncoder barrierAfterEncoderStages:beforeEncoderStages:visibilityOptions:]*/
static void prismel_mtl4_mtl4commandencoder_barrierafterstages_beforequeuestages_visibilityoptions_(id<MTL4CommandEncoder> receiver, MTLStages a0, MTLStages a1, MTL4VisibilityOptions a2){[receiver barrierAfterStages:a0 beforeQueueStages:a1 visibilityOptions:a2];}/*method:-[MTL4CommandEncoder barrierAfterStages:beforeQueueStages:visibilityOptions:]*/
static void prismel_mtl4_mtl4commandencoder_popdebuggroup(id<MTL4CommandEncoder> receiver){[receiver popDebugGroup];}/*method:-[MTL4CommandEncoder popDebugGroup]*/
static CFTimeInterval prismel_mtl4_mtl4commitfeedback_gpuendtime(id<MTL4CommitFeedback> receiver){return [receiver GPUEndTime];}/*method:-[MTL4CommitFeedback GPUEndTime]*/
static CFTimeInterval prismel_mtl4_mtl4commitfeedback_gpustarttime(id<MTL4CommitFeedback> receiver){return [receiver GPUStartTime];}/*method:-[MTL4CommitFeedback GPUStartTime]*/
static void prismel_mtl4_mtl4computecommandencoder_dispatchthreadgroups_threadsperthreadgroup_(id<MTL4ComputeCommandEncoder> receiver, MTLSize a0, MTLSize a1){[receiver dispatchThreadgroups:a0 threadsPerThreadgroup:a1];}/*method:-[MTL4ComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]*/
static void prismel_mtl4_mtl4computecommandencoder_dispatchthreadgroupswithindirectbuffer_threadsperthreadgroup_(id<MTL4ComputeCommandEncoder> receiver, MTLGPUAddress a0, MTLSize a1){[receiver dispatchThreadgroupsWithIndirectBuffer:a0 threadsPerThreadgroup:a1];}/*method:-[MTL4ComputeCommandEncoder dispatchThreadgroupsWithIndirectBuffer:threadsPerThreadgroup:]*/
static void prismel_mtl4_mtl4computecommandencoder_dispatchthreadswithindirectbuffer_(id<MTL4ComputeCommandEncoder> receiver, MTLGPUAddress a0){[receiver dispatchThreadsWithIndirectBuffer:a0];}/*method:-[MTL4ComputeCommandEncoder dispatchThreadsWithIndirectBuffer:]*/
static void prismel_mtl4_mtl4computecommandencoder_setimageblockwidth_height_(id<MTL4ComputeCommandEncoder> receiver, NSUInteger a0, NSUInteger a1){[receiver setImageblockWidth:a0 height:a1];}/*method:-[MTL4ComputeCommandEncoder setImageblockWidth:height:]*/
static MTLStages prismel_mtl4_mtl4computecommandencoder_stages(id<MTL4ComputeCommandEncoder> receiver){return [receiver stages];}/*method:-[MTL4ComputeCommandEncoder stages]*/
static void prismel_mtl4_mtl4computepipelinedescriptor_reset(MTL4ComputePipelineDescriptor * receiver){[receiver reset];}/*method:-[MTL4ComputePipelineDescriptor reset]*/
static NSUInteger prismel_mtl4_mtl4counterheap_count(id<MTL4CounterHeap> receiver){return [receiver count];}/*method:-[MTL4CounterHeap count]*/
static void prismel_mtl4_mtl4counterheap_invalidatecounterrange_(id<MTL4CounterHeap> receiver, NSRange a0){[receiver invalidateCounterRange:a0];}/*method:-[MTL4CounterHeap invalidateCounterRange:]*/
static MTL4CounterHeapType prismel_mtl4_mtl4counterheap_type(id<MTL4CounterHeap> receiver){return [receiver type];}/*method:-[MTL4CounterHeap type]*/
static NSUInteger prismel_mtl4_mtl4counterheapdescriptor_count(MTL4CounterHeapDescriptor * receiver){return [receiver count];}/*method:-[MTL4CounterHeapDescriptor count]*/
static void prismel_mtl4_mtl4counterheapdescriptor_setcount_(MTL4CounterHeapDescriptor * receiver, NSUInteger a0){[receiver setCount:a0];}/*method:-[MTL4CounterHeapDescriptor setCount:]*/
static void prismel_mtl4_mtl4counterheapdescriptor_settype_(MTL4CounterHeapDescriptor * receiver, MTL4CounterHeapType a0){[receiver setType:a0];}/*method:-[MTL4CounterHeapDescriptor setType:]*/
static MTL4CounterHeapType prismel_mtl4_mtl4counterheapdescriptor_type(MTL4CounterHeapDescriptor * receiver){return [receiver type];}/*method:-[MTL4CounterHeapDescriptor type]*/
static void prismel_mtl4_mtl4machinelearningpipelinedescriptor_reset(MTL4MachineLearningPipelineDescriptor * receiver){[receiver reset];}/*method:-[MTL4MachineLearningPipelineDescriptor reset]*/
static NSUInteger prismel_mtl4_mtl4machinelearningpipelinestate_intermediatesheapsize(id<MTL4MachineLearningPipelineState> receiver){return [receiver intermediatesHeapSize];}/*method:-[MTL4MachineLearningPipelineState intermediatesHeapSize]*/
static void prismel_mtl4_mtl4rendercommandencoder_drawindexedprimitives_indexcount_indextype_indexbuffer_indexbufferlength_instancecount_(id<MTL4RenderCommandEncoder> receiver, MTLPrimitiveType a0, NSUInteger a1, MTLIndexType a2, MTLGPUAddress a3, NSUInteger a4, NSUInteger a5){[receiver drawIndexedPrimitives:a0 indexCount:a1 indexType:a2 indexBuffer:a3 indexBufferLength:a4 instanceCount:a5];}/*method:-[MTL4RenderCommandEncoder drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferLength:instanceCount:]*/
static void prismel_mtl4_mtl4rendercommandencoder_drawmeshthreadgroupswithindirectbuffer_threadsperobjectthreadgroup_threadspermeshthreadgroup_(id<MTL4RenderCommandEncoder> receiver, MTLGPUAddress a0, MTLSize a1, MTLSize a2){[receiver drawMeshThreadgroupsWithIndirectBuffer:a0 threadsPerObjectThreadgroup:a1 threadsPerMeshThreadgroup:a2];}/*method:-[MTL4RenderCommandEncoder drawMeshThreadgroupsWithIndirectBuffer:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:]*/
static void prismel_mtl4_mtl4rendercommandencoder_drawmeshthreads_threadsperobjectthreadgroup_threadspermeshthreadgroup_(id<MTL4RenderCommandEncoder> receiver, MTLSize a0, MTLSize a1, MTLSize a2){[receiver drawMeshThreads:a0 threadsPerObjectThreadgroup:a1 threadsPerMeshThreadgroup:a2];}/*method:-[MTL4RenderCommandEncoder drawMeshThreads:threadsPerObjectThreadgroup:threadsPerMeshThreadgroup:]*/
static void prismel_mtl4_mtl4rendercommandencoder_drawprimitives_vertexstart_vertexcount_instancecount_(id<MTL4RenderCommandEncoder> receiver, MTLPrimitiveType a0, NSUInteger a1, NSUInteger a2, NSUInteger a3){[receiver drawPrimitives:a0 vertexStart:a1 vertexCount:a2 instanceCount:a3];}/*method:-[MTL4RenderCommandEncoder drawPrimitives:vertexStart:vertexCount:instanceCount:]*/
static void prismel_mtl4_mtl4rendercommandencoder_setobjectthreadgroupmemorylength_atindex_(id<MTL4RenderCommandEncoder> receiver, NSUInteger a0, NSUInteger a1){[receiver setObjectThreadgroupMemoryLength:a0 atIndex:a1];}/*method:-[MTL4RenderCommandEncoder setObjectThreadgroupMemoryLength:atIndex:]*/
static void prismel_mtl4_mtl4rendercommandencoder_setthreadgroupmemorylength_offset_atindex_(id<MTL4RenderCommandEncoder> receiver, NSUInteger a0, NSUInteger a1, NSUInteger a2){[receiver setThreadgroupMemoryLength:a0 offset:a1 atIndex:a2];}/*method:-[MTL4RenderCommandEncoder setThreadgroupMemoryLength:offset:atIndex:]*/
static void prismel_mtl4_mtl4renderpipelinebinaryfunctionsdescriptor_reset(MTL4RenderPipelineBinaryFunctionsDescriptor * receiver){[receiver reset];}/*method:-[MTL4RenderPipelineBinaryFunctionsDescriptor reset]*/
static void prismel_mtl4_mtl4renderpipelinecolorattachmentdescriptor_reset(MTL4RenderPipelineColorAttachmentDescriptor * receiver){[receiver reset];}/*method:-[MTL4RenderPipelineColorAttachmentDescriptor reset]*/
static void prismel_mtl4_mtl4renderpipelinecolorattachmentdescriptorarray_reset(MTL4RenderPipelineColorAttachmentDescriptorArray * receiver){[receiver reset];}/*method:-[MTL4RenderPipelineColorAttachmentDescriptorArray reset]*/
