#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
static void qualify(id<MTLRenderCommandEncoder>e,id<MTLBuffer>b,id<MTLSamplerState>s,id<MTLCounterSampleBuffer>c,MTLLogicalToPhysicalColorAttachmentMap*m){if(!e)return;id<MTLBuffer>bs[1]={b};id<MTLSamplerState>ss[1]={s};NSUInteger os[1]={0},st[1]={4};float lo[1]={0},hi[1]={1};uint32_t bytes=0;
[e dispatchThreadsPerTile:MTLSizeMake(1,1,1)];[e drawIndexedPatches:1 patchIndexBuffer:nil patchIndexBufferOffset:0 controlPointIndexBuffer:b controlPointIndexBufferOffset:0 indirectBuffer:b indirectBufferOffset:0];[e drawIndexedPatches:1 patchStart:0 patchCount:1 patchIndexBuffer:nil patchIndexBufferOffset:0 controlPointIndexBuffer:b controlPointIndexBufferOffset:0 instanceCount:1 baseInstance:0];
[e drawMeshThreadgroups:MTLSizeMake(1,1,1) threadsPerObjectThreadgroup:MTLSizeMake(1,1,1) threadsPerMeshThreadgroup:MTLSizeMake(1,1,1)];[e drawMeshThreadgroupsWithIndirectBuffer:b indirectBufferOffset:0 threadsPerObjectThreadgroup:MTLSizeMake(1,1,1) threadsPerMeshThreadgroup:MTLSizeMake(1,1,1)];[e drawMeshThreads:MTLSizeMake(1,1,1) threadsPerObjectThreadgroup:MTLSizeMake(1,1,1) threadsPerMeshThreadgroup:MTLSizeMake(1,1,1)];
[e drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];[e drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3 instanceCount:1 baseInstance:0];[e sampleCountersInBuffer:c atSampleIndex:0 withBarrier:YES];[e setColorAttachmentMap:m];[e setFragmentBufferOffset:0 atIndex:0];[e setFragmentBuffers:bs offsets:os withRange:NSMakeRange(0,1)];[e setFragmentSamplerStates:ss lodMinClamps:lo lodMaxClamps:hi withRange:NSMakeRange(0,1)];
[e setMeshBufferOffset:0 atIndex:0];[e setMeshBuffers:bs offsets:os withRange:NSMakeRange(0,1)];[e setMeshSamplerStates:ss lodMinClamps:lo lodMaxClamps:hi withRange:NSMakeRange(0,1)];[e setObjectBufferOffset:0 atIndex:0];[e setObjectBuffers:bs offsets:os withRange:NSMakeRange(0,1)];[e setObjectSamplerStates:ss lodMinClamps:lo lodMaxClamps:hi withRange:NSMakeRange(0,1)];[e setObjectThreadgroupMemoryLength:4 atIndex:0];[e setThreadgroupMemoryLength:4 offset:0 atIndex:0];
[e setTileBufferOffset:0 atIndex:0];[e setTileBuffers:bs offsets:os withRange:NSMakeRange(0,1)];[e setTileSamplerStates:ss lodMinClamps:lo lodMaxClamps:hi withRange:NSMakeRange(0,1)];[e setVertexBufferOffset:0 atIndex:0];[e setVertexBufferOffset:0 attributeStride:4 atIndex:0];[e setVertexBuffers:bs offsets:os attributeStrides:st withRange:NSMakeRange(0,1)];[e setVertexBuffers:bs offsets:os withRange:NSMakeRange(0,1)];[e setVertexBytes:&bytes length:sizeof(bytes) attributeStride:sizeof(bytes) atIndex:0];[e setVertexSamplerStates:ss lodMinClamps:lo lodMaxClamps:hi withRange:NSMakeRange(0,1)];}
int main(){@autoreleasepool{id<MTLDevice>d=MTLCreateSystemDefaultDevice();if(!d)return 77;NSError*error=nil;NSString*src=@"#include <metal_stdlib>\nusing namespace metal; vertex float4 v(uint i [[vertex_id]]) { return float4(i==1?1:-1,i==2?1:-1,0,1); } fragment float4 f(){return float4(1);}";id<MTLLibrary>l=[d newLibraryWithSource:src options:nil error:&error];MTLRenderPipelineDescriptor*p=[MTLRenderPipelineDescriptor new];p.vertexFunction=[l newFunctionWithName:@"v"];p.fragmentFunction=[l newFunctionWithName:@"f"];p.colorAttachments[0].pixelFormat=MTLPixelFormatRGBA8Unorm;id<MTLRenderPipelineState>ps=[d newRenderPipelineStateWithDescriptor:p error:&error];if(!ps)return 2;MTLTextureDescriptor*td=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm width:4 height:4 mipmapped:NO];td.usage=MTLTextureUsageRenderTarget;id<MTLTexture>t=[d newTextureWithDescriptor:td];MTLRenderPassDescriptor*rp=[MTLRenderPassDescriptor renderPassDescriptor];rp.colorAttachments[0].texture=t;rp.colorAttachments[0].loadAction=MTLLoadActionClear;rp.colorAttachments[0].storeAction=MTLStoreActionStore;id<MTLCommandBuffer>cb=[[d newCommandQueue] commandBuffer];id<MTLRenderCommandEncoder>e=[cb renderCommandEncoderWithDescriptor:rp];[e setRenderPipelineState:ps];[e drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];[e endEncoding];[cb commit];[cb waitUntilCompleted];qualify(nil,nil,nil,nil,nil);return cb.status==MTLCommandBufferStatusCompleted?0:3;}}
