(test
 (name test_runtime_next_parity)
 (modules test_runtime_next_parity)
 (libraries prismel_runtime_next_sketch)
 (link_flags -linkall)
 (action
  (setenv PRISMEL_TEST_RUNTIME_NEXT_PARITY 1 (run %{test}))))

(test
 (name test_runtime_next_resources)
 (modules test_runtime_next_resources)
 (libraries prismel_runtime_next_sketch)
 (link_flags -linkall)
 (action
  (setenv PRISMEL_TEST_RUNTIME_NEXT_RESOURCES 1 (run %{test}))))

(test
 (name test_runtime_next_canvas)
 (modules test_runtime_next_canvas)
 (libraries prismel_runtime_next_sketch)
 (link_flags -linkall)
 (action
  (setenv PRISMEL_TEST_RUNTIME_NEXT_CANVAS 1 (run %{test}))))

(test
 (name test_runtime_next_image_text)
 (modules test_runtime_next_image_text)
 (libraries prismel_runtime_next_sketch)
 (link_flags -linkall)
 (action
  (setenv PRISMEL_TEST_RUNTIME_NEXT_IMAGE_TEXT 1 (run %{test}))))
