type load = Load | Clear | Dont_care
type store = Store | Discard | Resolve
type rect = { x:int; y:int; width:int; height:int }
type cull = Cull_none | Cull_front | Cull_back
type comparison = Never | Less | Equal | Less_equal | Greater | Not_equal | Greater_equal | Always
type stencil_operation = Keep | Zero | Replace | Increment_clamp | Decrement_clamp | Invert | Increment_wrap | Decrement_wrap
type stencil_face = { compare:comparison; stencil_fail:stencil_operation; depth_fail:stencil_operation; pass:stencil_operation; read_mask:int32; write_mask:int32 }
type stencil_state = { front:stencil_face; back:stencil_face; front_reference:int32; back_reference:int32 }
type primitive = Point_list | Line_list | Triangle_list | Triangle_strip
type index_type = Uint16 | Uint32
