(library
 (name prismel_next_api)
 (public_name prismel.prismel_next_api)
 (modules vec2 vec3 color math mat3 mat4 quat rand noise fog3 light material
  node3 path parallel texture shader3 compute3 input event frame time image
  canvas font audio assets mesh camera easy_camera transform_feedback3 shadow3
  scene3 scene3_raster2_lowering scene3_raster2_resources framebuffer3 render3)
 (libraries domainslib prismel_next_resources runtime_next_input raster2 unix))

(test
 (name test_prismel_next_api)
 (modules test_prismel_next_api)
 (libraries prismel_next_api))

(test
 (name test_prismel_next_api_batch_d)
 (modules test_prismel_next_api_batch_d)
 (libraries prismel_next_api prismel_next_resources))

(test
 (name test_prismel_next_api_batch_a)
 (modules test_prismel_next_api_batch_a)
 (libraries prismel_next_api))

(test
 (name test_prismel_next_api_batch_b)
 (modules test_prismel_next_api_batch_b)
 (libraries prismel_next_api))

(test
 (name test_prismel_next_api_batch_c)
 (modules test_prismel_next_api_batch_c)
 (libraries prismel_next_api runtime_next_input unix))

(test
 (name test_prismel_next_api_batch_e)
 (modules test_prismel_next_api_batch_e)
 (libraries prismel_next_api)
 (action (setenv SDL_AUDIODRIVER dummy (run %{test}))))

(test
 (name test_prismel_next_api_batch_f)
 (modules test_prismel_next_api_batch_f)
 (libraries prismel_next_api))
