(lang dune 3.17)

(name ocaml_graphics_test)

(generate_opam_files true)

(source
 (github nexo-tech/ocaml_graphics_test))

(authors "Oleg Pustovit <oleg@nexo.sh>")

(maintainers "Oleg Pustovit <oleg@nexo.sh>")

(license LICENSE)

(documentation https://nexo.sh/ocaml_graphics_test)

(package
 (name ocaml_graphics_test)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("ocaml" "graphics" "test")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
