module P = Prismel
module Lower = Prismel__Scene3_raster2_lowering
module Description = Prismel__Scene_description
module Native = Prismel__Scene_ogpu_renderer

let get = function Ok value -> value | Error _ -> failwith "Scene3 qualification error"
let resources : Lower.resources = { texture=(fun _->Error Lower.Texture_error);shadow=(fun _->Error Lower.Shadow_error) }
let camera=P.Camera.orthographic~height:2.~at:(P.Vec3.create 0. 0. 2.)~target:P.Vec3.zero()
let vertices=[P.Vec3.create(-0.75)(-0.75)0.;P.Vec3.create 0.75(-0.75)0.;P.Vec3.create 0.75 0.75 0.;P.Vec3.create(-0.75)0.75 0.]
let normals=List.init 4(fun _->P.Vec3.unit_z)
let reversed=List.init 4(fun _->P.Vec3.create 0. 0.(-1.))
let sources=P.Mesh.["points",Points,[0;1;2;3];"lines",Lines,[0;1;1;2;2;3];"line-strip",Line_strip,[0;1;2;3];"line-loop",Line_loop,[0;1;2;3];"triangles",Triangles,[0;1;2;0;2;3];"triangle-strip",Triangle_strip,[0;1;3;2];"triangle-fan",Triangle_fan,[0;1;2;3]]
let modes=P.Scene3.["faces",Faces;"wireframe",Wireframe;"vertices",Vertices]
let lower scene=get(Lower.lower_view3d~resources~default_viewport:(0,0,32,32)(Description.View3d(camera,scene,Some(0,0,32,32))))
let raster (prepared:Lower.prepared)=let color=get(Raster2.Surface.create~width:32~height:32())and depth=get(Raster2.Depth_stencil.create~width:32~height:32())in let target:Raster2.Scene3_consumer.target={color;depth=Some depth;multisample=None}in get(Raster2.Scene3_consumer.render~target~clear:0x000000ffl~clear_depth:prepared.Lower.clear_depth~clear_stencil:prepared.clear_stencil~draws:prepared.draws);Bytes.copy(Raster2.Surface.bytes color)
let native runtime (prepared:Lower.prepared)=let draws=Array.to_list prepared.Lower.draws|>List.mapi(fun index draw->let rendered,state=Native.draw3 draw in let rendered={rendered with Scene_execution.state={rendered.state with depth_clear=prepared.clear_depth;depth_load=(if index=0 then Ogpu.Render_pass.Clear else Load)}}in let family=match rendered.state.stencil_state with None->Scene_execution.Scene3|Some _->Scene3_stencil in family,Native.pipeline_blend state.blend,None,None,prepared.samples,rendered)in ignore(get(Runtime_next.render_sampled_resources runtime draws));get(Runtime_next.read_pixels runtime~bytes_per_row:128)
let mismatch a b=let count=ref 0 in for index=0 to min(Bytes.length a)(Bytes.length b)-1 do if abs(Char.code(Bytes.get a index)-Char.code(Bytes.get b index))>3 then incr count done;!count
let expected_gap topology mode=match topology,mode with"points",_->1930|"lines",("faces"|"wireframe")->1882|"lines","vertices"->1456|"line-strip",("faces"|"wireframe")->1942|"line-strip","vertices"->1930|"line-loop",("faces"|"wireframe")->2200|"line-loop","vertices"->1930|"triangles","faces"->448|"triangles","wireframe"->1954|"triangles","vertices"->2392|"triangle-strip","faces"->1648|"triangle-strip","wireframe"->2236|"triangle-strip","vertices"->1918|"triangle-fan","faces"->1552|"triangle-fan","wireframe"->2140|"triangle-fan","vertices"->1930|_->failwith"missing topology/mode golden"
let ()=match Runtime_next.create~width:32~height:32 with Error _->print_endline"Scene3 native qualification: skipped (no M1/Metal)"|Ok runtime->let gaps=ref[]in let qualify label golden mesh mode shading=let material=P.Material.unlit P.Color.white in let scene=P.Scene3.create[P.Scene3.with_raster(P.Scene3.raster_state~line_width:3.~point_size:5.())[P.Scene3.mesh~material~mode~cull:P.Scene3.Cull_none~shading mesh]]in let prepared=lower scene and terminal=ref None in let expected=raster prepared in for frame=1 to 600 do let actual=native runtime prepared in if List.mem frame[1;2;60;600]then let differences=mismatch expected actual in if differences<>golden then failwith(Printf.sprintf"%s frame %d parity golden changed: %d <> %d"label frame differences golden);if differences<>0 then gaps:=(label,frame,differences)::!gaps;terminal:=Some actual done;ignore!terminal in List.iter(fun(name,topology,indices)->List.iter(fun(mode_name,mode)->let mesh=P.Mesh.create_exn~mode:topology~indices~normals vertices and golden=expected_gap name mode_name in qualify(name^"/"^mode_name^"/smooth")golden mesh mode P.Scene3.Smooth;qualify(name^"/"^mode_name^"/flat")golden mesh mode P.Scene3.Flat)modes)sources;let reversed_mesh=P.Mesh.create_exn~mode:P.Mesh.Triangles~indices:[0;1;2;0;2;3]~normals:reversed vertices in qualify"triangles/faces/reversed-authored-normals"448 reversed_mesh P.Scene3.Faces P.Scene3.Smooth;get(Runtime_next.destroy runtime);if!gaps=[]then print_endline"Scene3 native qualification: all topology/mode/shading pixels match Raster2"else(List.rev!gaps|>List.iter(fun(label,frame,count)->Printf.eprintf"GAP %s frame=%d differing_channels=%d\n"label frame count);Printf.printf"Scene3 native qualification: %d stable explicit parity gaps\n"(List.length!gaps))
