(library
 (name scene_execution)
 (public_name prismel.scene_execution)
 (modules scene_execution scene_attachment_pool)
 (private_modules scene_attachment_pool)
 (libraries ogpu))

(test
 (name test_prepared_scene3)
 (modules test_prepared_scene3)
 (libraries scene_execution ogpu))

(test
 (name test_automatic_scratch)
 (modules test_automatic_scratch)
 (libraries scene_execution ogpu))

(test
 (name test_offscreen_metal)
 (modules test_offscreen_metal)
 (libraries scene_execution ogpu ogpu_metal metal))
