/* Generated by prismel-sdl3-extension-clang-inventory-v2; do not edit. */
#ifndef PRISMEL_SDL3_TTF_GENERATED_ABI_H
#define PRISMEL_SDL3_TTF_GENERATED_ABI_H
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3/SDL.h>
_Static_assert(SDL_TTF_MAJOR_VERSION == 3, "SDL3_ttf major changed");
_Static_assert(SDL_TTF_MINOR_VERSION == 2, "SDL3_ttf minor changed");
_Static_assert(SDL_TTF_MICRO_VERSION == 2, "SDL3_ttf patch changed");
typedef int (SDLCALL *prismel_ttf_version_fn)(void);
typedef bool (SDLCALL *prismel_ttf_init_fn)(void);
typedef void (SDLCALL *prismel_ttf_quit_fn)(void);
typedef TTF_Font * (SDLCALL *prismel_ttf_open_font_fn)(const char *, float);
typedef void (SDLCALL *prismel_ttf_close_font_fn)(TTF_Font *);
typedef bool (SDLCALL *prismel_ttf_size_fn)(TTF_Font *, const char *, size_t, int *, int *);
typedef SDL_Surface * (SDLCALL *prismel_ttf_render_fn)(TTF_Font *, const char *, size_t, SDL_Color);
_Static_assert(_Generic(&TTF_Version, prismel_ttf_version_fn: 1, default: 0),
  "TTF_Version signature/calling convention changed");
_Static_assert(_Generic(&TTF_Init, prismel_ttf_init_fn: 1, default: 0),
  "TTF_Init signature/calling convention changed");
_Static_assert(_Generic(&TTF_Quit, prismel_ttf_quit_fn: 1, default: 0),
  "TTF_Quit signature/calling convention changed");
_Static_assert(_Generic(&TTF_OpenFont, prismel_ttf_open_font_fn: 1, default: 0),
  "TTF_OpenFont signature/calling convention changed");
_Static_assert(_Generic(&TTF_CloseFont, prismel_ttf_close_font_fn: 1, default: 0),
  "TTF_CloseFont signature/calling convention changed");
_Static_assert(_Generic(&TTF_GetStringSize, prismel_ttf_size_fn: 1, default: 0),
  "TTF_GetStringSize signature/calling convention changed");
_Static_assert(_Generic(&TTF_RenderText_Blended, prismel_ttf_render_fn: 1, default: 0),
  "TTF_RenderText_Blended signature/calling convention changed");
#endif
