(* Generated by prismel-sdl3-extension-clang-inventory-v1; do not edit. *)
type version = { major : int; minor : int; patch : int }

let generator_version = "prismel-sdl3-extension-clang-inventory-v1"
let header_version = { major = 3; minor = 2; patch = 2 }
let stable_headers = true
let header_sha256 = "4cfa5c13c68e87de6d513b1ae297055c8877432aa140d49dbcb29252b87701ed"
let clang_version = "Apple clang version 21.0.0 (clang-2100.1.1.101)"
let target_triple = "arm64-apple-darwin25.4.0"
let function_count = 117
let safe_function_count = 15
