/* Generated by prismel-sdl3-extension-clang-inventory-v2; do not edit. */
#ifndef PRISMEL_SDL3_IMAGE_GENERATED_ABI_H
#define PRISMEL_SDL3_IMAGE_GENERATED_ABI_H
#include <SDL3_image/SDL_image.h>
#include <SDL3/SDL.h>
_Static_assert(SDL_IMAGE_MAJOR_VERSION == 3, "SDL3_image major changed");
_Static_assert(SDL_IMAGE_MINOR_VERSION == 4, "SDL3_image minor changed");
_Static_assert(SDL_IMAGE_MICRO_VERSION == 4, "SDL3_image patch changed");
typedef int (SDLCALL *prismel_img_version_fn)(void);
typedef SDL_Surface * (SDLCALL *prismel_img_load_fn)(const char *);
typedef SDL_Surface * (SDLCALL *prismel_img_load_io_fn)(SDL_IOStream *, bool);
typedef SDL_Surface * (SDLCALL *prismel_img_load_typed_io_fn)(SDL_IOStream *, bool, const char *);
_Static_assert(_Generic(&IMG_Version, prismel_img_version_fn: 1, default: 0),
  "IMG_Version signature/calling convention changed");
_Static_assert(_Generic(&IMG_Load, prismel_img_load_fn: 1, default: 0),
  "IMG_Load signature/calling convention changed");
_Static_assert(_Generic(&IMG_Load_IO, prismel_img_load_io_fn: 1, default: 0),
  "IMG_Load_IO signature/calling convention changed");
_Static_assert(_Generic(&IMG_LoadTyped_IO, prismel_img_load_typed_io_fn: 1, default: 0),
  "IMG_LoadTyped_IO signature/calling convention changed");
#endif
