(* Generated by prismel-sdl3-extension-clang-inventory-v1; do not edit. *)
type version = { major : int; minor : int; patch : int }

let generator_version = "prismel-sdl3-extension-clang-inventory-v1"
let header_version = { major = 3; minor = 4; patch = 4 }
let stable_headers = true
let header_sha256 = "3d794e35279ffa3dc4131c907f5ba243036b62d4902d7a7863888769aa7d4356"
let clang_version = "Apple clang version 21.0.0 (clang-2100.1.1.101)"
let target_triple = "arm64-apple-darwin25.4.0"
let function_count = 102
let safe_function_count = 4
