(library
 (name flow)
 (public_name prismel.flow)
 (modules diagnostic context symbol port_type expr value_kind graph sexp check)
 (libraries param))

(test
 (name test_value_core)
 (modules test_value_core)
 (libraries flow param))

(test
 (name test_expr)
 (modules test_expr)
 (libraries flow))

(test
 (name test_value_graph)
 (modules test_value_graph)
 (libraries flow param))

(test
 (name test_sexp)
 (modules test_sexp)
 (libraries flow))

(test
 (name test_check)
 (modules test_check)
 (libraries flow param))
