(library
 (name flow)
 (public_name rays.flow)
 (modules diagnostic context symbol port_type check syntax ty lisp macro workspace eval)
 (libraries param))

(test
 (name test_value_core)
 (modules test_value_core)
 (libraries flow param))

(test
 (name test_check)
 (modules test_check)
 (libraries flow param))

(test
 (name test_syntax)
 (modules test_syntax)
 (libraries flow))

(test
 (name test_lisp)
 (modules test_lisp)
 (deps (glob_files ../../specification/workspace/cases/*.lisp))
 (libraries flow))

(test
 (name test_ty)
 (modules test_ty)
 (libraries flow))

(test
 (name test_macro)
 (modules test_macro)
 (libraries flow))

(test
 (name test_workspace)
 (modules test_workspace)
 (deps
  (glob_files ../../specification/workspace/cases/*.lisp)
  ../sop_catalog/flow_manifest.sexp)
 (libraries flow param))

(test
 (name test_workspace_eval)
 (modules test_workspace_eval)
 (deps
  (glob_files ../../specification/workspace/cases/*.lisp)
  ../sop_catalog/flow_manifest.sexp)
 (libraries flow param))
