(executable
 (name codemod)
 (modules codemod metal_registry result_bind open_domains)
 (libraries compiler-libs.common str))

(rule
 (alias runtest)
 (action (run %{exe:codemod.exe} metal-registry --self-test)))

(rule
 (alias runtest)
 (action (run %{exe:codemod.exe} result-bind --self-test %{exe:../../ppx/result_bind/result_bind_ppx.exe})))

(rule
 (alias runtest)
 (action (run %{exe:codemod.exe} rename --self-test)))

(rule
 (alias runtest)
 (action (run %{exe:codemod.exe} open-domains --self-test)))
