(library
 (name editor_core)
 (public_name prismel.editor_core)
 (modules editor_core store)
 (libraries param prismel yojson unix))

(test
 (name test_history)
 (modules test_history)
 (libraries editor_core prismel))

(test
 (name test_store)
 (modules test_store)
 (libraries editor_core prismel yojson unix))
