(* Generated by prismel-sdl3-extension-clang-inventory-v2; do not edit. *)
type version = { major : int; minor : int; patch : int }

let generator_version = "prismel-sdl3-extension-clang-inventory-v2"
let header_version = { major = 3; minor = 2; patch = 4 }
let stable_headers = true
let header_sha256 = "77be3b4fc5156e63fdad4e71eebf2a80ab3fae27f07f7de79923257a909c69a5"
let clang_version = "Apple clang version 21.0.0 (clang-2100.1.1.101)"
let target_triple = "arm64-apple-darwin25.4.0"
let function_count = 94
let safe_function_count = 30
