/* Generated by prismel-sdl3-extension-clang-inventory-v1; do not edit. */
#ifndef PRISMEL_SDL3_MIXER_GENERATED_ABI_H
#define PRISMEL_SDL3_MIXER_GENERATED_ABI_H
#include <SDL3_mixer/SDL_mixer.h>
#include <SDL3/SDL.h>
_Static_assert(SDL_MIXER_MAJOR_VERSION == 3, "SDL3_mixer major changed");
_Static_assert(SDL_MIXER_MINOR_VERSION == 2, "SDL3_mixer minor changed");
_Static_assert(SDL_MIXER_MICRO_VERSION == 4, "SDL3_mixer patch changed");
typedef int (SDLCALL *prismel_mix_version_fn)(void);
typedef bool (SDLCALL *prismel_mix_init_fn)(void);
typedef void (SDLCALL *prismel_mix_quit_fn)(void);
typedef MIX_Mixer * (SDLCALL *prismel_mix_create_device_fn)(SDL_AudioDeviceID, const SDL_AudioSpec *);
typedef MIX_Mixer * (SDLCALL *prismel_mix_create_fn)(const SDL_AudioSpec *);
typedef MIX_Audio * (SDLCALL *prismel_mix_load_fn)(MIX_Mixer *, const char *, bool);
typedef MIX_Track * (SDLCALL *prismel_mix_create_track_fn)(MIX_Mixer *);
typedef bool (SDLCALL *prismel_mix_play_track_fn)(MIX_Track *, SDL_PropertiesID);
typedef int (SDLCALL *prismel_mix_generate_fn)(MIX_Mixer *, void *, int);
_Static_assert(_Generic(&MIX_Version, prismel_mix_version_fn: 1, default: 0),
  "MIX_Version signature/calling convention changed");
_Static_assert(_Generic(&MIX_Init, prismel_mix_init_fn: 1, default: 0),
  "MIX_Init signature/calling convention changed");
_Static_assert(_Generic(&MIX_Quit, prismel_mix_quit_fn: 1, default: 0),
  "MIX_Quit signature/calling convention changed");
_Static_assert(_Generic(&MIX_CreateMixerDevice, prismel_mix_create_device_fn: 1, default: 0),
  "MIX_CreateMixerDevice signature/calling convention changed");
_Static_assert(_Generic(&MIX_CreateMixer, prismel_mix_create_fn: 1, default: 0),
  "MIX_CreateMixer signature/calling convention changed");
_Static_assert(_Generic(&MIX_LoadAudio, prismel_mix_load_fn: 1, default: 0),
  "MIX_LoadAudio signature/calling convention changed");
_Static_assert(_Generic(&MIX_CreateTrack, prismel_mix_create_track_fn: 1, default: 0),
  "MIX_CreateTrack signature/calling convention changed");
_Static_assert(_Generic(&MIX_PlayTrack, prismel_mix_play_track_fn: 1, default: 0),
  "MIX_PlayTrack signature/calling convention changed");
_Static_assert(_Generic(&MIX_Generate, prismel_mix_generate_fn: 1, default: 0),
  "MIX_Generate signature/calling convention changed");
#endif
