(library
 (name rdk_spatial)
 (public_name rays.rdk.spatial)
 (libraries rdk_core rdk_exact rays_math)
 (flags (:standard -open Rdk_core -open Rdk_exact))
 (private_modules )
 (modules spatial_index surface_index bounds3_index proximity_index linear_piece_index point_clusters point_snap triangle_intersection curve_intersection))
