type stats={pipeline_cache_entries:int;mesh_cache_entries:int;uploaded_bytes:int64}
type frame_facts={logical_width:int;logical_height:int;drawable_width:int;drawable_height:int;pixel_scale_x:float;pixel_scale_y:float}
type t={window:Sdl3.Window.t;view:Sdl3.Metal_view.t;renderer:Scene_execution.t;cache:Ogpu_metal.Pipeline.cache;mutable facts:frame_facts;mutable dead:bool}
let error op text=Error(Ogpu.Error.make op Ogpu.Error.Invalid_state text)
let sdl op=function Ok x->Ok x|Error e->error op(Format.asprintf"%a"Sdl3.pp_error e)
let metal op=function Ok x->Ok x|Error e->error op(Format.asprintf"%a"Metal.pp_error e)
let facts window=match Sdl3.Window.size window,Sdl3.Window.size_in_pixels window with Ok(lw,lh),Ok(dw,dh)when lw>0&&lh>0&&dw>0&&dh>0->Ok{logical_width=lw;logical_height=lh;drawable_width=dw;drawable_height=dh;pixel_scale_x=float dw/.float lw;pixel_scale_y=float dh/.float lh}|Error e,_->sdl"Runtime_next.facts"(Error e)|_,Error e->sdl"Runtime_next.facts"(Error e)|_->error"Runtime_next.facts""window dimensions are invalid"
let source={|#include <metal_stdlib>
using namespace metal;
struct V { float4 position [[position]]; };
struct Input { float2 position; uint color; uint reserved; };
struct Out { float4 position [[position]]; float4 color; };
vertex Out scene_vertex(uint i [[vertex_id]], const device Input *input [[buffer(0)]]) { Out v;v.position=float4(input[i].position,0.,1.);uint c=input[i].color;v.color=float4(float((c>>24)&255),float((c>>16)&255),float((c>>8)&255),float(c&255))/255.;return v; }
fragment float4 scene_fragment(Out value [[stage_in]]){return value.color;}
|}
let create ~width ~height=let op="Runtime_next.create"in if width<=0||height<=0 then Error(Ogpu.Error.make op Invalid_argument"dimensions must be positive")else match sdl op(Sdl3.Init.init[Sdl3.Init.Video])with Error _ as e->e|Ok()->match sdl op(Sdl3.Window.create~title:"Prismel native-next"~width~height~flags:[Hidden;Metal;High_pixel_density]())with Error _ as e->e|Ok window->match sdl op(Sdl3.Metal_view.create window)with Error e->ignore(Sdl3.Window.destroy window);Error e|Ok view->match sdl op(Sdl3.Metal_view.layer view),Ogpu_metal.Device.system_default()with Error e,_->Error e|_,Error e->Error e|Ok token,Ok device->let config=Metal.Metal_layer.default~width~height in match metal op(Metal.Metal_layer.adopt_borrowed(Ogpu_metal.Device.Private.metal device)token config)with Error _ as e->e|Ok layer->let driver,control=Ogpu_metal.Backend.create~device~layer()in let configuration:Ogpu.Surface.configuration={logical_width=width;logical_height=height;physical_width=width;physical_height=height;format=Bgra8_unorm;present_mode=Fifo;max_acquired=2}in let cache=match Ogpu_metal.Pipeline.create_cache~capacity:1 with Ok x->x|Error e->raise(Failure(Ogpu.Error.to_string e))in let make_pipeline backend_device=match Ogpu.Shader.create{backend="metal";label=Some"runtime-next";bytes=Bytes.of_string source;entry_points=[{name="scene_vertex";stage=Vertex};{name="scene_fragment";stage=Fragment}];bindings=[{group=0;binding=0;kind=Storage_buffer;visibility=[Vertex;Fragment]}]}with Error _ as e->e|Ok shader->match Ogpu.Binding.create_layout[{binding=0;kind=Ogpu.Binding.Buffer;visibility=[Ogpu.Binding.Vertex;Ogpu.Binding.Fragment]}]with Error _ as e->e|Ok bindings->match Ogpu.Binding.create_pipeline_layout~device:(Ogpu.Backend.device_handle backend_device)~capabilities:(Ogpu.Backend.capabilities backend_device)[0,bindings]with Error _ as e->e|Ok layout->let descriptor:Ogpu.Pipeline.render_descriptor={backend="metal";label=Some"runtime-next";layout;vertex=shader;vertex_entry="scene_vertex";fragment=Some shader;fragment_entry=Some"scene_fragment";color_format=Rgba8_unorm;depth_format=No_depth;sample_count=1}in match Ogpu_metal.Pipeline.create_render_runtime_msl cache device descriptor with Error _ as e->e|Ok native->Ogpu_metal.Backend.register_pipeline control native;Ok(Ogpu_metal.Pipeline.Private.portable native)in match Scene_execution.create_with_pipeline driver configuration~before_device_destroy:(fun()->Ogpu_metal.Pipeline.clear_cache cache;match Metal.Metal_layer.destroy layer with Ok()->Ok()|Error e->error op(Format.asprintf"%a"Metal.pp_error e))make_pipeline with Error _ as e->e|Ok renderer->match facts window with Error _ as e->e|Ok facts->let actual={configuration with logical_width=facts.logical_width;logical_height=facts.logical_height;physical_width=facts.drawable_width;physical_height=facts.drawable_height}in match Scene_execution.resize renderer actual with Error _ as e->e|Ok()->Ok{window;view;renderer;cache;facts;dead=false}
let scale_rect facts(x,y,w,h)=let edge value logical drawable=value*drawable/logical in let l=edge x facts.logical_width facts.drawable_width and t=edge y facts.logical_height facts.drawable_height and r=edge(x+w)facts.logical_width facts.drawable_width and b=edge(y+h)facts.logical_height facts.drawable_height in(l,t,r-l,b-t)
let map_logical_rect=scale_rect
let render ?clear value draws=if value.dead then Error(Ogpu.Error.make"Runtime_next.render"Stale_handle"runtime is destroyed")else let draws=List.map(fun(draw:Scene_execution.draw)->{draw with state={viewport=scale_rect value.facts draw.state.viewport;scissor=scale_rect value.facts draw.state.scissor}})draws in Scene_execution.render ?clear value.renderer draws
let apply_facts value facts=let configuration:Ogpu.Surface.configuration={logical_width=facts.logical_width;logical_height=facts.logical_height;physical_width=facts.drawable_width;physical_height=facts.drawable_height;format=Bgra8_unorm;present_mode=Fifo;max_acquired=2}in match Scene_execution.resize value.renderer configuration with Error _ as e->e|Ok()->value.facts<-facts;Ok()
let resize value ~width ~height=if value.dead then Error(Ogpu.Error.make"Runtime_next.resize"Stale_handle"runtime is destroyed")else match sdl"Runtime_next.resize"(Sdl3.Window.set_size value.window~width~height)with Error _ as e->e|Ok()->Result.bind(facts value.window)(apply_facts value)
let read_pixels value=Scene_execution.read_pixels value.renderer
let stats value={pipeline_cache_entries=Ogpu_metal.Pipeline.cache_length value.cache;mesh_cache_entries=Scene_execution.cache_entries value.renderer;uploaded_bytes=Scene_execution.upload_bytes value.renderer}
let frame_facts value=value.facts
let handle_window_event value=function Sdl3.Event.Window{change=Resized _;_}->Result.map(fun()->true)(Result.bind(facts value.window)(apply_facts value))|_->Ok false
let destroy value=if value.dead then Ok()else(value.dead<-true;match Scene_execution.destroy value.renderer with Error _ as e->e|Ok()->match sdl"Runtime_next.destroy"(Sdl3.Metal_view.destroy value.view)with Error _ as e->e|Ok()->match sdl"Runtime_next.destroy"(Sdl3.Window.destroy value.window)with Error _ as e->e|Ok()->sdl"Runtime_next.destroy"(Sdl3.Init.quit_subsystems[Sdl3.Init.Video]))
