type t={window:Sdl3.Window.t;view:Sdl3.Metal_view.t;renderer:Scene_execution.t;mutable dead:bool}
let error op text=Error(Ogpu.Error.make op Ogpu.Error.Invalid_state text)
let sdl op=function Ok x->Ok x|Error e->error op(Format.asprintf"%a"Sdl3.pp_error e)
let metal op=function Ok x->Ok x|Error e->error op(Format.asprintf"%a"Metal.pp_error e)
let source={|#include <metal_stdlib>
using namespace metal;
struct V { float4 position [[position]]; };
vertex V scene_vertex(uint i [[vertex_id]]) { constexpr float2 p[3]={{-1.,-1.},{3.,-1.},{-1.,3.}}; V v;v.position=float4(p[i],0.,1.);return v; }
fragment float4 scene_fragment(){return float4(0.25,0.5,0.75,1.);}
|}
let create ~width ~height=let op="Runtime_next.create"in if width<=0||height<=0 then Error(Ogpu.Error.make op Invalid_argument"dimensions must be positive")else match sdl op(Sdl3.Init.init[Sdl3.Init.Video])with Error _ as e->e|Ok()->match sdl op(Sdl3.Window.create~title:"Prismel native-next"~width~height~flags:[Hidden;Metal;High_pixel_density]())with Error _ as e->e|Ok window->match sdl op(Sdl3.Metal_view.create window)with Error e->ignore(Sdl3.Window.destroy window);Error e|Ok view->match sdl op(Sdl3.Metal_view.layer view),Ogpu_metal.Device.system_default()with Error e,_->Error e|_,Error e->Error e|Ok token,Ok device->let config=Metal.Metal_layer.default~width~height in match metal op(Metal.Metal_layer.adopt_borrowed(Ogpu_metal.Device.Private.metal device)token config)with Error _ as e->e|Ok layer->let driver,control=Ogpu_metal.Backend.create~device~layer()in let configuration:Ogpu.Surface.configuration={logical_width=width;logical_height=height;physical_width=width;physical_height=height;format=Bgra8_unorm;present_mode=Fifo;max_acquired=2}in let cache=match Ogpu_metal.Pipeline.create_cache~capacity:1 with Ok x->x|Error e->raise(Failure(Ogpu.Error.to_string e))in let make_pipeline backend_device=match Ogpu.Shader.create{backend="metal";label=Some"runtime-next";bytes=Bytes.of_string source;entry_points=[{name="scene_vertex";stage=Vertex};{name="scene_fragment";stage=Fragment}];bindings=[]}with Error _ as e->e|Ok shader->match Ogpu.Binding.create_layout[]with Error _ as e->e|Ok empty->match Ogpu.Binding.create_pipeline_layout~device:(Ogpu.Backend.device_handle backend_device)~capabilities:(Ogpu.Backend.capabilities backend_device)[0,empty]with Error _ as e->e|Ok layout->let descriptor:Ogpu.Pipeline.render_descriptor={backend="metal";label=Some"runtime-next";layout;vertex=shader;vertex_entry="scene_vertex";fragment=Some shader;fragment_entry=Some"scene_fragment";color_format=Rgba8_unorm;depth_format=No_depth;sample_count=1}in match Ogpu_metal.Pipeline.create_render_runtime_msl cache device descriptor with Error _ as e->e|Ok native->Ogpu_metal.Backend.register_pipeline control native;Ok(Ogpu_metal.Pipeline.Private.portable native)in match Scene_execution.create_with_pipeline driver configuration~before_device_destroy:(fun()->match Metal.Metal_layer.destroy layer with Ok()->Ok()|Error e->error op(Format.asprintf"%a"Metal.pp_error e))make_pipeline with Error _ as e->e|Ok renderer->Ok{window;view;renderer;dead=false}
let render value draws=if value.dead then Error(Ogpu.Error.make"Runtime_next.render"Stale_handle"runtime is destroyed")else Scene_execution.render value.renderer draws
let resize value ~width ~height=if value.dead then Error(Ogpu.Error.make"Runtime_next.resize"Stale_handle"runtime is destroyed")else match sdl"Runtime_next.resize"(Sdl3.Window.set_size value.window~width~height)with Error _ as e->e|Ok()->let configuration:Ogpu.Surface.configuration={logical_width=width;logical_height=height;physical_width=width;physical_height=height;format=Bgra8_unorm;present_mode=Fifo;max_acquired=2}in Scene_execution.resize value.renderer configuration
let read_pixels value=Scene_execution.read_pixels value.renderer
let destroy value=if value.dead then Ok()else(value.dead<-true;match Scene_execution.destroy value.renderer with Error _ as e->e|Ok()->match sdl"Runtime_next.destroy"(Sdl3.Metal_view.destroy value.view)with Error _ as e->e|Ok()->match sdl"Runtime_next.destroy"(Sdl3.Window.destroy value.window)with Error _ as e->e|Ok()->sdl"Runtime_next.destroy"(Sdl3.Init.quit_subsystems[Sdl3.Init.Video]))
