(* prismel-plisp: check, ml, dune and fmt for .plisp sketches (plan W11).
   Stdlib and Arg only; the catalog is the in-process one. *)
module S = Flow.Syntax
module D = Flow.Diagnostic
module Doc = Editor_document.Workspace_doc

let read path = In_channel.with_open_bin path In_channel.input_all

let die fmt = Printf.ksprintf (fun m -> prerr_endline m; exit 1) fmt

let catalog () =
  match Editor_document.Contexts.catalog ~version:Flow_sop.Manifest.version Sop_catalog.Editor.factories with
  | Ok c -> c
  | Error d -> die "prismel-plisp: catalog: %s" (D.to_string d)

let head (f : S.t) = match f.node with S.List ({ S.node = S.Sym h; _ } :: _) -> Some h | _ -> None

(* The checked document and every diagnostic to print. Warnings fail the file
   unless the workspace form carries ^:allow-warnings. *)
let check_text text =
  match S.parse text with
  | Error d -> None, [ d ], true
  | Ok forms ->
      match List.find_opt (fun f -> head f = Some "workspace") forms with
      | None -> None, [ D.error ~code:"E_WORKSPACE" "Expected a (workspace ...) form." ], true
      | Some ws ->
          let allow = List.mem "allow-warnings" ws.meta in
          let catalog = catalog () in
          let checked, ds = Flow.Workspace.check catalog [ ws ] in
          let ds, doc = match checked with
            | None -> ds, None
            | Some _ -> (match Doc.of_text catalog text with  (* layout and settings forms *)
                | Ok doc -> ds, Some doc
                | Error extra -> ds @ extra, None) in
          doc, ds, allow

let check_file path =
  let text = read path in
  let doc, ds, allow = check_text text in
  List.iter (fun d -> prerr_endline (D.report ~file:path ~source:text d)) ds;
  let failed = List.exists (fun (d : D.t) -> d.severity = D.Error || not allow) ds in
  text, (if failed then None else doc)

let check_all files =
  let ok = List.fold_left (fun ok f -> snd (check_file f) <> None && ok) true files in
  if not ok then exit 1

let ml path =
  let text, doc = check_file path in
  if doc = None then exit 1;
  let digest = Editor_document.Contexts.sha256 text in
  let d = Delimiter.make digest text in
  Printf.printf "(* generated by prismel-plisp from %s; do not edit *)\nlet () =\n  Prismel_editor.Workspace.main\n    ~path:%S\n    ~digest:%S\n    ~catalog:%S\n    {%s|%s|%s}\n"
    path path digest (Editor_document.Contexts.catalog_digest Sop_catalog.Editor.factories) d text d

let dune dir =
  let sub name = Filename.concat dir name in
  let sketches = Sys.readdir dir |> Array.to_list |> List.sort compare |> List.filter (fun n ->
    Sys.is_directory (sub n) && Sys.file_exists (Filename.concat (sub n) "sketch.plisp")) in
  List.iter (fun n -> if Sys.file_exists (Filename.concat (sub n) "dune") then
    die "%s has both dune and sketch.plisp; delete %s" (sub n) (Filename.concat (sub n) "dune")) sketches;
  print_string "; generated by prismel-plisp dune sketches; accept changes with dune promote\n";
  List.iter (fun n -> Printf.printf
{|(subdir %s
 (rule
  (target main.ml)
  (deps sketch.plisp (glob_files *.png) (glob_files *.ttf))
  (action (chdir %%{workspace_root} (with-stdout-to %%{target} (run %%{bin:prismel-plisp} ml %%{dep:sketch.plisp})))))
 (executable (name main) (modules main) (libraries prismel_editor))
 (rule (alias smoke-all)
  (action (setenv PRISMEL_MAX_FRAMES 120 (run ./main.exe)))))
|} n) sketches

let fmt path =
  match check_file path with
  | _, Some doc -> print_string (Doc.to_text doc)
  | _, None -> exit 1

let () = match Array.to_list Sys.argv with
  | _ :: "check" :: (_ :: _ as files) -> check_all files
  | [ _; "ml"; f ] -> ml f
  | [ _; "dune"; d ] -> dune d
  | [ _; "fmt"; f ] -> fmt f
  | _ -> die "usage: prismel-plisp check FILE... | ml FILE | dune DIR | fmt FILE"
