(library
 (name rdk_attrib)
 (public_name rays.rdk.attrib)
 (libraries rdk_core rdk_exact rdk_spatial rays_math)
 (flags (:standard -open Rdk_core -open Rdk_exact -open Rdk_spatial))
 (private_modules attribute_blur attribute_combine attribute_copy attribute_enumerate attribute_generate attribute_image attribute_interpolate attribute_promote attribute_transfer)
 (modules attribute_blur attribute_combine attribute_composite attribute_copy attribute_enumerate attribute_fade attribute_generate attribute_image attribute_interpolate attribute_lifecycle attribute_mirror attribute_ops attribute_promote attribute_transfer blend_shapes color_by_height group_ops material_assign))
