/* Browser-only interaction study. The native editor remains PXUI / Metal. */
'use strict';
const M=Workspace,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ast=M.read(M.initial),program=M.compile(ast),scope='geometry',view='graph',selection=new Set(['flower']),groups={},past=[],future=[],returnScope=null,draft=M.initial,dirty=false;
const icons={sop:'◇',scene:'◉',world:'◎',settings:'⚙',editor:'▤',value:'ƒ'};
function current(){return program.graphs.get(scope)||program.defs.get(scope);}
function status(message,error=false){$('#status').textContent=message;$('#status').classList.toggle('error',error);}
function snapshot(){return {source:M.print(ast),groups:structuredClone(groups)};}
function commit(next,message,metadata=groups){
  if(dirty){status('Unapplied Lisp draft. Apply or discard it before changing the document.',true);setView('text');return false;}
  try{const checked=M.compile(next);past.push(snapshot());if(past.length>60)past.shift();future=[];ast=next;program=checked;groups=metadata;draft=M.print(ast);render();status(message);return true;}catch(e){status(e.message,true);return false;}
}
function undo(redo=false){if(dirty){status('Apply or discard the Lisp draft before document undo.',true);return;}const from=redo?future:past,to=redo?past:future;if(!from.length)return;to.push(snapshot());const s=from.pop();ast=M.read(s.source);program=M.compile(ast);groups=s.groups;draft=s.source;render();status(redo?'Redid document edit.':'Undid document edit.');}
function go(name){scope=name;selection=new Set();render();}
function setView(next){view=next;renderProjection();renderToolbar();}
function countCalls(name){let count=0;function walk(x){if(Array.isArray(x)){if(x[0]===name)count++;x.forEach(walk);}}ast.slice(2).forEach(walk);return count;}
function describe(v){if(!v)return 'parameterized';if(['float','int'].includes(v.type))return Number(v.data.toFixed(3)).toString();if(v.type==='text')return v.data;if(v.type==='geometry')return `${v.data.count} petals · r ${v.data.radius}`;return v.type;}
function record(name){return program.records.get((program.defs.has(scope)?'def:':'')+scope+'/'+name);}
function rowData(){const rows=M.bindings(current());if(rows.length)return rows;return [{name:'result',expr:M.body(current()),index:-1}];}
function render(){
  $('#preview-label').textContent=dirty?'Last applied version':'Illustrative 2D output';
  if(!program.graphs.has(scope)&&!program.defs.has(scope))scope=program.graphs.keys().next().value;
  const names=new Set(rowData().map(r=>r.name));selection=new Set([...selection].filter(n=>names.has(n)));
  let previewCall='';
  if(program.defs.has(scope)){
    const owner=returnScope?program.graphs.get(returnScope.scope):[...program.graphs.values()].find(f=>M.bindings(f).some(r=>r.expr?.[0]===scope));
    const call=owner&&M.bindings(owner).find(r=>r.expr?.[0]===scope&&(!returnScope||r.name===returnScope.name));
    if(call){const env=new Map(M.bindings(owner).map(r=>[r.name,program.records.get(owner[1]+'/'+r.name)]));program.inspectCall(call.expr,owner[3],env,owner[1]);previewCall=` · values from ${owner[1]}/${call.name}`;}
  }
  $('#scopes').innerHTML=[...program.graphs].map(([name,f])=>`<button class="nav-item ${name===scope?'active':''}" data-scope="${esc(name)}">${icons[f[3]]} ${esc(name)}<small>${f[3]==='sop'?'geo':''}</small></button>`).join('');
  $('#definitions').innerHTML=[...program.defs].map(([name])=>`<button class="nav-item ${name===scope?'active':''}" data-scope="${esc(name)}">ƒ ${esc(name)}<small>${countCalls(name)} calls</small></button>`).join('')+[...program.macros].map(([name])=>`<button class="nav-item" data-macro="${esc(name)}">✧ ${esc(name)}<small>macro</small></button>`).join('');
  $$('[data-scope]').forEach(b=>b.onclick=()=>{returnScope=null;go(b.dataset.scope);});$$('[data-macro]').forEach(b=>b.onclick=()=>macroDialog(b.dataset.macro));
  $('#breadcrumb').innerHTML=`<span>workspace / </span>${program.defs.has(scope)?'functions / ':''}${esc(scope)}`;
  const f=current();$('#scope-info').innerHTML=program.defs.has(scope)?`<strong>SHARED DEFINITION</strong> · ${countCalls(scope)} calls use this body · ${esc(M.print(f[4]))}${esc(previewCall)}`:`${icons[f[3]]} ${f[3].toUpperCase()} CONTEXT · ${f[3]==='editor'?'Compose panels as typed values. Preview before choosing a layout.':'Select a binding. Its identity follows you across graph and list.'}`;
  renderProjection();renderToolbar();renderInspector();renderPreview();$('#undo').disabled=!past.length;$('#redo').disabled=!future.length;
}
function renderToolbar(){
  $$('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===view)));
  $('#group').disabled=selection.size===0||view==='text';$('#extract').disabled=selection.size===0||program.defs.has(scope)||view==='text';
  $('#return').hidden=!returnScope;$('#selection-note').textContent=selection.size?`${selection.size} selected`:'';
  $('#guide-text').textContent=program.defs.has(scope)?'Shared changes affect every call. Return to the call to edit only its arguments.':'Click to select · Shift-click to select a chain · Double-click a function to enter';
}
function select(name,multi=false){if(multi){selection.has(name)?selection.delete(name):selection.add(name);}else selection=new Set([name]);renderProjection();renderToolbar();renderInspector();}
function renderProjection(){
  ['graph','list','text'].forEach(v=>$('#'+v+'-view').hidden=v!==view);
  if(view==='text'){$('#source').value=draft;const name=[...selection][0],start=draft.indexOf(`(${current()[0]} ${scope} `),at=name?draft.indexOf(name+' ',start):-1;if(at>=0){$('#source').setSelectionRange(at,at+name.length);$('#source').scrollTop=Math.max(0,(draft.slice(0,at).split('\n').length-4)*20.4);}return;}
  const rows=rowData();
  if(view==='list'){$('#list-view').innerHTML=`<p class="hint">Ordered bindings · same selection and inspector as the graph</p>`+rows.map(r=>`<button class="list-row ${selection.has(r.name)?'selected':''}" data-node="${esc(r.name)}"><strong>${esc(r.name)}</strong><code>${esc(M.print(r.expr))}</code><small>${esc(record(r.name)?.type||'value')}</small></button>`).join('');bindNodes();return;}
  const levels=new Map(),positions=new Map(),laneCounts=new Map();
  rows.forEach(r=>{let level=0;const refs=M.symbols(r.expr);if(typeof r.expr==='string')refs.add(r.expr);refs.forEach(n=>{if(levels.has(n))level=Math.max(level,levels.get(n)+1);});levels.set(r.name,level);const row=laneCounts.get(level)||0;laneCounts.set(level,row+1);positions.set(r.name,{x:24+level*192,y:38+row*110});});
  const width=Math.max(620,...[...positions.values()].map(p=>p.x+190)),height=Math.max(400,...[...positions.values()].map(p=>p.y+120));
  $('#graph').style.width=width+'px';$('#graph').style.minHeight=height+'px';
  let html='';(groups[scope]||[]).forEach((g,i)=>{const ps=g.filter(n=>positions.has(n)).map(n=>positions.get(n));if(!ps.length)return;const x=Math.min(...ps.map(p=>p.x))-10,y=Math.min(...ps.map(p=>p.y))-24,w=Math.max(...ps.map(p=>p.x))+168-x,h=Math.max(...ps.map(p=>p.y))+96-y;html+=`<div class="group-frame" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px">GROUP ${i+1} · visual only</div>`;});
  html+=`<svg class="wires" width="${width}" height="${height}" aria-hidden="true">`;
  rows.forEach(r=>{const b=positions.get(r.name);const refs=M.symbols(r.expr);if(typeof r.expr==='string')refs.add(r.expr);refs.forEach(n=>{const a=positions.get(n);if(!a)return;html+=`<path d="M ${a.x+158} ${a.y+19} H ${a.x+175} V ${b.y+19} H ${b.x}"/>`;});});html+='</svg>';
  rows.forEach(r=>{const p=positions.get(r.name),fn=Array.isArray(r.expr)&&program.defs.has(r.expr[0]);html+=`<button class="node ${fn?'function':''} ${selection.has(r.name)?'selected':''}" data-node="${esc(r.name)}" aria-pressed="${selection.has(r.name)}" style="left:${p.x}px;top:${p.y}px"><span class="node-title">${esc(r.name)}<span>${fn?'ƒ':'·'}</span></span><span class="node-op">${esc(Array.isArray(r.expr)?r.expr[0]:typeof r.expr==='number'?'literal':typeof r.expr==='string'?'connection':'text')}</span><span class="node-value">${esc(describe(record(r.name)))}</span></button>`;});
  const b=M.body(current());html+=`<div class="graph-result">RETURN → ${esc(M.print(b?.[0]==='let*'?b[2]:b))}</div>`;$('#graph').innerHTML=html;bindNodes();
}
function bindNodes(){$$('[data-node]').forEach(b=>{b.onclick=e=>select(b.dataset.node,e.shiftKey);b.ondblclick=()=>enterFunction(b.dataset.node);b.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();select(b.dataset.node);enterFunction(b.dataset.node);}};});}
function selectedRow(){return rowData().find(r=>selection.has(r.name));}
function changeExpr(name,source){try{const expr=M.read(source),next=M.clone(ast),f=next.slice(2).find(f=>f[1]===scope),r=M.bindings(f).find(r=>r.name===name);if(r)M.body(f)[1][r.index+1]=expr;else f[f[0]==='graph'?4:5]=expr;commit(next,`Applied ${name}. All contexts checked.`);}catch(e){status(e.message,true);}}
function renderInspector(){
  const row=selectedRow(),panel=$('#inspector');
  if(!row){panel.innerHTML=`<h3>${esc(scope)}</h3><div class="type-label">${esc(current()[3])} composition</div><p class="hint">Select a node to inspect its value or expression. All bindings are also available in the List view.</p>`;if(scope==='editor')panel.innerHTML+=`<button id="layout-options" class="primary">Try workspace layouts</button>`;if($('#layout-options'))$('#layout-options').onclick=layoutDialog;return;}
  const expr=row.expr,fn=Array.isArray(expr)&&program.defs.get(expr[0]),macro=Array.isArray(expr)&&program.macros.get(expr[0]),v=record(row.name);
  const available=rowData().filter(r=>r.index<row.index);
  const connectionMenu=(type,arg)=>{const matches=available.filter(r=>{const t=record(r.name)?.type;return t===type||(t==='int'&&type==='float');});return matches.length?`<label class="connection-label">Connect a ${esc(type)}<select class="connection" data-arg="${arg}" aria-label="Connect ${arg==='whole'?row.name:'argument '+(Number(arg)+1)}"><option value="">Choose a binding…</option>${matches.map(r=>`<option value="${esc(r.name)}">${esc(r.name)} · ${esc(describe(record(r.name)))}</option>`).join('')}</select></label>`:'';};
  panel.innerHTML=`<h3>${esc(row.name)}</h3><div class="type-label">${esc(v?.type||'parameterized expression')} ${fn?'· function call':''}</div><div class="badge">${typeof expr==='number'?'LITERAL':typeof expr==='string'?'CONNECTION':'EXPRESSION'}</div><form id="expression-form" class="field"><label for="expression">Value, expression or binding name</label><div class="field-line"><input id="expression" value="${esc(M.print(expr))}" spellcheck="false"><button type="submit">Apply</button></div></form>`;
  if(typeof expr==='number')panel.innerHTML+=`<div class="field"><label for="scrub">Adjust ${esc(row.name)} · ${expr}</label><input id="scrub" type="range" min="${row.name==='petals'?1:0.05}" max="${row.name==='petals'?32:row.name==='fps'?120:row.name==='seed'?100:3}" step="${Number.isInteger(expr)?1:0.05}" value="${expr}"></div><p class="hint">Try <code>(half 1.4)</code> or connect to another binding by name. Applying an expression replaces this literal in the study.</p>`;
  if(fn){panel.innerHTML+=`<p class="hint">Arguments belong to this call. The body is shared by <strong>${countCalls(expr[0])} calls</strong>.</p>`;fn[4].forEach((p,i)=>{panel.innerHTML+=`<form class="field arg-form" data-arg="${i}"><label>${esc(p[0])} · ${p[2]}<span class="field-line"><input aria-label="${esc(p[0])} argument" value="${esc(M.print(expr[i+1]))}"><button>Apply</button></span></label>${connectionMenu(p[2],i)}</form>`;});panel.innerHTML+=`<div class="inspector-actions"><button id="enter-function" class="primary">Edit shared definition ↗</button><button id="unique">Make unique</button></div>`;}
  else if(Array.isArray(expr)&&Object.hasOwn(M.ops,expr[0])){M.ops[expr[0]][1].forEach((type,i)=>{panel.innerHTML+=`<div class="field">${connectionMenu(type,i)}</div>`;});}
  else if(v)panel.innerHTML+=`<div class="field">${connectionMenu(v.type,'whole')}</div>`;
  if(typeof expr==='string'&&available.some(r=>r.name===expr))panel.innerHTML+=`<button id="go-source">Go to ${esc(expr)} ↗</button>`;
  if(macro)panel.innerHTML+=`<button id="inspect-macro">Inspect macro expansion</button>`;
  if(scope==='editor')panel.innerHTML+=`<div class="inspector-actions"><button id="layout-options">Try workspace layouts</button></div>`;
  if(selection.size>1)panel.innerHTML+=`<p class="hint">${selection.size} bindings selected. Group to organize; Make function to create a typed reusable call.</p>`;
  $('#expression-form').onsubmit=e=>{e.preventDefault();changeExpr(row.name,$('#expression').value);};
  if($('#scrub'))$('#scrub').onchange=e=>changeExpr(row.name,e.target.value);
  $$('.arg-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();try{const copy=M.clone(expr);copy[Number(form.dataset.arg)+1]=M.read(form.querySelector('input').value);changeExpr(row.name,M.print(copy));}catch(err){status(err.message,true);}});
  $$('.connection').forEach(input=>input.onchange=()=>{if(!input.value)return;if(input.dataset.arg==='whole')changeExpr(row.name,input.value);else{const copy=M.clone(expr);copy[Number(input.dataset.arg)+1]=input.value;changeExpr(row.name,M.print(copy));}});
  if($('#go-source'))$('#go-source').onclick=()=>select(expr);
  if($('#enter-function'))$('#enter-function').onclick=()=>enterFunction(row.name);
  if($('#unique'))$('#unique').onclick=()=>makeUnique(row);
  if($('#inspect-macro'))$('#inspect-macro').onclick=()=>macroDialog(expr[0],expr);
  if($('#layout-options'))$('#layout-options').onclick=layoutDialog;
}
function enterFunction(name){const row=rowData().find(r=>r.name===name);if(!Array.isArray(row?.expr)||!program.defs.has(row.expr[0]))return;returnScope={scope,name};scope=row.expr[0];selection=new Set();render();status(`Editing shared definition ${scope}; ${countCalls(scope)} calls are affected.`);}
function returnToCall(){if(!returnScope)return;scope=returnScope.scope;selection=new Set([returnScope.name]);returnScope=null;render();}
function makeUnique(row){const next=M.clone(ast),f=next.slice(2).find(f=>f[1]===row.expr[0]);let name=f[1]+'_copy',i=2;while(program.defs.has(name))name=f[1]+'_copy'+i++;const copy=M.clone(f);copy[1]=name;next.splice(2,0,copy);const owner=next.slice(2).find(f=>f[1]===scope),r=M.bindings(owner).find(r=>r.name===row.name);if(r)M.body(owner)[1][r.index+1][0]=name;else owner[owner[0]==='graph'?4:5][0]=name;commit(next,`Created ${name}. Only this call uses the new definition.`);}
function group(){if(!selection.size)return;const metadata=structuredClone(groups),existing=metadata[scope]||[];const same=existing.findIndex(g=>g.length===selection.size&&g.every(n=>selection.has(n)));if(same>=0)existing.splice(same,1);else existing.push([...selection]);metadata[scope]=existing;commit(M.clone(ast),same>=0?'Removed visual group.':'Grouped selection. Semantics and source are unchanged.',metadata);}
function extractDialog(){
  if(program.defs.has(scope)||!selection.size)return;
  const rows=rowData(),chosen=rows.filter(r=>selection.has(r.name));if(chosen.some(r=>r.index<0)){status('Extract named let* bindings. This graph has only an inline result.',true);return;}
  const selected=new Set(chosen.map(r=>r.name)),usedOutside=new Set();rows.filter(r=>!selected.has(r.name)).forEach(r=>M.symbols(r.expr).forEach(n=>usedOutside.add(n)));const b=M.body(current());M.symbols(b[2]).forEach(n=>usedOutside.add(n));
  const outputs=chosen.filter(r=>usedOutside.has(r.name));if(outputs.length!==1){status('This study extracts one outward result. Select a chain with exactly one result used outside it.',true);return;}
  const free=new Set();chosen.forEach(r=>M.symbols(r.expr).forEach(n=>{if(!selected.has(n))free.add(n);}));
  const inputs=[...free].filter(n=>rows.some(r=>r.name===n));if(free.size!==inputs.length){status('This selection captures a graph ref or unknown name. Pass that data through a local binding first.',true);return;}
  const last=Math.max(...chosen.map(r=>r.index));if(rows.some(r=>!selected.has(r.name)&&r.index<last&&M.symbols(r.expr).has(outputs[0].name))){status('Move the selection into a contiguous dependency chain before extracting.',true);return;}
  dialog('Make a reusable function',`<p>Replace ${chosen.length} bindings with one call. Its boundary becomes an explicit interface.</p><pre>inputs: ${esc(inputs.map(n=>`${n}: ${record(n)?.type}`).join(', ')||'none')}\nresult: ${esc(outputs[0].name)} → ${esc(record(outputs[0].name)?.type||'value')}</pre><label for="function-name">Function name</label><input id="function-name" value="my_shape"><p class="hint">The definition is shared. Each call keeps its own arguments. Undo restores the original chain.</p><button id="confirm-extract" class="primary">Create function</button>`);
  $('#confirm-extract').onclick=()=>{const name=$('#function-name').value.trim();if(!/^[a-z][a-z0-9_-]*$/.test(name)||program.defs.has(name)||program.graphs.has(name)||program.macros.has(name)){status('Choose a unique lowercase function name.',true);return;}
    const next=M.clone(ast),f=next.slice(2).find(f=>f[1]===scope),params=M.vec(inputs.map(n=>[n,':',record(n).type])),inner=M.vec(chosen.flatMap(r=>[r.name,M.clone(r.expr)]));
    const def=['defn',name,':context',f[3],params,['let*',inner,outputs[0].name]];next.splice(2,0,def);
    const entries=[];rows.forEach(r=>{if(!selected.has(r.name))entries.push(r.name,M.clone(r.expr));if(r.index===last)entries.push(outputs[0].name,[name,...inputs]);});M.body(f)[1]=M.vec(entries);
    if(commit(next,`Created ${name} with ${inputs.length} typed inputs.`)){selection=new Set([outputs[0].name]);$('#dialog').close();render();}
  };
}
function renderPreview(){
  const scene=[...program.cache.values()].find(v=>v.type==='scene')?.data,settings=[...program.cache.values()].find(v=>v.type==='settings')?.data;let html='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M 20 0 H 0 V 20" fill="none" stroke="#b7c5b4" stroke-width=".35"/></pattern></defs><rect width="300" height="240" fill="url(#grid)"/>';
  (scene?.items||[]).forEach((g,j)=>{const cx=j?215:119,cy=j?165:104,scale=38*g.radius;html+=`<g transform="translate(${cx} ${cy}) rotate(${g.twist*57.3})" opacity="${Math.min(1,(settings?.exposure??1)*.8)}">`;for(let k=0;k<g.count;k++){html+=`<ellipse cx="0" cy="${-scale}" rx="${Math.max(3,scale*.3)}" ry="${scale*.9}" transform="rotate(${k*360/g.count})" fill="${g.color}" stroke="#435c493b"/>`;}html+='<circle r="9" fill="#f0deb0"/><circle r="4" fill="#6b7650"/></g>';});html+='<text x="14" y="225" fill="#64725f" font-family="monospace" font-size="9">'+esc(`${scene?.items.length||0} objects · seed ${settings?.seed??'—'}`)+'</text>';$('#preview').innerHTML=html;
}
function dialog(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function macroDialog(name,call){const m=program.macros.get(name),args=call?.slice(1)||m[2].map(()=>0.5),expanded=M.replace(m[3],new Map(m[2].map((p,i)=>[p,args[i]])));dialog('Macro · '+name,`<p>Templates transform syntax before type checking. The expansion is read-only; edit the call or the macro source.</p><pre>${esc(M.print(m))}</pre><p>Call → expansion</p><pre>${esc(M.print([name,...args]))}\n↓\n${esc(M.print(expanded))}</pre><p class="hint">This study implements only binding-free value templates. Full hygienic macros, source maps and compile-time expansion limits are part of the proposal.</p><button id="macro-source">Edit source</button>`);$('#macro-source').onclick=()=>{$('#dialog').close();setView('text');};}
function shellHTML(p){if(p.kind==='split')return `<div class="shell-panel split ${p.axis==='vertical'?'vertical':''}">${p.children.map(shellHTML).join('')}</div>`;if(p.kind==='floating')return `<div class="shell-panel floating">${p.children.map(shellHTML).join('')}</div>`;return `<div class="shell-panel">${esc(p.kind==='viewport'?'◉ LIVE VIEW':p.kind==='graph'?'◇ GRAPH':'≡ INSPECTOR')}</div>`;}
const layouts={three:'(let* [preview (ui/viewport (ref scene)) network (ui/graph) inspector (ui/inspector) tools (ui/split "horizontal" network inspector) panels (ui/split "vertical" preview tools) workspace (ui/workspace panels)] workspace)',single:'(let* [preview (ui/viewport (ref scene)) workspace (ui/workspace preview)] workspace)',floating:'(let* [preview (ui/viewport (ref scene)) tools (ui/floating (ui/inspector)) panels (ui/split "horizontal" preview tools) workspace (ui/workspace panels)] workspace)'};
function applyLayout(key){const next=M.clone(ast),f=next.slice(2).find(f=>f[0]==='graph'&&f[3]==='editor');if(!f){status('This document has no editor graph.',true);return false;}f[4]=M.read(layouts[key]);return commit(next,`Applied ${key} panel composition. Host recovery remains available.`);}
function layoutDialog(){const editor=[...program.cache.values()].find(v=>v.type==='editor');dialog('Compose the editor',`<p>The applied editor graph describes this preview. Host navigation and recovery stay outside the authored layout.</p><div class="shell-preview">${editor?shellHTML(editor.data.panel):'No editor composition'}</div><div class="inspector-actions"><button data-layout="three">Three panels</button><button data-layout="single">Single view</button><button data-layout="floating">Floating tools</button></div><p class="hint">These choices really change the Lisp and graph. The panel preview is schematic: floating tools are not operating-system windows in this HTML study.</p>`);$$('[data-layout]').forEach(b=>b.onclick=()=>{if(applyLayout(b.dataset.layout))layoutDialog();});}
function actions(){dialog('Actions & keyboard',`<label for="action-search">Find an action</label><input id="action-search" placeholder="Group, function, layout…"><div id="actions"></div><p class="hint">Shortcuts work outside text fields. Tab follows normal keyboard focus. Shift-click selects several bindings. Graph connections are edited by naming a binding in the inspector or Lisp.</p>`);const entries=[['Group / ungroup selection · G',group],['Make function · F',extractDialog],['Graph view · 1',()=>setView('graph')],['List view · 2',()=>setView('list')],['Lisp view · 3',()=>setView('text')],['Compose editor panels',layoutDialog],['Undo · ⌘/Ctrl Z',()=>undo()],['Return to call · Esc',returnToCall]];function show(){const q=$('#action-search').value.toLowerCase();$('#actions').innerHTML='';entries.filter(([s])=>s.toLowerCase().includes(q)).forEach(([label,fn])=>{const b=document.createElement('button');b.className='action';b.textContent=label;b.onclick=()=>{$('#dialog').close();fn();};$('#actions').append(b);});}$('#action-search').oninput=show;show();$('#action-search').focus();}
$$('[data-view]').forEach((b,i)=>{b.onclick=()=>setView(b.dataset.view);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowLeft'?2:1))%3;const target=$$('[data-view]')[next];setView(target.dataset.view);target.focus();};});$('#group').onclick=group;$('#extract').onclick=extractDialog;$('#return').onclick=returnToCall;$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#help').onclick=actions;$('#close-dialog').onclick=()=>$('#dialog').close();$('#recover').onclick=()=>applyLayout('three');
$('#source').oninput=e=>{draft=e.target.value;dirty=draft!==M.print(ast);$('#preview-label').textContent=dirty?'Last applied version':'Illustrative 2D output';status(dirty?'Unapplied draft · live preview uses the last valid document.':'Source matches the applied document.');};
function applySource(){try{const next=M.read(draft);M.compile(next);dirty=false;if(commit(next,'Source checked and applied in one transaction.'))setView('text');}catch(e){dirty=true;status('Draft error · '+e.message,true);}}
$('#apply').onclick=applySource;$('#discard').onclick=()=>{dirty=false;draft=M.print(ast);$('#preview-label').textContent='Illustrative 2D output';setView('text');status('Discarded draft. The applied document is unchanged.');};
$('#reset').onclick=()=>{dialog('Reset the study?',`<p>Replace the applied document with the original Bloom studio. This is undoable. An unapplied source draft must be applied or discarded first.</p><button id="confirm-reset" class="primary">Reset study</button>`);$('#confirm-reset').onclick=()=>{if(commit(M.read(M.initial),'Reset to the original study.',{})){scope='geometry';selection=new Set(['flower']);$('#dialog').close();render();}};};
$('#export').onclick=()=>{const blob=new Blob([M.print(ast)+'\n'],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bloom-studio.flow.lisp';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Exported the applied Lisp. Visual groups are session metadata.');};
$$('[data-journey]').forEach(b=>b.onclick=()=>{const j=b.dataset.journey;if(j==='shape'){go('geometry');selection=new Set(['size']);setView('graph');render();}if(j==='reuse'){returnScope={scope:'geometry',name:'flower'};go('bloom');setView('graph');}if(j==='layout'){go('editor');setView('graph');layoutDialog();}if(j==='code'){setView('text');$('#source').focus();}$('.studio').scrollIntoView({behavior:'smooth',block:'start'});});
document.addEventListener('keydown',e=>{const text=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if((e.metaKey||e.ctrlKey)&&e.key==='Enter'&&view==='text'){e.preventDefault();applySource();return;}if(text||$('#dialog').open)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}if(e.metaKey||e.ctrlKey||e.altKey)return;const key=e.key.toLowerCase();if(key==='g')group();if(key==='f')extractDialog();if(key==='escape')returnToCall();if(key==='?')actions();if(['1','2','3'].includes(key))setView(['graph','list','text'][Number(key)-1]);});
window.addEventListener('beforeunload',e=>{if(dirty||past.length){e.preventDefault();e.returnValue='';}});
render();
