/* Ambiguity register: every place the design could be read two ways, with the proposed rule or the open options. */
window.Register=[
{id:'L1',area:'iteration',status:'decided',q:'Does for return a list or merged geometry?',
 why:'Houdini’s for-each and Blender’s repeat zone hand back geometry. Lisp’s for returns a sequence. If for silently merged, a loop over numbers and a loop over shapes would behave differently.',
 rule:'for always returns a list of its body type. Variadic slots such as sop/merge, scene/merge and ui/tile splice a list argument one level deep. Lists never flatten anywhere else. Repeat (R) writes the merge node explicitly.',
 study:'Bloom: ring is a list of 12 geometries, bloom is (sop/merge ring).'},
{id:'L2',area:'iteration',status:'decided',q:'Several clauses in one for: product or zip?',
 why:'Clojure’s for is a product. vvvv’s ForEach is a zip that stops at the shortest input. Both are reasonable, and they disagree on (for [x xs y ys] …).',
 rule:'Product, row-major, with the last clause varying fastest. A later clause may read earlier names, as in (for [x (range 4) y (range x)] …). Zip is a separate, explicit form (for-zip), deferred until a case needs it.',
 study:'Ten print and Facade use two clauses: 8 × 8 and 6 × 5 iterations.'},
{id:'L3',area:'iteration',status:'decided',q:'How is repetition bounded?',
 why:'A creative tool must not hang on a typo such as (range 100000) or a runaway fold. A static bound fails when counts come from inputs or geometry.',
 rule:'Each zone runs at most 4,096 iterations and a whole evaluation at most a fixed step budget. Both limits are published and give diagnostics that name the zone. A literal count is checked at compile time; a count from an input, t or geometry is checked at run time. There is no while and no recursion: fold with a fixed count is the only feedback.',
 study:'(range 5000) is rejected with the zone’s name.'},
{id:'L4',area:'iteration',status:'decided',q:'What do zero iterations produce?',
 why:'An empty list, empty geometry, 0 and the initial value are all plausible, and they matter because counts are often driven.',
 rule:'for gives an empty list, merge of nothing is empty geometry, sum gives 0 (an int, which coerces), fold gives its initial value and scan gives an empty list. Types are still checked, because the static pass types the body once whatever the count.'},
{id:'L5',area:'iteration',status:'decided',q:'Is the loop variable an int or a float?',
 why:'(range 12) gives indices, but most artistic uses want a 0‥1 fraction or an angle. An implicit float would print 3.0 where the author wrote 3.',
 rule:'range yields ints, and int coerces to float wherever a float is expected. linspace yields floats and includes both endpoints. There is no hidden normalized variable: (/ i n) is written out, so it shows up as a node.',
 study:'Bloom: u (/ i petals) is its own node, with a sparkline.'},
{id:'L6',area:'iteration',status:'decided',q:'fold, scan, sum: one accumulator or many?',
 why:'vvvv regions carry several accumulators. Multiple state values need either tuples or several named outputs, and neither exists yet.',
 rule:'Exactly one accumulator per fold or scan, but it may be a record: (fold [s {:shape frame :size 1.0}] …) carries several values, and the rail shows one row per field. There is no second accumulator syntax.'},
{id:'L7',area:'iteration',status:'decided',q:'Are captured values recomputed every iteration?',
 why:'Semantically pure, so it should not matter. Users still ask about cost, and Houdini users expect upstream nodes to cook once.',
 rule:'Values bound outside a zone are evaluated once and captured. A node inside a zone that does not depend on the loop names is loop-invariant: the compiler may hoist it, and the editor marks it “same each time” with a one-click Move out.',
 study:'Sunflower: turn is flagged; Tree: up is flagged.'},
{id:'L8',area:'iteration',status:'decided',q:'Where does per-iteration randomness come from?',
 why:'A stateful random stream gives different results under hoisting, parallel evaluation or reordering. That breaks the determinism rule.',
 rule:'value/rand is a pure hash of its keys, so (value/rand seed i) is identical across runs, domains and reorderings. Nested loops pass every index: (value/rand seed x y). A rand without the loop variable is the same every iteration, and the invariant badge makes that visible.',
 study:'Ten print hashes seed, x and y.'},
{id:'L9',area:'iteration',status:'decided',q:'Are both branches of if evaluated?',
 why:'Evaluating both costs time inside loops and can raise errors on the path not taken, such as allocation limits. Evaluating one hides type errors on the other.',
 rule:'The static pass types both branches, and they must agree. Execution runs only the taken branch. Inside loops the graph counts how often each branch ran.',
 study:'Ten print: angle and lift show how many cells took each branch.'},
{id:'L10',area:'iteration',status:'decided',q:'How does a loop inside a field expression parse?',
 why:'Flow.Expr is the infix language typed into parameter fields, with only t as a variable. Σ needs a bound variable, and fields have no binding syntax.',
 rule:'Fields accept s-expressions for everything beyond arithmetic. A field starting with ( is read as Lisp, so (sum [k (range 5)] …) works there, and the chip prints it back the same way. The infix field grammar gains no loop syntax: one spelling per construct. Unfolding the chip turns the loop into a zone.',
 study:'Square wave: y holds a Σ chip, and the inspector field accepts the same s-expression.'},
{id:'L11',area:'language',status:'decided',q:'May an inner name shadow an outer one?',
 why:'Lexical shadowing is normal in Lisp. In a graph, two nodes named x on either side of a zone border make every wire ambiguous to read.',
 rule:'No. Shadowing is an error that names both bindings. Loop and accumulator names follow the same rule. Unfold, extract and Repeat always generate a fresh name.'},
{id:'L12',area:'language',status:'decided',q:'Is a nested let* a group, and what is a “group”?',
 why:'Four boxes look alike on a canvas: a visual frame, a scope, a compound or function, and a loop zone. Frames change nothing. Scopes change which names are visible. Functions share a body. Zones repeat.',
 rule:'A frame is layout, never printed. A scope is a nested let* bound to a name: it is printed, has a dashed border, and only its result leaves. A function is a card with an enter chevron. A zone is a tinted region with a rail and a strip. Geometry groups (named selections) are a fifth, separate thing; see G1.',
 study:'Facade: marked is a scope around two group operations.'},
{id:'L13',area:'language',status:'decided',q:'Keyword or positional arguments?',
 why:'Flow uses positional geometry slots and keyword parameters. The first workspace study used positional calls only, which do not survive catalog changes.',
 rule:'Geometry slots are positional; every other parameter is a keyword. Defaults are omitted, so they print only when overridden. A graph’s rows still show every parameter, with defaults dimmed, and scrubbing a default writes the keyword. Functions take keywords, and their positional form is accepted but printed as keywords.'},
{id:'L14',area:'language',status:'decided',q:'Do graphs take inputs?',
 why:'Without inputs, the only way to vary a graph is to copy it. With them, (ref garden) must be callable with arguments, and graphs become functions with a context.',
 rule:'(graph name :context c [(input : type default) …] body). Every input needs a default, so a graph still runs on its own. (ref g :input v) evaluates it with overrides, cached by input values. Inputs are also the OCaml-visible interface (see O2).',
 study:'Variations: (ref scene :seed (+ s 1)) inside an editor loop.'},
{id:'L15',area:'language',status:'decided',q:'Is 2.0 an int or a float?',
 why:'An integral float must stay a float through print and read, or Int fields could start accepting it and the round trip would change the program.',
 rule:'A literal with a decimal point is a float, and it prints with its point. Scrubbing a float field keeps it float, even at a whole number.'},
{id:'G1',area:'groups',status:'decided',q:'Geometry groups are strings: how do they connect?',
 why:'group_bounds writes :name "attic" and blast reads :group "attic". The dependency is real but invisible, and a typo gives silently empty results.',
 rule:'The catalog marks parameters as group-writer or group-reader. The checker tracks literal group names written upstream on the same wire. A reader naming a group no upstream writer made is a warning (W_UNKNOWN_GROUP). The graph draws a named dotted link from writer to reader, and renaming the writer offers to rename its readers.',
 study:'Facade: ▦ attic and ▦ lit links, and a “?” on a group nobody makes.'},
{id:'G2',area:'groups',status:'decided',q:'What about group names computed in a loop?',
 why:'(str "floor_" f) makes names at run time. Static tracking and link drawing stop working.',
 rule:'Allowed. A computed name is an ordinary text value, so the editor offers Name this group: it binds the expression once, and the writer and every reader take it by wire. The dependency is then a real wire instead of a string coincidence. A reader whose name is a literal still gets W_UNKNOWN_GROUP when no upstream writer makes it; a computed name gets no warning.',
 study:'Facade: windows are grouped with (str "floor_" f) inside the loop, and gone = (str "floor_" hide) is wired into blast.'},
{id:'V1',area:'graph',status:'decided',q:'How do outer values enter a loop on the canvas?',
 why:'A direct wire from outside to a node deep in a zone hides that the value is shared by every iteration. Blender forbids nothing here; vvvv draws a plain link through the border.',
 rule:'Zones have a left rail. Loop variables (∈), the accumulator (⟲) and every captured outer name get a rail row. Outer wires end at the rail; inner wires start from it. Captures are derived from the body’s free names and are never authored, so the rail cannot drift from the Lisp.'},
{id:'V2',area:'graph',status:'decided',q:'Can a value leave a loop except through its result?',
 why:'Blender forbids links out of zones. A graph that allowed it would have no Lisp to print.',
 rule:'No. Wiring from inside a zone to a node outside is rejected with an explanation. The only exit is the yield row on the right rail: collect, next, add or result.'},
{id:'V3',area:'graph',status:'decided',q:'What does a node inside a loop display?',
 why:'One value per node hides that it has 12 or 240. Showing all of them does not fit on a card.',
 rule:'The footer shows the value at the probed iteration, a sparkline across iterations for numbers, and a count ×n. The zone’s iteration selector (‹ slider ›) sets the probe; the viewport shows the result. The inspector lists every value. Nested zones probe the inner loop at the outer probe.'},
{id:'V4',area:'graph',status:'decided',q:'Scrubbing a number inside a loop: one iteration or all?',
 why:'Direct manipulation invites “make this petal longer”. But the number is code, so it changes every petal.',
 rule:'It changes every iteration, and the status says so while scrubbing. A separate action, Only iteration k differs, writes (if (= i k) new old) explicitly, so the special case is visible in both Lisp and graph.'},
{id:'V5',area:'graph',status:'decided',q:'How does a picture map back to the program?',
 why:'Artists see a petal, not a node. Without back-mapping, finding the loop that made a shape means searching.',
 rule:'Loops tag the primitives they produce with (zone, iteration). Clicking a shape selects the zone and sets the probe. Highlighting uses the same tags. Tags are provenance metadata, never attributes the program can read.'},
{id:'V6',area:'graph',status:'decided',q:'Expression chip or zone?',
 why:'A loop nested in an argument can render inline, which is compact, or as a zone, which can be inspected. Choosing automatically would make the graph jump as text is edited.',
 rule:'It follows the source. A loop bound to a name is a zone; a loop inside an argument is a chip whose glyph names the form (for, Σ, fold, let). ƒ on a chip unfolds it into a binding; ƒ on a node folds it back. Both are ordinary, undoable Lisp edits.'},
{id:'V7',area:'graph',status:'decided',q:'Collapsed zones: layout or code?',
 why:'Collapse is presentation, but a collapsed loop could also mean “inline”.',
 rule:'Layout only, stored with positions and never printed. A collapsed zone is a card that keeps its rail rows, so its wiring stays readable.'},
{id:'E1',area:'editor',status:'decided',q:'Panels generated by a loop in the editor graph: who owns them?',
 why:'A panel from (for [s (range 4)] (ui/viewport …)) has no binding, so split, close and retype have nothing to rewrite.',
 rule:'Their headers say “from a loop” and link to the loop node. Structural edits happen on the loop. Focus and selection are keyed by iteration index, so a count change keeps the first panels stable.',
 study:'Variations: four viewports from one for.'},
{id:'E2',area:'editor',status:'decided',q:'Does editing a function show one call or all?',
 why:'Inside a shared definition, the values come from some call, and the user must know which one.',
 rule:'The header names the preview call. Values and loop probes inside the definition come from that call. Make unique copies the definition for one call before a divergent edit.'},
{id:'O1',area:'sketch',status:'decided',q:'Where is the source of truth for a sketch?',
 why:'A sketch is compiled at build time, and the running editor then changes the program. Saving into source, keeping a separate document, and refusing edits are all defensible. When the Lisp lived inside main.ml, saving meant splicing a string literal.',
 rule:'The file is the source. A sketch is sketches/<name>/sketch.rays, with no OCaml wrapper. Save (⌘S) rewrites that file atomically with the comment-preserving printer, but only when its digest equals the digest the binary was built from. Otherwise edits are saved as a document preset and the status bar says why. The editor also reloads the file when it changes on disk.',
 study:'Every case shows its .rays file and the generated dune stanza (the button on each case study).'},
{id:'O2',area:'sketch',status:'decided',q:'How do OCaml values enter a sketch?',
 why:'Antiquotation, such as $(petals), makes the text uncheckable on its own and cannot be edited back from the graph. A pure .rays sketch has no OCaml at all.',
 rule:'No antiquotation. Graph inputs are the interface. A .rays sketch runs its inputs at their defaults. An OCaml host loads a .rays with Workspace.load and overrides inputs through Workspace_program.with_inputs, which checks names and types at run time. The editor shows an overridden input as driven from OCaml. Generated typed input records (a [%workspace] PPX) are deferred until OCaml hosts need them.'},
{id:'O3',area:'sketch',status:'decided',q:'Which errors are build-time, which run-time?',
 why:'dune build runs the checker on the file, which sees literals but not driven counts or geometry sizes.',
 rule:'Build time (rays-plisp check, run by the generated dune rule): syntax, names, arity, keywords, types (both if branches, loop bodies typed once), shadowing, recursion, literal loop bounds, E_TIME_COUNT, E_TIME_BRANCH and unknown literal groups (warnings are errors). Run time: driven counts over the bound, the step budget, nonfinite math and missing assets. Every diagnostic is printed as File "…sketch.rays", line L, characters A-B, so dune and editors jump to it.'},
{id:'O4',area:'sketch',status:'decided',q:'Does the build compile loops to OCaml, or to a plan?',
 why:'Native OCaml loops are fast but make the live editor a second compiler. A shared execution plan is one implementation, but interpreted.',
 rule:'One checked plan for both. The generated main.ml embeds the verbatim source and its digest, re-parses it at startup (milliseconds), and runs the same plan the live editor edits. Generating OCaml for hot numeric zones is a later optimization that must be justified by measurements on the case studies and must produce byte-identical results to the plan.'},
{id:'T1',area:'time',status:'decided',q:'Which nodes recook when t changes?',
 why:'Recooking everything each frame wastes the cache. Recooking only the nodes that mention t is wrong, because a node can depend on t through a binding, a capture, an accumulator, a function or a graph reference.',
 rule:'A term is live when it mentions t or depends on a live binding, capture, fold accumulator, ref override, graph or function. Live nodes carry a ◷ t mark and recook every frame while playing, and so does everything downstream of them. Every other node is cooked once and stays cached. t is reserved and cannot be bound, and a gensym such as t# is not t.',
 study:'Orrery: base and plinth are cached; spin, pulse, sun, glow, the moon loop and the merges are live. The viewport reads ◷ 10 live · 4 cached.'},
{id:'T2',area:'time',status:'decided',q:'Can a loop count depend on t?',
 why:'A count that changes with time changes the unrolled network every frame, which means re-lowering, new ids, lost probes and cache misses. It also breaks the promise that one lowering serves every frame.',
 rule:'No: E_TIME_COUNT. Loop collections and counts, range arguments, fold step counts, and any list whose length depends on t and reaches geometry are static. Animate parameters instead, for example scale a piece to 0 to hide it. Value-only lists may have live lengths, as in (sum (filter …)).',
 study:'Change (range moons) in Orrery to (range (+ moons (floor (* 2 (sin t))))) and apply: E_TIME_COUNT names moons_each.'},
{id:'T3',area:'time',status:'decided',q:'Can t choose between shapes?',
 why:'(if (> (sin t) 0) (sop/box) (sop/uv_sphere)) is natural to write, but it swaps sub-networks frame by frame.',
 rule:'No: E_TIME_BRANCH. An if, cond or case with a live test must not choose between geometry arms. A live choice between values (a size, a colour, a group name) is a parameter and is fine. A later sop/switch with a driven selector can lift this rule when a case needs it.',
 study:'Orrery colours each moon with (if (> bob 0) …): a live value branch, accepted.'},
{id:'T4',area:'time',status:'decided',q:'What happens when a frame\'s cook is slower than the frame?',
 why:'Blocking the frame loop freezes the UI. Dropping work makes exports nondeterministic. Live cache entries evict the static entries that make playback cheap.',
 rule:'Interactive play never blocks. Cooking is latest-request, so the viewport shows the last completed result and the status bar says frames are being skipped. Fixed-step runs and exports wait for each frame\'s cook and are byte-identical at any domain count. A live node keeps one cache slot, replaced in place, so it never evicts cached static nodes.'},
{id:'I1',area:'identity',status:'decided',q:'What identifies a node inside a loop?',
 why:'Selection, layout, cache keys and probes need stable identity. The same binding runs n times.',
 rule:'Identity is the lexical path, for example flower/ring/leaf. Per-iteration identity is path plus index tuple. Cache keys include the tuple, so iteration 3 survives a count change from 12 to 13. Renames keep layout by rewriting keys in the same transaction.'},
{id:'I2',area:'identity',status:'decided',q:'Loops over geometry points: identity by index?',
 why:'(for [p (sop/point_list g)] …) orders by point number. An upstream topology change reorders iterations, so probes and cache entries jump.',
 rule:'Identity is the index. point_list and piece_list take an optional :key attribute name; when the geometry carries it, iterations are identified by that attribute and ordered by it, so probes and caches follow the element instead of its position. Without :key, the zone title shows “by index” so the instability is visible.'},
{id:'F1',area:'functions',status:'decided',q:'Can a function be stored, returned or put in a list?',
 why:'First-class functions that escape make the graph unbounded: a list of closures has no single drawing, and a returned closure hides what it captured.',
 rule:'No. fn values are non-escaping: they may be bound in let*, passed to map, filter, reduce, sort-by or to a defn parameter of type fn, and called. Returning one, storing it in a list or record, passing it through ref or carrying it in a fold is E_FN_ESCAPES. Every program therefore still has one finite graph, and recursion stays impossible because a fn cannot see its own name.',
 study:'Garland: bead, leaf and size are local λ zones; ring takes make : fn.'},
{id:'F2',area:'functions',status:'decided',q:'How are unannotated λ parameters typed?',
 why:'(fn [x] …) has no types. Requiring annotations everywhere is noisy for artists; inferring them globally is complex and error messages get vague.',
 rule:'Annotations are optional, (fn [(x : float)] …). The static pass types the body with the declared types or with any, then again with the argument types at each call site it can see, such as the element type of the list given to map. Errors name the call site.'},
{id:'F3',area:'functions',status:'decided',q:'What does a function zone show, and what is its probe?',
 why:'A function runs once per call, not once per iteration, and it may be called from several places. Showing one value hides what it did.',
 rule:'A λ zone is a loop over its calls. Its selector steps through the calls received, in evaluation order; the probe selects a call, and every node inside shows its value in that call. Shapes a call produces are tagged with (function, call), so clicking a bead in the viewport finds the call that made it. The inspector lists each call as arguments → result.',
 study:'Garland: probe bead; click a bead in the viewport.'},
{id:'F4',area:'functions',status:'decided',q:'map over several lists: zip or product?',
 why:'L2 made several for clauses a product. A higher-order map over two lists is conventionally a zip.',
 rule:'map takes 1–3 lists and zips them, stopping at the shortest. Products are written with for. The two forms therefore never overlap.',
 study:'Garland: (map bead ordered (range (count ordered))).'},
{id:'D1',area:'data',status:'decided',q:'Do scalar operations broadcast over lists?',
 why:'Implicit broadcasting (Grasshopper, Apparatus spreads) is quick to write but hides cost and makes types ambiguous: is (* xs 2) a list or an error?',
 rule:'No implicit broadcasting. Lists are homogeneous; int and float mix to float. Applying a scalar operation to a list is a type error whose fix wraps the node in map. Lists and geometry stay distinct: a list of shapes is not a shape with pieces until it is merged.'},
{id:'D2',area:'data',status:'decided',q:'Records: structural or nominal, and what are multiple outputs?',
 why:'Blender bundles match by name and need a sync button; Houdini multi-output nodes are indexed and brittle.',
 rule:'Records are structural and closed. A record fits where a record with a subset of its fields is expected. (values :a x :b y) is a record, so a function with several results and a node with several outputs are the same thing: the node shows one output row per field, and wiring from a row writes r.field. Renaming a field should rewrite every accessor in one transaction (the study renames bindings, not fields yet); nothing ever syncs by name.',
 study:'Kit of parts: window returns frame, pane and area.'},
{id:'D3',area:'data',status:'decided',q:'What happens when destructuring does not match?',
 why:'[a b] over a list of one, or {:keys [z]} over a record without z, can be silently nil in Clojure.',
 rule:'It is an error that names the pattern and the value’s length or fields. There is no nil. A destructuring binding is one node with one output row per name.',
 study:'Kit of parts: [left mid right] over widths.'},
{id:'D4',area:'data',status:'decided',q:'How do people build lists without typing?',
 why:'A literal (list 0.3 0.45 0.3) is text. Artists expect to add, reorder and fill items like spreadsheet cells.',
 rule:'A list literal is a node with one row per item. Rows scrub like any number, move up with ↑, accept wires, and + extends the list: when the last two items are numbers, the new one continues their step, like a spreadsheet fill handle. Every gesture rewrites the literal.',
 study:'Kit of parts: widths.'},
{id:'C1',area:'branches',status:'decided',q:'May cond and case fall through?',
 why:'A missing branch would need nil, and nil would travel into geometry operations.',
 rule:'Both require a final :else. Only the matching arm runs; every arm is typed statically and they must agree. A case matches numbers, text and booleans exactly.',
 study:'Kit of parts: style (case) and part (cond).'},
{id:'C2',area:'branches',status:'decided',q:'How does str format numbers?',
 why:'Computed names such as floor_2 must be identical on every run and platform, and 2.0 versus 2 would change a group name.',
 rule:'Ints print plainly; floats print up to 4 decimals with trailing zeros removed; booleans print true or false; vec3 prints [x y z]. The printer is deterministic and independent of locale.'},
{id:'M1',area:'macros',status:'decided',q:'What can a macro template do?',
 why:'Procedural macros can run arbitrary code at compile time, so the expansion cannot always be shown, stepped or trusted.',
 rule:'Macros are declarative quasiquote templates: ~p fills a hole, ~@rest splices a rest parameter, and x# is a fresh name at every use. A free name in a template must be global (an operator, defn, macro or special form); a name from the call site can only arrive through a hole. That is hygiene in both directions. Expansion depth is at most 32 and output at most 5,000 forms.',
 study:'Rosette: radial and wobble.'},
{id:'M2',area:'macros',status:'decided',q:'May a hole be a binding name?',
 why:'Anaphoric macros that silently introduce i are unhygienic, but a macro that repeats a body is useless if the body cannot see the index.',
 rule:'Yes, when the caller supplies it. A parameter used in binding position, as in (for [~i …]), is a binder hole; the call node shows it as a name pill, and the body sees the name the caller wrote.',
 study:'Rosette: (radial k petals …).'},
{id:'M3',area:'macros',status:'decided',q:'Is the expansion editable, and where do clicks land?',
 why:'Editing expanded code cannot be mapped back into a template in general.',
 rule:'The call is the only authored form. The ⤵ lens shows the expansion one step at a time, read-only. Replace call with expansion turns it into ordinary nodes as an explicit, undoable edit. Provenance of shapes lands on the call node, never on invisible expanded nodes. Make macro from selection offers the literals as holes and turns the selection’s own names into fresh names.',
 study:'Rosette: ⤵ on outer.'},
{id:'M4',area:'macros',status:'decided',q:'Macro or function?',
 why:'Both abstract a selection; users of Unreal and Houdini routinely pick the wrong one.',
 rule:'Prefer a function. A macro is justified only when a hole is a name the body binds or a piece of code evaluated in a new context (such as inside a loop). Make macro says so, and its hint points to λ and defn otherwise.'},
{id:'N1',area:'notes',status:'decided',q:'Where do comments go when the graph is edited?',
 why:'Graph edits reorder and rebuild bindings, which is exactly what destroys comments in round-trip editors.',
 rule:'A ; comment attaches to the next binding (or top-level form) by name, not by position. Reordering, rewiring and renaming keep it; the graph shows it as a note on the node, and editing the note writes the comment. Deleting a node deletes its note. Comments before a form’s end attach to that form’s end.',
 study:'Rosette and Garland carry notes.'},
{id:'N2',area:'notes',status:'decided',q:'What does ^:bypass do?',
 why:'Houdini’s bypass flag passes geometry through, but a bypassed value node has no obvious meaning.',
 rule:'A bypassed call returns its first positional argument when that argument’s type fits the call’s result, and is still type-checked. Otherwise bypass is refused. The node shows a B flag and a striped title. ^:bypass is the only metadata; anything else is an error.',
 study:'Rosette: soft.'}
];
