/* Ambiguity register: every place the design could be read two ways, with the proposed rule or the open options. */
window.Register=[
{id:'L1',area:'iteration',status:'decided',q:'Does for return a list or merged geometry?',
 why:'Houdini’s for-each and Blender’s repeat zone hand back geometry. Lisp’s for returns a sequence. If for silently merged, a loop over numbers and a loop over shapes would behave differently.',
 rule:'for always returns a list of its body type. Variadic slots such as sop/merge, scene/merge and ui/tile splice a list argument one level deep. Lists never flatten anywhere else. Repeat (R) writes the merge node explicitly.',
 study:'Bloom: ring is a list of 12 geometries, bloom is (sop/merge ring).'},
{id:'L2',area:'iteration',status:'decided',q:'Several clauses in one for: product or zip?',
 why:'Clojure’s for is a product. vvvv’s ForEach is a zip that stops at the shortest input. Both are reasonable, and they disagree on (for [x xs y ys] …).',
 rule:'Product, row-major, with the last clause varying fastest. A later clause may read earlier names, as in (for [x (range 4) y (range x)] …). Zip is a separate, explicit form (for-zip), deferred until a case needs it.',
 study:'Ten print and Facade use two clauses: 8 × 8 and 6 × 5 iterations.'},
{id:'L3',area:'iteration',status:'decided',q:'How is repetition bounded?',
 why:'A creative tool must not hang on a typo such as (range 100000) or a runaway fold. A static bound fails when counts come from inputs or geometry.',
 rule:'Each zone runs at most 4,096 iterations and a whole evaluation at most a fixed step budget. Both limits are published and give diagnostics that name the zone. A literal count is checked at compile time; a count from an input, t or geometry is checked at run time. There is no while and no recursion: fold with a fixed count is the only feedback.',
 study:'(range 5000) is rejected with the zone’s name.'},
{id:'L4',area:'iteration',status:'decided',q:'What do zero iterations produce?',
 why:'An empty list, empty geometry, 0 and the initial value are all plausible, and they matter because counts are often driven.',
 rule:'for gives an empty list, merge of nothing is empty geometry, sum gives 0 (an int, which coerces), fold gives its initial value and scan gives an empty list. Types are still checked, because the static pass types the body once whatever the count.'},
{id:'L5',area:'iteration',status:'decided',q:'Is the loop variable an int or a float?',
 why:'(range 12) gives indices, but most artistic uses want a 0‥1 fraction or an angle. An implicit float would print 3.0 where the author wrote 3.',
 rule:'range yields ints, and int coerces to float wherever a float is expected. linspace yields floats and includes both endpoints. There is no hidden normalized variable: (/ i n) is written out, so it shows up as a node.',
 study:'Bloom: u (/ i petals) is its own node, with a sparkline.'},
{id:'L6',area:'iteration',status:'decided',q:'fold, scan, sum: one accumulator or many?',
 why:'vvvv regions carry several accumulators. Multiple state values need either tuples or several named outputs, and neither exists yet.',
 rule:'Exactly one accumulator per fold or scan, but it may be a record: (fold [s {:shape frame :size 1.0}] …) carries several values, and the rail shows one row per field. There is no second accumulator syntax.'},
{id:'L7',area:'iteration',status:'decided',q:'Are captured values recomputed every iteration?',
 why:'Semantically pure, so it should not matter. Users still ask about cost, and Houdini users expect upstream nodes to cook once.',
 rule:'Values bound outside a zone are evaluated once and captured. A node inside a zone that does not depend on the loop names is loop-invariant: the compiler may hoist it, and the editor marks it “same each time” with a one-click Move out.',
 study:'Sunflower: turn is flagged; Tree: up is flagged.'},
{id:'L8',area:'iteration',status:'decided',q:'Where does per-iteration randomness come from?',
 why:'A stateful random stream gives different results under hoisting, parallel evaluation or reordering. That breaks the determinism rule.',
 rule:'value/rand is a pure hash of its keys, so (value/rand seed i) is identical across runs, domains and reorderings. Nested loops pass every index: (value/rand seed x y). A rand without the loop variable is the same every iteration, and the invariant badge makes that visible.',
 study:'Ten print hashes seed, x and y.'},
{id:'L9',area:'iteration',status:'decided',q:'Are both branches of if evaluated?',
 why:'Evaluating both costs time inside loops and can raise errors on the path not taken, such as allocation limits. Evaluating one hides type errors on the other.',
 rule:'The static pass types both branches, and they must agree. Execution runs only the taken branch. Inside loops the graph counts how often each branch ran.',
 study:'Ten print: angle and lift show how many cells took each branch.'},
{id:'L10',area:'iteration',status:'decided',q:'How does a loop inside a field expression parse?',
 why:'Flow.Expr is the infix language typed into parameter fields, with only t as a variable. Σ needs a bound variable, and fields have no binding syntax.',
 rule:'Fields accept s-expressions for everything beyond arithmetic. A field starting with ( is read as Lisp, so (sum [k (range 5)] …) works there, and the chip prints it back the same way. The infix field grammar gains no loop syntax: one spelling per construct. Unfolding the chip turns the loop into a zone.',
 study:'Square wave: y holds a Σ chip, and the inspector field accepts the same s-expression.'},
{id:'L11',area:'language',status:'decided',q:'May an inner name shadow an outer one?',
 why:'Lexical shadowing is normal in Lisp. In a graph, two nodes named x on either side of a zone border make every wire ambiguous to read.',
 rule:'No. Shadowing is an error that names both bindings. Loop and accumulator names follow the same rule. Unfold, extract and Repeat always generate a fresh name.'},
{id:'L12',area:'language',status:'decided',q:'Is a nested let* a group, and what is a “group”?',
 why:'Four boxes look alike on a canvas: a visual frame, a scope, a compound or function, and a loop zone. Frames change nothing. Scopes change which names are visible. Functions share a body. Zones repeat.',
 rule:'A frame is layout, never printed. A scope is a nested let* bound to a name: it is printed, has a dashed border, and only its result leaves. A function is a card with an enter chevron. A zone is a tinted region with a rail and a strip. Geometry groups (named selections) are a fifth, separate thing; see G1.',
 study:'Facade: marked is a scope around two group operations.'},
{id:'L13',area:'language',status:'decided',q:'Keyword or positional arguments?',
 why:'Flow uses positional geometry slots and keyword parameters. The first workspace study used positional calls only, which do not survive catalog changes.',
 rule:'Geometry slots are positional; every other parameter is a keyword. Defaults are omitted, so they print only when overridden. A graph’s rows still show every parameter, with defaults dimmed, and scrubbing a default writes the keyword. Functions take keywords, and their positional form is accepted but printed as keywords.'},
{id:'L14',area:'language',status:'decided',q:'Do graphs take inputs?',
 why:'Without inputs, the only way to vary a graph is to copy it. With them, (ref garden) must be callable with arguments, and graphs become functions with a context.',
 rule:'(graph name :context c [(input : type default) …] body). Every input needs a default, so a graph still runs on its own. (ref g :input v) evaluates it with overrides, cached by input values. Inputs are also the OCaml-visible interface (see O2).',
 study:'Variations: (ref scene :seed (+ s 1)) inside an editor loop.'},
{id:'L15',area:'language',status:'decided',q:'Is 2.0 an int or a float?',
 why:'An integral float must stay a float through print and read, or Int fields could start accepting it and the round trip would change the program.',
 rule:'A literal with a decimal point is a float, and it prints with its point. Scrubbing a float field keeps it float, even at a whole number.'},
{id:'G1',area:'groups',status:'decided',q:'Geometry groups are strings: how do they connect?',
 why:'group_bounds writes :name "attic" and blast reads :group "attic". The dependency is real but invisible, and a typo gives silently empty results.',
 rule:'The catalog marks parameters as group-writer or group-reader. The checker tracks literal group names written upstream on the same wire. A reader naming a group no upstream writer made is a warning (W_UNKNOWN_GROUP). The graph draws a named dotted link from writer to reader, and renaming the writer offers to rename its readers.',
 study:'Facade: ▦ attic and ▦ lit links, and a “?” on a group nobody makes.'},
{id:'G2',area:'groups',status:'decided',q:'What about group names computed in a loop?',
 why:'(str "floor_" f) makes names at run time. Static tracking and link drawing stop working.',
 rule:'Allowed. A computed name is an ordinary text value, so the editor offers Name this group: it binds the expression once, and the writer and every reader take it by wire. The dependency is then a real wire instead of a string coincidence. A reader whose name is a literal still gets W_UNKNOWN_GROUP when no upstream writer makes it; a computed name gets no warning.',
 study:'Facade: floors are grouped with (str "floor_" f), and the bound name wires writer to reader.'},
{id:'V1',area:'graph',status:'decided',q:'How do outer values enter a loop on the canvas?',
 why:'A direct wire from outside to a node deep in a zone hides that the value is shared by every iteration. Blender forbids nothing here; vvvv draws a plain link through the border.',
 rule:'Zones have a left rail. Loop variables (∈), the accumulator (⟲) and every captured outer name get a rail row. Outer wires end at the rail; inner wires start from it. Captures are derived from the body’s free names and are never authored, so the rail cannot drift from the Lisp.'},
{id:'V2',area:'graph',status:'decided',q:'Can a value leave a loop except through its result?',
 why:'Blender forbids links out of zones. A graph that allowed it would have no Lisp to print.',
 rule:'No. Wiring from inside a zone to a node outside is rejected with an explanation. The only exit is the yield row on the right rail: collect, next, add or result.'},
{id:'V3',area:'graph',status:'decided',q:'What does a node inside a loop display?',
 why:'One value per node hides that it has 12 or 240. Showing all of them does not fit on a card.',
 rule:'The footer shows the value at the probed iteration, a sparkline across iterations for numbers, and a count ×n. The zone strip draws thumbnails or bars per iteration and sets the probe. The inspector lists every value. Nested zones probe the inner loop at the outer probe.'},
{id:'V4',area:'graph',status:'decided',q:'Scrubbing a number inside a loop: one iteration or all?',
 why:'Direct manipulation invites “make this petal longer”. But the number is code, so it changes every petal.',
 rule:'It changes every iteration, and the status says so while scrubbing. A separate action, Only iteration k differs, writes (if (= i k) new old) explicitly, so the special case is visible in both Lisp and graph.'},
{id:'V5',area:'graph',status:'decided',q:'How does a picture map back to the program?',
 why:'Artists see a petal, not a node. Without back-mapping, finding the loop that made a shape means searching.',
 rule:'Loops tag the primitives they produce with (zone, iteration). Clicking a shape selects the zone and sets the probe. Highlighting uses the same tags. Tags are provenance metadata, never attributes the program can read.'},
{id:'V6',area:'graph',status:'decided',q:'Expression chip or zone?',
 why:'A loop nested in an argument can render inline, which is compact, or as a zone, which can be inspected. Choosing automatically would make the graph jump as text is edited.',
 rule:'It follows the source. A loop bound to a name is a zone; a loop inside an argument is a chip whose glyph names the form (for, Σ, fold, let). ƒ on a chip unfolds it into a binding; ƒ on a node folds it back. Both are ordinary, undoable Lisp edits.'},
{id:'V7',area:'graph',status:'decided',q:'Collapsed zones: layout or code?',
 why:'Collapse is presentation, but a collapsed loop could also mean “inline”.',
 rule:'Layout only, stored with positions and never printed. A collapsed zone is a card that keeps its rail rows, so its wiring stays readable.'},
{id:'E1',area:'editor',status:'decided',q:'Panels generated by a loop in the editor graph: who owns them?',
 why:'A panel from (for [s (range 4)] (ui/viewport …)) has no binding, so split, close and retype have nothing to rewrite.',
 rule:'Their headers say “from a loop” and link to the loop node. Structural edits happen on the loop. Focus and selection are keyed by iteration index, so a count change keeps the first panels stable.',
 study:'Variations: four viewports from one for.'},
{id:'E2',area:'editor',status:'decided',q:'Does editing a function show one call or all?',
 why:'Inside a shared definition, the values come from some call, and the user must know which one.',
 rule:'The header names the preview call. Values and loop probes inside the definition come from that call. Make unique copies the definition for one call before a divergent edit.'},
{id:'O1',area:'ocaml',status:'decided',q:'Where is the source of truth for a sketch written in OCaml?',
 why:'The sketch embeds a Lisp string compiled at build time. The live editor then changes the program. Saving back into the .ml file, keeping a separate document, and refusing edits are all defensible.',
 rule:'The string is the source. The running editor edits a live copy and offers Write back to main.ml, which rewrites only the string literal, preserves comments and is shown as a diff first. Without write-back, edits persist as a document preset whose header names the sketch and the manifest digest.'},
{id:'O2',area:'ocaml',status:'decided',q:'How do OCaml values enter a compile-time Lisp string?',
 why:'Antiquotation, such as $(petals), makes the string uncheckable on its own and cannot be edited back from the graph.',
 rule:'No antiquotation. Graph inputs are the interface. The PPX generates a typed record per graph with inputs, plus defaults. OCaml overrides values at run time through Program.with_inputs, and the editor shows overridden inputs as driven from OCaml.'},
{id:'O3',area:'ocaml',status:'decided',q:'Which errors are compile-time, which run-time?',
 why:'The PPX sees literals, not driven counts or geometry sizes.',
 rule:'Compile time: syntax, names, arity, keywords, types (both if branches, loop bodies typed once), shadowing, recursion, literal loop bounds and unknown literal groups (as warnings). Run time: driven counts over the bound, step budget, nonfinite math and missing assets. Each is reported at a line inside the string.'},
{id:'O4',area:'ocaml',status:'decided',q:'Does the PPX compile loops to OCaml, or to a plan?',
 why:'Native OCaml loops are fast but make the live editor a second compiler. A shared execution plan is one implementation, but interpreted.',
 rule:'One checked plan for both, as [%flow] already embeds plan data through Flow_sop.Build. Generating OCaml for hot numeric zones is a later optimization that must be justified by measurements on the case studies and must produce byte-identical results to the plan.'},
{id:'I1',area:'identity',status:'decided',q:'What identifies a node inside a loop?',
 why:'Selection, layout, cache keys and probes need stable identity. The same binding runs n times.',
 rule:'Identity is the lexical path, for example flower/ring/leaf. Per-iteration identity is path plus index tuple. Cache keys include the tuple, so iteration 3 survives a count change from 12 to 13. Renames keep layout by rewriting keys in the same transaction.'},
{id:'I2',area:'identity',status:'decided',q:'Loops over geometry points: identity by index?',
 why:'(for [p (sop/point_list g)] …) orders by point number. An upstream topology change reorders iterations, so probes and cache entries jump.',
 rule:'Identity is the index. point_list and piece_list take an optional :key attribute name; when the geometry carries it, iterations are identified by that attribute and ordered by it, so probes and caches follow the element instead of its position. Without :key, the zone title shows “by index” so the instability is visible.'},
];
