type resource=Buffer of Buffer.t|Texture of Texture.t
type control={resources:(int64,resource)Hashtbl.t;pipelines:(string,Pipeline.t)Hashtbl.t;pipeline_tokens:(int64,Pipeline.t)Hashtbl.t;sampler_cache:(Ogpu.Types.sampler_descriptor,Sampler.t)Hashtbl.t;mutable next:int64;layer:Metal.Metal_layer.t option}
let error op kind text=Error(Ogpu.Error.make op kind text)
let token c=let x=c.next in c.next<-Int64.succ x;x
let register_pipeline c pipeline=Hashtbl.replace c.pipelines(Pipeline.key pipeline)pipeline
let sampler_cache_entries c=Hashtbl.length c.sampler_cache
let create ?device:provided_device ?layer ()=
  let c={resources=Hashtbl.create 32;pipelines=Hashtbl.create 16;pipeline_tokens=Hashtbl.create 16;sampler_cache=Hashtbl.create 64;next=1L;layer}in
  let obtain_device()=match provided_device with Some device->Ok device|None->Device.system_default()in
  let create_device()=match obtain_device()with Error _ as e->e|Ok device->let device_token=token c in
    let create_buffer descriptor=match Buffer.create device~memory:Buffer.Shared descriptor with Error _ as e->e|Ok buffer->let id=token c in Hashtbl.add c.resources id(Buffer buffer);Ok{Ogpu.Backend.token=id;write=(fun offset bytes->Buffer.write_bytes device buffer~dst_offset:offset bytes);read=(fun offset length->Buffer.read_bytes device buffer~offset~length);destroy=(fun()->match Buffer.destroy buffer with Error _ as e->e|Ok()->Hashtbl.remove c.resources id;Ok())}in
    let create_texture_format ~format ~host_read descriptor=match Texture.create device~memory:(if descriptor.Ogpu.Types.sample_count=1&&host_read then Texture.Shared else Device_local)~format descriptor with Error _ as e->e|Ok texture->let id=token c in Hashtbl.add c.resources id(Texture texture);Ok{Ogpu.Backend.token=id;write=(fun _ _->error"Ogpu_metal.Backend.texture.write"Ogpu.Error.Unsupported"use a transfer pass for textures");read=(fun offset length->if not host_read then error"Ogpu_metal.Backend.depth.read"Ogpu.Error.Unsupported"depth textures are not host readable"else if offset<>0L||descriptor.height<=0||length mod descriptor.height<>0 then error"Ogpu_metal.Backend.texture.read"Ogpu.Error.Invalid_argument"texture read range is invalid"else Texture.read_bytes device texture~mip_level:0~bytes_per_row:(length/descriptor.height));destroy=(fun()->match Texture.destroy texture with Error _ as e->e|Ok()->Hashtbl.remove c.resources id;Ok())}in
    let create_texture descriptor=create_texture_format~format:Texture.Rgba8_unorm~host_read:true descriptor in
    let create_depth_texture descriptor=create_texture_format~format:Texture.Depth32_float~host_read:false descriptor in
    let create_stencil_texture descriptor=create_texture_format~format:Texture.Stencil8~host_read:false descriptor in
    let create_pipeline portable=match Hashtbl.find_opt c.pipelines(Ogpu.Pipeline.cache_key portable)with None->error"Ogpu_metal.Backend.create_pipeline"Ogpu.Error.Invalid_argument"portable pipeline was not registered with the Metal adapter"|Some pipeline->let id=token c in Hashtbl.add c.pipeline_tokens id pipeline;Ok{Ogpu.Backend.pipeline_token=id;destroy_pipeline=(fun()->match Pipeline.destroy pipeline with Error _ as e->e|Ok()->Hashtbl.remove c.pipeline_tokens id;Ok())}in
    let native_resource token=Hashtbl.find_opt c.resources token in
    let create_queue()=match Queue.create device with Error _ as e->e|Ok queue->let queue_token=token c in
      let submit command ~resources ~pipelines=let find id=Option.bind(List.assoc_opt id resources)native_resource in
        let one_pipeline()=match pipelines with[id]->Hashtbl.find_opt c.pipeline_tokens id|_->None in
        let native_render_descriptor (descriptor:Ogpu.Render_pass.descriptor)=
          let fact usage (value:Ogpu.Render_pass.texture)=match find value.id with Some(Texture texture)->Render_pass.attachment device texture~usage|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render attachment graph is incomplete"in
          let colors=Array.map(function None->Ok None|Some(color:Ogpu.Render_pass.color)->match fact Render_target color.texture with Error _ as e->e|Ok texture->(match color.resolve with None->Ok(Some{color with texture})|Some resolve->Result.map(fun resolve->Some{color with texture;resolve=Some resolve})(fact Resolve_target resolve)))descriptor.colors in
          if Array.exists Result.is_error colors then Array.find_opt Result.is_error colors|>Option.get|>Result.map(fun _->assert false)else let depth=match descriptor.depth with None->Ok None|Some(d:Ogpu.Render_pass.depth)->Result.map(fun texture->Some{d with texture})(fact Render_target d.texture)and stencil=match descriptor.stencil with None->Ok None|Some(s:Ogpu.Render_pass.stencil)->Result.map(fun texture->Some{s with texture})(fact Render_target s.texture)in match depth,stencil with Error e,_->Error e|_,Error e->Error e|Ok depth,Ok stencil->Ok{descriptor with colors=Array.map Result.get_ok colors;depth;stencil}in
        let result=match command with
        |Ogpu.Backend.Transfer descriptions->let pass=Ogpu.Transfer_pass.create(Device.Private.handle device)in let b id=match find id with Some(Buffer x)->Ok x|_->error"Ogpu_metal.Backend.transfer"Ogpu.Error.Invalid_argument"buffer graph is incomplete"and t id=match find id with Some(Texture x)->Ok x|_->error"Ogpu_metal.Backend.transfer"Ogpu.Error.Invalid_argument"texture graph is incomplete"in let rec replay i=if i=Array.length descriptions then match Transfer_pass.create device pass~buffers:(List.filter_map(fun(_,tok)->match native_resource tok with Some(Buffer x)->Some x|_->None)resources)~textures:(List.filter_map(fun(_,tok)->match native_resource tok with Some(Texture x)->Some x|_->None)resources)with Error _ as e->e|Ok encoded->Queue.submit_transfer_pass queue encoded else let next=match descriptions.(i)with
          |Ogpu.Transfer_pass.Copy_buffer(a,ao,d,do_,n)->(match b a,b d with Ok a,Ok d->Ogpu.Transfer_pass.copy_buffer pass~src:(Result.get_ok(Transfer_pass.buffer device a))~src_offset:ao~dst:(Result.get_ok(Transfer_pass.buffer device d))~dst_offset:do_~length:n|Error e,_->Error e|_,Error e->Error e)
          |Fill_buffer(a,o,n,v)->(match b a with Error _ as e->e|Ok a->Ogpu.Transfer_pass.fill_buffer pass(Result.get_ok(Transfer_pass.buffer device a))~offset:o~length:n~value:v)
          |Buffer_to_texture(a,o,row,image,d,mip,origin,extent)->(match b a,t d with Ok a,Ok d->Ogpu.Transfer_pass.buffer_to_texture pass~src:(Result.get_ok(Transfer_pass.buffer device a))~offset:o~bytes_per_row:row~bytes_per_image:image~dst:(Result.get_ok(Transfer_pass.texture device d))~mip~origin~extent|Error e,_->Error e|_,Error e->Error e)
          |Texture_to_buffer(a,mip,origin,extent,d,o,row,image)->(match t a,b d with Ok a,Ok d->Ogpu.Transfer_pass.texture_to_buffer pass~src:(Result.get_ok(Transfer_pass.texture device a))~mip~origin~extent~dst:(Result.get_ok(Transfer_pass.buffer device d))~offset:o~bytes_per_row:row~bytes_per_image:image|Error e,_->Error e|_,Error e->Error e)
          |Copy_texture(a,am,ao,d,dm,do_,extent)->(match t a,t d with Ok a,Ok d->Ogpu.Transfer_pass.copy_texture pass~src:(Result.get_ok(Transfer_pass.texture device a))~src_mip:am~src_origin:ao~dst:(Result.get_ok(Transfer_pass.texture device d))~dst_mip:dm~dst_origin:do_~extent|Error e,_->Error e|_,Error e->Error e)in match next with Error _ as e->e|Ok()->replay(i+1)in replay 0
        |Compute description->(match one_pipeline()with None->error"Ogpu_metal.Backend.compute"Ogpu.Error.Invalid_argument"compute pipeline graph is incomplete"|Some pipeline->let slots=Array.to_list description.groups|>List.concat_map(fun(_,xs)->xs)|>List.map fst and ids=Array.to_list description.commands|>List.filter_map(function Ogpu.Command.Declare_resource r->Some r.resource_id|_->None)in if List.length slots<>List.length ids then error"Ogpu_metal.Backend.compute"Ogpu.Error.Invalid_argument"binding/resource cardinality differs"else let native_id id=match find id with Some(Buffer buffer)->Buffer.id buffer|_->id in let bindings=List.map2(fun index id->match find id with Some(Buffer buffer)->Ok{Compute_pass.id=Buffer.id buffer;index;buffer}|_->error"Ogpu_metal.Backend.compute"Ogpu.Error.Invalid_argument"compute buffer graph is incomplete")slots ids in if List.exists Result.is_error bindings then List.find Result.is_error bindings|>Result.map(fun _->assert false)else let description=Ogpu.Compute_pass.Private.map_resource_ids native_id description in match Compute_pass.create device(Ogpu.Compute_pass.Private.of_description description)~pipeline~bindings:(List.map Result.get_ok bindings)with Error _ as e->e|Ok encoded->Queue.submit_compute_pass queue encoded)
        |Render submission->
          let sampler_binding(s:Ogpu.Render_pass.sampler_binding)=match Hashtbl.find_opt c.sampler_cache s.sampler with Some sampler->Ok{Render_pass.stage=(match s.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=s.index;sampler}|None->if Hashtbl.length c.sampler_cache>=64 then(Hashtbl.iter(fun _ sampler->ignore(Sampler.destroy sampler))c.sampler_cache;Hashtbl.clear c.sampler_cache);match Sampler.create device s.sampler with Error _ as e->e|Ok sampler->Hashtbl.add c.sampler_cache s.sampler sampler;Ok{Render_pass.stage=(match s.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=s.index;sampler}in
          let pipeline_by_key key=pipelines|>List.find_map(fun id->match Hashtbl.find_opt c.pipeline_tokens id with Some p when Pipeline.key p=key->Some p|_->None)in
          let convert(portable_draw:Ogpu.Render_pass.draw)=
            match pipeline_by_key portable_draw.pipeline_key with None->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render pipeline graph is incomplete"|Some pipeline->
            let buffer_binding(b:Ogpu.Render_pass.buffer_binding)=match find b.buffer_id with Some(Buffer buffer)->Ok{Render_pass.stage=(match b.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=b.index;buffer;offset=b.offset}|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render buffer graph is incomplete"and texture_binding(t:Ogpu.Render_pass.texture_binding)=match find t.texture_id with Some(Texture texture)->Ok{Render_pass.stage=(match t.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=t.index;texture}|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render texture graph is incomplete"in
            let buffers=List.map buffer_binding portable_draw.buffers and textures=List.map texture_binding portable_draw.textures and samplers=List.map sampler_binding portable_draw.samplers in
            if List.exists Result.is_error buffers||List.exists Result.is_error textures||List.exists Result.is_error samplers then error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render binding graph is invalid"else
            let index=match portable_draw.index with None->Ok None|Some(kind,id,offset,count)->match find id with Some(Buffer buffer)->Ok(Some((match kind with Ogpu.Render_pass.Uint16->Render_pass.Uint16|Uint32->Uint32),buffer,offset,count))|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render index graph is incomplete"in
            Result.map(fun index->{Render_pass.pipeline;buffers=List.map Result.get_ok buffers;textures=List.map Result.get_ok textures;samplers=List.map Result.get_ok samplers;primitive=(match portable_draw.primitive with Ogpu.Render_pass.Triangle_list->Render_pass.Triangle_list|Triangle_strip->Triangle_strip);vertex_start=portable_draw.vertex_start;vertex_count=portable_draw.vertex_count;index})index in
          let draws=List.map convert(Ogpu.Render_pass.submission_draws submission)in
          if List.exists Result.is_error draws then(List.find Result.is_error draws|>Result.map(fun _->assert false))else
          let descriptor=Ogpu.Render_pass.descriptor(Ogpu.Render_pass.submission_pass submission)and attachments=resources|>List.filter_map(fun(_,tok)->match native_resource tok with Some(Texture x)->Some x|_->None)in
          let portable_pass=Ogpu.Render_pass.submission_pass submission in
          let rendered=match native_render_descriptor descriptor with Error _ as e->e|Ok descriptor->match Ogpu.Render_pass.create~raster_state:(Ogpu.Render_pass.raster_state portable_pass)?stencil_state:(Ogpu.Render_pass.stencil_state portable_pass)(Device.Private.handle device)descriptor with Error _ as e->e|Ok pass->match Render_pass.create_batch device pass~attachments(List.map Result.get_ok draws)with Error _ as e->e|Ok encoded->Queue.submit_render_pass queue encoded in rendered in
        Result.map(fun(receipt:Queue.receipt)->{Ogpu.Backend.epoch=receipt.epoch})result in
      Ok{Ogpu.Backend.queue_token;submit;complete_through=(fun epoch->Queue.wait_through queue epoch);destroy_queue=(fun()->Queue.destroy queue)}in
    let create_surface configuration=match c.layer with None->error"Ogpu_metal.Backend.create_surface"Ogpu.Error.Unsupported"adapter was created without a typed Metal layer"|Some layer->match Surface.create device~layer configuration with Error _ as e->e|Ok surface->let surface_token=token c and frames=Hashtbl.create 4 in let acquire()=match Surface.acquire surface with Error _ as e->e|Ok Surface.Timeout->Ok`Timeout|Ok Occluded->Ok`Occluded|Ok Device_lost->Ok`Device_lost|Ok(Acquired frame)->let frame_token=Surface.frame_id frame in Hashtbl.add frames frame_token frame;Ok(`Acquired{Ogpu.Backend.frame_token})in let take f frame=match Hashtbl.find_opt frames frame.Ogpu.Backend.frame_token with None->error"Ogpu_metal.Backend.surface"Ogpu.Error.Invalid_state"frame token is stale"|Some native->match f surface native with Error _ as e->e|Ok()->Hashtbl.remove frames frame.frame_token;Ok()in Ok{Ogpu.Backend.surface_token;configure=(fun x->Surface.configure surface x);acquire;present=take Surface.present;discard=take Surface.discard;destroy_surface=(fun()->if Hashtbl.length frames<>0 then error"Ogpu_metal.Backend.destroy_surface"Ogpu.Error.Invalid_state"surface has outstanding frames"else(Surface.destroy surface;Ok()))}in
    Ok{Ogpu.Backend.device_token;device_handle=Device.Private.handle device;capabilities=Device.capabilities device;create_buffer;create_texture;create_depth_texture;create_stencil_texture;create_pipeline;create_queue;create_surface;destroy_device=(fun()->Hashtbl.iter(fun _ sampler->ignore(Sampler.destroy sampler))c.sampler_cache;Hashtbl.clear c.sampler_cache;Device.destroy device)}in
  {Ogpu.Backend.create_device},c
