type resource=Buffer of Buffer.t|Texture of Texture.t
module Native_metal=Metal
module Metal=struct
  include Native_metal
  type indirect_primitive=Native_metal.Indirect_command_buffer.Render_command.primitive=Point|Line|Line_strip|Triangle|Triangle_strip
end
type plan_owner={queue_token:int64;mutable last_epoch:int64;dependencies:int64 list;pipeline_keys:string list;commands:Metal.Indirect_command_buffer.Render_command.t list;samplers:Metal.Sampler.t list;encoders:Metal.Shader_argument_encoder.t list;buffers:Metal.Buffer.t list}
type retired={queue_token:int64;epoch:int64;icb:Metal.Indirect_command_buffer.t;owner:plan_owner option}
type retained_plan_stats={builds:int64;hits:int64;misses:int64;evictions:int64;executions:int64;entries:int;capacity:int}
type control={resources:(int64,resource)Hashtbl.t;pipelines:(string,Pipeline.t)Hashtbl.t;pipeline_tokens:(int64,Pipeline.t)Hashtbl.t;sampler_cache:(Ogpu.Types.sampler_descriptor,Sampler.t)Hashtbl.t;plan_owners:(string,plan_owner)Hashtbl.t;active_queues:(int64,unit)Hashtbl.t;completed_epochs:(int64,int64)Hashtbl.t;mutable retired:retired list;mutable plan_cache:Metal.Retained_render_plan.t option;mutable cleanup_error:Metal.error option;mutable device_live:bool;mutable next:int64;mutable plan_builds:int64;mutable plan_hits:int64;mutable plan_misses:int64;mutable plan_evictions:int64;mutable plan_executions:int64;plan_capacity:int;layer:Metal.Metal_layer.t option}
let error op kind text=Error(Ogpu.Error.make op kind text)
let token c=let x=c.next in c.next<-Int64.succ x;x
let register_pipeline c pipeline=Hashtbl.replace c.pipelines(Pipeline.key pipeline)pipeline
let sampler_cache_entries c=Hashtbl.length c.sampler_cache
let retained_plans_enabled=true
let retained_plan_entries c=Hashtbl.length c.plan_owners
let retired_plan_entries c=List.length c.retired
let retained_plan_stats c={builds=c.plan_builds;hits=c.plan_hits;misses=c.plan_misses;evictions=c.plan_evictions;executions=c.plan_executions;entries=Hashtbl.length c.plan_owners;capacity=c.plan_capacity}
let disable_retained_plans_for_test c=Option.iter(fun cache->ignore(Metal.Retained_render_plan.destroy cache))c.plan_cache;c.plan_cache<-None
module Private=struct let disable_retained_plans_for_test=disable_retained_plans_for_test end
let first_error current=function
  |Ok()->current
  |Error error->(match current with Some _->current|None->Some error)
let destroy_owner_front owner=let failure=List.fold_left(fun e command->first_error e(Metal.Indirect_command_buffer.Render_command.destroy command))None owner.commands in List.fold_left(fun e encoder->first_error e(Metal.Shader_argument_encoder.destroy encoder))failure owner.encoders
let destroy_owner_back owner failure=let failure=List.fold_left(fun e buffer->first_error e(Metal.Buffer.destroy buffer))failure owner.buffers in List.fold_left(fun e sampler->first_error e(Metal.Sampler.destroy sampler))failure owner.samplers
let destroy_owner owner=destroy_owner_back owner(destroy_owner_front owner)
let destroy_retired retired=let failure=Option.fold~none:None~some:destroy_owner_front retired.owner in let failure=first_error failure(Metal.Indirect_command_buffer.destroy retired.icb)in Option.fold~none:failure~some:(fun owner->destroy_owner_back owner failure)retired.owner
let create ?device:provided_device ?layer ?(retained_plan_capacity=64) ()=
  let c={resources=Hashtbl.create 32;pipelines=Hashtbl.create 16;pipeline_tokens=Hashtbl.create 16;sampler_cache=Hashtbl.create 64;plan_owners=Hashtbl.create 64;active_queues=Hashtbl.create 4;completed_epochs=Hashtbl.create 4;retired=[];plan_cache=None;cleanup_error=None;device_live=false;next=1L;plan_builds=0L;plan_hits=0L;plan_misses=0L;plan_evictions=0L;plan_executions=0L;plan_capacity=retained_plan_capacity;layer}in
  let record_cleanup failure=Option.iter(fun error->if Option.is_none c.cleanup_error then c.cleanup_error<-Some error)failure in
  let obtain_device()=match provided_device with Some device->Ok device|None->Device.system_default()in
  let create_device()=if c.device_live then error"Ogpu_metal.Backend.create_device"Ogpu.Error.Invalid_state"adapter already owns a live device"else match obtain_device()with Error _ as e->e|Ok device->c.device_live<-true;let device_token=token c in
    let handoff~key~generation:_ icb=c.plan_evictions<-Int64.succ c.plan_evictions;let owner:plan_owner option=Hashtbl.find_opt c.plan_owners key in Hashtbl.remove c.plan_owners key;let queue_token=Option.fold~none:0L~some:(fun(owner:plan_owner)->owner.queue_token)owner and epoch=Option.fold~none:0L~some:(fun(owner:plan_owner)->owner.last_epoch)owner in let retired={queue_token;epoch;icb;owner}in let completed=Option.value(Hashtbl.find_opt c.completed_epochs queue_token)~default:0L in if epoch=0L||epoch<=completed||not(Hashtbl.mem c.active_queues queue_token)then record_cleanup(destroy_retired retired)else c.retired<-retired::c.retired in
    (match Metal.Retained_render_plan.create~device:(Device.Private.metal device)~capacity:retained_plan_capacity~on_evict:handoff()with Ok cache->c.plan_cache<-Some cache|Error _->());
    let invalidate_resource id=match c.plan_cache with None->()|Some cache->let keys=Hashtbl.fold(fun key(owner:plan_owner) acc->if List.mem id owner.dependencies then key::acc else acc)c.plan_owners[]in List.iter(fun key->ignore(Metal.Retained_render_plan.invalidate cache key))keys in
    let create_buffer descriptor=match Buffer.create device~memory:Buffer.Shared descriptor with Error _ as e->e|Ok buffer->let id=token c in Hashtbl.add c.resources id(Buffer buffer);Ok{Ogpu.Backend.token=id;write=(fun offset bytes->Buffer.write_bytes device buffer~dst_offset:offset bytes);read=(fun offset length->Buffer.read_bytes device buffer~offset~length);destroy=(fun()->invalidate_resource(Buffer.id buffer);match Buffer.destroy buffer with Error _ as e->e|Ok()->Hashtbl.remove c.resources id;Ok())}in
    let create_texture_format ~format ~host_read descriptor=match Texture.create device~memory:(if descriptor.Ogpu.Types.sample_count=1&&host_read then Texture.Shared else Device_local)~format descriptor with Error _ as e->e|Ok texture->let id=token c in Hashtbl.add c.resources id(Texture texture);Ok{Ogpu.Backend.token=id;write=(fun _ _->error"Ogpu_metal.Backend.texture.write"Ogpu.Error.Unsupported"use a transfer pass for textures");read=(fun offset length->if not host_read then error"Ogpu_metal.Backend.depth.read"Ogpu.Error.Unsupported"depth textures are not host readable"else if offset<>0L||descriptor.height<=0||length mod descriptor.height<>0 then error"Ogpu_metal.Backend.texture.read"Ogpu.Error.Invalid_argument"texture read range is invalid"else Texture.read_bytes device texture~mip_level:0~bytes_per_row:(length/descriptor.height));destroy=(fun()->invalidate_resource(Texture.id texture);match Texture.destroy texture with Error _ as e->e|Ok()->Hashtbl.remove c.resources id;Ok())}in
    let create_texture descriptor=create_texture_format~format:Texture.Rgba8_unorm~host_read:true descriptor in
    let create_depth_texture descriptor=create_texture_format~format:Texture.Depth32_float~host_read:false descriptor in
    let create_stencil_texture descriptor=create_texture_format~format:Texture.Stencil8~host_read:false descriptor in
    let invalidate_pipeline key=match c.plan_cache with None->()|Some cache->let keys=Hashtbl.fold(fun plan_key(owner:plan_owner) acc->if List.mem key owner.pipeline_keys then plan_key::acc else acc)c.plan_owners[]in List.iter(fun plan_key->ignore(Metal.Retained_render_plan.invalidate cache plan_key))keys in
    let compact_sampler_cache()=
      Hashtbl.filter_map_inplace(fun _ sampler->match Sampler.destroy sampler with Ok()->None|Error _->Some sampler)c.sampler_cache
    in
    let create_pipeline portable=match Hashtbl.find_opt c.pipelines(Ogpu.Pipeline.cache_key portable)with None->error"Ogpu_metal.Backend.create_pipeline"Ogpu.Error.Invalid_argument"portable pipeline was not registered with the Metal adapter"|Some pipeline->let id=token c in Hashtbl.add c.pipeline_tokens id pipeline;Ok{Ogpu.Backend.pipeline_token=id;destroy_pipeline=(fun()->invalidate_pipeline(Pipeline.key pipeline);match Pipeline.destroy pipeline with Error _ as e->e|Ok()->Hashtbl.remove c.pipeline_tokens id;Ok())}in
    let native_resource token=Hashtbl.find_opt c.resources token in
    let create_queue()=match Queue.create device with Error _ as e->e|Ok queue->let queue_token=token c in Hashtbl.add c.active_queues queue_token();
      let submit command ~resources ~pipelines=let find id=Option.bind(List.assoc_opt id resources)native_resource in
        let one_pipeline()=match pipelines with[id]->Hashtbl.find_opt c.pipeline_tokens id|_->None in
        let native_render_descriptor (descriptor:Ogpu.Render_pass.descriptor)=
          let fact usage (value:Ogpu.Render_pass.texture)=match find value.id with Some(Texture texture)->Render_pass.attachment device texture~usage|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render attachment graph is incomplete"in
          let colors=Array.map(function None->Ok None|Some(color:Ogpu.Render_pass.color)->match fact Render_target color.texture with Error _ as e->e|Ok texture->(match color.resolve with None->Ok(Some{color with texture})|Some resolve->Result.map(fun resolve->Some{color with texture;resolve=Some resolve})(fact Resolve_target resolve)))descriptor.colors in
          if Array.exists Result.is_error colors then Array.find_opt Result.is_error colors|>Option.get|>Result.map(fun _->assert false)else let depth=match descriptor.depth with None->Ok None|Some(d:Ogpu.Render_pass.depth)->Result.map(fun texture->Some{d with texture})(fact Render_target d.texture)and stencil=match descriptor.stencil with None->Ok None|Some(s:Ogpu.Render_pass.stencil)->Result.map(fun texture->Some{s with texture})(fact Render_target s.texture)in match depth,stencil with Error e,_->Error e|_,Error e->Error e|Ok depth,Ok stencil->Ok{descriptor with colors=Array.map Result.get_ok colors;depth;stencil}in
        let result=match command with
        |Ogpu.Backend.Transfer descriptions->let pass=Ogpu.Transfer_pass.create(Device.Private.handle device)in let b id=match find id with Some(Buffer x)->Ok x|_->error"Ogpu_metal.Backend.transfer"Ogpu.Error.Invalid_argument"buffer graph is incomplete"and t id=match find id with Some(Texture x)->Ok x|_->error"Ogpu_metal.Backend.transfer"Ogpu.Error.Invalid_argument"texture graph is incomplete"in let rec replay i=if i=Array.length descriptions then match Transfer_pass.create device pass~buffers:(List.filter_map(fun(_,tok)->match native_resource tok with Some(Buffer x)->Some x|_->None)resources)~textures:(List.filter_map(fun(_,tok)->match native_resource tok with Some(Texture x)->Some x|_->None)resources)with Error _ as e->e|Ok encoded->Queue.submit_transfer_pass queue encoded else let next=match descriptions.(i)with
          |Ogpu.Transfer_pass.Copy_buffer(a,ao,d,do_,n)->(match b a,b d with Ok a,Ok d->Ogpu.Transfer_pass.copy_buffer pass~src:(Result.get_ok(Transfer_pass.buffer device a))~src_offset:ao~dst:(Result.get_ok(Transfer_pass.buffer device d))~dst_offset:do_~length:n|Error e,_->Error e|_,Error e->Error e)
          |Fill_buffer(a,o,n,v)->(match b a with Error _ as e->e|Ok a->Ogpu.Transfer_pass.fill_buffer pass(Result.get_ok(Transfer_pass.buffer device a))~offset:o~length:n~value:v)
          |Buffer_to_texture(a,o,row,image,d,mip,origin,extent)->(match b a,t d with Ok a,Ok d->Ogpu.Transfer_pass.buffer_to_texture pass~src:(Result.get_ok(Transfer_pass.buffer device a))~offset:o~bytes_per_row:row~bytes_per_image:image~dst:(Result.get_ok(Transfer_pass.texture device d))~mip~origin~extent|Error e,_->Error e|_,Error e->Error e)
          |Texture_to_buffer(a,mip,origin,extent,d,o,row,image)->(match t a,b d with Ok a,Ok d->Ogpu.Transfer_pass.texture_to_buffer pass~src:(Result.get_ok(Transfer_pass.texture device a))~mip~origin~extent~dst:(Result.get_ok(Transfer_pass.buffer device d))~offset:o~bytes_per_row:row~bytes_per_image:image|Error e,_->Error e|_,Error e->Error e)
          |Copy_texture(a,am,ao,d,dm,do_,extent)->(match t a,t d with Ok a,Ok d->Ogpu.Transfer_pass.copy_texture pass~src:(Result.get_ok(Transfer_pass.texture device a))~src_mip:am~src_origin:ao~dst:(Result.get_ok(Transfer_pass.texture device d))~dst_mip:dm~dst_origin:do_~extent|Error e,_->Error e|_,Error e->Error e)in match next with Error _ as e->e|Ok()->replay(i+1)in replay 0
        |Compute description->(match one_pipeline()with None->error"Ogpu_metal.Backend.compute"Ogpu.Error.Invalid_argument"compute pipeline graph is incomplete"|Some pipeline->let slots=Array.to_list description.groups|>List.concat_map(fun(_,xs)->xs)|>List.map fst and ids=Array.to_list description.commands|>List.filter_map(function Ogpu.Command.Declare_resource r->Some r.resource_id|_->None)in if List.length slots<>List.length ids then error"Ogpu_metal.Backend.compute"Ogpu.Error.Invalid_argument"binding/resource cardinality differs"else let native_id id=match find id with Some(Buffer buffer)->Buffer.id buffer|_->id in let bindings=List.map2(fun index id->match find id with Some(Buffer buffer)->Ok{Compute_pass.id=Buffer.id buffer;index;buffer}|_->error"Ogpu_metal.Backend.compute"Ogpu.Error.Invalid_argument"compute buffer graph is incomplete")slots ids in if List.exists Result.is_error bindings then List.find Result.is_error bindings|>Result.map(fun _->assert false)else let description=Ogpu.Compute_pass.Private.map_resource_ids native_id description in match Compute_pass.create device(Ogpu.Compute_pass.Private.of_description description)~pipeline~bindings:(List.map Result.get_ok bindings)with Error _ as e->e|Ok encoded->Queue.submit_compute_pass queue encoded)
        |Render submission->
          let sampler_binding(s:Ogpu.Render_pass.sampler_binding)=match Hashtbl.find_opt c.sampler_cache s.sampler with Some sampler->Ok{Render_pass.stage=(match s.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=s.index;sampler}|None->(if Hashtbl.length c.sampler_cache>=64 then compact_sampler_cache();if Hashtbl.length c.sampler_cache>=64 then error"Ogpu_metal.Backend.sampler"Ogpu.Error.Invalid_state"all bounded sampler entries are referenced by in-flight retained plans"else match Sampler.create device s.sampler with Error _ as e->e|Ok sampler->Hashtbl.add c.sampler_cache s.sampler sampler;Ok{Render_pass.stage=(match s.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=s.index;sampler})in
          let pipeline_by_key key=pipelines|>List.find_map(fun id->match Hashtbl.find_opt c.pipeline_tokens id with Some p when Pipeline.key p=key->Some p|_->None)in
          let convert(portable_draw:Ogpu.Render_pass.draw)=
            match pipeline_by_key portable_draw.pipeline_key with None->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render pipeline graph is incomplete"|Some pipeline->
            let buffer_binding(b:Ogpu.Render_pass.buffer_binding)=match find b.buffer_id with Some(Buffer buffer)->Ok{Render_pass.stage=(match b.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=b.index;buffer;offset=b.offset}|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render buffer graph is incomplete"and texture_binding(t:Ogpu.Render_pass.texture_binding)=match find t.texture_id with Some(Texture texture)->Ok{Render_pass.stage=(match t.stage with Ogpu.Command.Vertex->Render_pass.Vertex|Fragment->Fragment|_->assert false);index=t.index;texture}|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render texture graph is incomplete"in
            let buffers=List.map buffer_binding portable_draw.buffers and textures=List.map texture_binding portable_draw.textures and samplers=List.map sampler_binding portable_draw.samplers in
            if List.exists Result.is_error buffers||List.exists Result.is_error textures||List.exists Result.is_error samplers then error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render binding graph is invalid"else
            let index=match portable_draw.index with None->Ok None|Some(kind,id,offset,count)->match find id with Some(Buffer buffer)->Ok(Some((match kind with Ogpu.Render_pass.Uint16->Render_pass.Uint16|Uint32->Uint32),buffer,offset,count))|_->error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"render index graph is incomplete"in
            Result.map(fun index->{Render_pass.pipeline;buffers=List.map Result.get_ok buffers;textures=List.map Result.get_ok textures;samplers=List.map Result.get_ok samplers;primitive=(match portable_draw.primitive with Ogpu.Render_pass.Triangle_list->Render_pass.Triangle_list|Triangle_strip->Triangle_strip);vertex_start=portable_draw.vertex_start;vertex_count=portable_draw.vertex_count;index})index in
          let draws=List.map convert(Ogpu.Render_pass.submission_draws submission)in
          if List.exists Result.is_error draws then(List.find Result.is_error draws|>Result.map(fun _->assert false))else
          let descriptor=Ogpu.Render_pass.descriptor(Ogpu.Render_pass.submission_pass submission)and attachments=resources|>List.filter_map(fun(_,tok)->match native_resource tok with Some(Texture x)->Some x|_->None)in
          let portable_pass=Ogpu.Render_pass.submission_pass submission in
          let native_draws=List.map Result.get_ok draws in
          let argument_pipeline(draw:Render_pass.draw)=Option.is_some(Pipeline.Private.argument_function draw.pipeline)in
          let exact_argument_abi(draw:Render_pass.draw)=match draw.index,draw.buffers,draw.textures,draw.samplers,Pipeline.Private.argument_function draw.pipeline with None,[{stage=Render_pass.Vertex;index=0;_}],[{stage=Render_pass.Fragment;index=0;_}],[{stage=Render_pass.Fragment;index=1;_}],Some _->true|_->false in
          let maybe_indirect encoded=
            let eligible draw=retained_plans_enabled&&exact_argument_abi draw in
            match c.plan_cache with None when List.exists argument_pipeline native_draws->error"Ogpu_metal.Backend.render"Ogpu.Error.Unsupported"retained plan cache is unavailable"|None->Ok(encoded,None)|Some _ when not(List.for_all eligible native_draws)->Ok(encoded,None)|Some cache->
            let pipeline_identities=List.map(fun(draw:Render_pass.draw)->Pipeline.Private.native_identity draw.pipeline)native_draws in
            let generation=Int64.logand(List.fold_left(fun hash(id,value)->Int64.logxor(Int64.mul(Int64.logxor(Int64.mul hash 1099511628211L)id)1099511628211L)value)1469598103934665603L pipeline_identities)Int64.max_int in
            let identity=Marshal.to_string(Ogpu.Render_pass.submission_draws submission,pipeline_identities)[]in
            let key=Printf.sprintf"render:%Ld:%s"queue_token(Digest.to_hex(Digest.string identity))in
            let made=ref None in
            let icb_descriptor=Metal.Indirect_command_buffer.descriptor~inherit_buffers:false~inherit_pipeline_state:false~max_vertex_buffer_bind_count:1~max_fragment_buffer_bind_count:2~command_types:[Metal.Indirect_command_buffer.Indirect_draw]()in
            let dependencies=native_draws|>List.concat_map(fun(draw:Render_pass.draw)->List.map(fun(b:Render_pass.buffer_binding)->Buffer.id b.buffer)draw.buffers@List.map(fun(t:Render_pass.texture_binding)->Texture.id t.texture)draw.textures)|>List.sort_uniq Int64.compare and pipeline_keys=List.map(fun(draw:Render_pass.draw)->Pipeline.key draw.pipeline)native_draws|>List.sort_uniq String.compare in
            let build icb =
              let commands=ref[] and encoders=ref[] and buffers=ref[] and samplers=ref[] in
              let fail e=List.iter(fun x->ignore(Metal.Indirect_command_buffer.Render_command.destroy x))!commands;let count=List.length!commands in if count>0 then ignore(Metal.Indirect_command_buffer.reset icb~location:0~length:count);List.iter(fun x->ignore(Metal.Shader_argument_encoder.destroy x))!encoders;List.iter(fun x->ignore(Metal.Buffer.destroy x))!buffers;List.iter(fun x->ignore(Metal.Sampler.destroy x))!samplers;Error e in
              let configure command (draw:Render_pass.draw) argument_buffer =
                let pipeline=match Pipeline.Private.native draw.pipeline with Render pipeline->pipeline|Compute _->assert false in
                match Metal.Indirect_command_buffer.Render_command.set_pipeline command pipeline with Error _ as e->e|Ok()->
                let binding:Render_pass.buffer_binding=List.hd draw.buffers in
                match Metal.Indirect_command_buffer.Render_command.set_vertex_buffer command~index:binding.index~offset:binding.offset(Buffer.Private.metal binding.buffer)with Error _ as e->e|Ok()->
                match Metal.Indirect_command_buffer.Render_command.set_fragment_buffer command~index:1~offset:0L argument_buffer with Error _ as e->e|Ok()->
                Metal.Indirect_command_buffer.Render_command.draw_primitives command~primitive:(match draw.primitive with Triangle_list->Metal.Triangle|Triangle_strip->Metal.Triangle_strip)~vertex_start:draw.vertex_start~vertex_count:draw.vertex_count()
              in
              let rec loop i=function
                |[]->let owner={queue_token;last_epoch=0L;dependencies;pipeline_keys;commands=List.rev!commands;samplers=List.rev!samplers;encoders=List.rev!encoders;buffers=List.rev!buffers}in made:=Some owner;Ok()
                |(draw:Render_pass.draw)::rest->
                  let function_=Option.get(Pipeline.Private.argument_function draw.pipeline)in
                  match Metal.Function.argument_encoder function_~buffer_index:1L with Error e->fail e|Ok encoder->
                  let length=Metal.Shader_argument_encoder.encoded_length encoder in
                  match Metal.Buffer.create~device:(Device.Private.metal device)~length~storage:Metal.Buffer.Shared()with Error e->ignore(Metal.Shader_argument_encoder.destroy encoder);fail e|Ok argument_buffer->
                  encoders:=encoder::!encoders;buffers:=argument_buffer::!buffers;
                  match Metal.Shader_argument_encoder.set_argument_buffer encoder argument_buffer~offset:0L()with Error e->fail e|Ok()->
                  let texture=(List.hd draw.textures).Render_pass.texture and classic_sampler=(List.hd draw.samplers).Render_pass.sampler in
                  match Metal.Shader_argument_encoder.set encoder~index:0L(Metal.Shader_argument_encoder.Texture(Texture.Private.metal texture))with Error e->fail e|Ok()->
                  match Sampler.Private.create_argument device(Sampler.Private.descriptor classic_sampler)with Error e->fail e|Ok sampler->samplers:=sampler::!samplers;
                  match Metal.Shader_argument_encoder.set encoder~index:1L(Metal.Shader_argument_encoder.Sampler sampler)with Error e->fail e|Ok()->
                  match Metal.Indirect_command_buffer.Render_command.at icb i with Error e->fail e|Ok command->
                  commands:=command::!commands;let configured=configure command draw argument_buffer in
                  match configured with Error e->fail e|Ok()->loop(i+1)rest
              in loop 0 native_draws
            in
            (match Metal.Retained_render_plan.find_or_create cache~key~generation~command_count:(List.length native_draws)~descriptor:icb_descriptor~build with Error e->c.plan_misses<-Int64.succ c.plan_misses;Error(Adapter.error~operation:"Ogpu_metal.Backend.render_plan"e)|Ok(icb,hit)->if hit then c.plan_hits<-Int64.succ c.plan_hits else(c.plan_misses<-Int64.succ c.plan_misses;c.plan_builds<-Int64.succ c.plan_builds;Option.iter(fun owner->Hashtbl.replace c.plan_owners key owner)!made);let owner=Hashtbl.find c.plan_owners key in let unique id values=List.fold_left(fun kept value->if List.exists(fun old->id old=id value)kept then kept else value::kept)[]values|>List.rev in let vertex_buffers=native_draws|>List.map(fun(draw:Render_pass.draw)->(List.hd draw.buffers).buffer)|>unique Buffer.id|>List.map Buffer.Private.metal and textures=native_draws|>List.map(fun(draw:Render_pass.draw)->(List.hd draw.textures).texture)|>unique Texture.id|>List.map Texture.Private.metal in Ok(Render_pass.with_indirect encoded icb~vertex_buffers~fragment_buffers:owner.buffers~textures,Some key))in
          let has_argument=List.exists argument_pipeline native_draws in
          let rendered=if has_argument&&not(List.for_all exact_argument_abi native_draws)then error"Ogpu_metal.Backend.render"Ogpu.Error.Invalid_argument"argument-buffer render batch has mixed or noncanonical bindings"else if has_argument&&not retained_plans_enabled then error"Ogpu_metal.Backend.render"Ogpu.Error.Unsupported"argument-buffer rendering requires retained ICB support"else match native_render_descriptor descriptor with Error _ as e->e|Ok descriptor->match Ogpu.Render_pass.create~raster_state:(Ogpu.Render_pass.raster_state portable_pass)?stencil_state:(Ogpu.Render_pass.stencil_state portable_pass)(Device.Private.handle device)descriptor with Error _ as e->e|Ok pass->match Render_pass.create_batch device pass~attachments native_draws with Error _ as e->e|Ok encoded->match maybe_indirect encoded with Error _ as e->e|Ok(encoded,key)->match Queue.submit_render_pass queue encoded with Error _ as e->e|Ok receipt->Option.iter(fun key->c.plan_executions<-Int64.succ c.plan_executions;Option.iter(fun(owner:plan_owner)->owner.last_epoch<-receipt.epoch)(Hashtbl.find_opt c.plan_owners key))key;Ok receipt in rendered in
        Result.map(fun(receipt:Queue.receipt)->{Ogpu.Backend.epoch=receipt.epoch})result in
      let complete_through epoch=match Queue.wait_through queue epoch with Error _ as e->e|Ok()->Hashtbl.replace c.completed_epochs queue_token epoch;let ready,later=List.partition(fun(retired:retired)->retired.queue_token=queue_token&&retired.epoch<=epoch)c.retired in c.retired<-later;List.iter(fun retired->record_cleanup(destroy_retired retired))ready;match c.cleanup_error with None->Ok()|Some e->Error(Adapter.error~operation:"Ogpu_metal.Backend.complete_through"e)in
      let destroy_queue()=match Queue.destroy queue with Error _ as e->e|Ok()->Hashtbl.remove c.active_queues queue_token;Ok()in
      Ok{Ogpu.Backend.queue_token;submit;complete_through;destroy_queue}in
    let create_surface configuration=match c.layer with None->error"Ogpu_metal.Backend.create_surface"Ogpu.Error.Unsupported"adapter was created without a typed Metal layer"|Some layer->match Surface.create device~layer configuration with Error _ as e->e|Ok surface->let surface_token=token c and frames=Hashtbl.create 4 in let acquire()=match Surface.acquire surface with Error _ as e->e|Ok Surface.Timeout->Ok`Timeout|Ok Occluded->Ok`Occluded|Ok Device_lost->Ok`Device_lost|Ok(Acquired frame)->let frame_token=Surface.frame_id frame in Hashtbl.add frames frame_token frame;Ok(`Acquired{Ogpu.Backend.frame_token})in let take f frame=match Hashtbl.find_opt frames frame.Ogpu.Backend.frame_token with None->error"Ogpu_metal.Backend.surface"Ogpu.Error.Invalid_state"frame token is stale"|Some native->match f surface native with Error _ as e->e|Ok()->Hashtbl.remove frames frame.frame_token;Ok()in Ok{Ogpu.Backend.surface_token;configure=(fun x->Surface.configure surface x);acquire;present=take Surface.present;discard=take Surface.discard;destroy_surface=(fun()->if Hashtbl.length frames<>0 then error"Ogpu_metal.Backend.destroy_surface"Ogpu.Error.Invalid_state"surface has outstanding frames"else(Surface.destroy surface;Ok()))}in
    let destroy_device()=if Hashtbl.length c.active_queues<>0 then error"Ogpu_metal.Backend.destroy_device"Ogpu.Error.Invalid_state"device has active queues"else(Option.iter(fun cache->record_cleanup(match Metal.Retained_render_plan.destroy cache with Ok()->None|Error e->Some e))c.plan_cache;c.plan_cache<-None;List.iter(fun retired->record_cleanup(destroy_retired retired))c.retired;c.retired<-[];Hashtbl.iter(fun _ owner->record_cleanup(destroy_owner owner))c.plan_owners;Hashtbl.clear c.plan_owners;Hashtbl.iter(fun _ sampler->ignore(Sampler.destroy sampler))c.sampler_cache;Hashtbl.clear c.sampler_cache;let destroyed=Device.destroy device in match destroyed,c.cleanup_error with Error _ as e,_->e|Ok(),Some e->Error(Adapter.error~operation:"Ogpu_metal.Backend.destroy_device"e)|Ok(),None->c.device_live<-false;Ok())in
    Ok{Ogpu.Backend.device_token;device_handle=Device.Private.handle device;capabilities=Device.capabilities device;create_buffer;create_texture;create_depth_texture;create_stencil_texture;create_pipeline;create_queue;create_surface;destroy_device}in
  {Ogpu.Backend.create_device},c
