type binding={id:int64;index:int;buffer:Buffer.t}
type t={pipeline:Pipeline.t;bindings:binding list;dispatch:int*int*int}
let error op kind text=Error(Ogpu.Error.make op kind text)
let create device pass ~pipeline ~bindings=let op="Ogpu_metal.Compute_pass.create"in let d=Ogpu.Compute_pass.describe pass in match Pipeline.validate device pipeline with Error _ as e->e|Ok()->if Pipeline.key pipeline<>d.pipeline_key then error op Ogpu.Error.Invalid_argument"portable and native pipeline identities differ"else match Pipeline.Private.native pipeline with Render _->error op Ogpu.Error.Invalid_argument"render pipeline cannot execute compute"|Compute _->match d.dispatch with Indirect _->error op Ogpu.Error.Unsupported"indirect portable compute dispatch is not qualified"|Direct{x;y;z}->
  if Array.exists(fun(group,entries)->group<>0||List.exists(fun(_,kind)->kind<>Ogpu.Binding.Buffer)entries)d.groups then error op Ogpu.Error.Unsupported"this slice supports buffer bindings in group zero"else let expected=Array.to_list d.groups|>List.concat_map(fun(_,xs)->xs)|>List.map fst|>List.sort compare and actual=List.map(fun b->b.index)bindings|>List.sort compare in if expected<>actual||List.length actual<>List.length(List.sort_uniq compare actual)then error op Ogpu.Error.Invalid_argument"compute binding slots differ from the portable pass"else let declared=Array.to_list d.commands|>List.filter_map(function Ogpu.Command.Declare_resource r->Some r.resource_id|_->None)|>List.sort_uniq Int64.compare and supplied=List.map(fun b->b.id)bindings|>List.sort_uniq Int64.compare in if declared<>supplied then error op Ogpu.Error.Invalid_argument"compute resource declarations differ from typed bindings"else let rec validate=function []->Ok{pipeline;bindings;dispatch=x,y,z}|b::_ when b.id<>Buffer.id b.buffer->error op Ogpu.Error.Invalid_argument"compute binding ID differs from its buffer"|b::bs->match Buffer.descriptor device b.buffer with Error _ as e->e|Ok _->validate bs in validate bindings
module Private=struct
  let retain value=let releases=ref[]in let keep retain release=match retain()with Error _ as e->e|Ok()->releases:=release::!releases;Ok()in let fs=(fun()->keep(fun()->Pipeline.Private.retain_submission value.pipeline)(fun()->Pipeline.Private.release_submission value.pipeline))::List.map(fun b->fun()->keep(fun()->Buffer.Private.retain_submission b.buffer)(fun()->Buffer.Private.release_submission b.buffer))value.bindings in let rec loop=function []->Ok(List.rev!releases)|f::xs->match f()with Ok()->loop xs|Error _ as e->List.iter(fun r->r())!releases;e in loop fs
  let encode command value=let op="Ogpu_metal.Compute_pass.encode"in let native=match Pipeline.Private.native value.pipeline with Compute p->p|Render _->assert false in match Metal.Compute_encoder.create command with Error e->Error(Adapter.error~operation:op e)|Ok encoder->let rec bind=function []->Ok()|b::bs->match Metal.Compute_encoder.set_buffer encoder~index:b.index~offset:0L(Buffer.Private.metal b.buffer)with Error e->Error(Adapter.error~operation:op e)|Ok()->bind bs in match Metal.Compute_encoder.set_pipeline encoder native with Error e->Error(Adapter.error~operation:op e)|Ok()->match bind value.bindings with Error _ as e->e|Ok()->let x,y,z=value.dispatch in match Metal.Compute_encoder.dispatch_threads encoder~threads:(x,y,z)~threadgroup:(min x 64,1,1)with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.end_encoding encoder with Error e->Error(Adapter.error~operation:op e)|Ok()->Ok()
end
