open Ogpu.Pipeline
module Option = struct include Option let for_all f = function None -> true | Some value -> f value end
type native=Compute of Metal.Compute_pipeline.t|Render of Metal.Render_pipeline.t
type pipeline_kind
type t={native:native;library:Metal.Library.t;functions:Metal.Function.t list;descriptor_destroy:(unit->unit)option;handle:pipeline_kind Ogpu.Handle.t;device:Device.t;portable:Ogpu.Pipeline.t;mutable dead:bool;mutable submission_uses:int;mutable destroy_requested:bool}
type cache={values:t Ogpu.Cache.t}
let error op kind message=Error(Ogpu.Error.make op kind message)
let key value=Ogpu.Pipeline.cache_key value.portable
let label value=Ogpu.Pipeline.label value.portable
let device_id value=Device.id value.device
let generation value=Ogpu.Handle.generation value.handle
let destroyed value=value.dead
let validate device value=Ogpu.Handle.validate_for~operation:"Ogpu_metal.Pipeline.validate"(Device.Private.handle device)value.handle
let finish_destroy value=let native_result=match value.native with Compute x->Metal.Compute_pipeline.destroy x|Render x->Metal.Render_pipeline.destroy x in match native_result with Error e->Error(Adapter.error~operation:"Ogpu_metal.Pipeline.destroy" e)|Ok()->List.iter(fun f->ignore(Metal.Function.destroy f))value.functions;ignore(Metal.Library.destroy value.library);Option.iter(fun f->f())value.descriptor_destroy;Device.Private.detach_resource value.device;Ok()
let destroy value=if value.dead then Ok()else if value.submission_uses>0 then(Ogpu.Handle.destroy value.handle;value.dead<-true;value.destroy_requested<-true;Ok())else match finish_destroy value with Error _ as failure->failure|Ok()->Ogpu.Handle.destroy value.handle;value.dead<-true;Ok()
let create_cache~capacity=Result.map(fun values->{values})(Ogpu.Cache.create~capacity~on_evict:(fun~key:_ value _->ignore(destroy value)))
let cache_length value=Ogpu.Cache.length value.values
let cache_keys_lru value=Ogpu.Cache.keys_lru value.values
let clear_cache value=Ogpu.Cache.clear value.values
let metal_kind=function Ogpu.Shader.Uniform_buffer|Storage_buffer->`Buffer|Sampled_texture|Storage_texture->`Texture|Sampler->`Sampler
let reflected_kind (value:Metal.Binding.t)=match value.kind with Buffer_binding _->`Buffer|Texture_binding _->`Texture|Sampler_binding->`Sampler|_->`Other
let validate_reflection op shader bindings =
  let expected=Ogpu.Shader.bindings shader in
  if List.exists(fun(b:Ogpu.Shader.binding)->b.group<>0)expected then error op Ogpu.Error.Invalid_argument"Metal foundation maps only bind group zero"else
  let expected=List.sort compare(List.map(fun(b:Ogpu.Shader.binding)->b.binding,metal_kind b.kind)expected)and actual=bindings|>List.filter(fun(b:Metal.Binding.t)->b.used)|>List.map(fun(b:Metal.Binding.t)->Int64.to_int b.index,reflected_kind b)|>List.sort compare in
  if expected<>actual then error op Ogpu.Error.Invalid_argument"native Metal reflection does not match OGPU slots and resource classes"else Ok()
let compile_library op device shader=if Ogpu.Shader.backend shader<>"metal"then error op Ogpu.Error.Invalid_argument"shader backend is not metal"else match Metal.Library.compile_source~device:(Device.Private.metal device)?label:(Ogpu.Shader.label shader)(Bytes.to_string(Ogpu.Shader.bytes shader))with Ok x->Ok x|Error e->Error(Adapter.error~operation:op e)
let cached cache device portable build=let k=Ogpu.Pipeline.cache_key portable in match Ogpu.Cache.get cache.values k with Some value->(match validate device value with Ok()->Ok value|Error _ as e->e)|None->match build()with Error _ as e->e|Ok value->(match Ogpu.Cache.insert cache.values k value with Ok()->Ok value|Error e->ignore(destroy value);Error e)
let create_compute cache device descriptor=let op="Ogpu_metal.Pipeline.create_compute"in if Device.destroyed device then error op Ogpu.Error.Stale_handle"device is destroyed"else match Ogpu.Pipeline.create_compute(Device.capabilities device)descriptor with Error _ as e->e|Ok portable->cached cache device portable(fun()->match compile_library op device descriptor.shader with Error _ as e->e|Ok library->match Metal.Function.find~library descriptor.entry with Error e->ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok function_->match Metal.Compute_pipeline.create~label:(Option.value descriptor.label~default:descriptor.entry)~reflection:true function_ with Error e->ignore(Metal.Function.destroy function_);ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok pipeline->match Option.value(Metal.Compute_pipeline.bindings pipeline)~default:[]|>validate_reflection op descriptor.shader with Error e->ignore(Metal.Compute_pipeline.destroy pipeline);ignore(Metal.Function.destroy function_);ignore(Metal.Library.destroy library);Error e|Ok()->let value={native=Compute pipeline;library;functions=[function_];descriptor_destroy=None;handle=Ogpu.Handle.create~device:(Device.Private.handle device);device;portable;dead=false;submission_uses=0;destroy_requested=false}in Device.Private.attach_resource device;Ok value)
let create_render cache device descriptor=let op="Ogpu_metal.Pipeline.create_render"in if Device.destroyed device then error op Ogpu.Error.Stale_handle"device is destroyed"else match Ogpu.Pipeline.create_render(Device.capabilities device)descriptor with Error _ as e->e|Ok portable->cached cache device portable(fun()->match compile_library op device descriptor.vertex with Error _ as e->e|Ok library->let color=match descriptor.color_format with Rgba8_unorm->Metal.Texture.Rgba8_unorm|Bgra8_unorm->Metal.Texture.Bgra8_unorm in match Metal.Compiler.create(Device.Private.metal device)with Error e->ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok compiler->let fragment=Option.map(fun(_:Ogpu.Shader.t)->Option.get descriptor.fragment_entry)descriptor.fragment in match Metal.Compiler.create_render_pipeline?label:descriptor.label?fragment~reflection:true~raster_sample_count:descriptor.sample_count~color_formats:[color]compiler~library~vertex:descriptor.vertex_entry with Error e->ignore(Metal.Compiler.destroy compiler);ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok pipeline->ignore(Metal.Compiler.destroy compiler);let reflection=Option.value(Metal.Render_pipeline.reflection pipeline)~default:{vertex=[];fragment=[];tile=[];object_=[];mesh=[]}in match validate_reflection op descriptor.vertex reflection.vertex with Error e->ignore(Metal.Render_pipeline.destroy pipeline);ignore(Metal.Library.destroy library);Error e|Ok()->let value={native=Render pipeline;library;functions=[];descriptor_destroy=None;handle=Ogpu.Handle.create~device:(Device.Private.handle device);device;portable;dead=false;submission_uses=0;destroy_requested=false}in Device.Private.attach_resource device;Ok value)
let create_compute_runtime_msl=create_compute
let create_render_runtime_msl=create_render
let load_offline op device artifact=match Metal.Library.load_file~device:(Device.Private.metal device)(Shader_artifact.metallib artifact)with Ok x->Ok x|Error e->Error(Adapter.error~operation:op e)
let artifact_matches artifact shader=(Shader_artifact.metadata artifact).source_hash=Digest.to_hex(Digest.string(Bytes.to_string(Ogpu.Shader.bytes shader)))
let create_compute_offline cache device artifact descriptor=let op="Ogpu_metal.Pipeline.create_compute_offline"in if not(artifact_matches artifact descriptor.shader)then error op Ogpu.Error.Invalid_argument"offline artifact provenance differs from compute shader"else if Device.destroyed device then error op Ogpu.Error.Stale_handle"device is destroyed"else match Ogpu.Pipeline.create_compute(Device.capabilities device)descriptor with Error _ as e->e|Ok portable->cached cache device portable(fun()->match load_offline op device artifact with Error _ as e->e|Ok library->match Metal.Function.find~library descriptor.entry with Error e->ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok function_->match Metal.Compute_pipeline.create~label:(Option.value descriptor.label~default:descriptor.entry)~reflection:true function_ with Error e->ignore(Metal.Function.destroy function_);ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok pipeline->match Option.value(Metal.Compute_pipeline.bindings pipeline)~default:[]|>validate_reflection op descriptor.shader with Error e->ignore(Metal.Compute_pipeline.destroy pipeline);ignore(Metal.Function.destroy function_);ignore(Metal.Library.destroy library);Error e|Ok()->let value={native=Compute pipeline;library;functions=[function_];descriptor_destroy=None;handle=Ogpu.Handle.create~device:(Device.Private.handle device);device;portable;dead=false;submission_uses=0;destroy_requested=false}in Device.Private.attach_resource device;Ok value)
let create_render_offline cache device artifact descriptor=let op="Ogpu_metal.Pipeline.create_render_offline"in if not(artifact_matches artifact descriptor.vertex&&Option.for_all(artifact_matches artifact)descriptor.fragment)then error op Ogpu.Error.Invalid_argument"offline artifact provenance differs from render shaders"else if Device.destroyed device then error op Ogpu.Error.Stale_handle"device is destroyed"else match Ogpu.Pipeline.create_render(Device.capabilities device)descriptor with Error _ as e->e|Ok portable->cached cache device portable(fun()->match load_offline op device artifact with Error _ as e->e|Ok library->let color=match descriptor.color_format with Rgba8_unorm->Metal.Texture.Rgba8_unorm|Bgra8_unorm->Metal.Texture.Bgra8_unorm in match Metal.Compiler.create(Device.Private.metal device)with Error e->ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok compiler->let fragment=Option.map(fun(_:Ogpu.Shader.t)->Option.get descriptor.fragment_entry)descriptor.fragment in match Metal.Compiler.create_render_pipeline?label:descriptor.label?fragment~reflection:true~raster_sample_count:descriptor.sample_count~color_formats:[color]compiler~library~vertex:descriptor.vertex_entry with Error e->ignore(Metal.Compiler.destroy compiler);ignore(Metal.Library.destroy library);Error(Adapter.error~operation:op e)|Ok pipeline->ignore(Metal.Compiler.destroy compiler);let reflection=Option.value(Metal.Render_pipeline.reflection pipeline)~default:{vertex=[];fragment=[];tile=[];object_=[];mesh=[]}in match validate_reflection op descriptor.vertex reflection.vertex with Error e->ignore(Metal.Render_pipeline.destroy pipeline);ignore(Metal.Library.destroy library);Error e|Ok()->let value={native=Render pipeline;library;functions=[];descriptor_destroy=None;handle=Ogpu.Handle.create~device:(Device.Private.handle device);device;portable;dead=false;submission_uses=0;destroy_requested=false}in Device.Private.attach_resource device;Ok value)
module Private=struct
  type nonrec native=native=Compute of Metal.Compute_pipeline.t|Render of Metal.Render_pipeline.t
  let native value=value.native
  let portable value=value.portable
  let retain_submission value=if value.dead then Error(Ogpu.Error.make"Ogpu_metal.Pipeline.retain_submission"Ogpu.Error.Stale_handle"pipeline is destroyed")else(value.submission_uses<-value.submission_uses+1;Ok())
  let release_submission value=value.submission_uses<-value.submission_uses-1;if value.submission_uses=0&&value.destroy_requested then ignore(finish_destroy value)
end
