type cleanup=unit->unit
type native_completion=Classic of Metal.Command_buffer.t|Command4 of Metal.Command4.Submission.t*Metal.Command4.Command_buffer.t*Metal.Command4.Allocator.t
type pending={epoch:int64;command:native_completion;cleanup:cleanup list}
type t={device:Device.t;metal:Metal.Command_queue.t;submission:Ogpu.Submission.t;mutable command4:Metal.Command4.Queue.t option;mutable pending:pending list;mutable fail_next:bool;mutable dead:bool}
type receipt={epoch:int64}
let error op kind message=Error(Ogpu.Error.make op kind message)
let create ?(max_frames=3) device=let op="Ogpu_metal.Queue.create"in if Device.destroyed device then error op Ogpu.Error.Stale_handle"device is destroyed"else
  match Ogpu.Submission.create~max_frames(Device.Private.handle device)with Error _ as e->e|Ok submission->match Metal.Command_queue.create(Device.Private.metal device)with Error e->Error(Adapter.error~operation:op e)|Ok metal->Device.Private.attach_resource device;Ok{device;metal;submission;command4=None;pending=[];fail_next=false;dead=false}
let destroyed value=value.dead
let in_flight value=Ogpu.Submission.in_flight value.submission
let completed_epoch value=Ogpu.Submission.completed_epoch value.submission
let inject_next_error value=value.fail_next<-true
let validate_buffer device buffer=match Buffer.descriptor device buffer with Ok _->Ok()|Error e->Error e
let validate_texture device texture=match Texture.descriptor device texture with Ok _->Ok()|Error e->Error e
let validate_operation device=function
  |Command.Private.Copy(a,ao,b,bo,n)->(match validate_buffer device a with Error _ as e->e|Ok()->match validate_buffer device b with Error _ as e->e|Ok()->let ad=Result.get_ok(Buffer.descriptor device a)and bd=Result.get_ok(Buffer.descriptor device b)in if ao>Int64.sub ad.size n||bo>Int64.sub bd.size n then error"Ogpu_metal.Queue.submit"Ogpu.Error.Invalid_argument"copy exceeds buffer"else Ok())
  |Command.Private.Compute(_,_,b,_)->validate_buffer device b
  |Command.Private.Dispatch(p,b,_)->(match Pipeline.validate device p with Error _ as e->e|Ok()->validate_buffer device b)
  |Command.Private.Clear(t,_)->validate_texture device t
  |Command.Private.Draw_triangle(p,t)->(match Pipeline.validate device p with Error _ as e->e|Ok()->validate_texture device t)
let rec validate_all device=function []->Ok()|x::xs->match validate_operation device x with Error _ as e->e|Ok()->validate_all device xs
let retain_all operations=
  let retained=ref[]in let keep retain release=match retain()with Error _ as failure->failure|Ok()->retained:=release::!retained;Ok()in
  let rec loop=function
    |[]->Ok(List.rev!retained)
    |operation::rest->let resources=match operation with
      |Command.Private.Copy(a,_,b,_,_)->[(fun()->keep(fun()->Buffer.Private.retain_submission a)(fun()->Buffer.Private.release_submission a));(fun()->keep(fun()->Buffer.Private.retain_submission b)(fun()->Buffer.Private.release_submission b))]
      |Compute(_,_,b,_)->[(fun()->keep(fun()->Buffer.Private.retain_submission b)(fun()->Buffer.Private.release_submission b))]
      |Dispatch(p,b,_)->[(fun()->keep(fun()->Pipeline.Private.retain_submission p)(fun()->Pipeline.Private.release_submission p));(fun()->keep(fun()->Buffer.Private.retain_submission b)(fun()->Buffer.Private.release_submission b))]
      |Clear(t,_)->[(fun()->keep(fun()->Texture.Private.retain_submission t)(fun()->Texture.Private.release_submission t))]
      |Draw_triangle(p,t)->[(fun()->keep(fun()->Pipeline.Private.retain_submission p)(fun()->Pipeline.Private.release_submission p));(fun()->keep(fun()->Texture.Private.retain_submission t)(fun()->Texture.Private.release_submission t))]in
      let rec each=function []->loop rest|retain::tail->match retain()with Ok()->each tail|Error _ as failure->failure in each resources in
  match loop operations with Ok _ as success->success|Error _ as failure->List.iter(fun release->release())!retained;failure
let encode command operations =
  let op="Ogpu_metal.Queue.submit"in
  let cleanup=ref[]in let add f=cleanup:=f::!cleanup in
  let rec loop=function
    |[]->Ok(!cleanup)
    |Command.Private.Copy(a,ao,b,bo,n)::rest->(match Metal.Blit_encoder.create command with Error e->Error(Adapter.error~operation:op e)|Ok encoder->(match Metal.Blit_encoder.copy_buffer encoder~source:(Buffer.Private.metal a)~source_offset:ao~destination:(Buffer.Private.metal b)~destination_offset:bo~length:n with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Blit_encoder.end_encoding encoder with Error e->Error(Adapter.error~operation:op e)|Ok()->loop rest))
    |Command.Private.Compute(source,entry,buffer,threads)::rest->(match Metal.Library.compile_source~device:(Metal.Command_buffer.device command)source with Error e->Error(Adapter.error~operation:op e)|Ok library->add(fun()->ignore(Metal.Library.destroy library));match Metal.Function.find~library entry with Error e->Error(Adapter.error~operation:op e)|Ok function_->add(fun()->ignore(Metal.Function.destroy function_));match Metal.Compute_pipeline.create function_ with Error e->Error(Adapter.error~operation:op e)|Ok pipeline->add(fun()->ignore(Metal.Compute_pipeline.destroy pipeline));match Metal.Compute_encoder.create command with Error e->Error(Adapter.error~operation:op e)|Ok encoder->(match Metal.Compute_encoder.set_pipeline encoder pipeline with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.set_buffer encoder~index:0~offset:0L(Buffer.Private.metal buffer)with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.dispatch_threads encoder~threads:(threads,1,1)~threadgroup:(min threads 64,1,1)with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.end_encoding encoder with Error e->Error(Adapter.error~operation:op e)|Ok()->loop rest))
    |Command.Private.Dispatch(pipeline,buffer,threads)::rest->(match Pipeline.Private.native pipeline with Render _->error op Ogpu.Error.Invalid_argument"render pipeline used for compute dispatch"|Compute pipeline->match Metal.Compute_encoder.create command with Error e->Error(Adapter.error~operation:op e)|Ok encoder->(match Metal.Compute_encoder.set_pipeline encoder pipeline with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.set_buffer encoder~index:0~offset:0L(Buffer.Private.metal buffer)with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.dispatch_threads encoder~threads:(threads,1,1)~threadgroup:(min threads 64,1,1)with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Compute_encoder.end_encoding encoder with Error e->Error(Adapter.error~operation:op e)|Ok()->loop rest))
    |Command.Private.Clear(texture,color)::rest->(match Metal.Render_encoder.create command~target:(Texture.Private.metal texture)~clear:color()with Error e->Error(Adapter.error~operation:op e)|Ok encoder->match Metal.Render_encoder.end_encoding encoder with Error e->Error(Adapter.error~operation:op e)|Ok()->loop rest)
    |Command.Private.Draw_triangle(pipeline,texture)::rest->(match Pipeline.Private.native pipeline with Compute _->error op Ogpu.Error.Invalid_argument"compute pipeline used for render draw"|Render pipeline->match Metal.Render_encoder.create command~target:(Texture.Private.metal texture)~clear:(0.,0.,0.,1.)()with Error e->Error(Adapter.error~operation:op e)|Ok encoder->match Metal.Render_encoder.set_pipeline encoder pipeline with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Render_encoder.draw_triangles encoder~first:0~count:3()with Error e->Error(Adapter.error~operation:op e)|Ok()->match Metal.Render_encoder.end_encoding encoder with Error e->Error(Adapter.error~operation:op e)|Ok()->loop rest)
  in loop operations
let submit value command =let op="Ogpu_metal.Queue.submit"in if value.dead then error op Ogpu.Error.Stale_handle"queue is destroyed"else if value.fail_next then(value.fail_next<-false;error op Ogpu.Error.Device_lost"injected submission failure")else let operations=Command.Private.operations command in
  match validate_all value.device operations with Error _ as e->e|Ok()->match retain_all operations with Error _ as e->e|Ok retained->
  let rollback failure=List.iter(fun release->release())retained;failure in
  match Ogpu.Submission.submit value.submission(Command.Private.portable command)~resources:[]with Error _ as e->rollback e|Ok receipt->match Metal.Command_buffer.create value.metal()with Error e->rollback(Error(Adapter.error~operation:op e))|Ok native->match encode native operations with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error e)|Ok cleanup->match Metal.Command_buffer.commit native with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error(Adapter.error~operation:op e))|Ok()->value.pending<-value.pending@[{epoch=receipt.id;command=Classic native;cleanup=retained@cleanup}];Ok{epoch=receipt.id}
let command4_queue value=match value.command4 with Some queue->Ok queue|None->match Metal.Command4.Queue.create_default(Device.Private.metal value.device)with Error e->Error(Adapter.error~operation:"Ogpu_metal.Queue.command4" e)|Ok queue->value.command4<-Some queue;Ok queue
let submit_render_pass value pass=let op="Ogpu_metal.Queue.submit_render_pass"in if value.dead then error op Ogpu.Error.Stale_handle"queue is destroyed"else if Render_pass.Private.requires_command4 pass then
  match command4_queue value with Error _ as e->e|Ok queue->match Render_pass.Private.retain pass with Error _ as e->e|Ok retained->let rollback e=List.iter(fun f->f())retained;e in
  (match Metal.Command4.Allocator.create(Device.Private.metal value.device)with Error e->rollback(Error(Adapter.error~operation:op e))|Ok allocator->match Metal.Command4.Command_buffer.create allocator~label:"ogpu-metal-render-pass"()with Error e->ignore(Metal.Command4.Allocator.destroy allocator);rollback(Error(Adapter.error~operation:op e))|Ok native->match Render_pass.Private.encode_command4 native pass with Error e->ignore(Metal.Command4.Command_buffer.destroy native);ignore(Metal.Command4.Allocator.destroy allocator);rollback(Error e)|Ok cleanup->match Metal.Command4.Command_buffer.end_recording native with Error e->ignore(Metal.Command4.Command_buffer.destroy native);ignore(Metal.Command4.Allocator.destroy allocator);rollback(Error(Adapter.error~operation:op e))|Ok()->let portable=Ogpu.Command.begin_encoder()in(match Render_pass.Private.encode_portable pass portable with Error e->ignore(Metal.Command4.Command_buffer.destroy native);ignore(Metal.Command4.Allocator.destroy allocator);rollback(Error e)|Ok()->match Ogpu.Command.end_encoder portable with Error e->ignore(Metal.Command4.Command_buffer.destroy native);ignore(Metal.Command4.Allocator.destroy allocator);rollback(Error e)|Ok()->match Ogpu.Submission.submit value.submission portable~resources:[]with Error _ as e->ignore(Metal.Command4.Command_buffer.destroy native);ignore(Metal.Command4.Allocator.destroy allocator);rollback e|Ok receipt->match Metal.Command4.Queue.commit queue[native]with Error e->ignore(Metal.Command4.Command_buffer.destroy native);ignore(Metal.Command4.Allocator.destroy allocator);rollback(Error(Adapter.error~operation:op e))|Ok submission->value.pending<-value.pending@[{epoch=receipt.id;command=Command4(submission,native,allocator);cleanup=retained@cleanup}];Ok{epoch=receipt.id})) else match Render_pass.Private.retain pass with Error _ as e->e|Ok retained->let rollback e=List.iter(fun f->f())retained;e in match Metal.Command_buffer.create value.metal()with Error e->rollback(Error(Adapter.error~operation:op e))|Ok native->match Render_pass.Private.encode native pass with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error e)|Ok cleanup->let portable=Ogpu.Command.begin_encoder()in(match Render_pass.Private.encode_portable pass portable with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error e)|Ok()->match Ogpu.Command.end_encoder portable with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error e)|Ok()->match Ogpu.Submission.submit value.submission portable~resources:[]with Error _ as e->ignore(Metal.Command_buffer.destroy native);rollback e|Ok receipt->match Metal.Command_buffer.commit native with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error(Adapter.error~operation:op e))|Ok()->value.pending<-value.pending@[{epoch=receipt.id;command=Classic native;cleanup=retained@cleanup}];Ok{epoch=receipt.id})
let submit_typed value op retain encode=if value.dead then error op Ogpu.Error.Stale_handle"queue is destroyed"else match retain()with Error _ as e->e|Ok retained->let rollback e=List.iter(fun f->f())retained;e in match Metal.Command_buffer.create value.metal()with Error e->rollback(Error(Adapter.error~operation:op e))|Ok native->match encode native with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error e)|Ok()->let portable=Ogpu.Command.begin_encoder()in(match Ogpu.Command.end_encoder portable with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error e)|Ok()->match Ogpu.Submission.submit value.submission portable~resources:[]with Error _ as e->ignore(Metal.Command_buffer.destroy native);rollback e|Ok receipt->match Metal.Command_buffer.commit native with Error e->ignore(Metal.Command_buffer.destroy native);rollback(Error(Adapter.error~operation:op e))|Ok()->value.pending<-value.pending@[{epoch=receipt.id;command=Classic native;cleanup=retained}];Ok{epoch=receipt.id})
let submit_transfer_pass value pass=submit_typed value"Ogpu_metal.Queue.submit_transfer_pass"(fun()->Transfer_pass.Private.retain pass)(fun command->Transfer_pass.Private.encode command pass)
let submit_compute_pass value pass=submit_typed value"Ogpu_metal.Queue.submit_compute_pass"(fun()->Compute_pass.Private.retain pass)(fun command->Compute_pass.Private.encode command pass)
let wait_through value epoch=let op="Ogpu_metal.Queue.wait_through"in if epoch<=completed_epoch value||epoch>Int64.of_int(max_int)then error op Ogpu.Error.Invalid_argument"completion epoch is invalid"else
  let ready,later=List.partition(fun (p:pending)->p.epoch<=epoch)value.pending in
  if ready=[] then error op Ogpu.Error.Invalid_argument"epoch was not submitted"else
  let finish p=match p.command with Classic command->(match Metal.Command_buffer.wait_until_completed command with Error e->Error(Adapter.error~operation:op e)|Ok()->ignore(Metal.Command_buffer.destroy command);Ok())|Command4(submission,command,allocator)->(match Metal.Command4.Submission.wait submission with Error e->Error(Adapter.error~operation:op e)|Ok()->ignore(Metal.Command4.Submission.destroy submission);ignore(Metal.Command4.Command_buffer.destroy command);ignore(Metal.Command4.Allocator.destroy allocator);Ok())in
  let rec completed=function []->Ok()|p::ps->match finish p with Error _ as e->e|Ok()->List.iter(fun f->f())p.cleanup;completed ps in
  match completed ready with Error _ as e->e|Ok()->value.pending<-later;Ogpu.Submission.complete_through value.submission epoch
let destroy value=let op="Ogpu_metal.Queue.destroy"in if value.dead then Ok()else if value.pending<>[]then error op Ogpu.Error.Invalid_state"queue has commands in flight"else match Metal.Command_queue.destroy value.metal with Error e->Error(Adapter.error~operation:op e)|Ok()->(match value.command4 with None->()|Some queue->ignore(Metal.Command4.Queue.destroy queue));value.dead<-true;Device.Private.detach_resource value.device;Ok()
