type frame_state=Live|Presented|Discarded|Stale
type frame={portable:Ogpu.Surface.frame;drawable:Metal.Drawable.t;texture:Metal.Texture.t;generation:int64;mutable state:frame_state}
type t={device:Device.t;layer:Metal.Metal_layer.t;portable:Ogpu.Surface.t;mutable frames:frame list;mutable dead:bool}
type acquire_result=Acquired of frame|Timeout|Occluded|Device_lost
let error op kind message=Error(Ogpu.Error.make op kind message)
let metal_config (value:Ogpu.Surface.configuration)=
  let format=match value.format with Bgra8_unorm->Ok Metal.Texture.Bgra8_unorm|Rgba8_unorm->error"Ogpu_metal.Surface.configure"Ogpu.Error.Invalid_argument"CAMetalLayer does not expose RGBA8 drawable format"in
  Result.map(fun format->{Metal.Metal_layer.width=value.physical_width;height=value.physical_height;format;framebuffer_only=false;maximum_drawables=max 2 value.max_acquired;allows_timeout=true;display_sync=(value.present_mode=Fifo);presents_with_transaction=false})format
let create device~layer config=let op="Ogpu_metal.Surface.create"in if Device.destroyed device then error op Ogpu.Error.Stale_handle"device is destroyed"else if not(Metal.Device.same(Device.Private.metal device)(Metal.Metal_layer.device layer))then error op Ogpu.Error.Cross_device"layer belongs to another device"else match Ogpu.Surface.create(Device.Private.handle device)config with Error _ as e->e|Ok portable->match metal_config config with Error _ as e->e|Ok native->match Metal.Metal_layer.configure layer native with Error e->Error(Adapter.error~operation:op e)|Ok()->Device.Private.attach_resource device;Ok{device;layer;portable;frames=[];dead=false}
let destroyed value=value.dead
let generation value=Ogpu.Surface.generation value.portable
let outstanding value=List.length value.frames
let frame_id (value:frame)=Ogpu.Surface.frame_id value.portable
let frame_generation (value:frame)=value.generation
let frame_texture (value:frame)=match value.state with Live->Ok value.texture|Presented|Discarded|Stale->error"Ogpu_metal.Surface.frame_texture"Ogpu.Error.Stale_handle"frame is consumed or stale"
let release frame=ignore(Metal.Texture.destroy frame.texture);ignore(Metal.Drawable.destroy frame.drawable)
let stale_frames value=List.iter(fun frame->if frame.state=Live then(frame.state<-Stale;release frame))value.frames;value.frames<-[]
let configure value config=let op="Ogpu_metal.Surface.configure"in if value.dead then error op Ogpu.Error.Stale_handle"surface is destroyed"else match metal_config config with Error _ as e->e|Ok native->stale_frames value;match Metal.Metal_layer.configure value.layer native with Error e->Error(Adapter.error~operation:op e)|Ok()->Ogpu.Surface.configure value.portable config
let resize value~logical_width~logical_height~physical_width~physical_height=let current=Metal.Metal_layer.config value.layer in let format=if current.format=Metal.Texture.Bgra8_unorm then Ogpu.Surface.Bgra8_unorm else Rgba8_unorm in let config={Ogpu.Surface.logical_width;logical_height;physical_width;physical_height;format;present_mode=(if current.display_sync then Fifo else Immediate);max_acquired=current.maximum_drawables}in configure value config
let set_availability value availability=Ogpu.Surface.set_availability value.portable availability
let acquire value=let op="Ogpu_metal.Surface.acquire"in if value.dead then error op Ogpu.Error.Stale_handle"surface is destroyed"else match Ogpu.Surface.acquire value.portable with Error _ as e->e|Ok Timeout->Ok Timeout|Ok Occluded->Ok Occluded|Ok Device_lost->Ok Device_lost|Ok(Acquired portable)->match Metal.Drawable.acquire value.layer with Error e->ignore(Ogpu.Surface.discard value.portable portable);Error(Adapter.error~operation:op e)|Ok(Error Metal.Drawable.Timeout_or_unavailable)->ignore(Ogpu.Surface.discard value.portable portable);Ok Timeout|Ok(Ok drawable)->match Metal.Drawable.texture drawable with Error e->ignore(Metal.Drawable.destroy drawable);ignore(Ogpu.Surface.discard value.portable portable);Error(Adapter.error~operation:op e)|Ok texture->let frame={portable;drawable;texture;generation=generation value;state=Live}in value.frames<-value.frames@[frame];Ok(Acquired frame)
let validate op value frame=if value.dead then error op Ogpu.Error.Stale_handle"surface is destroyed"else if frame.generation<>generation value||frame.state=Stale then error op Ogpu.Error.Stale_handle"frame generation is stale"else match frame.state with Live->Ok()|Presented|Discarded->error op Ogpu.Error.Invalid_state"frame was already consumed"|Stale->error op Ogpu.Error.Stale_handle"frame generation is stale"
let remove value frame=value.frames<-List.filter(fun candidate->candidate!=frame)value.frames
let present value frame=let op="Ogpu_metal.Surface.present"in match validate op value frame with Error _ as e->e|Ok()->match Metal.Drawable.present frame.drawable()with Error e->Error(Adapter.error~operation:op e)|Ok()->match Ogpu.Surface.present value.portable frame.portable with Error e->Error e|Ok()->frame.state<-Presented;remove value frame;release frame;Ok()
let discard value frame=let op="Ogpu_metal.Surface.discard"in match validate op value frame with Error _ as e->e|Ok()->match Ogpu.Surface.discard value.portable frame.portable with Error _ as e->e|Ok()->frame.state<-Discarded;remove value frame;release frame;Ok()
let destroy value=if not value.dead then(stale_frames value;Ogpu.Surface.destroy value.portable;value.dead<-true;Device.Private.detach_resource value.device)
