open Ogpu_metal
let get=function Ok x->x|Error e->failwith(Ogpu.Error.to_string e)
let get_metal=function Ok x->x|Error e->failwith(Format.asprintf"%a"Metal.pp_error e)
let source={|#include <metal_stdlib>
using namespace metal;
kernel void portable_compute(device uint *v [[buffer(0)]], uint i [[thread_position_in_grid]]) { v[i] = v[i] * 3 + 1; }
|}
let ()=match Device.system_default()with Error _->print_endline"ogpu_metal portable passes: skipped (no device)"|Ok device->
  let before=get_metal(Metal.Release_queue.stats())in let queue=get(Queue.create device)in
  let bd usage size : Ogpu.Types.buffer_descriptor={label=None;size;usage}in
  let a=get(Buffer.create device~memory:Buffer.Shared(bd[Copy_src;Copy_dst]512L))and b=get(Buffer.create device~memory:Buffer.Shared(bd[Copy_src;Copy_dst]512L))in
  let td : Ogpu.Types.texture_descriptor={label=None;width=2;height=2;depth=1;mip_levels=1;sample_count=1;usage=[Texture_binding;Texture_copy_src;Texture_copy_dst]}in
  let ta=get(Texture.create device~memory:Texture.Shared~format:Texture.Rgba8_unorm td)and tb=get(Texture.create device~memory:Texture.Shared~format:Texture.Rgba8_unorm td)in
  let pass=Ogpu.Transfer_pass.create(Device.Private.handle device)in let pa=get(Transfer_pass.buffer device a)and pb=get(Transfer_pass.buffer device b)and pta=get(Transfer_pass.texture device ta)and ptb=get(Transfer_pass.texture device tb)in
  get(Ogpu.Transfer_pass.fill_buffer pass pa~offset:0L~length:512L~value:37);get(Ogpu.Transfer_pass.copy_buffer pass~src:pa~src_offset:0L~dst:pb~dst_offset:0L~length:512L);let origin : Ogpu.Transfer_pass.origin={x=0;y=0;z=0}and extent : Ogpu.Transfer_pass.extent={width=2;height=2;depth=1}in get(Ogpu.Transfer_pass.buffer_to_texture pass~src:pb~offset:0L~bytes_per_row:256L~bytes_per_image:512L~dst:pta~mip:0~origin~extent);get(Ogpu.Transfer_pass.copy_texture pass~src:pta~src_mip:0~src_origin:origin~dst:ptb~dst_mip:0~dst_origin:origin~extent);get(Ogpu.Transfer_pass.fill_buffer pass pb~offset:0L~length:512L~value:0);get(Ogpu.Transfer_pass.texture_to_buffer pass~src:ptb~mip:0~origin~extent~dst:pb~offset:0L~bytes_per_row:256L~bytes_per_image:512L);
  let encoded=get(Transfer_pass.create device pass~buffers:[a;b]~textures:[ta;tb])in let receipt=get(Queue.submit_transfer_pass queue encoded)in get(Queue.wait_through queue receipt.epoch);let bytes=get(Buffer.read_bytes device b~offset:0L~length:512)in for i=0 to 511 do let expected=if i<8||(i>=256&&i<264)then 37 else 0 in if Char.code(Bytes.get bytes i)<>expected then failwith"portable transfer row-pitch mismatch"done;
  let shader=get(Ogpu.Shader.create{backend="metal";label=None;bytes=Bytes.of_string source;entry_points=[{name="portable_compute";stage=Compute}];bindings=[{group=0;binding=0;kind=Storage_buffer;visibility=[Compute]}]})in let group_layout=get(Ogpu.Binding.create_layout[{binding=0;kind=Ogpu.Binding.Buffer;visibility=[Ogpu.Binding.Compute]}])in let layout=get(Ogpu.Binding.create_pipeline_layout~device:(Device.Private.handle device)~capabilities:(Device.capabilities device)[0,group_layout])in let group=get(Ogpu.Binding.create_group layout~group:0[{binding=0;resource=Ogpu.Binding.buffer(Buffer.Private.resource_handle a)}])in let cache=get(Pipeline.create_cache~capacity:1)in let pd : Ogpu.Pipeline.compute_descriptor={backend="metal";label=None;layout;shader;entry="portable_compute"}in let pipeline=get(Pipeline.create_compute cache device pd)in let resource : Ogpu.Compute_pass.resource={id=Buffer.id a;access=Ogpu.Command.Read_write;stages=[Compute_stage]}in let portable=get(Ogpu.Compute_pass.create(Device.Private.handle device)~limits:(Device.capabilities device).limits~pipeline:(Pipeline.Private.portable pipeline)~layout~groups:[|0,group|]~resources:[|resource|]~dispatch:(Direct{x=4;y=1;z=1}))in let input=Bytes.make 16 '\000'in for i=0 to 3 do Bytes.set_int32_le input(i*4)(Int32.of_int i)done;get(Buffer.write_bytes device a~dst_offset:0L input);
  let compute=get(Compute_pass.create device portable~pipeline~bindings:[{id=Buffer.id a;index=0;buffer=a}])in for _=1 to 3 do let r=get(Queue.submit_compute_pass queue compute)in get(Queue.wait_through queue r.epoch)done;let out=get(Buffer.read_bytes device a~offset:0L~length:16)in for i=0 to 3 do if Bytes.get_int32_le out(i*4)<>Int32.of_int(i*27+13)then failwith"portable compute result mismatch"done;
  Pipeline.clear_cache cache;List.iter(fun x->get(Buffer.destroy x))[a;b];List.iter(fun x->get(Texture.destroy x))[ta;tb];get(Queue.destroy queue);get(Device.destroy device);ignore(get_metal(Metal.Release_queue.drain()));let after=get_metal(Metal.Release_queue.stats())in if after.live_handles<>before.live_handles-1 then failwith"portable pass live-handle delta";print_endline"ogpu_metal portable passes: transfer graph + compute x3, zero delta"
