open Ogpu_metal
let get=function Ok x->x|Error e->failwith(Ogpu.Error.to_string e)
let metal=function Ok x->x|Error e->failwith(Format.asprintf"%a"Metal.pp_error e)
let source={|#include <metal_stdlib>
using namespace metal;
struct V { float4 position [[position]]; };
vertex V scene_vertex(uint i [[vertex_id]]) { constexpr float2 p[3]={{-1.,-1.},{3.,-1.},{-1.,3.}}; V v;v.position=float4(p[i],0.,1.);return v; }
fragment float4 scene_fragment(){return float4(1.,0.,0.5,1.);}
|}
let source3={|#include <metal_stdlib>
using namespace metal;
struct Out { float4 position [[position]]; };
inline float scene_double(const device uchar *p){uint lo=*reinterpret_cast<const device uint*>(p);uint hi=*reinterpret_cast<const device uint*>(p+4);ulong bits=(ulong(hi)<<32)|ulong(lo);float sign=(hi>>31)==0?1.:-1.;int exponent=int((bits>>52)&0x7fful);ulong fraction=bits&0xffffffffffffful;if(exponent==0)return sign*ldexp(float(fraction)/4503599627370496.,-1022);return sign*ldexp(1.+float(fraction)/4503599627370496.,exponent-1023);}
vertex Out scene_vertex(uint i [[vertex_id]],const device uchar *input [[buffer(0)]]){const device uchar*p=input+i*68;Out v;v.position=float4(scene_double(p),scene_double(p+8),scene_double(p+16),1.);return v;}
fragment float4 scene_fragment(){return float4(1.,0.,0.5,1.);}
|}
let source3_textured={|#include <metal_stdlib>
using namespace metal;
struct Out { float4 position [[position]]; float2 uv; };
inline float scene_double(const device uchar *p){uint lo=*reinterpret_cast<const device uint*>(p);uint hi=*reinterpret_cast<const device uint*>(p+4);ulong bits=(ulong(hi)<<32)|ulong(lo);float sign=(hi>>31)==0?1.:-1.;int exponent=int((bits>>52)&0x7fful);ulong fraction=bits&0xffffffffffffful;if(exponent==0)return sign*ldexp(float(fraction)/4503599627370496.,-1022);return sign*ldexp(1.+float(fraction)/4503599627370496.,exponent-1023);}
vertex Out scene_vertex(uint i [[vertex_id]],const device uchar *input [[buffer(0)]]){const device uchar*p=input+i*68;Out v;v.position=float4(scene_double(p),scene_double(p+8),scene_double(p+16),1.);v.uv=float2(scene_double(p+52),scene_double(p+60));return v;}
fragment float4 scene_fragment(Out value [[stage_in]],texture2d<float> image [[texture(1)]],sampler sampling [[sampler(2)]]){return image.sample(sampling,value.uv);}
|}
let source3_shadow={|#include <metal_stdlib>
using namespace metal;
struct Out { float4 position [[position]]; float4 color; float3 world; float3 normal; };
inline float scene_double(const device uchar *p){uint lo=*reinterpret_cast<const device uint*>(p);uint hi=*reinterpret_cast<const device uint*>(p+4);ulong bits=(ulong(hi)<<32)|ulong(lo);float sign=(hi>>31)==0?1.:-1.;int exponent=int((bits>>52)&0x7fful);ulong fraction=bits&0xffffffffffffful;if(exponent==0)return sign*ldexp(float(fraction)/4503599627370496.,-1022);return sign*ldexp(1.+float(fraction)/4503599627370496.,exponent-1023);}
vertex Out scene_vertex(uint i [[vertex_id]],const device uchar *input [[buffer(0)]]){const device uchar*p=input+i*68;Out v;v.world=float3(scene_double(p),scene_double(p+8),scene_double(p+16));v.normal=float3(scene_double(p+24),scene_double(p+32),scene_double(p+40));v.position=float4(v.world,1.);v.color=unpack_unorm4x8_to_float(*reinterpret_cast<const device uint*>(p+48)).abgr;return v;}
inline float unpack_depth(float4 c){float3 b=round(c.rgb*255.);return(b.x*65536.+b.y*256.+b.z)/16777215.;}
fragment float4 scene_fragment(Out v [[stage_in]],const device float*p [[buffer(3)]],texture2d<float>d [[texture(4)]],sampler s [[sampler(5)]]){float4 w=float4(v.world,1.);float4 q=float4(dot(w,float4(p[0],p[1],p[2],p[3])),dot(w,float4(p[4],p[5],p[6],p[7])),dot(w,float4(p[8],p[9],p[10],p[11])),dot(w,float4(p[12],p[13],p[14],p[15])));if(q.w<=0.)return v.color;float2 uv=float2(q.x/q.w*.5+.5,.5-q.y/q.w*.5);float z=q.z/q.w;if(any(uv<0.)||any(uv>1.)||z<0.||z>1.)return v.color;float compare=z-(p[16]+p[17]*(1.-clamp(normalize(v.normal).z,0.,1.)));int radius=int(p[19]);int2 center=int2(floor(uv*float2(d.get_width(),d.get_height())));float visible=0.,count=0.;for(int y=-radius;y<=radius;y++)for(int x=-radius;x<=radius;x++){int2 a=center+int2(x,y);count+=1.;if(a.x<0||a.y<0||a.x>=int(d.get_width())||a.y>=int(d.get_height()))visible+=1.;else visible+=compare<=unpack_depth(d.sample(s,(float2(a)+.5)/float2(d.get_width(),d.get_height())))?1.:0.;}float visibility=(1.-p[18])+p[18]*visible/count;return float4(v.color.rgb*visibility,v.color.a);}
|}
let ()=match Device.system_default()with Error _->print_endline"scene execution Metal: skipped (no M1 device)"|Ok native_device->
  let before=metal(Metal.Release_queue.stats())in
  let layer=metal(Metal.Metal_layer.create(Device.Private.metal native_device)(Metal.Metal_layer.default~width:4~height:4))in
  let driver,control=Backend.create~device:native_device~layer()in
  let supported=List.filter(fun samples->samples<=(Device.capabilities native_device).Ogpu.Capabilities.limits.max_sample_count)[1;4;9;16]in
  if Scene_execution.pipeline_variants_per_sample<>48 then failwith"pipeline family/blend cardinality drift";
  let cache=get(Pipeline.create_cache~capacity:(Scene_execution.pipeline_variants_per_sample*List.length supported))in
  let configuration:Ogpu.Surface.configuration={logical_width=4;logical_height=4;physical_width=4;physical_height=4;format=Bgra8_unorm;present_mode=Fifo;max_acquired=2}in
  let renderer=get(Scene_execution.create_with_sampled_pipeline_variants driver configuration(fun device family blend samples->let bytes,vertex_bindings,fragment_bindings,groups=match family with
    |Scene_execution.Scene2->source,[],[],[]
    |Scene3|Scene3_stencil->source3,[{Ogpu.Shader.group=0;binding=0;kind=Storage_buffer;visibility=[Vertex]}],[],[0,[{Ogpu.Binding.binding=0;kind=Buffer;visibility=[Vertex]}]]
    |Scene2_textured|Scene3_textured|Scene3_textured_stencil->source3_textured,[{Ogpu.Shader.group=0;binding=0;kind=Storage_buffer;visibility=[Vertex]}],[{Ogpu.Shader.group=0;binding=1;kind=Sampled_texture;visibility=[Fragment]};{group=0;binding=2;kind=Sampler;visibility=[Fragment]}],[0,[{Ogpu.Binding.binding=0;kind=Buffer;visibility=[Vertex]};{binding=1;kind=Texture;visibility=[Fragment]};{binding=2;kind=Sampler;visibility=[Fragment]}]]
    |Scene3_shadow|Scene3_shadow_stencil->source3_shadow,[{Ogpu.Shader.group=0;binding=0;kind=Storage_buffer;visibility=[Vertex]}],[{Ogpu.Shader.group=0;binding=3;kind=Storage_buffer;visibility=[Fragment]};{group=0;binding=4;kind=Sampled_texture;visibility=[Fragment]};{group=0;binding=5;kind=Sampler;visibility=[Fragment]}],[0,[{Ogpu.Binding.binding=0;kind=Buffer;visibility=[Vertex]};{binding=3;kind=Buffer;visibility=[Fragment]};{binding=4;kind=Texture;visibility=[Fragment]};{binding=5;kind=Sampler;visibility=[Fragment]}]]in
    let vertex=get(Ogpu.Shader.create{backend="metal";label=Some"scene-execution-metal-vertex";bytes=Bytes.of_string bytes;entry_points=[{name="scene_vertex";stage=Vertex}];bindings=vertex_bindings})and fragment=get(Ogpu.Shader.create{backend="metal";label=Some"scene-execution-metal-fragment";bytes=Bytes.of_string bytes;entry_points=[{name="scene_fragment";stage=Fragment}];bindings=fragment_bindings})in
    let layouts=List.map(fun(group,entries)->group,get(Ogpu.Binding.create_layout entries))groups in let layout=get(Ogpu.Binding.create_pipeline_layout~device:(Ogpu.Backend.device_handle device)~capabilities:(Ogpu.Backend.capabilities device)layouts)in let descriptor:Ogpu.Pipeline.render_descriptor={backend="metal";label=Some"scene-execution-metal";layout;vertex;vertex_entry="scene_vertex";fragment=Some fragment;fragment_entry=Some"scene_fragment";color_format=Rgba8_unorm;depth_format=(match family with Scene_execution.Scene2|Scene2_textured->Ogpu.Pipeline.No_depth|Scene3|Scene3_textured|Scene3_shadow->Depth32_float|Scene3_stencil|Scene3_textured_stencil|Scene3_shadow_stencil->Depth32_float_stencil8);sample_count=samples}in let native=get(Pipeline.create_render_runtime_msl~blend cache native_device descriptor)in Backend.register_pipeline control native;Ok(Pipeline.Private.portable native)))in
  let indices=Bytes.make 12 '\000'in Bytes.set_int32_le indices 4 1l;Bytes.set_int32_le indices 8 2l;let mesh:Scene_execution.mesh={key="fullscreen";vertices=Bytes.make 48 '\000';vertex_count=3;indices;index_count=3}and state:Scene_execution.state={viewport=(0,0,4,4);scissor=(0,0,4,4);cull=Ogpu.Render_pass.Cull_none;depth_compare=Ogpu.Render_pass.Always;depth_write=false;depth_load=Ogpu.Render_pass.Clear;depth_clear=1.;transform_uniforms=None;stencil_state=None;stencil_load=Ogpu.Render_pass.Load;stencil_clear=0}in
  ignore(get(Scene_execution.render renderer[{mesh;state};{mesh;state}]));let pixels=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in
  let r=Char.code(Bytes.get pixels 0)and g=Char.code(Bytes.get pixels 1)and b=Char.code(Bytes.get pixels 2)in if r<>255||g<>0||b<>128 then failwith(Printf.sprintf"scene execution Metal pixel mismatch %d,%d,%d"r g b);
  List.iter(fun(blend,expected)->List.iter(fun _frame->
    ignore(get(Scene_execution.render_blended renderer[blend,{mesh;state}]));
    let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in
    let actual=Char.code(Bytes.get bytes 0),Char.code(Bytes.get bytes 1),Char.code(Bytes.get bytes 2)in
    if actual<>expected then failwith"scene execution Metal blend pixel") [1;2;60;600])
    [Ogpu.Pipeline.Replace,(255,0,128);Alpha,(255,0,128);Add,(255,0,128);
     Multiply,(0,0,0);Screen,(255,0,128);Subtract,(0,0,0)];
  let vertices3=Bytes.make(68*3)'\000'in
  List.iteri(fun index(x,y)->let offset=index*68 in Bytes.set_int64_le vertices3 offset(Int64.bits_of_float x);Bytes.set_int64_le vertices3(offset+8)(Int64.bits_of_float y);Bytes.set_int64_le vertices3(offset+16)(Int64.bits_of_float 0.))[-1.,-1.;3.,-1.;-1.,3.];
  let mesh3:Scene_execution.mesh={key="fullscreen-scene3-double68";vertices=vertices3;vertex_count=3;indices;index_count=3}in
  List.iter(fun _frame->ignore(get(Scene_execution.render_family renderer[Scene_execution.Scene3,Ogpu.Pipeline.Replace,{mesh=mesh3;state}]));let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in if Char.code(Bytes.get bytes 0)<>255||Char.code(Bytes.get bytes 2)<>128 then failwith"scene execution Metal Scene3 double68 pixel")[1;2;60;600];
  if List.mem 4 supported then List.iter(fun _frame->ignore(get(Scene_execution.render_sampled_resources renderer[Scene_execution.Scene3,Ogpu.Pipeline.Replace,None,None,4,{mesh=mesh3;state}]));let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in if Char.code(Bytes.get bytes 0)<>255||Char.code(Bytes.get bytes 2)<>128 then failwith"scene execution Metal four-sample resolve pixel")[1;2;60;600];
  List.iter(fun samples->if not(List.mem samples supported)then let before=Scene_execution.upload_bytes renderer in match Scene_execution.render_sampled_resources renderer[Scene_execution.Scene3,Ogpu.Pipeline.Replace,None,None,samples,{mesh=mesh3;state}]with Error e when e.Ogpu.Error.kind=Unsupported&&Scene_execution.upload_bytes renderer=before->()|_->failwith"unsupported native sample count was not rejected atomically")[9;16];
  let mesh_uv u v=let bytes=Bytes.copy vertices3 in for index=0 to 2 do let offset=index*68 in Bytes.set_int64_le bytes(offset+52)(Int64.bits_of_float u);Bytes.set_int64_le bytes(offset+60)(Int64.bits_of_float v)done;{mesh3 with Scene_execution.key=Printf.sprintf"textured-%g-%g"u v;vertices=bytes}in
  let levels=[|{Scene_execution.width=2;height=2;bytes=Bytes.of_string"\255\000\000\255\000\255\000\255\000\000\255\255\255\255\255\255"};{width=1;height=1;bytes=Bytes.of_string"\255\255\000\255"}|]in
  let sampler ?(min_filter=Ogpu.Types.Nearest)?(mag_filter=Ogpu.Types.Nearest)?(mip_filter=Ogpu.Types.No_mip)?(address_u=Ogpu.Types.Clamp_to_edge)?(address_v=Ogpu.Types.Clamp_to_edge)?(lod_min=0.)?(lod_max=1.)() : Ogpu.Types.sampler_descriptor={label=Some"scene-texture-test";min_filter;mag_filter;mip_filter;address_u;address_v;lod_min;lod_max;max_anisotropy=1}in
  let cases=[mesh_uv 0.1 0.1,sampler(),(255,0,0);mesh_uv 0.5 0.5,sampler~min_filter:Linear~mag_filter:Linear(),(128,128,128);mesh_uv 1.1 0.1,sampler~address_u:Repeat(),(255,0,0);mesh_uv 1.9 0.1,sampler~address_u:Mirror_repeat(),(255,0,0);mesh_uv 0.1 0.1,sampler~mip_filter:Nearest_mip~lod_min:1.~lod_max:1.(),(255,255,0)]in
  let mixed_texture:Scene_execution.sampled_texture={key="native-mixed-scene2";levels;sampler=sampler()}in
  List.iter(fun _frame->
    ignore(get(Scene_execution.render_textured renderer[
      Scene_execution.Scene2,Ogpu.Pipeline.Replace,None,{mesh;state};
      Scene_execution.Scene2_textured,Ogpu.Pipeline.Replace,Some mixed_texture,{mesh=mesh_uv 0.1 0.1;state}
    ]));
    let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in
    if Char.code(Bytes.get bytes 0)<>255||Char.code(Bytes.get bytes 1)<>0||Char.code(Bytes.get bytes 2)<>0 then
      failwith"mixed Scene2/Scene2_textured native pixel") [1;2;60;600];
  List.iteri(fun index(mesh,sampler,expected)->let texture:Scene_execution.sampled_texture={key="native-mip-chain";levels;sampler}and stable=ref None in List.iter(fun _frame->ignore(get(Scene_execution.render_textured renderer[Scene_execution.Scene3_textured,Ogpu.Pipeline.Replace,Some texture,{mesh;state}]));let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in let actual=Char.code(Bytes.get bytes 0),Char.code(Bytes.get bytes 1),Char.code(Bytes.get bytes 2)in begin if actual<>expected then let r,g,b=actual in failwith(Printf.sprintf"scene execution Metal texture case %d: %d,%d,%d"index r g b)end;let uploaded=Scene_execution.upload_bytes renderer in match !stable with None->stable:=Some uploaded|Some value when value=uploaded->()|Some _->failwith"stable native mip chain reuploaded")[1;2;60;600])cases;
  for index=0 to 64 do
    let sampler={ (sampler()) with Ogpu.Types.label=Some(Printf.sprintf"sampler-eviction-%d"index)}in
    let texture:Scene_execution.sampled_texture={key="native-sampler-eviction";levels;sampler}in
    ignore(get(Scene_execution.render_textured renderer[Scene_execution.Scene2_textured,Ogpu.Pipeline.Replace,Some texture,{mesh=mesh_uv 0.1 0.1;state}]))
  done;
  if Backend.sampler_cache_entries control<1||Backend.sampler_cache_entries control>64 then failwith"native sampler cache capacity";
  let replacement=[|{Scene_execution.width=2;height=2;bytes=Bytes.make 16 '\255'};{width=1;height=1;bytes=Bytes.of_string"\000\000\255\255"}|]in let replaced:Scene_execution.sampled_texture={key="native-mip-chain";levels=replacement;sampler=sampler()}in let before_reload=Scene_execution.upload_bytes renderer in ignore(get(Scene_execution.render_textured renderer[Scene_execution.Scene3_textured,Ogpu.Pipeline.Replace,Some replaced,{mesh=mesh_uv 0.1 0.1;state}]));if Scene_execution.upload_bytes renderer<=before_reload then failwith"texture generation replacement was not uploaded";
  let malformed={replaced with Scene_execution.key="malformed";levels=[|{Scene_execution.width=2;height=2;bytes=Bytes.make 15 '\000'}|]}and before_reject=Scene_execution.upload_bytes renderer in begin match Scene_execution.render_textured renderer[Scene_execution.Scene3_textured,Ogpu.Pipeline.Replace,Some malformed,{mesh=mesh_uv 0.1 0.1;state}]with Error _ when Scene_execution.upload_bytes renderer=before_reject->()|_->failwith"malformed texture was not rejected atomically"end;
  let shadow_vertices=Bytes.copy vertices3 in for index=0 to 2 do let offset=index*68 in Bytes.set_int64_le shadow_vertices(offset+16)(Int64.bits_of_float 0.5);Bytes.set_int64_le shadow_vertices(offset+40)(Int64.bits_of_float 1.);Bytes.set_int32_le shadow_vertices(offset+48)0xffffffffl done;
  let shadow_mesh={mesh3 with Scene_execution.key="fullscreen-scene3-shadow";vertices=shadow_vertices}in
  let shadow_aux ?(bias=0.) ?(slope=0.) key kernel strength depth =
    let snapshot:Raster2.Shadow_map.snapshot={width=1;height=1;depths=[|depth|];matrix=[|1.;0.;0.;0.;0.;1.;0.;0.;0.;0.;1.;0.;0.;0.;0.;1.|];bias={constant=bias;slope};kernel;strength}in
    let resource=get(Scene_execution.shadow_resource~key snapshot)in
    ({Scene_execution.key;buffer=resource.parameters;texture=resource.texture}:Scene_execution.auxiliary_resource)in
  List.iter(fun(kernel,expected)->let auxiliary=shadow_aux("native-shadow-"^string_of_int expected)kernel 1. 0. and stable=ref None in List.iter(fun _frame->ignore(get(Scene_execution.render_resources renderer[Scene_execution.Scene3_shadow,Ogpu.Pipeline.Replace,None,Some auxiliary,{mesh=shadow_mesh;state}]));let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in let actual=Char.code(Bytes.get bytes 0)in if actual<>expected then failwith(Printf.sprintf"scene execution Metal shadow pixel %d<>%d"actual expected);let uploaded=Scene_execution.upload_bytes renderer in match!stable with None->stable:=Some uploaded|Some value when value=uploaded->()|Some _->failwith"stable native shadow reuploaded")[1;2;60;600])
    [Raster2.Shadow_map.Tap1,0;Tap9,227;Tap25,245];
  List.iter(fun(name,auxiliary,expected)->List.iter(fun _frame->ignore(get(Scene_execution.render_resources renderer[Scene_execution.Scene3_shadow,Ogpu.Pipeline.Replace,None,Some auxiliary,{mesh=shadow_mesh;state}]));let bytes=get(Scene_execution.read_pixels renderer~bytes_per_row:16)in let actual=Char.code(Bytes.get bytes 0)in if actual<>expected then failwith(Printf.sprintf"scene execution Metal shadow %s %d<>%d"name actual expected))[1;2;60;600])
    ["bias",shadow_aux~bias:0.02"native-shadow-bias"Raster2.Shadow_map.Tap1 1. 0.49,255;"strength",shadow_aux"native-shadow-strength"Raster2.Shadow_map.Tap1 0.5 0.,128];
  let reload_key="native-shadow-reload"in let first_shadow=shadow_aux reload_key Raster2.Shadow_map.Tap1 1. 0. in ignore(get(Scene_execution.render_resources renderer[Scene_execution.Scene3_shadow,Ogpu.Pipeline.Replace,None,Some first_shadow,{mesh=shadow_mesh;state}]));let before_shadow_reload=Scene_execution.upload_bytes renderer in let reloaded_shadow=shadow_aux reload_key Raster2.Shadow_map.Tap1 0.5 1. in ignore(get(Scene_execution.render_resources renderer[Scene_execution.Scene3_shadow,Ogpu.Pipeline.Replace,None,Some reloaded_shadow,{mesh=shadow_mesh;state}]));if Scene_execution.upload_bytes renderer<=before_shadow_reload then failwith"shadow generation replacement was not uploaded";
  let malformed_aux={reloaded_shadow with Scene_execution.key="malformed-shadow";buffer=Bytes.empty}and before_shadow_reject=Scene_execution.upload_bytes renderer in begin match Scene_execution.render_resources renderer[Scene_execution.Scene3_shadow,Ogpu.Pipeline.Replace,None,Some malformed_aux,{mesh=shadow_mesh;state}]with Error _ when Scene_execution.upload_bytes renderer=before_shadow_reject->()|_->failwith"malformed shadow was not rejected atomically"end;
  get(Scene_execution.resize renderer{configuration with physical_width=8;physical_height=8});ignore(get(Scene_execution.render renderer[{mesh;state={state with viewport=(0,0,8,8);scissor=(0,0,8,8)}}]));
  if List.mem 4 supported then(ignore(get(Scene_execution.render_sampled_resources renderer[Scene_execution.Scene3,Ogpu.Pipeline.Replace,None,None,4,{mesh=mesh3;state={state with viewport=(0,0,8,8);scissor=(0,0,8,8)}}]));let captured=get(Scene_execution.read_pixels renderer~bytes_per_row:32)in if Bytes.length captured<>256||Char.code(Bytes.get captured 0)<>255||Char.code(Bytes.get captured 2)<>128 then failwith"resized multisample capture pixel");
  metal(Metal.Metal_layer.destroy layer);get(Scene_execution.destroy renderer);if Backend.sampler_cache_entries control<>0 then failwith"native sampler cache teardown";ignore(metal(Metal.Release_queue.drain()));let after=metal(Metal.Release_queue.stats())in if after.live_handles<>before.live_handles-1 then failwith"scene execution Metal live delta";print_endline"scene execution Metal: SDL-free draw/resize, exact pixel, zero delta"
