open Ogpu_metal
let get=function Ok x->x|Error e->failwith(Ogpu.Error.to_string e)
let get_metal=function Ok x->x|Error e->failwith(Format.asprintf"%a"Metal.pp_error e)
let source={|#include <metal_stdlib>
using namespace metal;
kernel void backend_compute(device uint *v [[buffer(0)]], uint i [[thread_position_in_grid]]) { v[i]=v[i]*2+1; }
struct V { float4 position [[position]]; };
vertex V backend_vertex(uint i [[vertex_id]]) { constexpr float2 p[3]={{-1.,-1.},{3.,-1.},{-1.,3.}}; V v;v.position=float4(p[i],0.,1.);return v; }
fragment float4 backend_fragment(){return float4(0.25,0.5,0.75,1.);}
fragment float4 backend_fragment2(){return float4(0.0,1.0,0.0,1.);}
|}
let shader entries bindings=get(Ogpu.Shader.create{backend="metal";label=None;bytes=Bytes.of_string source;entry_points=entries;bindings})
let ()=match Device.system_default()with Error _->print_endline"ogpu_metal backend: skipped (no device)"|Ok native_device->
  let before=get_metal(Metal.Release_queue.stats())in let layer=get_metal(Metal.Metal_layer.create(Device.Private.metal native_device)(Metal.Metal_layer.default~width:4~height:4))in
  let driver,control=Backend.create~device:native_device~layer()in let device=get(Ogpu.Backend.create_device driver)in let cache=get(Pipeline.create_cache~capacity:4)in
  let compute_shader=shader[{name="backend_compute";stage=Compute}][{group=0;binding=0;kind=Storage_buffer;visibility=[Compute]}]in let gl=get(Ogpu.Binding.create_layout[{binding=0;kind=Ogpu.Binding.Buffer;visibility=[Ogpu.Binding.Compute]}])in let layout=get(Ogpu.Binding.create_pipeline_layout~device:(Ogpu.Backend.device_handle device)~capabilities:(Ogpu.Backend.capabilities device)[0,gl])in let compute_descriptor : Ogpu.Pipeline.compute_descriptor={backend="metal";label=None;layout;shader=compute_shader;entry="backend_compute"}in let native_compute=get(Pipeline.create_compute_runtime_msl cache native_device compute_descriptor)in Backend.register_pipeline control native_compute;let compute_pipeline=get(Ogpu.Backend.adopt_pipeline device(Pipeline.Private.portable native_compute))in
  let render_shader=shader[{name="backend_vertex";stage=Vertex};{name="backend_fragment";stage=Fragment};{name="backend_fragment2";stage=Fragment}][]in let empty=get(Ogpu.Binding.create_layout[])in let render_layout=get(Ogpu.Binding.create_pipeline_layout~device:(Ogpu.Backend.device_handle device)~capabilities:(Ogpu.Backend.capabilities device)[0,empty])in let render_descriptor : Ogpu.Pipeline.render_descriptor={backend="metal";label=None;layout=render_layout;vertex=render_shader;vertex_entry="backend_vertex";fragment=Some render_shader;fragment_entry=Some"backend_fragment";color_format=Rgba8_unorm;depth_format=No_depth;sample_count=1}in let native_render=get(Pipeline.create_render_runtime_msl cache native_device render_descriptor)in Backend.register_pipeline control native_render;let render_pipeline=get(Ogpu.Backend.adopt_pipeline device(Pipeline.Private.portable native_render))in let native_render2=get(Pipeline.create_render_runtime_msl cache native_device{render_descriptor with fragment_entry=Some"backend_fragment2"})in Backend.register_pipeline control native_render2;let render_pipeline2=get(Ogpu.Backend.adopt_pipeline device(Pipeline.Private.portable native_render2))in
  let bd : Ogpu.Types.buffer_descriptor={label=None;size=64L;usage=[Copy_src;Copy_dst;Storage]}in let a=get(Ogpu.Backend.create_buffer device bd)and b=get(Ogpu.Backend.create_buffer device bd)in let input=Bytes.make 16 '\000'in for i=0 to 3 do Bytes.set_int32_le input(i*4)(Int32.of_int i)done;get(Ogpu.Backend.write_buffer a~offset:0L input);
  let transfer=Ogpu.Transfer_pass.create(Ogpu.Backend.device_handle device)in get(Ogpu.Transfer_pass.copy_buffer transfer~src:(Ogpu.Backend.transfer_buffer a)~src_offset:0L~dst:(Ogpu.Backend.transfer_buffer b)~dst_offset:0L~length:16L);let queue=get(Ogpu.Backend.create_queue device)in let r=get(Ogpu.Backend.submit queue(get(Ogpu.Backend.transfer transfer))~resources:[`Buffer a;`Buffer b]~pipelines:[])in get(Ogpu.Backend.complete_through queue r.epoch);
  let group=get(Ogpu.Binding.create_group layout~group:0[{binding=0;resource=Ogpu.Backend.binding_buffer b}])in let declared : Ogpu.Compute_pass.resource={id=Ogpu.Backend.buffer_id b;access=Read_write;stages=[Compute_stage]}in let pass=get(Ogpu.Compute_pass.create(Ogpu.Backend.device_handle device)~limits:(Ogpu.Backend.capabilities device).limits~pipeline:(Pipeline.Private.portable native_compute)~layout~groups:[|0,group|]~resources:[|declared|]~dispatch:(Direct{x=4;y=1;z=1}))in for _=1 to 3 do let r=get(Ogpu.Backend.submit queue(Ogpu.Backend.compute pass)~resources:[`Buffer b]~pipelines:[compute_pipeline])in get(Ogpu.Backend.complete_through queue r.epoch)done;let out=get(Ogpu.Backend.read_buffer b~offset:0L~length:16)in for i=0 to 3 do if Bytes.get_int32_le out(i*4)<>Int32.of_int(i*8+7)then failwith"backend compute mismatch"done;
  let td : Ogpu.Types.texture_descriptor={label=None;width=4;height=4;depth=1;mip_levels=1;sample_count=1;usage=[Render_attachment;Texture_copy_src]}in let target=get(Ogpu.Backend.create_texture device td)in let texture=Ogpu.Backend.render_texture target~format:Rgba8~usage:Render_target in let color : Ogpu.Render_pass.color={texture;resolve=None;load=Clear;store=Store;clear=(0.,0.,0.,1.)}in let rp=get(Ogpu.Render_pass.create(Ogpu.Backend.device_handle device){colors=[|Some color|];depth=None;stencil=None;viewport={x=0;y=0;width=4;height=4};scissor={x=0;y=0;width=4;height=4}})in
  let draw : Ogpu.Render_pass.draw={pipeline_key=Pipeline.key native_render;buffers=[];textures=[];primitive=Triangle_list;vertex_start=0;vertex_count=3;index=None}in
  let bad={draw with buffers=[{stage=Ogpu.Command.Vertex;index=0;buffer_id=Ogpu.Backend.buffer_id a;offset=0L};{stage=Ogpu.Command.Vertex;index=0;buffer_id=Ogpu.Backend.buffer_id b;offset=0L}]}in(match Ogpu.Backend.render rp[bad]with Error e when e.Ogpu.Error.kind=Ogpu.Error.Invalid_argument->()|_->failwith"backend render atomic validation");
  let rr=get(Ogpu.Backend.submit queue(get(Ogpu.Backend.render rp[draw]))~resources:[`Texture target]~pipelines:[render_pipeline])in get(Ogpu.Backend.complete_through queue rr.epoch);let pixels=get(Ogpu.Backend.read_texture target~bytes_per_row:16)in if Char.code(Bytes.get pixels 0)<>64||Char.code(Bytes.get pixels 1)<>128||Char.code(Bytes.get pixels 2)<>191 then failwith"backend nonindexed render mismatch";
  let ibd : Ogpu.Types.buffer_descriptor={label=None;size=6L;usage=[Index;Copy_dst]}in let indices=get(Ogpu.Backend.create_buffer device ibd)in let ibytes=Bytes.create 6 in Bytes.set_uint16_le ibytes 0 0;Bytes.set_uint16_le ibytes 2 1;Bytes.set_uint16_le ibytes 4 2;get(Ogpu.Backend.write_buffer indices~offset:0L ibytes);let indexed={draw with index=Some(Uint16,Ogpu.Backend.buffer_id indices,0L,3)}in let draws=List.init 1000(fun i->if i land 1=0 then indexed else{draw with pipeline_key=Pipeline.key native_render2})in let rr=get(Ogpu.Backend.submit queue(get(Ogpu.Backend.render rp draws))~resources:[`Texture target;`Buffer indices]~pipelines:[render_pipeline;render_pipeline2])in get(Ogpu.Backend.destroy_buffer indices);get(Ogpu.Backend.complete_through queue rr.epoch);let pixels=get(Ogpu.Backend.read_texture target~bytes_per_row:16)in if Char.code(Bytes.get pixels 0)<>0||Char.code(Bytes.get pixels 1)<>255||Char.code(Bytes.get pixels 2)<>0 then failwith"backend ordered 1000-draw render mismatch";
  (* Surface lifecycle remains independently real and typed. *)
  let config : Ogpu.Surface.configuration={logical_width=4;logical_height=4;physical_width=4;physical_height=4;format=Bgra8_unorm;present_mode=Fifo;max_acquired=2}in let surface=get(Ogpu.Backend.create_surface device config)in for i=0 to 2 do match get(Ogpu.Backend.acquire surface)with`Acquired frame->if i land 1=0 then get(Ogpu.Backend.present frame)else get(Ogpu.Backend.discard frame)|_->failwith"backend surface acquire"done;
  get(Ogpu.Backend.destroy_surface surface);get(Ogpu.Backend.destroy_texture target);get(Ogpu.Backend.destroy_buffer a);get(Ogpu.Backend.destroy_buffer b);get(Ogpu.Backend.destroy_pipeline compute_pipeline);get(Ogpu.Backend.destroy_pipeline render_pipeline);get(Ogpu.Backend.destroy_pipeline render_pipeline2);get(Ogpu.Backend.destroy_queue queue);get_metal(Metal.Metal_layer.destroy layer);get(Ogpu.Backend.destroy_device device);ignore(get_metal(Metal.Release_queue.drain()));let after=get_metal(Metal.Release_queue.stats())in if after.live_handles<>before.live_handles-1 then failwith"backend adapter live delta";print_endline"ogpu_metal backend: transfer/compute/render1000/surface, zero delta"
