open Ogpu_metal
let get=function Ok x->x|Error e->failwith(Ogpu.Error.to_string e)
let get_metal=function Ok x->x|Error e->failwith(Format.asprintf"%a"Metal.pp_error e)
let expect kind=function Error e when e.Ogpu.Error.kind=kind->()|_->failwith"wrong rejection"
let source={|#include <metal_stdlib>
using namespace metal;
kernel void native_step(device uint *values [[buffer(0)]], uint i [[thread_position_in_grid]]) { values[i] += 11; }
|}
let ()=match Device.system_default()with Error _->print_endline"ogpu_metal native pass: skipped (no device)"|Ok device->
  let other=get(Device.system_default())in let before=get_metal(Metal.Release_queue.stats())in
  let buffer_descriptor : Ogpu.Types.buffer_descriptor={label=Some"native-pass";size=16L;usage=[Storage;Copy_src;Copy_dst]}in let buffer=get(Buffer.create device~memory:Buffer.Shared buffer_descriptor)in
  let shader=get(Ogpu.Shader.create{backend="metal";label=Some"native-step";bytes=Bytes.of_string source;entry_points=[{name="native_step";stage=Compute}];bindings=[{group=0;binding=0;kind=Storage_buffer;visibility=[Compute]}]})in
  let group=get(Ogpu.Binding.create_layout[{binding=0;kind=Ogpu.Binding.Buffer;visibility=[Ogpu.Binding.Compute]}])in let layout=get(Ogpu.Binding.create_pipeline_layout~device:(Device.Private.handle device)~capabilities:(Device.capabilities device)[0,group])in
  let descriptor : Ogpu.Pipeline.compute_descriptor={backend="metal";label=Some"native-step";layout;shader;entry="native_step"}in let cache=get(Pipeline.create_cache~capacity:1)in let pipeline=get(Pipeline.create_compute cache device descriptor)in
  let resource=Native_pass.Buffer buffer in let declaration=Native_pass.declaration resource~access:Ogpu.Command.Read_write~stages:[Ogpu.Command.Compute_stage]~owner:Ogpu.Native_pass.Native~resulting_state:Ogpu.Native_pass.Shader_write in let transition={Ogpu.Native_pass.resource_id=declaration.resource_id;before=Undefined;after=Shader_write}in let plan=get(Ogpu.Native_pass.create(Device.Private.handle device)~declarations:[|declaration|]~transitions:[|transition|])in
  let command=Command.create()in let snapshot=Command.descriptions command in let rejected : Ogpu.Native_pass.callback={run=(fun _->Error(Ogpu.Error.make"test"Ogpu.Error.Invalid_state"injected callback failure"))}in expect Ogpu.Error.Invalid_state(Native_pass.record device command plan~resources:[resource]rejected(Native_pass.Dispatch{pipeline;buffer;threads=4}));if Command.descriptions command<>snapshot then failwith"callback rejection partially mutated command";
  let raised : Ogpu.Native_pass.callback={run=(fun _->raise Exit)}in expect Ogpu.Error.Invalid_state(Native_pass.record device command plan~resources:[resource]raised(Native_pass.Dispatch{pipeline;buffer;threads=4}));if Command.descriptions command<>snapshot then failwith"callback exception partially mutated command";
  expect Ogpu.Error.Cross_device(Native_pass.record other command plan~resources:[resource]{run=(fun _->Ok())}(Native_pass.Dispatch{pipeline;buffer;threads=4}));
  let unsupported_declaration={declaration with resulting_state=Ogpu.Native_pass.Acceleration_write}in let unsupported_transition={transition with after=Ogpu.Native_pass.Acceleration_write}in let unsupported=get(Ogpu.Native_pass.create(Device.Private.handle device)~declarations:[|unsupported_declaration|]~transitions:[|unsupported_transition|])in expect Ogpu.Error.Invalid_argument(Native_pass.record device command unsupported~resources:[resource]{run=(fun _->Ok())}(Native_pass.Dispatch{pipeline;buffer;threads=4}));
  get(Native_pass.record device command plan~resources:[resource]{run=(fun _->Ok())}(Native_pass.Dispatch{pipeline;buffer;threads=4}));get(Command.end_ command);let queue=get(Queue.create device)in let receipt=get(Queue.submit queue command)in get(Queue.wait_through queue receipt.epoch);
  let bytes=get(Buffer.read_bytes device buffer~offset:0L~length:16)in for i=0 to 3 do if Bytes.get_int32_le bytes(i*4)<>11l then failwith"native pass output mismatch"done;
  let stale=get(Buffer.create device~memory:Buffer.Shared buffer_descriptor)in let stale_resource=Native_pass.Buffer stale in let stale_declaration=Native_pass.declaration stale_resource~access:Ogpu.Command.Read~stages:[Ogpu.Command.Transfer_stage]~owner:Ogpu.Native_pass.Ogpu~resulting_state:Ogpu.Native_pass.Copy_source in let stale_plan=get(Ogpu.Native_pass.create(Device.Private.handle device)~declarations:[|stale_declaration|]~transitions:[|{resource_id=stale_declaration.resource_id;before=Undefined;after=Copy_source}|])in get(Buffer.destroy stale);expect Ogpu.Error.Stale_handle(Native_pass.record device(Command.create())stale_plan~resources:[stale_resource]{run=(fun _->Ok())}(Native_pass.Copy_buffer{source=stale;source_offset=0L;destination=buffer;destination_offset=0L;length=4L}));
  Pipeline.clear_cache cache;get(Buffer.destroy buffer);get(Queue.destroy queue);get(Device.destroy device);get(Device.destroy other);ignore(get_metal(Metal.Release_queue.drain()));let after=get_metal(Metal.Release_queue.stats())in if after.live_handles<>before.live_handles-2 then failwith"native pass live-handle delta";
  print_endline"ogpu_metal native pass: scoped deterministic dispatch, atomic rejection, zero live-handle delta"
