type t={operations:Ogpu.Transfer_pass.description array;buffers:(int64*Buffer.t)list;textures:(int64*Texture.t)list}
let error op kind text=Error(Ogpu.Error.make op kind text)
let buffer device value=Result.map(fun descriptor->Ogpu.Transfer_pass.buffer~device:(Device.Private.handle device)(Buffer.Private.resource_handle value)descriptor)(Buffer.descriptor device value)
let texture device value=Result.map(fun descriptor->Ogpu.Transfer_pass.texture~device:(Device.Private.handle device)(Texture.Private.resource_handle value)descriptor)(Texture.descriptor device value)
let create device pass ~buffers ~textures=let op="Ogpu_metal.Transfer_pass.create"in match Ogpu.Transfer_pass.finish pass with Error _ as e->e|Ok operations->
  let bs=List.map(fun b->Buffer.id b,b)buffers and ts=List.map(fun t->Texture.id t,t)textures in
  let unique xs=List.length xs=List.length(List.sort_uniq Int64.compare(List.map fst xs))in
  if not(unique bs&&unique ts)then error op Ogpu.Error.Invalid_argument"resource association contains duplicate IDs"else
  let find id xs=List.assoc_opt id xs in let failure=ref None in let need_b id=match find id bs with None->failure:=Some"portable buffer is absent from the typed resource graph"|Some b->(match Buffer.descriptor device b with Error e->raise(Failure(Ogpu.Error.to_string e))|Ok _->())and need_t id=match find id ts with None->failure:=Some"portable texture is absent from the typed resource graph"|Some t->(match Texture.descriptor device t with Error e->raise(Failure(Ogpu.Error.to_string e))|Ok _->())in
  (try Array.iter(function Ogpu.Transfer_pass.Copy_buffer(a,_,b,_,_)->need_b a;need_b b|Fill_buffer(a,_,_,_)->need_b a|Buffer_to_texture(a,_,_,_,b,_,_,_)->need_b a;need_t b|Texture_to_buffer(a,_,_,_,b,_,_,_)->need_t a;need_b b|Copy_texture(a,_,_,b,_,_,_)->need_t a;need_t b)operations with Failure text->failure:=Some text);
  match!failure with Some text->error op Ogpu.Error.Invalid_argument text|None->Ok{operations;buffers=bs;textures=ts}
module Private=struct
  let retain value=let releases=ref[]in let keep retain release=match retain()with Error _ as e->e|Ok()->releases:=release::!releases;Ok()in let fs=List.map(fun(_,b)->fun()->keep(fun()->Buffer.Private.retain_submission b)(fun()->Buffer.Private.release_submission b))value.buffers@List.map(fun(_,t)->fun()->keep(fun()->Texture.Private.retain_submission t)(fun()->Texture.Private.release_submission t))value.textures in let rec loop=function []->Ok(List.rev!releases)|f::xs->match f()with Ok()->loop xs|Error _ as e->List.iter(fun r->r())!releases;e in loop fs
  let encode command value=let op="Ogpu_metal.Transfer_pass.encode"in let b id=Buffer.Private.metal(List.assoc id value.buffers)and t id=Texture.Private.metal(List.assoc id value.textures)in match Metal.Blit_encoder.create command with Error e->Error(Adapter.error~operation:op e)|Ok encoder->let region(o:Ogpu.Transfer_pass.origin)(s:Ogpu.Transfer_pass.extent):Metal.Texture.region={x=o.x;y=o.y;z=o.z;width=s.width;height=s.height;depth=s.depth}in let call=function
    |Ogpu.Transfer_pass.Copy_buffer(a,ao,d,do_,n)->Metal.Blit_encoder.copy_buffer encoder~source:(b a)~source_offset:ao~destination:(b d)~destination_offset:do_~length:n
    |Fill_buffer(a,o,n,v)->Metal.Blit_encoder.fill_buffer encoder(b a)~offset:o~length:n~byte:v
    |Buffer_to_texture(a,o,row,image,d,mip,origin,size)->Metal.Blit_encoder.copy_buffer_to_texture encoder~source:(b a)~source_offset:o~source_bytes_per_row:(Int64.to_int row)~source_bytes_per_image:(Int64.to_int image)~destination:(t d)~destination_slice:0~destination_level:mip~destination_region:(region origin size)
    |Texture_to_buffer(a,mip,origin,size,d,o,row,image)->Metal.Blit_encoder.copy_texture_to_buffer encoder~source:(t a)~source_slice:0~source_level:mip~source_region:(region origin size)~destination:(b d)~destination_offset:o~destination_bytes_per_row:row~destination_bytes_per_image:image()
    |Copy_texture(a,am,ao,d,dm,do_,size)->Metal.Blit_encoder.copy_texture_region encoder~source:(t a)~source_slice:0~source_level:am~source_region:(region ao size)~destination:(t d)~destination_slice:0~destination_level:dm~destination_origin:(do_.x,do_.y,do_.z)in
    let rec loop i=if i=Array.length value.operations then match Metal.Blit_encoder.end_encoding encoder with Ok()->Ok()|Error e->Error(Adapter.error~operation:op e)else match call value.operations.(i)with Ok()->loop(i+1)|Error e->Error(Adapter.error~operation:op e)in loop 0
end
