(library
 (name prismel_editor)
 (public_name prismel.prismel_editor)
 (private_modules selection common leader doc schedule pick cook lisp_text text_pane navigator bars source_file core environment
  viewport2 viewport3 renderer)
 (libraries editor_document prismel prismel_pathtracer procedural flow flow_sop editor_core pxui pxui_shell pxui_graph sop_catalog sketch_support unix)
 (preprocess (pps prismel.ppx)))
