(library
 (name prismel_next_execution)
 (public_name prismel.prismel_next_execution)
 (modules prismel_next_execution)
 (libraries ogpu scene_command scene_execution runtime_next_orchestrator
  runtime_next_input prismel_next_resources unix))

(test
 (name test_scene2_command)
 (modules test_scene2_command)
 (libraries prismel_next_execution))

(test
 (name test_offscreen)
 (modules test_offscreen)
 (libraries prismel_next_execution metal unix))
