(library
 (name prismel_next_execution)
 (public_name prismel.prismel_next_execution)
 (modules prismel_next_execution)
 (libraries ogpu scene_command scene_execution runtime_next_orchestrator
  runtime_next_input prismel_next_resources unix))

(executable
 (name test_main)
 (modules test_main test_offscreen test_scene2_coordinates test_dense_scene2 test_ui_pipeline)
 (libraries prismel_next_execution scene_command metal unix))

(rule
 (aliases runtest test_offscreen)
 (action (run %{exe:test_main.exe} test_offscreen)))

(rule
 (aliases runtest test_scene2_coordinates)
 (action (run %{exe:test_main.exe} test_scene2_coordinates)))

(rule
 (aliases runtest test_dense_scene2)
 (action (run %{exe:test_main.exe} test_dense_scene2)))

(rule
 (aliases runtest test_ui_pipeline)
 (action (run %{exe:test_main.exe} test_ui_pipeline)))
