(executable
 (name embed_metal)
 (modules embed_metal))

(rule
 (target pathtrace_source.ml)
 (deps pathtrace.metal)
 (action (with-stdout-to %{target}
  (run %{exe:embed_metal.exe} %{dep:pathtrace.metal}))))

(library
 (name prismel_pathtracer)
 (public_name prismel.pathtracer)
 (modules prismel_pathtracer pathtrace_source)
 (libraries prismel ogpu pdk prismel_execution runtime_resources unix))

(executable
 (name test_main)
 (modules test_main test_pathtracer test_gpu_film)
 (libraries prismel prismel_pathtracer prismel_execution runtime_resources ogpu pdk))

(rule
 (aliases runtest test_pathtracer)
 (deps pathtrace.metal)
 (action (run %{exe:test_main.exe} test_pathtracer)))

(rule
 (enabled_if (= %{env:PRISMEL_PATH_TRACER_EXACT_M1=0} 1))
 (alias qualification)
 (deps pathtrace.metal)
 (action
  (setenv PRISMEL_PATH_TRACER_EXACT_M1 1
   (run %{exe:test_main.exe} test_pathtracer))))

(rule
 (aliases runtest-native test_gpu_film)
 (action (run %{exe:test_main.exe} test_gpu_film)))
