/* Generated ABI assertions; do not edit. */
#ifndef PRISMEL_SDL3_GENERATED_ABI_H
#define PRISMEL_SDL3_GENERATED_ABI_H
#include <SDL3/SDL.h>
#include <stddef.h>
_Static_assert(SDL_MAJOR_VERSION == 3, "SDL major header changed");
_Static_assert(SDL_MINOR_VERSION == 4, "SDL minor header changed");
_Static_assert(SDL_MICRO_VERSION == 14, "SDL patch header changed");
_Static_assert(sizeof(SDL_Event) == 128, "SDL_Event size changed");
_Static_assert(_Alignof(SDL_Event) == 8, "SDL_Event alignment changed");
_Static_assert(sizeof(SDL_CommonEvent) == 16, "SDL_CommonEvent size changed");
_Static_assert(_Alignof(SDL_CommonEvent) == 8, "SDL_CommonEvent alignment changed");
_Static_assert(offsetof(SDL_CommonEvent, type) == 0, "SDL_CommonEvent.type offset changed");
_Static_assert(offsetof(SDL_CommonEvent, timestamp) == 8, "SDL_CommonEvent.timestamp offset changed");
_Static_assert(sizeof(SDL_DisplayEvent) == 32, "SDL_DisplayEvent size changed");
_Static_assert(_Alignof(SDL_DisplayEvent) == 8, "SDL_DisplayEvent alignment changed");
_Static_assert(offsetof(SDL_DisplayEvent, type) == 0, "SDL_DisplayEvent.type offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, timestamp) == 8, "SDL_DisplayEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, displayID) == 16, "SDL_DisplayEvent.displayID offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, data1) == 20, "SDL_DisplayEvent.data1 offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, data2) == 24, "SDL_DisplayEvent.data2 offset changed");
_Static_assert(sizeof(SDL_WindowEvent) == 32, "SDL_WindowEvent size changed");
_Static_assert(_Alignof(SDL_WindowEvent) == 8, "SDL_WindowEvent alignment changed");
_Static_assert(offsetof(SDL_WindowEvent, type) == 0, "SDL_WindowEvent.type offset changed");
_Static_assert(offsetof(SDL_WindowEvent, timestamp) == 8, "SDL_WindowEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_WindowEvent, windowID) == 16, "SDL_WindowEvent.windowID offset changed");
_Static_assert(offsetof(SDL_WindowEvent, data1) == 20, "SDL_WindowEvent.data1 offset changed");
_Static_assert(offsetof(SDL_WindowEvent, data2) == 24, "SDL_WindowEvent.data2 offset changed");
_Static_assert(sizeof(SDL_KeyboardEvent) == 40, "SDL_KeyboardEvent size changed");
_Static_assert(_Alignof(SDL_KeyboardEvent) == 8, "SDL_KeyboardEvent alignment changed");
_Static_assert(offsetof(SDL_KeyboardEvent, type) == 0, "SDL_KeyboardEvent.type offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, timestamp) == 8, "SDL_KeyboardEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, windowID) == 16, "SDL_KeyboardEvent.windowID offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, which) == 20, "SDL_KeyboardEvent.which offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, scancode) == 24, "SDL_KeyboardEvent.scancode offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, key) == 28, "SDL_KeyboardEvent.key offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, mod) == 32, "SDL_KeyboardEvent.mod offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, raw) == 34, "SDL_KeyboardEvent.raw offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, down) == 36, "SDL_KeyboardEvent.down offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, repeat) == 37, "SDL_KeyboardEvent.repeat offset changed");
_Static_assert(sizeof(SDL_TextEditingEvent) == 40, "SDL_TextEditingEvent size changed");
_Static_assert(_Alignof(SDL_TextEditingEvent) == 8, "SDL_TextEditingEvent alignment changed");
_Static_assert(offsetof(SDL_TextEditingEvent, type) == 0, "SDL_TextEditingEvent.type offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, timestamp) == 8, "SDL_TextEditingEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, windowID) == 16, "SDL_TextEditingEvent.windowID offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, text) == 24, "SDL_TextEditingEvent.text offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, start) == 32, "SDL_TextEditingEvent.start offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, length) == 36, "SDL_TextEditingEvent.length offset changed");
_Static_assert(sizeof(SDL_TextInputEvent) == 32, "SDL_TextInputEvent size changed");
_Static_assert(_Alignof(SDL_TextInputEvent) == 8, "SDL_TextInputEvent alignment changed");
_Static_assert(offsetof(SDL_TextInputEvent, type) == 0, "SDL_TextInputEvent.type offset changed");
_Static_assert(offsetof(SDL_TextInputEvent, timestamp) == 8, "SDL_TextInputEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TextInputEvent, windowID) == 16, "SDL_TextInputEvent.windowID offset changed");
_Static_assert(offsetof(SDL_TextInputEvent, text) == 24, "SDL_TextInputEvent.text offset changed");
_Static_assert(sizeof(SDL_MouseMotionEvent) == 48, "SDL_MouseMotionEvent size changed");
_Static_assert(_Alignof(SDL_MouseMotionEvent) == 8, "SDL_MouseMotionEvent alignment changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, type) == 0, "SDL_MouseMotionEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, timestamp) == 8, "SDL_MouseMotionEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, windowID) == 16, "SDL_MouseMotionEvent.windowID offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, which) == 20, "SDL_MouseMotionEvent.which offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, state) == 24, "SDL_MouseMotionEvent.state offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, x) == 28, "SDL_MouseMotionEvent.x offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, y) == 32, "SDL_MouseMotionEvent.y offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, xrel) == 36, "SDL_MouseMotionEvent.xrel offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, yrel) == 40, "SDL_MouseMotionEvent.yrel offset changed");
_Static_assert(sizeof(SDL_MouseButtonEvent) == 40, "SDL_MouseButtonEvent size changed");
_Static_assert(_Alignof(SDL_MouseButtonEvent) == 8, "SDL_MouseButtonEvent alignment changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, type) == 0, "SDL_MouseButtonEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, timestamp) == 8, "SDL_MouseButtonEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, windowID) == 16, "SDL_MouseButtonEvent.windowID offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, which) == 20, "SDL_MouseButtonEvent.which offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, button) == 24, "SDL_MouseButtonEvent.button offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, down) == 25, "SDL_MouseButtonEvent.down offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, clicks) == 26, "SDL_MouseButtonEvent.clicks offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, x) == 28, "SDL_MouseButtonEvent.x offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, y) == 32, "SDL_MouseButtonEvent.y offset changed");
_Static_assert(sizeof(SDL_MouseWheelEvent) == 56, "SDL_MouseWheelEvent size changed");
_Static_assert(_Alignof(SDL_MouseWheelEvent) == 8, "SDL_MouseWheelEvent alignment changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, type) == 0, "SDL_MouseWheelEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, timestamp) == 8, "SDL_MouseWheelEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, windowID) == 16, "SDL_MouseWheelEvent.windowID offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, which) == 20, "SDL_MouseWheelEvent.which offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, x) == 24, "SDL_MouseWheelEvent.x offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, y) == 28, "SDL_MouseWheelEvent.y offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, direction) == 32, "SDL_MouseWheelEvent.direction offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, mouse_x) == 36, "SDL_MouseWheelEvent.mouse_x offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, mouse_y) == 40, "SDL_MouseWheelEvent.mouse_y offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, integer_x) == 44, "SDL_MouseWheelEvent.integer_x offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, integer_y) == 48, "SDL_MouseWheelEvent.integer_y offset changed");
_Static_assert(sizeof(SDL_TouchFingerEvent) == 56, "SDL_TouchFingerEvent size changed");
_Static_assert(_Alignof(SDL_TouchFingerEvent) == 8, "SDL_TouchFingerEvent alignment changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, type) == 0, "SDL_TouchFingerEvent.type offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, timestamp) == 8, "SDL_TouchFingerEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, touchID) == 16, "SDL_TouchFingerEvent.touchID offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, fingerID) == 24, "SDL_TouchFingerEvent.fingerID offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, x) == 32, "SDL_TouchFingerEvent.x offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, y) == 36, "SDL_TouchFingerEvent.y offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, dx) == 40, "SDL_TouchFingerEvent.dx offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, dy) == 44, "SDL_TouchFingerEvent.dy offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, pressure) == 48, "SDL_TouchFingerEvent.pressure offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, windowID) == 52, "SDL_TouchFingerEvent.windowID offset changed");
_Static_assert(sizeof(SDL_PenMotionEvent) == 40, "SDL_PenMotionEvent size changed");
_Static_assert(_Alignof(SDL_PenMotionEvent) == 8, "SDL_PenMotionEvent alignment changed");
_Static_assert(offsetof(SDL_PenMotionEvent, type) == 0, "SDL_PenMotionEvent.type offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, timestamp) == 8, "SDL_PenMotionEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, windowID) == 16, "SDL_PenMotionEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, which) == 20, "SDL_PenMotionEvent.which offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, pen_state) == 24, "SDL_PenMotionEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, x) == 28, "SDL_PenMotionEvent.x offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, y) == 32, "SDL_PenMotionEvent.y offset changed");
_Static_assert(sizeof(SDL_PenTouchEvent) == 40, "SDL_PenTouchEvent size changed");
_Static_assert(_Alignof(SDL_PenTouchEvent) == 8, "SDL_PenTouchEvent alignment changed");
_Static_assert(offsetof(SDL_PenTouchEvent, type) == 0, "SDL_PenTouchEvent.type offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, timestamp) == 8, "SDL_PenTouchEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, windowID) == 16, "SDL_PenTouchEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, which) == 20, "SDL_PenTouchEvent.which offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, pen_state) == 24, "SDL_PenTouchEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, x) == 28, "SDL_PenTouchEvent.x offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, y) == 32, "SDL_PenTouchEvent.y offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, eraser) == 36, "SDL_PenTouchEvent.eraser offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, down) == 37, "SDL_PenTouchEvent.down offset changed");
_Static_assert(sizeof(SDL_PenButtonEvent) == 40, "SDL_PenButtonEvent size changed");
_Static_assert(_Alignof(SDL_PenButtonEvent) == 8, "SDL_PenButtonEvent alignment changed");
_Static_assert(offsetof(SDL_PenButtonEvent, type) == 0, "SDL_PenButtonEvent.type offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, timestamp) == 8, "SDL_PenButtonEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, windowID) == 16, "SDL_PenButtonEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, which) == 20, "SDL_PenButtonEvent.which offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, pen_state) == 24, "SDL_PenButtonEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, x) == 28, "SDL_PenButtonEvent.x offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, y) == 32, "SDL_PenButtonEvent.y offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, button) == 36, "SDL_PenButtonEvent.button offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, down) == 37, "SDL_PenButtonEvent.down offset changed");
_Static_assert(sizeof(SDL_PenAxisEvent) == 48, "SDL_PenAxisEvent size changed");
_Static_assert(_Alignof(SDL_PenAxisEvent) == 8, "SDL_PenAxisEvent alignment changed");
_Static_assert(offsetof(SDL_PenAxisEvent, type) == 0, "SDL_PenAxisEvent.type offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, timestamp) == 8, "SDL_PenAxisEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, windowID) == 16, "SDL_PenAxisEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, which) == 20, "SDL_PenAxisEvent.which offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, pen_state) == 24, "SDL_PenAxisEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, x) == 28, "SDL_PenAxisEvent.x offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, y) == 32, "SDL_PenAxisEvent.y offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, axis) == 36, "SDL_PenAxisEvent.axis offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, value) == 40, "SDL_PenAxisEvent.value offset changed");
_Static_assert(sizeof(SDL_GamepadAxisEvent) == 32, "SDL_GamepadAxisEvent size changed");
_Static_assert(_Alignof(SDL_GamepadAxisEvent) == 8, "SDL_GamepadAxisEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, type) == 0, "SDL_GamepadAxisEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, timestamp) == 8, "SDL_GamepadAxisEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, which) == 16, "SDL_GamepadAxisEvent.which offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, axis) == 20, "SDL_GamepadAxisEvent.axis offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, value) == 24, "SDL_GamepadAxisEvent.value offset changed");
_Static_assert(sizeof(SDL_GamepadButtonEvent) == 24, "SDL_GamepadButtonEvent size changed");
_Static_assert(_Alignof(SDL_GamepadButtonEvent) == 8, "SDL_GamepadButtonEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, type) == 0, "SDL_GamepadButtonEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, timestamp) == 8, "SDL_GamepadButtonEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, which) == 16, "SDL_GamepadButtonEvent.which offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, button) == 20, "SDL_GamepadButtonEvent.button offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, down) == 21, "SDL_GamepadButtonEvent.down offset changed");
_Static_assert(sizeof(SDL_DropEvent) == 48, "SDL_DropEvent size changed");
_Static_assert(_Alignof(SDL_DropEvent) == 8, "SDL_DropEvent alignment changed");
_Static_assert(offsetof(SDL_DropEvent, type) == 0, "SDL_DropEvent.type offset changed");
_Static_assert(offsetof(SDL_DropEvent, timestamp) == 8, "SDL_DropEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_DropEvent, windowID) == 16, "SDL_DropEvent.windowID offset changed");
_Static_assert(offsetof(SDL_DropEvent, x) == 20, "SDL_DropEvent.x offset changed");
_Static_assert(offsetof(SDL_DropEvent, y) == 24, "SDL_DropEvent.y offset changed");
_Static_assert(offsetof(SDL_DropEvent, source) == 32, "SDL_DropEvent.source offset changed");
_Static_assert(offsetof(SDL_DropEvent, data) == 40, "SDL_DropEvent.data offset changed");
_Static_assert(sizeof(SDL_AudioDeviceEvent) == 24, "SDL_AudioDeviceEvent size changed");
_Static_assert(_Alignof(SDL_AudioDeviceEvent) == 8, "SDL_AudioDeviceEvent alignment changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, type) == 0, "SDL_AudioDeviceEvent.type offset changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, timestamp) == 8, "SDL_AudioDeviceEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, which) == 16, "SDL_AudioDeviceEvent.which offset changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, recording) == 20, "SDL_AudioDeviceEvent.recording offset changed");
_Static_assert((unsigned long long)(SDL_INIT_AUDIO) == 16ULL, "SDL_INIT_AUDIO changed");
_Static_assert((unsigned long long)(SDL_INIT_VIDEO) == 32ULL, "SDL_INIT_VIDEO changed");
_Static_assert((unsigned long long)(SDL_INIT_JOYSTICK) == 512ULL, "SDL_INIT_JOYSTICK changed");
_Static_assert((unsigned long long)(SDL_INIT_HAPTIC) == 4096ULL, "SDL_INIT_HAPTIC changed");
_Static_assert((unsigned long long)(SDL_INIT_GAMEPAD) == 8192ULL, "SDL_INIT_GAMEPAD changed");
_Static_assert((unsigned long long)(SDL_INIT_EVENTS) == 16384ULL, "SDL_INIT_EVENTS changed");
_Static_assert((unsigned long long)(SDL_INIT_SENSOR) == 32768ULL, "SDL_INIT_SENSOR changed");
_Static_assert((unsigned long long)(SDL_INIT_CAMERA) == 65536ULL, "SDL_INIT_CAMERA changed");
_Static_assert((unsigned long long)(SDL_WINDOW_FULLSCREEN) == 1ULL, "SDL_WINDOW_FULLSCREEN changed");
_Static_assert((unsigned long long)(SDL_WINDOW_HIDDEN) == 8ULL, "SDL_WINDOW_HIDDEN changed");
_Static_assert((unsigned long long)(SDL_WINDOW_RESIZABLE) == 32ULL, "SDL_WINDOW_RESIZABLE changed");
_Static_assert((unsigned long long)(SDL_WINDOW_HIGH_PIXEL_DENSITY) == 8192ULL, "SDL_WINDOW_HIGH_PIXEL_DENSITY changed");
_Static_assert((unsigned long long)(SDL_WINDOW_METAL) == 536870912ULL, "SDL_WINDOW_METAL changed");
_Static_assert((unsigned long long)(SDL_EVENT_QUIT) == 256ULL, "SDL_EVENT_QUIT changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_RESIZED) == 518ULL, "SDL_EVENT_WINDOW_RESIZED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED) == 519ULL, "SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEY_DOWN) == 768ULL, "SDL_EVENT_KEY_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEY_UP) == 769ULL, "SDL_EVENT_KEY_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_TEXT_EDITING) == 770ULL, "SDL_EVENT_TEXT_EDITING changed");
_Static_assert((unsigned long long)(SDL_EVENT_TEXT_INPUT) == 771ULL, "SDL_EVENT_TEXT_INPUT changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_MOTION) == 1024ULL, "SDL_EVENT_MOUSE_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_BUTTON_DOWN) == 1025ULL, "SDL_EVENT_MOUSE_BUTTON_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_BUTTON_UP) == 1026ULL, "SDL_EVENT_MOUSE_BUTTON_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_WHEEL) == 1027ULL, "SDL_EVENT_MOUSE_WHEEL changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_DOWN) == 1792ULL, "SDL_EVENT_FINGER_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_UP) == 1793ULL, "SDL_EVENT_FINGER_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_MOTION) == 1794ULL, "SDL_EVENT_FINGER_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_MOTION) == 4870ULL, "SDL_EVENT_PEN_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_DOWN) == 4866ULL, "SDL_EVENT_PEN_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_UP) == 4867ULL, "SDL_EVENT_PEN_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_BUTTON_DOWN) == 4868ULL, "SDL_EVENT_PEN_BUTTON_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_BUTTON_UP) == 4869ULL, "SDL_EVENT_PEN_BUTTON_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_AXIS) == 4871ULL, "SDL_EVENT_PEN_AXIS changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_AXIS_MOTION) == 1616ULL, "SDL_EVENT_GAMEPAD_AXIS_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_BUTTON_DOWN) == 1617ULL, "SDL_EVENT_GAMEPAD_BUTTON_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_BUTTON_UP) == 1618ULL, "SDL_EVENT_GAMEPAD_BUTTON_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_FILE) == 4096ULL, "SDL_EVENT_DROP_FILE changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_TEXT) == 4097ULL, "SDL_EVENT_DROP_TEXT changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_BEGIN) == 4098ULL, "SDL_EVENT_DROP_BEGIN changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_COMPLETE) == 4099ULL, "SDL_EVENT_DROP_COMPLETE changed");
#endif
