/* Generated ABI assertions; do not edit. */
#ifndef PRISMEL_SDL3_GENERATED_ABI_H
#define PRISMEL_SDL3_GENERATED_ABI_H
#include <SDL3/SDL.h>
#include <stddef.h>
_Static_assert(SDL_MAJOR_VERSION == 3, "SDL major header changed");
_Static_assert(SDL_MINOR_VERSION == 4, "SDL minor header changed");
_Static_assert(SDL_MICRO_VERSION == 14, "SDL patch header changed");
_Static_assert(sizeof(SDL_Event) == 128, "SDL_Event size changed");
_Static_assert(_Alignof(SDL_Event) == 8, "SDL_Event alignment changed");
_Static_assert(sizeof(SDL_CommonEvent) == 16, "SDL_CommonEvent size changed");
_Static_assert(_Alignof(SDL_CommonEvent) == 8, "SDL_CommonEvent alignment changed");
_Static_assert(offsetof(SDL_CommonEvent, type) == 0, "SDL_CommonEvent.type offset changed");
_Static_assert(offsetof(SDL_CommonEvent, timestamp) == 8, "SDL_CommonEvent.timestamp offset changed");
_Static_assert(sizeof(SDL_DisplayEvent) == 32, "SDL_DisplayEvent size changed");
_Static_assert(_Alignof(SDL_DisplayEvent) == 8, "SDL_DisplayEvent alignment changed");
_Static_assert(offsetof(SDL_DisplayEvent, type) == 0, "SDL_DisplayEvent.type offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, timestamp) == 8, "SDL_DisplayEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, displayID) == 16, "SDL_DisplayEvent.displayID offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, data1) == 20, "SDL_DisplayEvent.data1 offset changed");
_Static_assert(offsetof(SDL_DisplayEvent, data2) == 24, "SDL_DisplayEvent.data2 offset changed");
_Static_assert(sizeof(SDL_WindowEvent) == 32, "SDL_WindowEvent size changed");
_Static_assert(_Alignof(SDL_WindowEvent) == 8, "SDL_WindowEvent alignment changed");
_Static_assert(offsetof(SDL_WindowEvent, type) == 0, "SDL_WindowEvent.type offset changed");
_Static_assert(offsetof(SDL_WindowEvent, timestamp) == 8, "SDL_WindowEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_WindowEvent, windowID) == 16, "SDL_WindowEvent.windowID offset changed");
_Static_assert(offsetof(SDL_WindowEvent, data1) == 20, "SDL_WindowEvent.data1 offset changed");
_Static_assert(offsetof(SDL_WindowEvent, data2) == 24, "SDL_WindowEvent.data2 offset changed");
_Static_assert(sizeof(SDL_KeyboardDeviceEvent) == 24, "SDL_KeyboardDeviceEvent size changed");
_Static_assert(_Alignof(SDL_KeyboardDeviceEvent) == 8, "SDL_KeyboardDeviceEvent alignment changed");
_Static_assert(offsetof(SDL_KeyboardDeviceEvent, type) == 0, "SDL_KeyboardDeviceEvent.type offset changed");
_Static_assert(offsetof(SDL_KeyboardDeviceEvent, timestamp) == 8, "SDL_KeyboardDeviceEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_KeyboardDeviceEvent, which) == 16, "SDL_KeyboardDeviceEvent.which offset changed");
_Static_assert(sizeof(SDL_KeyboardEvent) == 40, "SDL_KeyboardEvent size changed");
_Static_assert(_Alignof(SDL_KeyboardEvent) == 8, "SDL_KeyboardEvent alignment changed");
_Static_assert(offsetof(SDL_KeyboardEvent, type) == 0, "SDL_KeyboardEvent.type offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, timestamp) == 8, "SDL_KeyboardEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, windowID) == 16, "SDL_KeyboardEvent.windowID offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, which) == 20, "SDL_KeyboardEvent.which offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, scancode) == 24, "SDL_KeyboardEvent.scancode offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, key) == 28, "SDL_KeyboardEvent.key offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, mod) == 32, "SDL_KeyboardEvent.mod offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, raw) == 34, "SDL_KeyboardEvent.raw offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, down) == 36, "SDL_KeyboardEvent.down offset changed");
_Static_assert(offsetof(SDL_KeyboardEvent, repeat) == 37, "SDL_KeyboardEvent.repeat offset changed");
_Static_assert(sizeof(SDL_TextEditingEvent) == 40, "SDL_TextEditingEvent size changed");
_Static_assert(_Alignof(SDL_TextEditingEvent) == 8, "SDL_TextEditingEvent alignment changed");
_Static_assert(offsetof(SDL_TextEditingEvent, type) == 0, "SDL_TextEditingEvent.type offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, timestamp) == 8, "SDL_TextEditingEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, windowID) == 16, "SDL_TextEditingEvent.windowID offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, text) == 24, "SDL_TextEditingEvent.text offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, start) == 32, "SDL_TextEditingEvent.start offset changed");
_Static_assert(offsetof(SDL_TextEditingEvent, length) == 36, "SDL_TextEditingEvent.length offset changed");
_Static_assert(sizeof(SDL_TextEditingCandidatesEvent) == 48, "SDL_TextEditingCandidatesEvent size changed");
_Static_assert(_Alignof(SDL_TextEditingCandidatesEvent) == 8, "SDL_TextEditingCandidatesEvent alignment changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, type) == 0, "SDL_TextEditingCandidatesEvent.type offset changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, timestamp) == 8, "SDL_TextEditingCandidatesEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, windowID) == 16, "SDL_TextEditingCandidatesEvent.windowID offset changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, candidates) == 24, "SDL_TextEditingCandidatesEvent.candidates offset changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, num_candidates) == 32, "SDL_TextEditingCandidatesEvent.num_candidates offset changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, selected_candidate) == 36, "SDL_TextEditingCandidatesEvent.selected_candidate offset changed");
_Static_assert(offsetof(SDL_TextEditingCandidatesEvent, horizontal) == 40, "SDL_TextEditingCandidatesEvent.horizontal offset changed");
_Static_assert(sizeof(SDL_TextInputEvent) == 32, "SDL_TextInputEvent size changed");
_Static_assert(_Alignof(SDL_TextInputEvent) == 8, "SDL_TextInputEvent alignment changed");
_Static_assert(offsetof(SDL_TextInputEvent, type) == 0, "SDL_TextInputEvent.type offset changed");
_Static_assert(offsetof(SDL_TextInputEvent, timestamp) == 8, "SDL_TextInputEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TextInputEvent, windowID) == 16, "SDL_TextInputEvent.windowID offset changed");
_Static_assert(offsetof(SDL_TextInputEvent, text) == 24, "SDL_TextInputEvent.text offset changed");
_Static_assert(sizeof(SDL_MouseDeviceEvent) == 24, "SDL_MouseDeviceEvent size changed");
_Static_assert(_Alignof(SDL_MouseDeviceEvent) == 8, "SDL_MouseDeviceEvent alignment changed");
_Static_assert(offsetof(SDL_MouseDeviceEvent, type) == 0, "SDL_MouseDeviceEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseDeviceEvent, timestamp) == 8, "SDL_MouseDeviceEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseDeviceEvent, which) == 16, "SDL_MouseDeviceEvent.which offset changed");
_Static_assert(sizeof(SDL_MouseMotionEvent) == 48, "SDL_MouseMotionEvent size changed");
_Static_assert(_Alignof(SDL_MouseMotionEvent) == 8, "SDL_MouseMotionEvent alignment changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, type) == 0, "SDL_MouseMotionEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, timestamp) == 8, "SDL_MouseMotionEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, windowID) == 16, "SDL_MouseMotionEvent.windowID offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, which) == 20, "SDL_MouseMotionEvent.which offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, state) == 24, "SDL_MouseMotionEvent.state offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, x) == 28, "SDL_MouseMotionEvent.x offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, y) == 32, "SDL_MouseMotionEvent.y offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, xrel) == 36, "SDL_MouseMotionEvent.xrel offset changed");
_Static_assert(offsetof(SDL_MouseMotionEvent, yrel) == 40, "SDL_MouseMotionEvent.yrel offset changed");
_Static_assert(sizeof(SDL_MouseButtonEvent) == 40, "SDL_MouseButtonEvent size changed");
_Static_assert(_Alignof(SDL_MouseButtonEvent) == 8, "SDL_MouseButtonEvent alignment changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, type) == 0, "SDL_MouseButtonEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, timestamp) == 8, "SDL_MouseButtonEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, windowID) == 16, "SDL_MouseButtonEvent.windowID offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, which) == 20, "SDL_MouseButtonEvent.which offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, button) == 24, "SDL_MouseButtonEvent.button offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, down) == 25, "SDL_MouseButtonEvent.down offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, clicks) == 26, "SDL_MouseButtonEvent.clicks offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, x) == 28, "SDL_MouseButtonEvent.x offset changed");
_Static_assert(offsetof(SDL_MouseButtonEvent, y) == 32, "SDL_MouseButtonEvent.y offset changed");
_Static_assert(sizeof(SDL_MouseWheelEvent) == 56, "SDL_MouseWheelEvent size changed");
_Static_assert(_Alignof(SDL_MouseWheelEvent) == 8, "SDL_MouseWheelEvent alignment changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, type) == 0, "SDL_MouseWheelEvent.type offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, timestamp) == 8, "SDL_MouseWheelEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, windowID) == 16, "SDL_MouseWheelEvent.windowID offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, which) == 20, "SDL_MouseWheelEvent.which offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, x) == 24, "SDL_MouseWheelEvent.x offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, y) == 28, "SDL_MouseWheelEvent.y offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, direction) == 32, "SDL_MouseWheelEvent.direction offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, mouse_x) == 36, "SDL_MouseWheelEvent.mouse_x offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, mouse_y) == 40, "SDL_MouseWheelEvent.mouse_y offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, integer_x) == 44, "SDL_MouseWheelEvent.integer_x offset changed");
_Static_assert(offsetof(SDL_MouseWheelEvent, integer_y) == 48, "SDL_MouseWheelEvent.integer_y offset changed");
_Static_assert(sizeof(SDL_TouchFingerEvent) == 56, "SDL_TouchFingerEvent size changed");
_Static_assert(_Alignof(SDL_TouchFingerEvent) == 8, "SDL_TouchFingerEvent alignment changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, type) == 0, "SDL_TouchFingerEvent.type offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, timestamp) == 8, "SDL_TouchFingerEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, touchID) == 16, "SDL_TouchFingerEvent.touchID offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, fingerID) == 24, "SDL_TouchFingerEvent.fingerID offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, x) == 32, "SDL_TouchFingerEvent.x offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, y) == 36, "SDL_TouchFingerEvent.y offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, dx) == 40, "SDL_TouchFingerEvent.dx offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, dy) == 44, "SDL_TouchFingerEvent.dy offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, pressure) == 48, "SDL_TouchFingerEvent.pressure offset changed");
_Static_assert(offsetof(SDL_TouchFingerEvent, windowID) == 52, "SDL_TouchFingerEvent.windowID offset changed");
_Static_assert(sizeof(SDL_PinchFingerEvent) == 24, "SDL_PinchFingerEvent size changed");
_Static_assert(_Alignof(SDL_PinchFingerEvent) == 8, "SDL_PinchFingerEvent alignment changed");
_Static_assert(offsetof(SDL_PinchFingerEvent, type) == 0, "SDL_PinchFingerEvent.type offset changed");
_Static_assert(offsetof(SDL_PinchFingerEvent, timestamp) == 8, "SDL_PinchFingerEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PinchFingerEvent, scale) == 16, "SDL_PinchFingerEvent.scale offset changed");
_Static_assert(offsetof(SDL_PinchFingerEvent, windowID) == 20, "SDL_PinchFingerEvent.windowID offset changed");
_Static_assert(sizeof(SDL_PenProximityEvent) == 24, "SDL_PenProximityEvent size changed");
_Static_assert(_Alignof(SDL_PenProximityEvent) == 8, "SDL_PenProximityEvent alignment changed");
_Static_assert(offsetof(SDL_PenProximityEvent, type) == 0, "SDL_PenProximityEvent.type offset changed");
_Static_assert(offsetof(SDL_PenProximityEvent, timestamp) == 8, "SDL_PenProximityEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenProximityEvent, windowID) == 16, "SDL_PenProximityEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenProximityEvent, which) == 20, "SDL_PenProximityEvent.which offset changed");
_Static_assert(sizeof(SDL_PenMotionEvent) == 40, "SDL_PenMotionEvent size changed");
_Static_assert(_Alignof(SDL_PenMotionEvent) == 8, "SDL_PenMotionEvent alignment changed");
_Static_assert(offsetof(SDL_PenMotionEvent, type) == 0, "SDL_PenMotionEvent.type offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, timestamp) == 8, "SDL_PenMotionEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, windowID) == 16, "SDL_PenMotionEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, which) == 20, "SDL_PenMotionEvent.which offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, pen_state) == 24, "SDL_PenMotionEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, x) == 28, "SDL_PenMotionEvent.x offset changed");
_Static_assert(offsetof(SDL_PenMotionEvent, y) == 32, "SDL_PenMotionEvent.y offset changed");
_Static_assert(sizeof(SDL_PenTouchEvent) == 40, "SDL_PenTouchEvent size changed");
_Static_assert(_Alignof(SDL_PenTouchEvent) == 8, "SDL_PenTouchEvent alignment changed");
_Static_assert(offsetof(SDL_PenTouchEvent, type) == 0, "SDL_PenTouchEvent.type offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, timestamp) == 8, "SDL_PenTouchEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, windowID) == 16, "SDL_PenTouchEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, which) == 20, "SDL_PenTouchEvent.which offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, pen_state) == 24, "SDL_PenTouchEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, x) == 28, "SDL_PenTouchEvent.x offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, y) == 32, "SDL_PenTouchEvent.y offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, eraser) == 36, "SDL_PenTouchEvent.eraser offset changed");
_Static_assert(offsetof(SDL_PenTouchEvent, down) == 37, "SDL_PenTouchEvent.down offset changed");
_Static_assert(sizeof(SDL_PenButtonEvent) == 40, "SDL_PenButtonEvent size changed");
_Static_assert(_Alignof(SDL_PenButtonEvent) == 8, "SDL_PenButtonEvent alignment changed");
_Static_assert(offsetof(SDL_PenButtonEvent, type) == 0, "SDL_PenButtonEvent.type offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, timestamp) == 8, "SDL_PenButtonEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, windowID) == 16, "SDL_PenButtonEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, which) == 20, "SDL_PenButtonEvent.which offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, pen_state) == 24, "SDL_PenButtonEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, x) == 28, "SDL_PenButtonEvent.x offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, y) == 32, "SDL_PenButtonEvent.y offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, button) == 36, "SDL_PenButtonEvent.button offset changed");
_Static_assert(offsetof(SDL_PenButtonEvent, down) == 37, "SDL_PenButtonEvent.down offset changed");
_Static_assert(sizeof(SDL_PenAxisEvent) == 48, "SDL_PenAxisEvent size changed");
_Static_assert(_Alignof(SDL_PenAxisEvent) == 8, "SDL_PenAxisEvent alignment changed");
_Static_assert(offsetof(SDL_PenAxisEvent, type) == 0, "SDL_PenAxisEvent.type offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, timestamp) == 8, "SDL_PenAxisEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, windowID) == 16, "SDL_PenAxisEvent.windowID offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, which) == 20, "SDL_PenAxisEvent.which offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, pen_state) == 24, "SDL_PenAxisEvent.pen_state offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, x) == 28, "SDL_PenAxisEvent.x offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, y) == 32, "SDL_PenAxisEvent.y offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, axis) == 36, "SDL_PenAxisEvent.axis offset changed");
_Static_assert(offsetof(SDL_PenAxisEvent, value) == 40, "SDL_PenAxisEvent.value offset changed");
_Static_assert(sizeof(SDL_GamepadAxisEvent) == 32, "SDL_GamepadAxisEvent size changed");
_Static_assert(_Alignof(SDL_GamepadAxisEvent) == 8, "SDL_GamepadAxisEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, type) == 0, "SDL_GamepadAxisEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, timestamp) == 8, "SDL_GamepadAxisEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, which) == 16, "SDL_GamepadAxisEvent.which offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, axis) == 20, "SDL_GamepadAxisEvent.axis offset changed");
_Static_assert(offsetof(SDL_GamepadAxisEvent, value) == 24, "SDL_GamepadAxisEvent.value offset changed");
_Static_assert(sizeof(SDL_GamepadButtonEvent) == 24, "SDL_GamepadButtonEvent size changed");
_Static_assert(_Alignof(SDL_GamepadButtonEvent) == 8, "SDL_GamepadButtonEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, type) == 0, "SDL_GamepadButtonEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, timestamp) == 8, "SDL_GamepadButtonEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, which) == 16, "SDL_GamepadButtonEvent.which offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, button) == 20, "SDL_GamepadButtonEvent.button offset changed");
_Static_assert(offsetof(SDL_GamepadButtonEvent, down) == 21, "SDL_GamepadButtonEvent.down offset changed");
_Static_assert(sizeof(SDL_GamepadDeviceEvent) == 24, "SDL_GamepadDeviceEvent size changed");
_Static_assert(_Alignof(SDL_GamepadDeviceEvent) == 8, "SDL_GamepadDeviceEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadDeviceEvent, type) == 0, "SDL_GamepadDeviceEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadDeviceEvent, timestamp) == 8, "SDL_GamepadDeviceEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadDeviceEvent, which) == 16, "SDL_GamepadDeviceEvent.which offset changed");
_Static_assert(sizeof(SDL_GamepadTouchpadEvent) == 40, "SDL_GamepadTouchpadEvent size changed");
_Static_assert(_Alignof(SDL_GamepadTouchpadEvent) == 8, "SDL_GamepadTouchpadEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, type) == 0, "SDL_GamepadTouchpadEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, timestamp) == 8, "SDL_GamepadTouchpadEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, which) == 16, "SDL_GamepadTouchpadEvent.which offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, touchpad) == 20, "SDL_GamepadTouchpadEvent.touchpad offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, finger) == 24, "SDL_GamepadTouchpadEvent.finger offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, x) == 28, "SDL_GamepadTouchpadEvent.x offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, y) == 32, "SDL_GamepadTouchpadEvent.y offset changed");
_Static_assert(offsetof(SDL_GamepadTouchpadEvent, pressure) == 36, "SDL_GamepadTouchpadEvent.pressure offset changed");
_Static_assert(sizeof(SDL_GamepadSensorEvent) == 48, "SDL_GamepadSensorEvent size changed");
_Static_assert(_Alignof(SDL_GamepadSensorEvent) == 8, "SDL_GamepadSensorEvent alignment changed");
_Static_assert(offsetof(SDL_GamepadSensorEvent, type) == 0, "SDL_GamepadSensorEvent.type offset changed");
_Static_assert(offsetof(SDL_GamepadSensorEvent, timestamp) == 8, "SDL_GamepadSensorEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_GamepadSensorEvent, which) == 16, "SDL_GamepadSensorEvent.which offset changed");
_Static_assert(offsetof(SDL_GamepadSensorEvent, sensor) == 20, "SDL_GamepadSensorEvent.sensor offset changed");
_Static_assert(offsetof(SDL_GamepadSensorEvent, data) == 24, "SDL_GamepadSensorEvent.data offset changed");
_Static_assert(offsetof(SDL_GamepadSensorEvent, sensor_timestamp) == 40, "SDL_GamepadSensorEvent.sensor_timestamp offset changed");
_Static_assert(sizeof(SDL_DropEvent) == 48, "SDL_DropEvent size changed");
_Static_assert(_Alignof(SDL_DropEvent) == 8, "SDL_DropEvent alignment changed");
_Static_assert(offsetof(SDL_DropEvent, type) == 0, "SDL_DropEvent.type offset changed");
_Static_assert(offsetof(SDL_DropEvent, timestamp) == 8, "SDL_DropEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_DropEvent, windowID) == 16, "SDL_DropEvent.windowID offset changed");
_Static_assert(offsetof(SDL_DropEvent, x) == 20, "SDL_DropEvent.x offset changed");
_Static_assert(offsetof(SDL_DropEvent, y) == 24, "SDL_DropEvent.y offset changed");
_Static_assert(offsetof(SDL_DropEvent, source) == 32, "SDL_DropEvent.source offset changed");
_Static_assert(offsetof(SDL_DropEvent, data) == 40, "SDL_DropEvent.data offset changed");
_Static_assert(sizeof(SDL_ClipboardEvent) == 32, "SDL_ClipboardEvent size changed");
_Static_assert(_Alignof(SDL_ClipboardEvent) == 8, "SDL_ClipboardEvent alignment changed");
_Static_assert(offsetof(SDL_ClipboardEvent, type) == 0, "SDL_ClipboardEvent.type offset changed");
_Static_assert(offsetof(SDL_ClipboardEvent, timestamp) == 8, "SDL_ClipboardEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_ClipboardEvent, owner) == 16, "SDL_ClipboardEvent.owner offset changed");
_Static_assert(offsetof(SDL_ClipboardEvent, num_mime_types) == 20, "SDL_ClipboardEvent.num_mime_types offset changed");
_Static_assert(offsetof(SDL_ClipboardEvent, mime_types) == 24, "SDL_ClipboardEvent.mime_types offset changed");
_Static_assert(sizeof(SDL_AudioDeviceEvent) == 24, "SDL_AudioDeviceEvent size changed");
_Static_assert(_Alignof(SDL_AudioDeviceEvent) == 8, "SDL_AudioDeviceEvent alignment changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, type) == 0, "SDL_AudioDeviceEvent.type offset changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, timestamp) == 8, "SDL_AudioDeviceEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, which) == 16, "SDL_AudioDeviceEvent.which offset changed");
_Static_assert(offsetof(SDL_AudioDeviceEvent, recording) == 20, "SDL_AudioDeviceEvent.recording offset changed");
_Static_assert(sizeof(SDL_SensorEvent) == 56, "SDL_SensorEvent size changed");
_Static_assert(_Alignof(SDL_SensorEvent) == 8, "SDL_SensorEvent alignment changed");
_Static_assert(offsetof(SDL_SensorEvent, type) == 0, "SDL_SensorEvent.type offset changed");
_Static_assert(offsetof(SDL_SensorEvent, timestamp) == 8, "SDL_SensorEvent.timestamp offset changed");
_Static_assert(offsetof(SDL_SensorEvent, which) == 16, "SDL_SensorEvent.which offset changed");
_Static_assert(offsetof(SDL_SensorEvent, data) == 20, "SDL_SensorEvent.data offset changed");
_Static_assert(offsetof(SDL_SensorEvent, sensor_timestamp) == 48, "SDL_SensorEvent.sensor_timestamp offset changed");
_Static_assert(sizeof(SDL_Surface) == 48, "SDL_Surface size changed");
_Static_assert(_Alignof(SDL_Surface) == 8, "SDL_Surface alignment changed");
_Static_assert(offsetof(SDL_Surface, format) == 4, "SDL_Surface.format offset changed");
_Static_assert(offsetof(SDL_Surface, w) == 8, "SDL_Surface.w offset changed");
_Static_assert(offsetof(SDL_Surface, h) == 12, "SDL_Surface.h offset changed");
_Static_assert(offsetof(SDL_Surface, pitch) == 16, "SDL_Surface.pitch offset changed");
_Static_assert(offsetof(SDL_Surface, pixels) == 24, "SDL_Surface.pixels offset changed");
_Static_assert(offsetof(SDL_Surface, refcount) == 32, "SDL_Surface.refcount offset changed");
_Static_assert(sizeof(SDL_Rect) == 16, "SDL_Rect size changed");
_Static_assert(_Alignof(SDL_Rect) == 4, "SDL_Rect alignment changed");
_Static_assert(offsetof(SDL_Rect, x) == 0, "SDL_Rect.x offset changed");
_Static_assert(offsetof(SDL_Rect, y) == 4, "SDL_Rect.y offset changed");
_Static_assert(offsetof(SDL_Rect, w) == 8, "SDL_Rect.w offset changed");
_Static_assert(offsetof(SDL_Rect, h) == 12, "SDL_Rect.h offset changed");
_Static_assert((unsigned long long)(SDL_INIT_AUDIO) == 16ULL, "SDL_INIT_AUDIO changed");
_Static_assert((unsigned long long)(SDL_INIT_VIDEO) == 32ULL, "SDL_INIT_VIDEO changed");
_Static_assert((unsigned long long)(SDL_INIT_JOYSTICK) == 512ULL, "SDL_INIT_JOYSTICK changed");
_Static_assert((unsigned long long)(SDL_INIT_HAPTIC) == 4096ULL, "SDL_INIT_HAPTIC changed");
_Static_assert((unsigned long long)(SDL_INIT_GAMEPAD) == 8192ULL, "SDL_INIT_GAMEPAD changed");
_Static_assert((unsigned long long)(SDL_INIT_EVENTS) == 16384ULL, "SDL_INIT_EVENTS changed");
_Static_assert((unsigned long long)(SDL_INIT_SENSOR) == 32768ULL, "SDL_INIT_SENSOR changed");
_Static_assert((unsigned long long)(SDL_INIT_CAMERA) == 65536ULL, "SDL_INIT_CAMERA changed");
_Static_assert((unsigned long long)(SDL_WINDOW_FULLSCREEN) == 1ULL, "SDL_WINDOW_FULLSCREEN changed");
_Static_assert((unsigned long long)(SDL_WINDOW_HIDDEN) == 8ULL, "SDL_WINDOW_HIDDEN changed");
_Static_assert((unsigned long long)(SDL_WINDOW_RESIZABLE) == 32ULL, "SDL_WINDOW_RESIZABLE changed");
_Static_assert((unsigned long long)(SDL_WINDOW_HIGH_PIXEL_DENSITY) == 8192ULL, "SDL_WINDOW_HIGH_PIXEL_DENSITY changed");
_Static_assert((unsigned long long)(SDL_WINDOW_METAL) == 536870912ULL, "SDL_WINDOW_METAL changed");
_Static_assert((unsigned long long)(SDL_PIXELFORMAT_RGBA32) == 376840196ULL, "SDL_PIXELFORMAT_RGBA32 changed");
_Static_assert((unsigned long long)(SDL_EVENT_QUIT) == 256ULL, "SDL_EVENT_QUIT changed");
_Static_assert((unsigned long long)(SDL_EVENT_TERMINATING) == 257ULL, "SDL_EVENT_TERMINATING changed");
_Static_assert((unsigned long long)(SDL_EVENT_LOW_MEMORY) == 258ULL, "SDL_EVENT_LOW_MEMORY changed");
_Static_assert((unsigned long long)(SDL_EVENT_WILL_ENTER_BACKGROUND) == 259ULL, "SDL_EVENT_WILL_ENTER_BACKGROUND changed");
_Static_assert((unsigned long long)(SDL_EVENT_DID_ENTER_BACKGROUND) == 260ULL, "SDL_EVENT_DID_ENTER_BACKGROUND changed");
_Static_assert((unsigned long long)(SDL_EVENT_WILL_ENTER_FOREGROUND) == 261ULL, "SDL_EVENT_WILL_ENTER_FOREGROUND changed");
_Static_assert((unsigned long long)(SDL_EVENT_DID_ENTER_FOREGROUND) == 262ULL, "SDL_EVENT_DID_ENTER_FOREGROUND changed");
_Static_assert((unsigned long long)(SDL_EVENT_LOCALE_CHANGED) == 263ULL, "SDL_EVENT_LOCALE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_SYSTEM_THEME_CHANGED) == 264ULL, "SDL_EVENT_SYSTEM_THEME_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_ORIENTATION) == 337ULL, "SDL_EVENT_DISPLAY_ORIENTATION changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_ADDED) == 338ULL, "SDL_EVENT_DISPLAY_ADDED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_REMOVED) == 339ULL, "SDL_EVENT_DISPLAY_REMOVED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_MOVED) == 340ULL, "SDL_EVENT_DISPLAY_MOVED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED) == 341ULL, "SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED) == 342ULL, "SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED) == 343ULL, "SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED) == 344ULL, "SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_SHOWN) == 514ULL, "SDL_EVENT_WINDOW_SHOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_HIDDEN) == 515ULL, "SDL_EVENT_WINDOW_HIDDEN changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_EXPOSED) == 516ULL, "SDL_EVENT_WINDOW_EXPOSED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_MOVED) == 517ULL, "SDL_EVENT_WINDOW_MOVED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_RESIZED) == 518ULL, "SDL_EVENT_WINDOW_RESIZED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED) == 519ULL, "SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_METAL_VIEW_RESIZED) == 520ULL, "SDL_EVENT_WINDOW_METAL_VIEW_RESIZED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_MINIMIZED) == 521ULL, "SDL_EVENT_WINDOW_MINIMIZED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_MAXIMIZED) == 522ULL, "SDL_EVENT_WINDOW_MAXIMIZED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_RESTORED) == 523ULL, "SDL_EVENT_WINDOW_RESTORED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_MOUSE_ENTER) == 524ULL, "SDL_EVENT_WINDOW_MOUSE_ENTER changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_MOUSE_LEAVE) == 525ULL, "SDL_EVENT_WINDOW_MOUSE_LEAVE changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_FOCUS_GAINED) == 526ULL, "SDL_EVENT_WINDOW_FOCUS_GAINED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_FOCUS_LOST) == 527ULL, "SDL_EVENT_WINDOW_FOCUS_LOST changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_CLOSE_REQUESTED) == 528ULL, "SDL_EVENT_WINDOW_CLOSE_REQUESTED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_HIT_TEST) == 529ULL, "SDL_EVENT_WINDOW_HIT_TEST changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_ICCPROF_CHANGED) == 530ULL, "SDL_EVENT_WINDOW_ICCPROF_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_DISPLAY_CHANGED) == 531ULL, "SDL_EVENT_WINDOW_DISPLAY_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED) == 532ULL, "SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_SAFE_AREA_CHANGED) == 533ULL, "SDL_EVENT_WINDOW_SAFE_AREA_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_OCCLUDED) == 534ULL, "SDL_EVENT_WINDOW_OCCLUDED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_ENTER_FULLSCREEN) == 535ULL, "SDL_EVENT_WINDOW_ENTER_FULLSCREEN changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_LEAVE_FULLSCREEN) == 536ULL, "SDL_EVENT_WINDOW_LEAVE_FULLSCREEN changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_DESTROYED) == 537ULL, "SDL_EVENT_WINDOW_DESTROYED changed");
_Static_assert((unsigned long long)(SDL_EVENT_WINDOW_HDR_STATE_CHANGED) == 538ULL, "SDL_EVENT_WINDOW_HDR_STATE_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEY_DOWN) == 768ULL, "SDL_EVENT_KEY_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEY_UP) == 769ULL, "SDL_EVENT_KEY_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_TEXT_EDITING) == 770ULL, "SDL_EVENT_TEXT_EDITING changed");
_Static_assert((unsigned long long)(SDL_EVENT_TEXT_INPUT) == 771ULL, "SDL_EVENT_TEXT_INPUT changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEYMAP_CHANGED) == 772ULL, "SDL_EVENT_KEYMAP_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEYBOARD_ADDED) == 773ULL, "SDL_EVENT_KEYBOARD_ADDED changed");
_Static_assert((unsigned long long)(SDL_EVENT_KEYBOARD_REMOVED) == 774ULL, "SDL_EVENT_KEYBOARD_REMOVED changed");
_Static_assert((unsigned long long)(SDL_EVENT_TEXT_EDITING_CANDIDATES) == 775ULL, "SDL_EVENT_TEXT_EDITING_CANDIDATES changed");
_Static_assert((unsigned long long)(SDL_EVENT_SCREEN_KEYBOARD_SHOWN) == 776ULL, "SDL_EVENT_SCREEN_KEYBOARD_SHOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_SCREEN_KEYBOARD_HIDDEN) == 777ULL, "SDL_EVENT_SCREEN_KEYBOARD_HIDDEN changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_MOTION) == 1024ULL, "SDL_EVENT_MOUSE_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_BUTTON_DOWN) == 1025ULL, "SDL_EVENT_MOUSE_BUTTON_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_BUTTON_UP) == 1026ULL, "SDL_EVENT_MOUSE_BUTTON_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_WHEEL) == 1027ULL, "SDL_EVENT_MOUSE_WHEEL changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_ADDED) == 1028ULL, "SDL_EVENT_MOUSE_ADDED changed");
_Static_assert((unsigned long long)(SDL_EVENT_MOUSE_REMOVED) == 1029ULL, "SDL_EVENT_MOUSE_REMOVED changed");
_Static_assert((unsigned long long)(SDL_MOUSEWHEEL_NORMAL) == 0ULL, "SDL_MOUSEWHEEL_NORMAL changed");
_Static_assert((unsigned long long)(SDL_MOUSEWHEEL_FLIPPED) == 1ULL, "SDL_MOUSEWHEEL_FLIPPED changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_DOWN) == 1792ULL, "SDL_EVENT_FINGER_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_UP) == 1793ULL, "SDL_EVENT_FINGER_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_MOTION) == 1794ULL, "SDL_EVENT_FINGER_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_FINGER_CANCELED) == 1795ULL, "SDL_EVENT_FINGER_CANCELED changed");
_Static_assert((unsigned long long)(SDL_EVENT_PINCH_BEGIN) == 1808ULL, "SDL_EVENT_PINCH_BEGIN changed");
_Static_assert((unsigned long long)(SDL_EVENT_PINCH_UPDATE) == 1809ULL, "SDL_EVENT_PINCH_UPDATE changed");
_Static_assert((unsigned long long)(SDL_EVENT_PINCH_END) == 1810ULL, "SDL_EVENT_PINCH_END changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_PROXIMITY_IN) == 4864ULL, "SDL_EVENT_PEN_PROXIMITY_IN changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_PROXIMITY_OUT) == 4865ULL, "SDL_EVENT_PEN_PROXIMITY_OUT changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_MOTION) == 4870ULL, "SDL_EVENT_PEN_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_DOWN) == 4866ULL, "SDL_EVENT_PEN_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_UP) == 4867ULL, "SDL_EVENT_PEN_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_BUTTON_DOWN) == 4868ULL, "SDL_EVENT_PEN_BUTTON_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_BUTTON_UP) == 4869ULL, "SDL_EVENT_PEN_BUTTON_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_PEN_AXIS) == 4871ULL, "SDL_EVENT_PEN_AXIS changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_AXIS_MOTION) == 1616ULL, "SDL_EVENT_GAMEPAD_AXIS_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_BUTTON_DOWN) == 1617ULL, "SDL_EVENT_GAMEPAD_BUTTON_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_BUTTON_UP) == 1618ULL, "SDL_EVENT_GAMEPAD_BUTTON_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_ADDED) == 1619ULL, "SDL_EVENT_GAMEPAD_ADDED changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_REMOVED) == 1620ULL, "SDL_EVENT_GAMEPAD_REMOVED changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_REMAPPED) == 1621ULL, "SDL_EVENT_GAMEPAD_REMAPPED changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN) == 1622ULL, "SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION) == 1623ULL, "SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_TOUCHPAD_UP) == 1624ULL, "SDL_EVENT_GAMEPAD_TOUCHPAD_UP changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_SENSOR_UPDATE) == 1625ULL, "SDL_EVENT_GAMEPAD_SENSOR_UPDATE changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_UPDATE_COMPLETE) == 1626ULL, "SDL_EVENT_GAMEPAD_UPDATE_COMPLETE changed");
_Static_assert((unsigned long long)(SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED) == 1627ULL, "SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_FILE) == 4096ULL, "SDL_EVENT_DROP_FILE changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_TEXT) == 4097ULL, "SDL_EVENT_DROP_TEXT changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_BEGIN) == 4098ULL, "SDL_EVENT_DROP_BEGIN changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_COMPLETE) == 4099ULL, "SDL_EVENT_DROP_COMPLETE changed");
_Static_assert((unsigned long long)(SDL_EVENT_DROP_POSITION) == 4100ULL, "SDL_EVENT_DROP_POSITION changed");
_Static_assert((unsigned long long)(SDL_EVENT_CLIPBOARD_UPDATE) == 2304ULL, "SDL_EVENT_CLIPBOARD_UPDATE changed");
_Static_assert((unsigned long long)(SDL_EVENT_AUDIO_DEVICE_ADDED) == 4352ULL, "SDL_EVENT_AUDIO_DEVICE_ADDED changed");
_Static_assert((unsigned long long)(SDL_EVENT_AUDIO_DEVICE_REMOVED) == 4353ULL, "SDL_EVENT_AUDIO_DEVICE_REMOVED changed");
_Static_assert((unsigned long long)(SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED) == 4354ULL, "SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED changed");
_Static_assert((unsigned long long)(SDL_EVENT_SENSOR_UPDATE) == 4608ULL, "SDL_EVENT_SENSOR_UPDATE changed");
#endif
