(* Generated by prismel-sdl3-clang-inventory-v2; do not edit. *)
type version = { major : int; minor : int; patch : int }

let generator_version = "prismel-sdl3-clang-inventory-v2"
let header_version = { major = 3; minor = 4; patch = 18 }
let header_version_number = 3004018
let stable_headers = true
let header_aggregate_sha256 = "58412c6698f7c391403c167d0dcb83f73951b80332ce662a3de4c23f07c79a79"
let clang_version = "Apple clang version 21.0.0 (clang-2100.1.1.101)"
let target_triple = "arm64-apple-darwin25"
let function_count = 1246
let safe_function_count = 75
let layout_sha256 = "2011e9974498dfcccd4ca15eaf0e0c8d58c75f1305bc3a4143bf01c3c13905a7"
