type filter=Nearest|Bilinear type rect={x:int;y:int;width:int;height:int} type error=Invalid_extent|Invalid_pitch|Storage_too_small
let ch c n=Int32.(to_int(logand(shift_right_logical c n)0xffl))
let color r g b a=Int32.(logor(shift_left(of_int r)24)(logor(shift_left(of_int g)16)(logor(shift_left(of_int b)8)(of_int a))))
let alpha_mask_blend ~blend ~dst ~dst_x ~dst_y ~width ~height ~pitch bytes ~color:c=if width<0||height<0 then Error Invalid_extent else if pitch<width then Error Invalid_pitch else if height<>0&&(pitch>max_int/height||Bytes.length bytes<pitch*height)then Error Storage_too_small else(let a=ch c 0 in for y=0 to height-1 do let py=dst_y+y in if py>=0&&py<Surface.height dst then for x=0 to width-1 do let px=dst_x+x in if px>=0&&px<Surface.width dst then let coverage=Char.code(Bytes.unsafe_get bytes(y*pitch+x))in Composite.pixel dst~blend~x:px~y:py(color(ch c 24)(ch c 16)(ch c 8)((a*coverage+127)/255))done done;Ok())
let alpha_mask ~dst ~dst_x ~dst_y ~width ~height ~pitch bytes ~color=alpha_mask_blend~blend:Composite.Source_over~dst~dst_x~dst_y~width~height~pitch bytes~color
let sample s x y=match Surface.get_rgba s~x~y with Ok c->c|Error _->0l
let lerp a b w=((a*(65536-w))+(b*w)+32768)lsr 16
let bilinear s fx fy=let x=fx asr 16 and y=fy asr 16 and wx=fx land 65535 and wy=fy land 65535 in let x1=min(Surface.width s-1)(x+1)and y1=min(Surface.height s-1)(y+1)in let a=sample s x y and b=sample s x1 y and c=sample s x y1 and d=sample s x1 y1 in let f n=lerp(lerp(ch a n)(ch b n)wx)(lerp(ch c n)(ch d n)wx)wy in color(f 24)(f 16)(f 8)(f 0)
let blit_scaled_blend ~blend ~src ~src_rect:s ~dst ~dst_rect:d ~filter=if s.width<=0||s.height<=0||d.width<=0||d.height<=0 then Error Invalid_extent else let x0=max 0 d.x and y0=max 0 d.y and x1=min(Surface.width dst)(d.x+d.width)and y1=min(Surface.height dst)(d.y+d.height)in for y=y0 to y1-1 do for x=x0 to x1-1 do let rx=x-d.x and ry=y-d.y in let fx=(s.x lsl 16)+((rx*s.width lsl 16)/d.width)and fy=(s.y lsl 16)+((ry*s.height lsl 16)/d.height)in let c=match filter with Nearest->sample src(fx asr 16)(fy asr 16)|Bilinear->bilinear src fx fy in Composite.pixel dst~blend~x~y c done done;Ok()
let blit_scaled ~src ~src_rect ~dst ~dst_rect ~filter=blit_scaled_blend~blend:Composite.Copy~src~src_rect~dst~dst_rect~filter
