let ch c n=Int32.(to_int(logand(shift_right_logical c n)0xffl))
let rgba r g b a=Int32.(logor(shift_left(of_int r)24)(logor(shift_left(of_int g)16)(logor(shift_left(of_int b)8)(of_int a))))
let mix blend source destination=Composite.color~blend~source~destination
let pixel s blend x y c=if x>=0&&y>=0&&x<Surface.width s&&y<Surface.height s then let b=Surface.bytes s and i=y*Surface.pitch s+x*4 in let g n=Char.code(Bytes.unsafe_get b(i+n))in let c=mix blend c(rgba(g 0)(g 1)(g 2)(g 3))in Bytes.unsafe_set b i(Char.chr(ch c 24));Bytes.unsafe_set b(i+1)(Char.chr(ch c 16));Bytes.unsafe_set b(i+2)(Char.chr(ch c 8));Bytes.unsafe_set b(i+3)(Char.chr(ch c 0))
let rect s ~blend ~x ~y ~width ~height c=if width>0&&height>0 then for j=max 0 y to min(Surface.height s-1)(y+height-1)do for i=max 0 x to min(Surface.width s-1)(x+width-1)do pixel s blend i j c done done
let line s ~blend ~x0 ~y0 ~x1 ~y1 c=let dx=abs(x1-x0)and sx=if x0<x1 then 1 else -1 and dy = - (abs (y1-y0))and sy=if y0<y1 then 1 else -1 in let rec loop x y e= pixel s blend x y c;if x<>x1||y<>y1 then let e2=2*e in let x,e=if e2>=dy then x+sx,e+dy else x,e in let y,e=if e2<=dx then y+sy,e+dx else y,e in loop x y e in loop x0 y0(dx+dy)
let edge(ax,ay)(bx,by)(x,y)=Int64.(sub(mul(of_int(x-ax))(of_int(by-ay)))(mul(of_int(y-ay))(of_int(bx-ax))))
let triangle s ~blend a b c color=let area=edge a b c in if area=0L then(let ax,ay=a and bx,by=b and cx,cy=c in line s~blend~x0:ax~y0:ay~x1:bx~y1:by color;line s~blend~x0:bx~y0:by~x1:cx~y1:cy color)else let a,b=if area<0L then b,a else a,b in let xs=[fst a;fst b;fst c]and ys=[snd a;snd b;snd c]in for y=max 0(List.fold_left min max_int ys)to min(Surface.height s-1)(List.fold_left max min_int ys)do for x=max 0(List.fold_left min max_int xs)to min(Surface.width s-1)(List.fold_left max min_int xs)do if edge a b(x,y)>=0L&&edge b c(x,y)>=0L&&edge c a(x,y)>=0L then pixel s blend x y color done done
let circle s ~blend ~cx ~cy ~radius c=if radius>=0 then let plot x y=pixel s blend(cx+x)(cy+y)c;pixel s blend(cx+y)(cy+x)c;pixel s blend(cx-x)(cy+y)c;pixel s blend(cx-y)(cy+x)c;pixel s blend(cx+x)(cy-y)c;pixel s blend(cx+y)(cy-x)c;pixel s blend(cx-x)(cy-y)c;pixel s blend(cx-y)(cy-x)c in let rec loop x y d=if x>=y then(plot x y;if d<0 then loop x(y+1)(d+2*y+3)else loop(x-1)(y+1)(d+2*(y-x)+5))in loop radius 0(1-radius)
