type metric={advance:float;bearing_x:float;bearing_y:float;width:int;height:int}
type glyph={codepoint:int;metric:metric}
type kerning={left:int;right:int;adjustment:float}
type run={font:int64;density:int;origin_x:float;baseline:float;color:int32;clip:Render_ir.rect option;glyphs:glyph array;kernings:kerning array}
type prepared={ir:Render_ir.t;atlas:Consumer.glyph_atlas;resource_id:int;bounds:Render_ir.rect}
type error=Invalid_density|Invalid_metric|Invalid_page|Missing_glyph of int|Too_many_glyphs|Capacity_exceeded|Ir_error of Render_ir.error|Consumer_error of Consumer.error
let finite=Float.is_finite
let prepare ~atlas ~page_width ~page_height ~resource_id ~hard_capacity run=
 if run.density<=0 then Error Invalid_density else if Array.length run.glyphs>65_536 then Error Too_many_glyphs else if page_width<=0||page_height<=0||resource_id<=0 then Error Invalid_page else if not(finite run.origin_x&&finite run.baseline)then Error Invalid_metric else
 let bad=Array.exists(fun g->let m=g.metric in m.width<0||m.height<0||not(finite m.advance&&finite m.bearing_x&&finite m.bearing_y))run.glyphs in if bad then Error Invalid_metric else
 let cell_width=Array.fold_left(fun n g->max n g.metric.width)1 run.glyphs and cell_height=Array.fold_left(fun n g->max n g.metric.height)1 run.glyphs in let count=Array.length run.glyphs in if count<>0&&cell_width>max_int/count then Error Capacity_exceeded else let width=max 1(cell_width*max 1 count)in if width>hard_capacity||cell_height<>0&&width>hard_capacity/cell_height then Error Capacity_exceeded else
 let bytes=Bytes.make(width*cell_height)'\000'and positions=Array.make count{Render_ir.glyph_id=0;x=0.;y=0.}and pen=ref(run.origin_x*.float run.density)and min_x=ref infinity and min_y=ref infinity and max_x=ref neg_infinity and max_y=ref neg_infinity and failure=ref None in
 let kerning left right=Array.fold_left(fun value k->if k.left=left&&k.right=right then k.adjustment else value)0. run.kernings in
 Array.iteri(fun i glyph->let metric=glyph.metric and key=Atlas.Glyph{font=run.font;codepoint=glyph.codepoint;density=run.density}in match Atlas.find atlas key with None->failure:=Some(Missing_glyph glyph.codepoint)|Some placement->(match Atlas.page_bytes atlas~page:placement.page with None->failure:=Some Invalid_page|Some page->if placement.x<0||placement.y<0||placement.x+metric.width>page_width||placement.y+metric.height>page_height||Bytes.length page<page_width*page_height*4 then failure:=Some Invalid_page else(for y=0 to metric.height-1 do for x=0 to metric.width-1 do Bytes.set bytes(y*width+i*cell_width)(Bytes.get page(((placement.y+y)*page_width+placement.x+x)*4+3))done done;let x= !pen+.metric.bearing_x*.float run.density and y=run.baseline*.float run.density-.metric.bearing_y*.float run.density in positions.(i)<-{Render_ir.glyph_id=i;x;y};min_x:=min !min_x x;min_y:=min !min_y y;max_x:=max !max_x(x+.float metric.width);max_y:=max !max_y(y+.float metric.height);pen:=!pen+.metric.advance*.float run.density;if i+1<count then pen:=!pen+.kerning glyph.codepoint run.glyphs.(i+1).codepoint*.float run.density)))run.glyphs;
 match !failure with Some e->Error e|None->let commands=if count=0 then[||]else let glyphs=Render_ir.Glyphs{resource_id;color=run.color;glyphs=positions}in match run.clip with None->[|glyphs|]|Some clip->[|Render_ir.Push_clip clip;glyphs;Pop_clip|]in(match Render_ir.create commands with Error e->Error(Ir_error e)|Ok ir->let bounds=if count=0 then{Render_ir.x=run.origin_x*.float run.density;y=run.baseline*.float run.density;width=0.;height=0.}else{x= !min_x;y= !min_y;width= !max_x-. !min_x;height= !max_y-. !min_y}in Ok{ir;atlas={Consumer.width=width;height=cell_height;pitch=width;bytes;cell_width;cell_height};resource_id;bounds})
let ir p=p.ir and physical_bounds p=p.bounds
let render prepared ~target=match Consumer.execute~lookup:(fun id->if id=prepared.resource_id then Some(Consumer.Glyph_atlas prepared.atlas)else None)~target prepared.ir with Ok()->Ok()|Error e->Error(Consumer_error e)
