type color_space=Linear|Srgb
type address=Clamp|Repeat|Mirror
type filter=Nearest|Bilinear|Trilinear
type t={levels:Surface.t array;color_space:color_space;storage_bytes:int}
type error=Invalid_size|Invalid_capacity|Capacity_exceeded|Invalid_lod of float|Invalid_coordinate
let channel c n=Int32.(to_int(logand(shift_right_logical c n)0xffl))
let rgba r g b a=Int32.(logor(shift_left(of_int r)24)(logor(shift_left(of_int g)16)(logor(shift_left(of_int b)8)(of_int a))))
let linear_of_srgb x=let x=float x/.255. in if x<=0.04045 then x/.12.92 else((x+.0.055)/.1.055)**2.4
let srgb_of_linear x=let x=max 0.(min 1. x)in let x=if x<=0.0031308 then 12.92*.x else 1.055*.(x**(1./.2.4))-.0.055 in int_of_float(x*.255.+.0.5)
let create ~color_space ~hard_capacity source=
 let width=Surface.width source and height=Surface.height source in if width<=0||height<=0 then Error Invalid_size else if hard_capacity<0 then Error Invalid_capacity else
 let required=ref 0 and w=ref width and h=ref height in while !w>1 || !h>1 do if !w>max_int/4 || (!h<>0 && !w*4>max_int/ !h) then required:=max_int else required:=!required+ !w* !h*4;w:=max 1((!w+1)/2);h:=max 1((!h+1)/2)done;if !required<>max_int then required:=!required+4;
 if !required>hard_capacity then Error Capacity_exceeded else
 let first=match Surface.create~width~height()with Ok s->s|Error _->assert false in Bytes.blit(Surface.bytes source)0(Surface.bytes first)0(width*height*4);
 let levels=ref[first]and current=ref first in while Surface.width !current>1||Surface.height !current>1 do let nw=max 1((Surface.width !current+1)/2)and nh=max 1((Surface.height !current+1)/2)in let next=match Surface.create~width:nw~height:nh()with Ok s->s|Error _->assert false in for y=0 to nh-1 do for x=0 to nw-1 do let count=ref 0 and sums=Array.make 4 0. in for oy=0 to 1 do for ox=0 to 1 do let sx=x*2+ox and sy=y*2+oy in if sx<Surface.width !current&&sy<Surface.height !current then(match Surface.get_rgba !current~x:sx~y:sy with Ok c->incr count;for k=0 to 3 do let value=channel c(24-k*8)in sums.(k)<-sums.(k)+.(if color_space=Srgb&&k<3 then linear_of_srgb value else float value/.255.)done|_->())done done;let out k=if color_space=Srgb&&k<3 then srgb_of_linear(sums.(k)/.float !count)else int_of_float(sums.(k)/.float !count*.255.+.0.5)in ignore(Surface.set_rgba next~x~y(rgba(out 0)(out 1)(out 2)(out 3)))done done;levels:=next::!levels;current:=next done;Ok{levels=Array.of_list(List.rev !levels);color_space;storage_bytes= !required}
let width t=Surface.width t.levels.(0)and height t=Surface.height t.levels.(0)and levels t=Array.length t.levels and storage_bytes t=t.storage_bytes
let level t index=if index<0||index>=Array.length t.levels then Error(Invalid_lod(float index))else Ok t.levels.(index)
let address mode x=match mode with Clamp->max 0.(min 1. x)|Repeat->x-.floor x|Mirror->let base=floor x and fraction=x-.floor x in if int_of_float(abs_float base)land 1=0 then fraction else 1.-.fraction
let blend color_space a b t=let f n=let av=channel a n and bv=channel b n in if color_space=Srgb&&n<>0 then srgb_of_linear((1.-.t)*.linear_of_srgb av+.t*.linear_of_srgb bv)else int_of_float((1.-.t)*.float av+.t*.float bv+.0.5)in rgba(f 24)(f 16)(f 8)(f 0)
let sample_level t level ~address_u ~address_v ~filter u v=let surface=t.levels.(level)in let u=address address_u u and v=address address_v v and w=Surface.width surface and h=Surface.height surface in let get x y=match Surface.get_rgba surface~x:(max 0(min(w-1)x))~y:(max 0(min(h-1)y))with Ok c->c|_->assert false in match filter with Nearest->get(int_of_float(floor(u*.float w)))(int_of_float(floor(v*.float h)))|Bilinear|Trilinear->let x=u*.float w-.0.5 and y=v*.float h-.0.5 in let x0=int_of_float(floor x)and y0=int_of_float(floor y)in let a=blend t.color_space(get x0 y0)(get(x0+1)y0)(x-.floor x)and b=blend t.color_space(get x0(y0+1))(get(x0+1)(y0+1))(x-.floor x)in blend t.color_space a b(y-.floor y)
let sample t ~address_u ~address_v ~filter ~u ~v ~lod=if not(Float.is_finite u&&Float.is_finite v)then Error Invalid_coordinate else if not(Float.is_finite lod)||lod<0. then Error(Invalid_lod lod)else let maximum=Array.length t.levels-1 in let low=min maximum(int_of_float(floor lod))in match filter with Trilinear->let high=min maximum(low+1)in Ok(blend t.color_space(sample_level t low~address_u~address_v~filter:Bilinear u v)(sample_level t high~address_u~address_v~filter:Bilinear u v)(lod-.floor lod))|Nearest|Bilinear->Ok(sample_level t low~address_u~address_v~filter u v)
