type vertex={x:float;y:float;depth:float;color:int32;u:float;v:float} type cull=Cull_none|Back|Front type texture={surface:Surface.t;filter:Image.filter} type clip={x:int;y:int;width:int;height:int}
let ch c n=Int32.(to_int(logand(shift_right_logical c n)0xffl))
let rgba r g b a=Int32.(logor(shift_left(of_int r)24)(logor(shift_left(of_int g)16)(logor(shift_left(of_int b)8)(of_int a))))
let sample t u v=let w=Surface.width t.surface and h=Surface.height t.surface in let get x y=match Surface.get_rgba t.surface~x:(max 0(min(w-1)x))~y:(max 0(min(h-1)y))with Ok c->c|_->0xffffffffl in match t.filter with Image.Nearest->get(int_of_float(u*.float w))(int_of_float(v*.float h))|Bilinear->let fx=u*.float w-.0.5 and fy=v*.float h-.0.5 in let x=int_of_float(floor fx)and y=int_of_float(floor fy)in let wx=fx-.floor fx and wy=fy-.floor fy and p00=get x y and p10=get(x+1)y and p01=get x(y+1)and p11=get(x+1)(y+1)in let f n=int_of_float(((1.-.wx)*.(1.-.wy)*.float(ch p00 n)+.wx*.(1.-.wy)*.float(ch p10 n)+.(1.-.wx)*.wy*.float(ch p01 n)+.wx*.wy*.float(ch p11 n))+.0.5)in rgba(f 24)(f 16)(f 8)(f 0)
let edge (a:vertex) (b:vertex) x y=(x-.a.x)*.(b.y-.a.y)-.(y-.a.y)*.(b.x-.a.x)
let top (a:vertex) (b:vertex)=a.y<b.y||(a.y=b.y&&a.x>b.x)
let visible ~cull (a:vertex) (b:vertex) (c:vertex)=let area=edge a b c.x c.y in area<>0.&&match cull with Back->area>0.|Front->area<0.|Cull_none->true
let draw ~color ~depth ~depth_state ~blend ~cull ~clip ~texture (a:vertex) (b:vertex) (c:vertex)=let area=edge a b c.x c.y in let rejected=area=0.||match cull with Back->area<=0.|Front->area>=0.|Cull_none->false in if not rejected then let a,b,area=if area<0. then b,a,-.area else a,b,area in let xmin=max clip.x(max 0(int_of_float(floor(min a.x(min b.x c.x)))))and ymin=max clip.y(max 0(int_of_float(floor(min a.y(min b.y c.y)))))and xmax=min(clip.x+clip.width-1)(min(Surface.width color-1)(int_of_float(ceil(max a.x(max b.x c.x)))))and ymax=min(clip.y+clip.height-1)(min(Surface.height color-1)(int_of_float(ceil(max a.y(max b.y c.y)))))in for y=ymin to ymax do for x=xmin to xmax do let px=float x+.0.5 and py=float y+.0.5 in let w0=edge b c px py and w1=edge c a px py and w2=edge a b px py in if (w0>0.||w0=0.&&top b c)&&(w1>0.||w1=0.&&top c a)&&(w2>0.||w2=0.&&top a b)then let w0=w0/.area and w1=w1/.area and w2=w2/.area in let z=w0*.a.depth+.w1*.b.depth+.w2*.c.depth in let pass=match depth with None->true|Some d->(match Depth_stencil.test_and_update d depth_state~x~y~depth:z with Ok p->p|_->false)in if pass then let f n=int_of_float(w0*.float(ch a.color n)+.w1*.float(ch b.color n)+.w2*.float(ch c.color n)+.0.5)in let base=rgba(f 24)(f 16)(f 8)(f 0)in let out=match texture with None->base|Some t->let q=sample t(w0*.a.u+.w1*.b.u+.w2*.c.u)(w0*.a.v+.w1*.b.v+.w2*.c.v)in rgba(ch base 24*ch q 24/255)(ch base 16*ch q 16/255)(ch base 8*ch q 8/255)(ch base 0*ch q 0/255)in Composite.pixel color~blend~x~y out done done
let interpolate_vertex (a:vertex) (b:vertex) t=let f n=int_of_float(float(ch a.color n)+.t*.float(ch b.color n-ch a.color n)+.0.5)in{x=a.x+.t*.(b.x-.a.x);y=a.y+.t*.(b.y-.a.y);depth=a.depth+.t*.(b.depth-.a.depth);color=rgba(f 24)(f 16)(f 8)(f 0);u=a.u+.t*.(b.u-.a.u);v=a.v+.t*.(b.v-.a.v)}
let fragment ~color ~depth ~depth_state ~blend ~texture ~x ~y (v:vertex)=let pass=match depth with None->true|Some d->(match Depth_stencil.test_and_update d depth_state~x~y~depth:v.depth with Ok p->p|_->false)in if pass then let out=match texture with None->v.color|Some t->let q=sample t v.u v.v in rgba(ch v.color 24*ch q 24/255)(ch v.color 16*ch q 16/255)(ch v.color 8*ch q 8/255)(ch v.color 0*ch q 0/255)in Composite.pixel color~blend~x~y out
let draw_line ~color ~depth ~depth_state ~blend ~clip ~texture ~width (a:vertex) (b:vertex)=let half=width*.0.5 and dx=b.x-.a.x and dy=b.y-.a.y in let length2=dx*.dx+.dy*.dy in let xmin=max clip.x(max 0(int_of_float(floor(min a.x b.x-.half))))and ymin=max clip.y(max 0(int_of_float(floor(min a.y b.y-.half))))and xmax=min(clip.x+clip.width-1)(min(Surface.width color-1)(int_of_float(ceil(max a.x b.x+.half))))and ymax=min(clip.y+clip.height-1)(min(Surface.height color-1)(int_of_float(ceil(max a.y b.y+.half))))in for y=ymin to ymax do for x=xmin to xmax do let px=float x+.0.5 and py=float y+.0.5 in let t=if length2=0. then 0. else max 0.(min 1.(((px-.a.x)*.dx+.(py-.a.y)*.dy)/.length2))in let qx=a.x+.t*.dx and qy=a.y+.t*.dy in if(px-.qx)*.(px-.qx)+.(py-.qy)*.(py-.qy)<=half*.half then fragment~color~depth~depth_state~blend~texture~x~y(interpolate_vertex a b t)done done
let draw_point ~color ~depth ~depth_state ~blend ~clip ~texture ~size (v:vertex)=let half=size*.0.5 in let xmin=max clip.x(max 0(int_of_float(ceil(v.x-.half-.0.5))))and ymin=max clip.y(max 0(int_of_float(ceil(v.y-.half-.0.5))))and xmax=min(clip.x+clip.width-1)(min(Surface.width color-1)(int_of_float(floor(v.x+.half-.0.5))))and ymax=min(clip.y+clip.height-1)(min(Surface.height color-1)(int_of_float(floor(v.y+.half-.0.5))))in for y=ymin to ymax do for x=xmin to xmax do fragment~color~depth~depth_state~blend~texture~x~y v done done
