  $ mkdir -p s/one s/two s/empty s/plain
  $ echo '(workspace one (graph g :context sop (sop/box)))' > s/one/sketch.plisp
  $ echo '(workspace two (graph g :context sop (sop/box)))' > s/two/sketch.plisp
  $ echo '(executable (name main))' > s/plain/dune
  $ prismel-plisp dune s
  ; generated by prismel-plisp dune sketches; accept changes with dune promote
  (subdir one
   (rule
    (target main.ml)
    (deps sketch.plisp (glob_files *.png) (glob_files *.ttf))
    (action (chdir %{workspace_root} (with-stdout-to %{target} (run %{bin:prismel-plisp} ml %{dep:sketch.plisp})))))
   (executable (name main) (modules main) (libraries prismel_editor))
   (rule (alias smoke-all)
    (action (setenv PRISMEL_MAX_FRAMES 120 (run ./main.exe)))))
  (subdir two
   (rule
    (target main.ml)
    (deps sketch.plisp (glob_files *.png) (glob_files *.ttf))
    (action (chdir %{workspace_root} (with-stdout-to %{target} (run %{bin:prismel-plisp} ml %{dep:sketch.plisp})))))
   (executable (name main) (modules main) (libraries prismel_editor))
   (rule (alias smoke-all)
    (action (setenv PRISMEL_MAX_FRAMES 120 (run ./main.exe)))))

A directory with its own dune file is hand-written (a sketch with its own main.ml uses
`prismel-plisp source`) and is skipped.

  $ cp s/one/sketch.plisp s/plain/sketch.plisp
  $ prismel-plisp dune s | grep -c subdir
  2

An empty directory lists nothing.

  $ mkdir e
  $ prismel-plisp dune e
  ; generated by prismel-plisp dune sketches; accept changes with dune promote
