  $ mkdir -p s/one s/two s/empty s/plain
  $ echo '(workspace one (graph g :context sop (sop/box)))' > s/one/sketch.rays
  $ echo '(workspace two (graph g :context sop (sop/box)))' > s/two/sketch.rays
  $ echo '(executable (name main))' > s/plain/dune
  $ rays-plisp dune s
  ; generated by rays-plisp dune sketches; accept changes with dune promote
  (subdir one
   (rule
    (target main.ml)
    (deps sketch.rays (glob_files *.png) (glob_files *.ttf))
    (action (chdir %{workspace_root} (with-stdout-to %{target} (run %{bin:rays-plisp} ml %{dep:sketch.rays})))))
   (executable (name main) (modules main) (libraries rays_editor))
   (rule (alias smoke-all)
    (action (setenv RAYS_MAX_FRAMES 120 (run ./main.exe)))))
  (subdir two
   (rule
    (target main.ml)
    (deps sketch.rays (glob_files *.png) (glob_files *.ttf))
    (action (chdir %{workspace_root} (with-stdout-to %{target} (run %{bin:rays-plisp} ml %{dep:sketch.rays})))))
   (executable (name main) (modules main) (libraries rays_editor))
   (rule (alias smoke-all)
    (action (setenv RAYS_MAX_FRAMES 120 (run ./main.exe)))))

A directory with its own dune file is hand-written (a sketch with its own main.ml uses
`rays-plisp source`) and is skipped.

  $ cp s/one/sketch.rays s/plain/sketch.rays
  $ rays-plisp dune s | grep -c subdir
  2

An empty directory lists nothing.

  $ mkdir e
  $ rays-plisp dune e
  ; generated by rays-plisp dune sketches; accept changes with dune promote
