  $ cat > a.plisp <<'X'
  > (workspace a
  >   ; kept verbatim
  >   (graph g :context sop (sop/box)))
  > X
  $ prismel-plisp ml a.plisp
  (* generated by prismel-plisp from a.plisp; do not edit *)
  let () =
    Prismel_editor.Workspace.main
      ~path:"a.plisp"
      ~digest:"bf39269baa63b402c1947e8889fba03568ef9dcd44684eb783a5bb119075bf4d"
      ~catalog:"dc1e8f2010a92cc6dd02282c17c77bea39cd030130bc3a4c91587fbe5a27968f"
      {plisp_bfjp|(workspace a
    ; kept verbatim
    (graph g :context sop (sop/box)))
  |plisp_bfjp}

The delimiter (plisp_ and the digest's first four hex digits, the digits as letters;
a collision is unit-tested in test_delimiter) is in the file once at each end. A
failing check prints its diagnostics and no OCaml.

  $ cat > bad.plisp <<'X'
  > (workspace a (graph g :context sop (sop/bx)))
  > X
  $ prismel-plisp ml bad.plisp
  File "bad.plisp", line 1, characters 35-43:
  Error [E_UNKNOWN_KIND]: Unknown operator “sop/bx”. Did you mean box?
  [1]

A sketch with its own main.ml gets the text as a module instead, unchecked (its catalog is its own).

  $ prismel-plisp source a.plisp
  (* generated by prismel-plisp from a.plisp; do not edit *)
  let path = "a.plisp"
  let digest = "bf39269baa63b402c1947e8889fba03568ef9dcd44684eb783a5bb119075bf4d"
  let text = {plisp_bfjp|(workspace a
    ; kept verbatim
    (graph g :context sop (sop/box)))
  |plisp_bfjp}
