type control={mutable next:int64;mutable epoch:int64;mutable completed:int64;mutable lost:bool;mutable fail_texture_after:int option;mutable fail_depth_after:int option;mutable fail_configure:bool;mutable trace:string list;mutable buffers:int;mutable textures:int;mutable pipelines:int;mutable queues:int;mutable surfaces:int}
let error op kind text=Error(Error.make op kind text)
let add c text=c.trace<-text::c.trace
let token c=let value=c.next in c.next<-Int64.succ value;value
let render_trace submission =
  let depth=match (Render_pass.descriptor(Render_pass.submission_pass submission)).Render_pass.depth with None->"nodepth"|Some attachment->Printf.sprintf"depth:%Ld:%s:%g"attachment.texture.id(match attachment.load with Clear->"clear"|Load->"load"|Dont_care->"discard")attachment.clear in
  let raster=Render_pass.raster_state(Render_pass.submission_pass submission)in
  let cull=match raster.cull with Cull_none->"none"|Cull_front->"front"|Cull_back->"back"and comparison=match raster.depth_compare with Never->"never"|Less->"less"|Equal->"equal"|Less_equal->"le"|Greater->"greater"|Not_equal->"ne"|Greater_equal->"ge"|Always->"always"in
  Printf.sprintf"%s:%s:%s:%b:"depth cull comparison raster.depth_write^(Render_pass.submission_draws submission
  |> List.map (fun (draw : Render_pass.draw) ->
         let index =
           match draw.index with
           | None -> "none"
           | Some (Uint16, id, offset, count) ->
               Printf.sprintf "u16:%Ld:%Ld:%d" id offset count
           | Some (Uint32, id, offset, count) ->
               Printf.sprintf "u32:%Ld:%Ld:%d" id offset count
         in
         Printf.sprintf "%s:%s:%d:%d:%s" draw.pipeline_key
           (match draw.primitive with Triangle_list -> "list" | Triangle_strip -> "strip")
           draw.vertex_start draw.vertex_count index)
  |> String.concat ";")
let create ?(capabilities=Capabilities.minimum_m1)()=
  let c={next=1L;epoch=0L;completed=0L;lost=false;fail_texture_after=None;fail_depth_after=None;fail_configure=false;trace=[];buffers=0;textures=0;pipelines=0;queues=0;surfaces=0}in
  let should_fail field=match field with Some 0->true|None|Some _->false in
  let advance field=match field with None->None|Some 0->None|Some remaining->Some(remaining-1)in
  let resource kind count set size=let id=token c and bytes=Bytes.make size '\000' in set(count+1);add c(Printf.sprintf"create-%s:%Ld"kind id);let range offset length=offset>=0L&&length>=0&&length<=size&&offset<=Int64.of_int(size-length)in let read_into offset destination destination_offset length=if not(range offset length)||destination_offset<0||length>Bytes.length destination-destination_offset then error"Backend_mock.read_into"Error.Invalid_argument"range"else(Bytes.blit bytes(Int64.to_int offset)destination destination_offset length;Ok())in Ok{Backend.token=id;write=(fun offset source->if not(range offset(Bytes.length source))then error"Backend_mock.write"Error.Invalid_argument"range"else(Bytes.blit source 0 bytes(Int64.to_int offset)(Bytes.length source);Ok()));read=(fun offset length->if not(range offset length)then error"Backend_mock.read"Error.Invalid_argument"range"else Ok(Bytes.sub bytes(Int64.to_int offset)length));read_into;destroy=(fun()->set((if kind="buffer"then c.buffers else c.textures)-1);add c(Printf.sprintf"destroy-%s:%Ld"kind id);Ok())}in
  let create_device()=let device_token=token c and device_handle=Handle.create_device()in Ok{Backend.device_token;device_handle;capabilities;
    create_buffer=(fun d->resource"buffer"c.buffers(fun n->c.buffers<-n)(Int64.to_int d.Types.size));
    create_texture=(fun d->if should_fail c.fail_texture_after then(c.fail_texture_after<-None;error"Backend_mock.create_texture"Error.Capacity"injected texture allocation failure")else(c.fail_texture_after<-advance c.fail_texture_after;resource"texture"c.textures(fun n->c.textures<-n)(d.Types.width*d.height*4)));
    create_depth_texture=(fun _d->if should_fail c.fail_depth_after then(c.fail_depth_after<-None;error"Backend_mock.create_depth_texture"Error.Capacity"injected depth allocation failure")else(c.fail_depth_after<-advance c.fail_depth_after;let id=token c in c.textures<-c.textures+1;add c(Printf.sprintf"create-depth-texture:%Ld"id);Ok{Backend.token=id;write=(fun _ _->error"Backend_mock.depth.write"Error.Unsupported"depth textures are not host writable");read=(fun _ _->error"Backend_mock.depth.read"Error.Unsupported"depth textures are not host readable");read_into=(fun _ _ _ _->error"Backend_mock.depth.read_into"Error.Unsupported"depth textures are not host readable");destroy=(fun()->c.textures<-c.textures-1;add c(Printf.sprintf"destroy-depth-texture:%Ld"id);Ok())}));
    create_stencil_texture=(fun _d->let id=token c in c.textures<-c.textures+1;add c(Printf.sprintf"create-stencil-texture:%Ld"id);Ok{Backend.token=id;write=(fun _ _->error"Backend_mock.stencil.write"Error.Unsupported"stencil textures are not host writable");read=(fun _ _->error"Backend_mock.stencil.read"Error.Unsupported"stencil textures are not host readable");read_into=(fun _ _ _ _->error"Backend_mock.stencil.read_into"Error.Unsupported"stencil textures are not host readable");destroy=(fun()->c.textures<-c.textures-1;add c(Printf.sprintf"destroy-stencil-texture:%Ld"id);Ok())});
    create_pipeline=(fun p->let id=token c in c.pipelines<-c.pipelines+1;add c("pipeline:"^Pipeline.cache_key p);Ok{pipeline_token=id;destroy_pipeline=(fun()->c.pipelines<-c.pipelines-1;Ok())});
    create_queue=(fun()->let id=token c in c.queues<-c.queues+1;Ok{queue_token=id;submit=(fun command~resources~pipelines->if c.lost then error"Backend_mock.submit"Error.Device_lost"injected device loss"else let ids=List.map fst resources in let required=match command with Backend.Transfer ops->Array.to_list ops|>List.concat_map(function Transfer_pass.Copy_buffer(a,_,b,_,_)->[a;b]|Fill_buffer(a,_,_,_)->[a]|Buffer_to_texture(a,_,_,_,b,_,_,_)->[a;b]|Texture_to_buffer(a,_,_,_,b,_,_,_)->[a;b]|Copy_texture(a,_,_,b,_,_,_)->[a;b])|Compute d->Array.to_list d.Compute_pass.commands|>List.filter_map(function Command.Declare_resource r->Some r.resource_id|_->None)|Render submission->let d=Render_pass.descriptor(Render_pass.submission_pass submission)in(Array.to_list d.Render_pass.colors|>List.filter_map(function None->None|Some(a:Render_pass.color)->Some a.texture.id))@(Render_pass.submission_draws submission|>List.concat_map(fun(draw:Render_pass.draw)->List.map(fun(b:Render_pass.buffer_binding)->b.buffer_id)draw.buffers@List.map(fun(t:Render_pass.texture_binding)->t.texture_id)draw.textures@match draw.index with None->[]|Some(_,id,_,_)->[id]))in if List.exists(fun id->not(List.mem id ids))required then error"Backend_mock.submit"Error.Invalid_argument"command resource is absent"else if(match command with Transfer _->false|Compute _->pipelines=[]|Render submission->List.length pipelines<>List.length(List.sort_uniq String.compare(List.map(fun(d:Render_pass.draw)->d.pipeline_key)(Render_pass.submission_draws submission))))then error"Backend_mock.submit"Error.Invalid_argument"pipeline graph differs from draws"else((match command with Render submission->add c("render:"^render_trace submission)|Transfer _|Compute _->());c.epoch<-Int64.succ c.epoch;add c(Printf.sprintf"submit:%Ld"c.epoch);Ok{Backend.epoch=c.epoch}));complete_through=(fun epoch->if epoch<=c.completed||epoch>c.epoch then error"Backend_mock.complete"Error.Invalid_argument"epoch is invalid"else(c.completed<-epoch;add c(Printf.sprintf"complete:%Ld"epoch);Ok()));destroy_queue=(fun()->c.queues<-c.queues-1;Ok())});
    create_surface=(fun _->let id=token c and frame=ref 0L in c.surfaces<-c.surfaces+1;Ok({surface_token=id;configure=(fun _->if c.fail_configure then(c.fail_configure<-false;error"Backend_mock.configure"Error.Invalid_state"injected configure failure")else Ok());acquire=(fun()->if c.lost then Ok`Device_lost else(frame:=Int64.succ !frame;Ok(`Acquired({Backend.frame_token = !frame}:Backend.driver_frame))));present=(fun _->add c"present";Ok());discard=(fun _->add c"discard";Ok());destroy_surface=(fun()->c.surfaces<-c.surfaces-1;Ok())}:Backend.driver_surface));destroy_device=(fun()->Handle.destroy_device device_handle;add c"destroy-device";Ok())}in
  {Backend.create_device},c
let inject_device_loss c=c.lost<-true
let fail_texture_allocation_after c count=if count<0 then invalid_arg"negative allocation count"else c.fail_texture_after<-Some count
let fail_depth_allocation_after c count=if count<0 then invalid_arg"negative allocation count"else c.fail_depth_after<-Some count
let fail_next_configure c=c.fail_configure<-true
let trace c=List.rev c.trace
let clear_trace c=c.trace<-[]
let live_counts c=c.buffers,c.textures,c.pipelines,c.queues,c.surfaces
