(library
 (name ogpu)
 (public_name prismel.ogpu)
 (modules Error Handle Capabilities Types Command Mock Submission Shader Surface Binding))

(test
 (name test_ogpu_foundation)
 (modules test_ogpu_foundation)
 (libraries ogpu))

(test
 (name test_ogpu_command)
 (modules test_ogpu_command)
 (libraries ogpu))

(test
 (name test_ogpu_mock)
 (modules test_ogpu_mock)
 (libraries ogpu))

(test
 (name test_ogpu_submission)
 (modules test_ogpu_submission)
 (libraries ogpu))

(test
 (name test_ogpu_shader)
 (modules test_ogpu_shader)
 (libraries ogpu))

(test
 (name test_ogpu_surface)
 (modules test_ogpu_surface)
 (libraries ogpu))

(test
 (name test_ogpu_binding)
 (modules test_ogpu_binding)
 (libraries ogpu))
