type pending={mutable id:int64;mutable commands:Command.description array;mutable resource_count:int}
type t={device:Handle.device;max_frames:int;mutable next_id:int64;mutable completed:int64;mutable lost:bool;pending:pending array;mutable pending_head:int;mutable pending_count:int}
type receipt={id:int64;commands:Command.description array}
let create ?(max_frames=2) device=if max_frames<1||max_frames>3 then Error(Error.make"Ogpu.Submission.create"Error.Invalid_argument"frames in flight must be between 1 and 3")else Ok{device;max_frames;next_id=1L;completed=0L;lost=false;pending=Array.init max_frames(fun _->{id=0L;commands=[||];resource_count=0});pending_head=0;pending_count=0}
let in_flight value=value.pending_count
let retained_resource_count value=let total=ref 0 in for i=0 to value.pending_count-1 do total:= !total+value.pending.((value.pending_head+i)mod value.max_frames).resource_count done;!total
let completed_epoch value=value.completed
let pending_descriptions value=Array.init value.pending_count(fun i->let p=value.pending.((value.pending_head+i)mod value.max_frames)in p.id,Array.copy p.commands)
let admit value command ~resources=let operation="Ogpu.Submission.submit"in if value.lost||Handle.device_destroyed value.device then Error(Error.make operation Error.Device_lost"queue device is lost")else if in_flight value>=value.max_frames then Error(Error.make operation Error.Capacity"frames-in-flight capacity reached")else match List.find_map(fun resource->match Handle.validate_for ~operation value.device resource with Ok()->None|Error e->Some e)resources with Some error->Error error|None->match Command.take_for_submission command with Error _ as e->e|Ok commands->let id=value.next_id in value.next_id<-Int64.succ id;let slot=value.pending.((value.pending_head+value.pending_count)mod value.max_frames)in slot.id<-id;slot.commands<-commands;slot.resource_count<-List.length resources;value.pending_count<-value.pending_count+1;Ok(id,commands)
let submit value command ~resources=Result.map(fun(id,commands)->{id;commands=Array.copy commands})(admit value command~resources)
let complete_through value epoch=let operation="Ogpu.Submission.complete_through"in if epoch<value.completed then Error(Error.make operation Error.Invalid_argument"completion epoch moved backwards")else let last=Int64.pred value.next_id in if epoch>last then Error(Error.make operation Error.Invalid_argument"completion epoch was never submitted")else(value.completed<-epoch;while value.pending_count>0&&value.pending.(value.pending_head).id<=epoch do let slot=value.pending.(value.pending_head)in slot.commands<-[||];slot.resource_count<-0;value.pending_head<-(value.pending_head+1)mod value.max_frames;value.pending_count<-value.pending_count-1 done;Ok())
let drain value=let last=Int64.pred value.next_id in value.completed<-max value.completed last;for i=0 to value.pending_count-1 do let slot=value.pending.((value.pending_head+i)mod value.max_frames)in slot.commands<-[||];slot.resource_count<-0 done;value.pending_head<-0;value.pending_count<-0
let lose_device value=value.lost<-true;drain value
module Private=struct
  let submit_epoch value command ~resources=Result.map fst(admit value command~resources)
end
