let fail message=raise(Failure message)
let ok=function Ok value->value|Error e->fail(Ogpu.Error.to_string e)
let expect kind=function Error(e:Ogpu.Error.t)when e.kind=kind->()|_->fail"unexpected acceleration-pass result"
let make()=
  let device=Ogpu.Handle.create_device()in let buffer=Ogpu.Handle.create ~device in let geometry_range={Ogpu.Acceleration.buffer;buffer_size=4096L;offset=0L;length=1024L}in let descriptor=Ogpu.Acceleration.Blas{geometries=[|Triangles{vertices=geometry_range;vertex_stride=12;vertex_count=3}|];allow_refit=true}in let structure=ok(Ogpu.Acceleration.create device ~ray_tracing:true descriptor)in let scratch={Ogpu.Acceleration_pass.resource_id=7L;buffer;buffer_size=4096L;offset=0L;length=1024L}in device,structure,scratch
let description()=let device,structure,scratch=make()in let result=ok(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Build structure)~scratch ~auxiliary:None)in {result with copied=None}
let ()=
  let device,structure,scratch=make()in expect Ogpu.Error.Unsupported(Ogpu.Acceleration_pass.execute device ~ray_tracing:false(Build structure)~scratch ~auxiliary:None);expect Ogpu.Error.Invalid_argument(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Build structure)~scratch:{scratch with offset=1L}~auxiliary:None);ignore(ok(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Build structure)~scratch ~auxiliary:None));ignore(ok(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Refit structure)~scratch ~auxiliary:None));let copied=ok(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Copy structure)~scratch ~auxiliary:None)in if copied.copied=None then fail"copy did not return a structure";ignore(ok(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Compact structure)~scratch ~auxiliary:None));Ogpu.Handle.destroy scratch.buffer;expect Ogpu.Error.Stale_handle(Ogpu.Acceleration_pass.execute device ~ray_tracing:true(Copy structure)~scratch ~auxiliary:None);
  let sequential=description()and parallel=Domain.spawn description|>Domain.join in if sequential.kind<>parallel.kind||sequential.commands<>parallel.commands then fail"acceleration-pass descriptions differ across domains";print_endline"OGPU acceleration-pass validation passed"
