type buffer={device:Handle.device;id:int64;validate:Handle.device->(unit,Error.t)result;descriptor:Types.buffer_descriptor}
type texture={device:Handle.device;id:int64;validate:Handle.device->(unit,Error.t)result;descriptor:Types.texture_descriptor}
type origin={x:int;y:int;z:int} type extent={width:int;height:int;depth:int}
type description=Copy_buffer of int64*int64*int64*int64*int64|Fill_buffer of int64*int64*int64*int|Buffer_to_texture of int64*int64*int64*int64*int64*int*origin*extent|Texture_to_buffer of int64*int*origin*extent*int64*int64*int64*int64|Copy_texture of int64*int*origin*int64*int*origin*extent
type t={device:Handle.device;mutable commands:description list;mutable ended:bool}
let buffer ~device handle (descriptor:Types.buffer_descriptor):buffer={device;id=Handle.id handle;validate=(fun d->Handle.validate_for~operation:"Ogpu.Transfer_pass.buffer"d handle);descriptor}
let texture ~device handle (descriptor:Types.texture_descriptor):texture={device;id=Handle.id handle;validate=(fun d->Handle.validate_for~operation:"Ogpu.Transfer_pass.texture"d handle);descriptor}
let create device={device;commands=[];ended=false}
let err op kind text=Error(Error.make op kind text)
let add t op d=if t.ended then err op Error.Invalid_state"encoder ended"else(t.commands<-d::t.commands;Ok())
let range size offset length=offset>=0L&&length>0L&&offset<=size&&length<=Int64.sub size offset
let vb op d (b:buffer)=if Handle.device_id d<>Handle.device_id b.device then err op Error.Cross_device"foreign buffer"else Result.map(fun()->b)(b.validate d)
let vt op d (x:texture)=if Handle.device_id d<>Handle.device_id x.device then err op Error.Cross_device"foreign texture"else Result.map(fun()->x)(x.validate d)
let copy_buffer t ~src ~src_offset ~dst ~dst_offset ~length=let op="Ogpu.Transfer_pass.copy_buffer"in match vb op t.device src,vb op t.device dst with Ok s,Ok d when not(List.mem Types.Copy_src s.descriptor.usage&&List.mem Types.Copy_dst d.descriptor.usage)->err op Error.Invalid_argument"usage"|Ok s,Ok d when not(range s.descriptor.size src_offset length&&range d.descriptor.size dst_offset length)->err op Error.Invalid_argument"range"|Ok s,Ok d when s.id=d.id&&src_offset<Int64.add dst_offset length&&dst_offset<Int64.add src_offset length->err op Error.Invalid_argument"overlap"|Ok s,Ok d->add t op(Copy_buffer(s.id,src_offset,d.id,dst_offset,length))|Error e,_->Error e|_,Error e->Error e
let fill_buffer t (b:buffer) ~offset ~length ~value:byte=let op="Ogpu.Transfer_pass.fill_buffer"in match vb op t.device b with Error e->Error e|Ok b when byte<0||byte>255||not(List.mem Types.Copy_dst b.descriptor.usage)||not(range b.descriptor.size offset length)->err op Error.Invalid_argument"fill"|Ok b->add t op(Fill_buffer(b.id,offset,length,byte))
let texrange d mip o e=mip>=0&&mip<d.Types.mip_levels&&o.x>=0&&o.y>=0&&o.z>=0&&e.width>0&&e.height>0&&e.depth>0&&o.x+e.width<=max 1(d.width lsr mip)&&o.y+e.height<=max 1(d.height lsr mip)&&o.z+e.depth<=d.depth
let pitches e row image=let needed=Int64.mul row(Int64.of_int e.height)in row>=Int64.of_int(e.width*4)&&Int64.rem row 256L=0L&&image>=needed
let buffer_to_texture t ~src ~offset ~bytes_per_row ~bytes_per_image ~dst ~mip ~origin ~extent=let op="Ogpu.Transfer_pass.buffer_to_texture"in match vb op t.device src,vt op t.device dst with Ok b,Ok x when List.mem Types.Copy_src b.descriptor.usage&&List.mem Types.Texture_copy_dst x.descriptor.usage&&texrange x.descriptor mip origin extent&&pitches extent bytes_per_row bytes_per_image&&range b.descriptor.size offset bytes_per_image->add t op(Buffer_to_texture(b.id,offset,bytes_per_row,bytes_per_image,x.id,mip,origin,extent))|Error e,_->Error e|_,Error e->Error e|_->err op Error.Invalid_argument"upload descriptor"
let texture_to_buffer t ~src ~mip ~origin ~extent ~dst ~offset ~bytes_per_row ~bytes_per_image=let op="Ogpu.Transfer_pass.texture_to_buffer"in match vt op t.device src,vb op t.device dst with Ok x,Ok b when List.mem Types.Texture_copy_src x.descriptor.usage&&List.mem Types.Copy_dst b.descriptor.usage&&texrange x.descriptor mip origin extent&&pitches extent bytes_per_row bytes_per_image&&range b.descriptor.size offset bytes_per_image->add t op(Texture_to_buffer(x.id,mip,origin,extent,b.id,offset,bytes_per_row,bytes_per_image))|Error e,_->Error e|_,Error e->Error e|_->err op Error.Invalid_argument"readback descriptor"
let copy_texture t ~src ~src_mip ~src_origin ~dst ~dst_mip ~dst_origin ~extent=let op="Ogpu.Transfer_pass.copy_texture"in match vt op t.device src,vt op t.device dst with Ok s,Ok d when List.mem Types.Texture_copy_src s.descriptor.usage&&List.mem Types.Texture_copy_dst d.descriptor.usage&&texrange s.descriptor src_mip src_origin extent&&texrange d.descriptor dst_mip dst_origin extent->add t op(Copy_texture(s.id,src_mip,src_origin,d.id,dst_mip,dst_origin,extent))|Error e,_->Error e|_,Error e->Error e|_->err op Error.Invalid_argument"texture copy"
let finish t=if t.ended then err"Ogpu.Transfer_pass.finish"Error.Invalid_state"already ended"else(t.ended<-true;Ok(Array.of_list(List.rev t.commands)))
