(library
 (name runtime)
 (public_name prismel.runtime)
 (modules runtime runtime_shaders)
 (private_modules runtime_shaders)
 (libraries sdl3 ogpu scene_execution))

(library
 (name runtime_input)
 (public_name prismel.runtime_input)
 (wrapped false)
 (modules runtime_input runtime_input_sdl3)
 (libraries sdl3))

(executable
 (name test_main)
 (modules test_main test_runtime test_runtime_visibility test_runtime_scaling test_runtime_scene3_lighting test_runtime_scene3_instances test_runtime_scene2_argument_shader test_runtime_scene2_argument test_runtime_input)
 (libraries runtime runtime_input scene_execution ogpu sdl3))

(rule
 (aliases runtest-native test_runtime)
 (action (run %{exe:test_main.exe} test_runtime)))

(rule
 (aliases runtest-native test_runtime_visibility)
 (action (run %{exe:test_main.exe} test_runtime_visibility)))

(rule
 (aliases runtest test_runtime_scaling)
 (action (run %{exe:test_main.exe} test_runtime_scaling)))

(rule
 (aliases runtest-native test_runtime_scene3_lighting)
 (action (run %{exe:test_main.exe} test_runtime_scene3_lighting)))

(rule
 (aliases runtest test_runtime_scene3_instances)
 (action (run %{exe:test_main.exe} test_runtime_scene3_instances)))

(rule
 (aliases runtest-native test_runtime_scene2_argument_shader)
 (action (run %{exe:test_main.exe} test_runtime_scene2_argument_shader)))

(rule
 (aliases runtest-native test_runtime_scene2_argument)
 (action (run %{exe:test_main.exe} test_runtime_scene2_argument)))

(rule
 (aliases runtest test_runtime_input)
 (action (run %{exe:test_main.exe} test_runtime_input)))
