(executable
 (name embed_metal)
 (modules embed_metal))

(rule
 (target pathtrace_source.ml)
 (deps pathtrace.metal)
 (action (with-stdout-to %{target}
  (run %{exe:embed_metal.exe} %{dep:pathtrace.metal}))))

(library
 (name rays_pathtracer)
 (public_name rays.pathtracer)
 (modules rays_pathtracer pathtrace_source)
 (libraries rays ogpu rdk rays_execution runtime_resources unix))

(executable
 (name test_main)
 (modules test_main test_pathtracer test_gpu_film test_parity test_world test_scene)
 (libraries rays rays_pathtracer rays_execution runtime_resources ogpu rdk unix))

(rule
 (aliases qualification runtest-native test_pathtracer)
 (deps pathtrace.metal)
 (action (run %{exe:test_main.exe} test_pathtracer)))

(rule
 (aliases qualification runtest-native test_world)
 (action (run %{exe:test_main.exe} test_world)))

(rule
 (enabled_if (= %{env:RAYS_PATH_TRACER_EXACT_M1=0} 1))
 (alias qualification)
 (locks smoke_window)
 (deps pathtrace.metal)
 (action
  (setenv RAYS_PATH_TRACER_EXACT_M1 1
   (run %{exe:test_main.exe} test_pathtracer))))

(rule
 (aliases runtest-native test_gpu_film)
 (locks smoke_window)
 (action (run %{exe:test_main.exe} test_gpu_film)))

(rule
 (alias qualification)
 (locks smoke_window)
 (deps pathtrace.metal)
 (action (run %{exe:test_main.exe} test_parity)))

(rule
 (aliases qualification runtest-native test_scene)
 (action (run %{exe:test_main.exe} test_scene)))
