  $ cat > a.rays <<'X'
  > (workspace a
  >   ; kept verbatim
  >   (graph g :context sop (sop/box)))
  > X
  $ rays-lisp ml a.rays
  (* generated by rays-lisp from a.rays; do not edit *)
  let () =
    Rays_editor.Workspace.main
      ~path:"a.rays"
      ~digest:"bf39269baa63b402c1947e8889fba03568ef9dcd44684eb783a5bb119075bf4d"
      ~catalog:"84f55bc3821897e594fda2cfcd03c76ee8ab2395d7de962686c7ba71d6bb1dbc"
      {lisp_bfjp|(workspace a
    ; kept verbatim
    (graph g :context sop (sop/box)))
  |lisp_bfjp}

The delimiter (lisp_ and the digest's first four hex digits, the digits as letters;
a collision is unit-tested in test_delimiter) is in the file once at each end. A
failing check prints its diagnostics and no OCaml.

  $ cat > bad.rays <<'X'
  > (workspace a (graph g :context sop (sop/bx)))
  > X
  $ rays-lisp ml bad.rays
  File "bad.rays", line 1, characters 35-43:
  Error [E_UNKNOWN_KIND]: Unknown operator “sop/bx”. Did you mean box?
  [1]

A sketch with its own main.ml gets the text as a module instead, unchecked (its catalog is its own).

Math operators and the normal-displacement mode use the same declarations in the CLI and editor.

  $ cat > noise.rays <<'X'
  > (workspace noise
  >   (graph field :context value (noise3 [0.3 0.7 -0.2]))
  >   (graph surface :context sop
  >     (sop/noise_displace (sop/grid) :mode "normal_3d" :seed 0)))
  > X
  $ rays-lisp check noise.rays

  $ rays-lisp source a.rays
  (* generated by rays-lisp from a.rays; do not edit *)
  let path = "a.rays"
  let digest = "bf39269baa63b402c1947e8889fba03568ef9dcd44684eb783a5bb119075bf4d"
  let text = {lisp_bfjp|(workspace a
    ; kept verbatim
    (graph g :context sop (sop/box)))
  |lisp_bfjp}
