  $ cat > a.rays <<'X'
  > (workspace a
  >   ; kept verbatim
  >   (graph g :context sop (sop/box)))
  > X
  $ rays-lisp ml a.rays
  (* generated by rays-lisp from a.rays; do not edit *)
  let () =
    Rays_editor.Workspace.main
      ~path:"a.rays"
      ~digest:"bf39269baa63b402c1947e8889fba03568ef9dcd44684eb783a5bb119075bf4d"
      ~catalog:"0e620f7907ca579267fb5350cca59f6ec4bea0f5a9935692fb3bf32c477a373d"
      {lisp_bfjp|(workspace a
    ; kept verbatim
    (graph g :context sop (sop/box)))
  |lisp_bfjp}

The delimiter (lisp_ and the digest's first four hex digits, the digits as letters;
a collision is unit-tested in test_delimiter) is in the file once at each end. A
failing check prints its diagnostics and no OCaml.

  $ cat > bad.rays <<'X'
  > (workspace a (graph g :context sop (sop/bx)))
  > X
  $ rays-lisp ml bad.rays
  File "bad.rays", line 1, characters 35-43:
  Error [E_UNKNOWN_KIND]: Unknown operator “sop/bx”. Did you mean box?
  [1]

A sketch with its own main.ml gets the text as a module instead, unchecked (its catalog is its own).

  $ rays-lisp source a.rays
  (* generated by rays-lisp from a.rays; do not edit *)
  let path = "a.rays"
  let digest = "bf39269baa63b402c1947e8889fba03568ef9dcd44684eb783a5bb119075bf4d"
  let text = {lisp_bfjp|(workspace a
    ; kept verbatim
    (graph g :context sop (sop/box)))
  |lisp_bfjp}
