(* rays-lisp: check, ml, source, dune and fmt for .rays sketches.
   Stdlib and Arg only; the catalog is the in-process one. *)
module S = Flow.Syntax
module D = Flow.Diagnostic
module Doc = Editor_document.Workspace_doc

let read path = In_channel.with_open_bin path In_channel.input_all

let die fmt = Printf.ksprintf (fun m -> prerr_endline m; exit 1) fmt

let catalog () =
  match Editor_document.Contexts.catalog ~version:Flow_sop.Manifest.version Sop_catalog.Editor.factories with
  | Ok c -> c
  | Error d -> die "rays-lisp: catalog: %s" (D.to_string d)

let head = S.head

(* The checked document and every diagnostic to print. Warnings fail the file
   unless the workspace form carries ^:allow-warnings.  The document is also
   evaluated and lowered as a window opens it, so a file that passes opens. *)
let check_text text =
  let allow = match S.parse text with
    | Ok forms -> List.exists (fun (f : S.t) -> head f = Some "workspace" && List.mem "allow-warnings" f.meta) forms
    | Error _ -> false in
  match Doc.check_text (catalog ()) text with
  | Error ds -> None, ds, allow
  | Ok (doc, warnings) ->
      (match Editor_document.Contexts.of_workspace ~factories:Sop_catalog.Editor.factories doc with
       | Ok _ -> Some doc, warnings, allow
       | Error d -> None, warnings @ [ d ], allow)

(* The text, the document when the file reads, and whether it passes. *)
let check_file path =
  let text = read path in
  let doc, ds, allow = check_text text in
  List.iter (fun d -> prerr_endline (D.report ~file:path ~source:text d)) ds;
  let failed = doc = None || List.exists (fun (d : D.t) -> d.severity = D.Error || not allow) ds in
  text, doc, not failed

let check_all files =
  let ok = List.fold_left (fun ok f -> let _, _, passed = check_file f in passed && ok) true files in
  if not ok then exit 1

let ml path =
  let text, _, passed = check_file path in
  if not passed then exit 1;
  let digest = Editor_document.Contexts.sha256 text in
  let d = Delimiter.make digest text in
  Printf.printf "(* generated by rays-lisp from %s; do not edit *)\nlet () =\n  Rays_editor.Workspace.main\n    ~path:%S\n    ~digest:%S\n    ~catalog:%S\n    {%s|%s|%s}\n"
    path path digest (Editor_document.Contexts.catalog_digest Sop_catalog.Editor.factories) d text d

(* For a sketch with its own main.ml and dune (custom factories, renderer, settings): the
   text as a module, unchecked here because the catalog is the sketch's; [open_text] checks. *)
let source path =
  let text = read path in
  let digest = Editor_document.Contexts.sha256 text in
  let d = Delimiter.make digest text in
  Printf.printf "(* generated by rays-lisp from %s; do not edit *)\nlet path = %S\nlet digest = %S\nlet text = {%s|%s|%s}\n"
    path path digest d text d

let dune dir =
  let sub name = Filename.concat dir name in
  let sketches = Sys.readdir dir |> Array.to_list |> List.sort compare |> List.filter (fun n ->
    Sys.is_directory (sub n) && Sys.file_exists (Filename.concat (sub n) "sketch.rays")) in
  (* a directory with its own dune file is hand-written (see [source]) *)
  let sketches = List.filter (fun n -> not (Sys.file_exists (Filename.concat (sub n) "dune"))) sketches in
  print_string "; generated by rays-lisp dune sketches; accept changes with dune promote\n";
  List.iter (fun n -> Printf.printf
{|(subdir %s
 (rule
  (target main.ml)
  (deps sketch.rays (glob_files *.png) (glob_files *.ttf))
  (action (chdir %%{workspace_root} (with-stdout-to %%{target} (run %%{bin:rays-lisp} ml %%{dep:sketch.rays})))))
 (executable (name main) (modules main) (libraries rays_editor))
 (rule (alias smoke-all)
  (action (setenv RAYS_MAX_FRAMES 120 (run ./main.exe)))))
|} n) sketches

let fmt path =
  (* a file with warnings still formats *)
  match check_file path with
  | _, Some doc, _ -> print_string (Doc.to_text doc)
  | _, None, _ -> exit 1

let () = match Array.to_list Sys.argv with
  | _ :: "check" :: (_ :: _ as files) -> check_all files
  | [ _; "ml"; f ] -> ml f
  | [ _; "source"; f ] -> source f
  | [ _; "dune"; d ] -> dune d
  | [ _; "fmt"; f ] -> fmt f
  | _ -> die "usage: rays-lisp check FILE... | ml FILE | source FILE | dune DIR | fmt FILE"
